<?php

/**
 * Error Codes.
 */

namespace App\Common;


interface ErrorCodes extends Errors, ErrorCodesEN, ErrorCodesZhTW, ErrorCodesPOR, ErrorCodesES, ErrorCodesDE
{
    const ERROR_MESSAGES = [
        \Key\Constants::SYS_SUCCESS => 'OK',

        \Key\Constants::SYS_ERROR_DEFAULT => '未知错误',
        \Key\Constants::SYS_INPUT_INVALID => '参数错误',

        \Key\Constants::USER_OBJECT_NOT_FOUND => '对象不存在',
        \Key\Constants::USER_OBJECT_ALREADY_EXISTS => '对象已存在',
        \Key\Constants::USER_OBJECT_OCCUPIED => '对象已被使用',

        \Key\Constants::OPERATION_TOO_FREQUENT => '操作过于频繁，请稍候再试',

        self::SECURITY_PWD_WEAK => '默认密码过于简单',

        self::ACCOUNT_NOT_FOUNT => '公司不存在或已被禁用',
        self::ACCOUNT_NAME_EXISTS => '企业名称重复',
        self::ACCOUNT_CREATE_DICTIONARY_ERROR => '创建数据字典失败',
        self::ACCOUNT_CREATE_DEPARTMENT_ERROR => '创建部门失败',
        self::ACCOUNT_CREATE_ROLE_ERROR => '创建角色失败',
        self::ACCOUNT_CREATE_USER_ERROR => '创建用户失败',
        self::ACCOUNT_CREATE_EMPLOYEE_ERROR => '创建员工失败',
        self::ACCOUNT_CREATE_ASSESSMENT_ERROR => '创建默认的测评失败',
        self::ACCOUNT_INVALID => '关联公司已过期或被禁用',
        self::ACCOUNT_CODE_INVALID => '无效的公司编号',
        self::ACCOUNT_EXPIRED => '公司已过期',
        self::ACCOUNT_FUNCTION_NOT_ENABLED => '该功能未启用',
        self::ACCOUNT_URL_EXPIRE => '登录失效，请检查链接或重试',

        self::CUSTOM_FIELD_NAME_EXISTS => '自定义字段名称已存在',
        self::IMPORT_CONFIG_NOT_FOUND => '未配置导入设置',
        self::IMPORT_MAX_ROWS => '超过规定行数',

        // 360评估相关
        self::PUBLISH_NO_QUESTIONNAIRE => '问卷已经被删除',
        self::PUBLISH_NO_MODEL => '问卷中模型已被删除，请重新选择问卷',
        self::PUBLISH_NO_DIMENSION => '问卷中能力纬度已被删除，请重新选择问卷',
        self::PUBLISH_NO_ELEMENT => '问卷中能力要素已被删除，请重新选择问卷',
        self::PUBLISH_NO_QUESTION => '问卷中暂无试题，请重新选择问卷',

        self::EMPLOYEE_HAVE_LOCKED => '账户被锁定，请联系管理员',
        self::EMPLOYEE_NO_EXISTS => '员工编号已存在',
        self::USER_INVALID_NEW_PWD => '密码格式不正确，请检查密码要求',
        self::USER_PWD_NEW_SAME_OLD => '新密码不能和旧密码相同',
        self::USER_USR_ERROR_DEFAULT => '未知错误',
        self::USER_CAPTCHA_IMAGE_INVALID => '图形验证码已过期或填写错误',
        self::USER_CAPTCHA_SMS_INVALID => '错误的短信验证码',
        self::USER_PHONE_INVALID => 'Phone number is invalid',
        self::USER_ACCOUNT_NOT_FOUND => 'No account found',
        self::USER_LOGIN_FAIL => '用户名或者密码错误',
        self::USER_QR_LOGIN_FAIL => 'Scan code login failed, please refresh the retry or select other login',
        self::USER_QR_LOGIN_TIMEOUT => 'QR code has expired, please refresh the QR code to re-scan',
        self::USER_PWD_ERROR => '用户密码错误',
        self::USER_LOGIN_FAIL_TOO_MANY => '重试次数过多',
        self::USER_NOT_FOUND => '该用户不存在',
        self::USER_EXISTS_IN_COMPANY => '用户已经在公司里面了',
        self::USER_INVALID_OLD_PASSWORD => '无效的旧密码',
        self::USER_CREATE_ERROR => 'create a user fail',
        self::USER_SMS_CAPTCHA_FREQUENCY => '发送验证码过于频繁',
        self::USER_INVALID_USERNAME => '非法的用户名',
        self::USER_LEAVE_OFFICE => '员工已离职',
        self::USER_SMS_TIMEOUT => '短信验证码超时',
        self::USER_SMS_INVALID => '无效的短信验证码',
        self::MOBILE_EXIST => '手机号已存在',

        self::USER_2FA_BOUND => '2FA已绑定过了',
        self::USER_2FA_DISBLED => '',
        self::USER_2FA_MOBILE_NOT_MATCH => '错误的手机号码',
        self::USER_2FA_MOBILE_CAPTCHA_NOT_MATCH => '错误的短信验证码',
        self::USER_2FA_MOBILE_INVALID_TOKEN => '超时了，请重新登录',

        self::QUESTION_BANK_EXISTS => '题库标题已存在',
        self::QUESTION_IMPORT_TEMPLETE => '表头不符,请重新下载模板',
        self::QUESTION_EXISTS => '题目已存在',
        self::QUESTION_COYE_FAIL => '题复制失败',
        self::PAPER_EXISTS => '试卷的标题已存在',
        self::EXAM_EXISTS => '考试名称已存在',
        self::EXAM_END => '考试已结束',
        self::EXAM_COYE_FAIL => '复制考试失败',
        self::EXAM_EMPLOYEE_END => '员工考试已结束',
        self::EXAM_DETAIL_FAIL => '获取考试详情失败',
        self::EXAM_DIR_NOT_FOUND => '获取考试目录失败',
        self::SYSTEM_EXAM_DIR_CANNOT_DELETE => "默认的考试目录不能被删除",
        self::EXAM_DIR_EXISTS_CHILD => '此目录有子目录,不能删除,请先删除子目录',
        self::EXAM_USERNAME_EXIST => '手机号或邮箱有误',
        self::EXAM_DIR_EXISTS_BANK => '此目录有题库,不能删除,请先删除题库',
        self::EXAM_DIR_EXISTS_PAPER => '此目录有试卷,不能删除,请先删除试题',
        self::EXAM_NEED_LOGIN => '该考试需要登录',
        self::EXAM_EMPLOYEE_TEMPLATE => '表头不符,请重新下载模板',
        self::EXAM_MOBILE_NOT_EXIST => '手机号不存在',
        self::EXAM_REDIS_NO_DATE => 'redis没有考生的答案',
        self::EXAM_STUDENT_OUT_TIME => '很抱歉，当前时间不在考试范围内!',
        self::EXAM_MOCK_DIR_HAS_EXAM => '此目录有考试,不能删除,请先删除考试',
        self::EXAM_NOTIFY_UNPUBLISHED => '考试未发布，不允许发送通知',
        self::EXAM_NOTIFY_END => '考试已结束，不允许发送通知',
        self::EXAM_NOT_EXIST => '考试不存在',
        self::EXAM_PAPER_HAS_UPDATE => '试题已更新，请重新考试',
        self::EXAM_SMS_SEND_FAIL => '短信发送失败',
        self::EXAM_UNPUBLISHED => '考试未发布，请联系管理员！',

        self::LEARNING_PLAN_NAME_EXIST => '学习计划名称已存在',
        self::LEARNING_NO_EXIST => '编号被占用！',
        self::LEARNING_DURATION_TO_LONG => '时长太长了！',
        self::LEARNING_BREAKTHROUGH_NAME_EXIST => '闯关名称已存在',
        self::LEARNING_CATEGORY_DELETE_CONTAINS => '分类下有闯关，请先删除闯关',
        self::LEARNING_PLAN_NO_PERMISSION => '没有权限',
        self::LEARNING_LEARNER_OVERSTEP => '报名人数已达上限',
        self::LEARNING_LEARNER_ALREADY_EXIST => '该学员已存在',
        self::LEARNING_PLAN_NO_MORE_GROUP => '该智能班级没有更多分组了',
        self::LEARNING_PLAN_NOT_PUBLISHED => '学习计划未发布',
        self::LEARNING_CLASS_NOT_PUBLISHED => '班级未发布',
        self::LEARNING_PACK_NOT_PUBLISHED => '学习包未发布',
        self::LEARNING_PACK_SETTINGS_CREDIT => '学习包学分奖励超过限制',
        self::LERN_ENROLL_POSITION_NOT_PASSED => '岗位不满足，不允许报名',
        self::LERN_ENROLL_OFFLINE_NOT_PASSED => '授课数量不满足，不允许报名',
        self::LERN_ENROLL_NOT_LECTURER => '不是讲师，不允许报名',
        self::LEARNING_UN_EXISTS => '很抱歉，项目不存在！',
        self::LEARNING_LEARNER_UNDER_REVIEW => '审核中',
        self::LEARNING_TASK_OBLIGATORY => '请先添加学习内容',
        self::LEARNING_TEACHING_TEMPLATE_USED => '带教模板已被使用，无法删除',
        self::LEARNING_TEACHING_ALREADY_STARTED => '带教已开始',
        self::LEARNING_TEACHING_PROJECT_HAS_LEANRER => '带教项目下存在带教关系，无法删除',
        self::LEARNING_TEACHING_PROJECT_NO_EDIT => '非草稿的带教不允许修改',
        self::LEARNING_TEACHING_TEACHING_OVER_NUM => '导师带教数量超过限制，请先结束其它带教',
        self::LEARNING_TEACHING_ON_ONE => '该带教模板学员只能参与一次',
        self::LEARNING_TASK_EXISTS => '任务已存在',
        self::LEARNING_TASK_ASSIGNING => '任务分配中，请稍后再试',
        self::LEARNING_APPRAISER_NO_CERTIFICATE => '被鉴定人暂未获得相关证书！',
        self::LEARNING_TEACHER_NO_CERTIFICATE => '鉴定人暂未获得相关证书！',
        self::LEARNING_PACK_NOT_FOUND => '学习包不存在',
        self::LEARNING_INTERACTION_NOT_EXISTS_ERROR => '互动不存在',
        self::LEARNING_SIMPLE_NO_OFFLINE => '请先添加面授课再发布。',
        self::LEARNING_PLAN_ACTIVITY_NOT_FOUND => '活动不存在',
        self::LEARNING_PLAN_ACTIVITY_NOT_STARTED => '活动未开始',
        self::LEARNING_PLAN_ACTIVITY_NO_AUTH => '无权限签到该活动',
        self::LEARNING_NO_OPERATION_AUTH => '无权限',
        self::LEARNING_PLAN_NO_EXISTS => '学习模块儿不存在',
        self::LEARNING_PLAN_NO_VISIT_AUTH => '无访问权限',
        self::LEARNING_PLAN_IS_RELATED_PROJECT => '该项目已经执行！',
        self::LEARNING_BREAKTHROUGH_OCCUPIED => '该闯关被占用！',
        self::LEARNING_BREAKTHROUGH_CAG_HAVE_BREAKTHROUGH => '该分类下有闯关，不允许删除！',
        self::LEARNING_APPLICATION_NON_START => '报名未开始',
        self::LEARNING_APPLICATION_ALREADY_OVER => '报名已结束',
        self::LERN_ENROLL_SCORE_NOT_SUBSTANDARD => '学分未达标，不允许报名！',
        self::LERN_ENROLL_UNCERTIFIED => '未获得相应证书，不允许报名！',
        self::LERN_ENROLL_EXAM_NOT_PASSED => '未通过相应考试，不允许报名！',
        self::LERN_ENROLL_NOT_ALLOW_CANCEL => '该班级不允许取消报名！',
        self::LERN_ENROLL_CANCEL_TIME_CUT_OFF => '取消报名时间已截止！',
        self::LERN_ENROLL_DELEGATE_TOP => '达到项目人数上限！',
        self::LERN_ENROLL_DELEGATE_CLOSE => '代报名未开启！',
        self::LERN_DELEGATE_IS_EXIST => '新增条件与已有条件冲突！',
        self::LERN_DELEGATE_DELEGATE_NO_EXIST => '相同负责人，只可以添加已设置的部门！',
        self::LEARNING_PACK_END => '学习包已结束！',
        self::LEARNER_NOT_ZERO => '已添加学员，不允许删除！',
        self::LEARNING_PACK_UN_ENABLED => '学习包已禁用！',
        self::LEARNING_PLAN_LEARNER_ALREADY_SIGNED => '请勿重复签到',
        self::LEARNING_APPLICATION_NOT_ALLOWED => '班级未开放报名',
        self::LEARNING_PLAN_NO_AUTH => '无权限',
        self::LEARNING_PLAN_INVALID_QR_CODE => '无效二维码',
        self::LEARNING_PLAN_ALREADY_ENDED => '班级已结束',
        self::LEARNING_CLASS_SIGN_NOT_START => '签到未开始',
        self::LEARNING_CLASS_SIGN_ENDED => '签到已结束',
        self::LEARNING_CLASS_SIGN_OUTING_END => '签退已结束',
        self::LEARNING_CLASS_SIGN_LEARNER_SIGNED => '已签到',
        self::LEARNING_PLAN_SIGN_NOT_PUBLISHED => '班级未发布',
        self::LEARNING_PLAN_SIGN_NO_AUTH => '您还未加入该班级，暂无法签到',
        self::LEARNING_PLAN_ENDED_SIGN => '班级已结束',
        self::LEARNING_PACK_SIGN_NO_AUTH => '您还未加入该学习包，暂无法签到',
        self::LEARNING_PLAN_SIGN_INVALID_QR_CODE => '无效二维码',
        self::LEARNING_PLAN_SIGN_OVER_DISTANCE => '您所在的位置不在签到范围内，暂无法签到',
        self::LEARNING_PLAN_SIGN_CLOSED_GPS => '没有获取到地理位置信息，请检查是否打开定位',
        self::LERN_MAP_TAGGING_FINISHED_UNCERTIFIED => '获得证书条件尚未满足，无法标记完成',
        self::LERN_MAP_TAGGING_FINISHED_NOT_AUTH => '无权限，该任务由管理员标记完成',
        self::LERN_MAP_TAGGING_FINISHED_CLASS_INCOMPLETE => '该班级完成率未达到100%，无法标记完成',
        self::LEARNING_QUEUE_EXISTS => '处理中，请稍后',
        self::LERN_PACK_DISABLED => '该学习包已被禁用，请稍后再试！',
        self::LERN_PASS_DISABLED => '该闯关已被禁用，请稍后再试！',
        self::LERN_OPERATE_NOT_ALLOWED => '维护中，请到管理后台进行操作！',
        self::LEARNING_PLAN_NO_SIGNS => '暂无签到！',
        self::OFFLINE_TEACHING_SIGN_TIME_OUT => '二维码失效！',
        self::LERN_CLASS_NO_VISIT_AUTH => '您还未加入该班级！',
        self::LERN_PLAN_NO_VISIT_AUTH => '您还未加入该学习计划！',
        self::LERN_PACK_NO_VISIT_AUTH => '您还未加入该学习包！',
        self::LERN_PASS_NO_VISIT_AUTH => '您还未加入该闯关！',
        self::LERN_ADD_LEARNER_ON_GOING => '操作频繁，请稍后重试！',
        self::LERN_PASS_UNPUBLISHED => '闯关未发布',
        self::LERN_PASS_NOT_EXISTS => '闯关不存在',
        self::LERN_PASS_NOT_AUTH => '您无权限参与该闯关',

        self::LERN_PRO_NOT_ALLOW_LEARNER_IN_MULTI_CLASS => '该项目不允许同一个人报名多个班级',
        self::LERN_PRO_NOT_ALLOW_LEARNER_SHIFT => '该项目不允许学员自主调班',
        self::LERN_OVERSTEP_SHIFT_CLASS_TIME => '超出调班时间，请选择其它班级',

        self::KNOWLEDGE_NOT_EXISTS_ERROR => '知识不存在',
        self::DIRECTORY_NAME_EXISTS_ERROR => '目录名已经存在',
        self::DIRECTORY_NOT_EXISTS_ERROR => '目录不存在',
        self::DIRECTORY_LEVEL_LIMIT => '不能在此目录级别上创建目录',
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_KNOW_ERROR => '目录库里有知识时不能删除哦,请先删除目录库里的知识',
        self::DIRECTORY_EXISTS_CHILD_ERROR => '此目录有子目录,不能删除,请先删除子目录哦',
        self::CONTENT_IS_NOT_EXISTS_ERROR => '此内容不存在',
        self::DIRECTORY_COURSE_NOT_EXISTS_ERROR => '课程不存在',
        self::DIRECTORY_HAS_CHILD_ERROR => '此目录有子目录,不能移动目录',
        self::KNOWLEDGE_NOT_HAVE_AUTH_ERROR => '暂无查看权限',
        self::KNOWLEDGE_HAS_USE => '此知识已在任务中使用,不能删除',
        self::ORG_NOT_FIND_IN_KNOWLEDGE => '此公司暂未开通微问功能',
        self::USER_NOT_PERMISSION => '抱歉,你没有访问此知识的权限!',
        self::KNOWLEDGE_TOKEN_ERROR => 'Token值错误!',
        self::COURSE_IS_NOT_COMPANY => '此课程不是公司自建课程,不能设置公共的课',
        self::COURSE_TYPE_IS_NOT_ALLOWED => '直播课不能设置为公共课',
        self::ROOT_DIRECTORY_CANNOT_DELETE_ERROR => '默认的课程目录不能被删除',
        self::DIRECTORY_LEVEL_MAX_LIMIT => '目录层级最多不超过5级',
        self::DIRECTORY_PARENT_NOT_CHILD => '本目录的下级目录不能作为上级目录',

        self::COURSE_DIR_NOT_SETTING=>"当前目录不支持设置跟随上级目录",
        self::ASSIGN_TASKS_EID_ASSIGNED => '该学员已指派任务',
        self::ASSIGN_TASKS_NO_AUTH => '您没有权限操作该指派',
        self::ASSIGN_TASKS_NOT_FOUND => '未找到对应指派任务',
        self::ASSIGN_TASKS_NO_AUTH_WRITE => '抱歉！您无权限提交心得体会',

        self::COURSE_NOT_EXIST => '该课程不存在',
        self::COURSE_IS_SELF => '不能收藏自己创建的课程哦',
        self::COURSE_HAS_FOLLOWED => '你已收藏了该课程',
        self::COURSE_HAS_USED_USER => '指定的用户已有此课程',
        self::COURSE_EXIST_IN_GROUP => '该课程已存在',
        self::SERIES_GROUP_ORDER_EXISTS => '排序值已存在',
        self::IMG_LIMIT_ERROR => '图片大小超过限制',
        self::FILE_LIMIT_ERROR => '文件大小超过限制',
        self::FILE_READ_FAIL => '无法读取文件，请按要求上传',
        self::UPLOAD_FILE_FAIL => '上传文件失败',
        self::SECURITY_RULE_INVALID_IP_CONFIG => '错误IP白名单配置',

        self::POSITION_ERROR_UNDEFINED => '未知的岗位错误',
        self::POSITION_NOT_FOUND => '岗位不存在',
        self::POSITION_NUMBER_OCCUPIED => '岗位编号已被占用',
        self::POSITION_CATEGORY_DELETE_CONTAINS => '分组里存在岗位,无法删除',
        self::POSITION_CATEGORY_NOT_FOUND => '岗位分组不存在',
        self::POSITION_EMPLOYEE_USED => '岗位被使用',
        self::POSITION_TARGET_INCLUDE_SELF => '目标岗位不能是自身',

        self::MEDAL_SCORE_EXIST => '勋章分数已存在',
        self::MEDAL_NAME_EXIST => '勋章名称已存在',
        self::BANNER_SORT_EXIST => '优先级已存在',
        self::BANNER_TOTAL_NUM => '轮播图已达最大数量',
        self::MEDAL_SCORE_INSUFFICIENT => '学分不足',
        self::NOT_AUTH_DEPT => '此部门没有设置权限',
        self::NOT_REPEAT_DEPT => '此部门已设置，不能重复添加',

        self::ORDER_COURSE_ERROR => '订单里的课程数据拼装错误',
        self::ORDER_ACCREDIT_ERROR => '订单授权失败',
        self::ORDER_PAY_REFUND => '订单转入退款',
        self::ORDER_PAY_NOTPAY => '订单未支付',
        self::ORDER_PAY_CLOSED => '订单已关闭',
        self::ORDER_PAY_REVOKED => '订单已撤销（刷卡支付）',
        self::ORDER_PAY_USERPAYING => '订单用户支付中 ',
        self::ORDER_PAY_PAYERROR => '订单支付失败',
        self::ORDER_COURSE_EXIST => '您加入的免费课，或加密课已存在',

        self::DEPT_UNDEFINED_ERROR => '未知的部门错误',
        self::DEPT_NOT_FOUND => '部门不存在',
        self::DEPT_NON_GROUP_DENY_CHILD => '不能在未分组下创建下级部门',
        self::DEPT_DUPLICATED_IN_BRANCH => '当前节点部门已存在',
        self::DEPT_DENY_CHILD => '不能在该部门下创建下级部门',
        self::DEPT_NAME_EDIT_DISABLED => '该部门名称禁止编辑',
        self::DEPT_EDIT_DISABLED => '该部门禁止编辑',
        self::DEPT_EMPLOYEE_EXISTS => '该部门存在员工，无法执行操作',
        self::DEPT_NO_EXISTS => '部门编号已存在',
        self::DEPT_PARENT_NOT_FOUND => '上级部门不存在',

        self::EMPLOYEE_UNDEFINED_ERROR => '未知的错误',
        self::EMPLOYEE_NOT_FOUND => '员工不存在',
        self::EMPLOYEE_DISPLAY_OCCUPIED => '姓名已被占用',
        self::EMPLOYEE_NUMBER_EXISTS => '员工编号已被占用',
        self::EMPLOYEE_NOT_FOUND_OR_DISABLED => '用户不存在或者被禁用',
        self::EMPLOYEE_LIMIT_EXCEEDS => '员工数量已达上限',
        self::EMPLOYEE_MOBILE_OCCUPIED => '手机号已被使用',
        self::EMPLOYEE_EMAIL_CAPTCHA_INVALID => '无效的邮箱验证码',
        self::EMPLOYEE_EMAIL_OCCUPIED => '该邮箱已被使用',
        self::EMPLOYEE_IMPORT_TEMPLATE_INVALID => '无效的导入模板',
        self::EMPLOYEE_USERNAME_USED => '用户名已被使用',

        self::ACTIVITY_NAME_EXIST => '活动名称已存在',
        self::EMPLOEE_NO_AUTH => '您不是该公司员工',
        self::EMPLOEE_NOT_EXIST => '员工不在系统中',
        self::EXPIRY_TIME_CAN_NOT_EMPTY => '报名截止日期必填',
        self::EXCEEDING_LIMIT => '活动人员超过活动最大人数',
        self::END_TIME_WRONG => '结束时间要大于开始时间',
        self::EXPIRY_TIME_WRONG => '报名截止日期要小于等于活动结束日期',

        self::COURSE_NOT_ALLOW_REMOVE => '课程结束不满7天，不允许删除/下架',
        self::COURSE_NOT_OVER => '课程还未结束',
        self::COURSE_IS_OVER => '课程已结束',
        self::COURSE_NOT_AUTH_VIEW => '无权限查看课程',
        self::COURSE_UPLOAD_AUDIO_ERROR => '上传音频文件失败',
        self::COURSE_AUDIO_EMPTY => '请生成音频文件',
        self::COURSE_HAS_USED => '课程正在被使用，不允许删除',
        self::COURSE_NOT_AUTH => '暂无查看权限',
        self::COURSE_NO_EXISTS => '课程不存在',
        self::SERIES_CREATE_COURSE_FILE_LIMIT=>"一次只能创建10个课程",

        self::FAVORITE_HAS_EXISTS_ERROR => '已经收藏此内容',
        self::FAVORITE_NO_EXISTS_ERROR => '你还没有收藏此内容,无法取消收藏',
        self::COMMENT_NOT_EXISTS_ERROR => '评论不存在',
        self::EMPTY_MISTAKE_QUESTION => '暂无错题',
        self::COMMENT_NOT_ROLE_ERROR => '评论只能管理员和本人删除',

        self::SIGN_DAILY_SIGNED => '今天已签到',
        self::PK_CREATE_ERROR => 'PK创建失败',
        self::PK_DETAIL_ERROR => 'PK详情获取失败',
        // self::PK_DETAIL_ERROR => 'PK保存失败',
        self::VOTE_TOPIC_EXIST => '投票主题已存在',
        self::VOTE_NO_PERMISSIONS => '非成员不能参加投票',

        self::REPLY_EXIST => '已有回复,不能删除',
        self::NOT_ISSUE_CREATOR => '非问题创建者,不能操作',
        self::NOT_REPLY_CREATOR => '非回答创建者,不能操作',
        self::SURVEY_TITLE_EXIST => '调研的标题已存在',
        self::SURVEY_NO_PERMISSIONS => '非成员不能参加调研',
        self::TEAM_USED => '该团队下有知识不能删除',
        self::TEAM_NAME_EXIST => '团队名称不能重复',
        self::SURVEY_NOT_ENABLED => '调研已禁用',
        self::SURVEY_NOT_START => '调研未开始',
        self::SURVEY_IS_OVER => '调研已结束',

        self::LIEVROOM_NOT_FOUND => '直播间不存在',
        self::QUESTION_NOT_RECOGNIZE => '不能识别',
        self::VENDOR_OLD_PASSWORD_WRONG => '供应商原密码错误',
        self::VENDOR_NEW_PASSWORD_WRONG => '新密码不能与原密码相同',

        self::COURSE_REPOSITORY_HAS_USED => '课程正在被使用,不能移出课程库',
        self::COURSE_REPOSITORY_HAS_USED_BANNER => '课程被推荐或者轮播图使用,不能移出',
        self::COURSE_REPOSITORY_CANNOT_REMOVE => '非超级管理员不能移除课程',
        self::COURSE_CONSUMER_POINT_NOT_ENOUGH => '积分不够',
        self::TASK_TITLE_EXIST => '作业名称已存在',

        self::TRAINING_PLAN_EXIST => '培训计划名称已存在',
        self::TRAINING_TASK_GROUP_EXIST => '分组名称已存在',
        self::TRAINING_PROJECT_PUSH_FAULT => '审批提交失败',
        self::TRAINING_PROJECT_HAS_PUSH => '已提交审批',
        self::TRAINING_ACTIVE_HAS_SUBMIT => '活动已提交，请勿修改',
        self::TRAINING_HAS_SPLITED => '计划已分解过，请勿重复分解',
        self::TRAINING_MONTH_NO_SPLITED => '月度计划无法分解',
        self::TRAINING_YAER_NOT_FOUND => '计划年份未设置，无法分解',
        self::TRAINING_PLAN_NO_ACTIVE => '计划里没有活动，无法分解',

        self::HEADLINE_NO_ASSESS => '无操作权限',
        self::HEADLINE_NO_OPEN => '功能被禁用',
        self::PERMISSION_ROLE_EXIST => '角色名称已存在',
        self::PERMISSION_ROLE_CLASSIFY_EXIST => '角色分类名称已存在',
        self::PERMISSION_ROLE_EXISTS => '该分类下已存在角色',
        self::PERMISSION_ROLE_FUNCTION_EMPTY => '功能权限不能为空',

        self::QUEUE_EXISTS => '任务正在执行，请稍后再试',

        self::DEMO_ACCOUNT_TIMEOUT => '试用账号到期',
        self::DEMO_ACCOUNT_NO_TRIAL => '试用账号开通中',

        self::LHA_OP_ERROR => '该申请已通过或已拒绝',
        self::INTEGRAL_ORDER_FAIL => '积分或库存不足',
        self::INTEGRAL_PRODUCT_EXISTS => '商品名称已存在',
        self::INTEGRAL_ORDER_LIMIT => "当前商品兑换次数已达上限",
        self::INTEGRAL_ORDER_LIMIT_TIME => "已超出商品兑换时间",
        self::INTEGRAL_ORDER_ADDRESS => "你的收货地址格式不对，缺少省、市、区，请先补充该信息，否则将影响您正常收货",



        self::KNOWLEDGE_POINT_NAME_HAS_EXISTS => '知识点名称已存在',
        self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => '知识点不存在',

        self::LOGIN_NEED_ACCOUNT_CODE => '缺少公司编号',
        self::LOGIN_INVALID_ACCOUNT_CODE => '无效公司编号',
        self::USER_RESET_PASSWORD_EMAILS_ERROR => '此邮箱对应多个账户,不能使用找回',
        self::LOGIN_USER_MOBILE_NOT_BINDING => '手机号未绑定，无法登录',
        self::LOGIN_MOBILE_USED_MANY => '该手机号被多人使用，无法登录',
        self::LOGIN_IP_BLOCKED => 'IP已被阻止',
        self::USER_EXPIRED => '用户已过期',

        self::ASSESSMENT_TOPIC_EXIST => '评估名称已存在',
        self::ASSESSMENT_NO_PERMISSIONS => '无权限创建评估',
        self::ASSESSMENT_PARTAKE_NO_PERMISSIONS => '抱歉,您没有参与此评估的权限!',
        self::ASSESSMENT_END => '抱歉,评估已结束',

        self::OFFLINE_TEACHING_NAME_EXIST => '该名称的面授课已存在',
        self::OFFLINE_TEACHING_USED => '该课已被智能班级使用，不能删除',
        self::OFFLINE_TEACHING_RECORD_CANT_DELETE => '该记录已经审核通过，不能删除',

        self::COURSE_HAVE_ESTIMATE => '你已经评价过了,不能再评论了哦',
        self::COURSE_NO_PERMISSION => '无操作权限',

        self::PLATFORM_NOT_SETTING_DING => '第三方平台未绑定钉钉',
        self::PRODUCT_NOT_ENOUGH => '礼物数量不足',

        self::BASE_OBJECT_THUMBED_UP => '该对象已经被点赞过了',
        self::BASE_OBJECT_CATEGORY_NOT_FOUND => '分组不存在',
        self::BASE_OBJECT_CATEGORY_USED => '分组已经被使用',

        self::CIRCLE_APPLICATION_FAULT => '已经加入该圈子，不能重复加入',
        self::CIRCLE_TOPIC_EXISTS => '话题名称不可重复',
        self::CIRCLE_IS_USED => '问答圈已占用，不可删除',
        self::CIRCLE_NO_PERMISSION => '不在问答圈范围内',
        self::CIRCLE_INFO_NOT_FOUND => '帖子/问题不存在',
        self::CIRCL_VIEWE_NO_PERMISSION => '暂无查看权限',
        self::ROBOT_ANSWER_NOT_FOUND => '未找到指定机器人回答',
        self::ROBOT_ANSWER_HAD_PROGRESS => '该机器人回答已审核',
        self::CIRCLE_QUESTIONS_IS_NULL => '请确认问题内容是否正确',
        self::CIRCLE_ROBOT_NOT_OPEN => '机器人回答未开启',
        self::ROBOT_ANSWER_GET_ERROR => '机器人回答获取失败',
        self::CIRCLE_APPROVAL_LIMIT => '批量审核数量超过限制，请重新选择',
        self::CIRCLE_APPROVAL_HAD => '有已完成的审核数据，请重新选择',
        self::CIRCLE_REPLY_BANNED_POST => '您已被禁言，暂无法评论',

        self::GAME_UNDEFINED => '未知错误',
        self::GAME_BEYOND_ATTEMPT => '超过了尝试次数',
        self::GAME_WON_ALREADY => '您已经中过奖了',
        self::GAME_PRIZE_DEPLETED => '已无奖品',
        self::GAME_NOT_ENABLED => '游戏未启用',
        self::GAME_NOT_START => '游戏未开始',
        self::GAME_OVER => '游戏已结束',
        self::GAME_NOT_OPEN => '开奖未开始',
        self::GAME_PEOPLE_NUM_NOT_ENOUGH => '开奖人数不够',
        self::GAME_NUMBER_EXISTS => '竞赛编号已存在',
        self::GAME_DUMMY_FREQUENT => '网络系统繁忙,请稍后再试',
        self::GAME_INVAID_PARTICIPANT => '无效的参与者',
        self::GAME_OP_FREQUENT => '操作过于频繁，请稍候再试',

        self::SYNC_ERROR_DATA_FORM_ERROR => '请求的数据格式不对,请检查数据格式',

        self::FUNDING_IS_JOIN => '已参与',
        self::FUNDING_IS_APPLY => '已报名',

        self::COIN_NOT_SUFFICIENT_FUNDS => '金币余额不足',
        self::COURSE_CATEGORY_NAME_EXISTS => '课程分类名称已存在',
        self::COURSE_CATEGORY_HAS_USED => '课程分类正在被使用',
        self::SKILLED_CATEGORY_NAME_EXISTS => '名称已存在',
        self::SKILLED_CATEGORY_HAS_USED => '此擅长类别正在被使用',

        self::OFFLINE_ASSESSMENT_USED => '鉴定已开始',
        self::OFFLINE_ASSESSMENT_TEMPLATE_USED => '鉴定模板已经开始使用，不能删除',
        self::OFFLINE_ASSESSMENT_REACH_RE_NUM => '可重复考核的次数已用完',
        self::OFFLINE_ASSESSMENT_CANT_RE => '该考核不可重复考核',
        self::OFFLINE_ASSESSMENT_NO_ACL => '暂无操作权限，请联系管理员',

        self::SMS_CAPTCHA_SMS_INVALID => '短信验证码有误',
        self::SMS_CAPTCHA_SMS_EXPIRED => '短信验证码已过期',
        self::SMS_LIMIT_EXCEEDS => '验证码未失效',

        self::LEARNING_PROJECT_NO_EXISTS => '项目编号已存在',

        self::LEARNING_SIGN_INVALID => '无效的签到',
        self::LEARNING_SIGN_NONSUPPORT_CODE => '该签到不支持签到码签到',
        self::LEARNING_SIGN_CODE_ERROR => '签到码错误',
        self::LERN_SIGN_UNAUTHORIZED_PARTICIPATION => '无权限',
        self::LERN_SIGN_PASSWORD_ERROR => '密码错误',

        self::LIVE_INVALID => '无效的直播',
        self::LIVE_NOT_FOUND => '直播不存在',
        self::LIVE_NO_PERMISSION => '无权限',
        self::LIVE_ROOM_NOT_FOUND => '直播间不存在',
        self::LIVE_MEMBER_IS_EXISTS => '已存在',
        self::LIVE_MEMBER_IS_NULL => '您选择的人员为空',
        self::LIVE_APPROVED_EXISTS => '已存在上麦人员',
        self::LIVE_LECTURER_NOT_REQUEST => '未发起上麦操作',
        self::LIVE_LECTURER_NOT_APPROVED => '未被允许上麦',
        self::LIVE_LECTURER_APPROVED_ALREADY => '已允许上麦',
        self::LIVE_COMPERE_IN_LECTURERS => '主持人不可以设置为讲师',

        self::LECTURER_LEVEL_STANDARD_MUST_SET => '讲师评级指标至少设置一项',
        self::LECTURER_INSIDE_IS_EXISTS => '该员工已经是讲师',
        self::LECTURER_INSIDE_TYPE_ERROR => '内部讲师格式错误',
        self::LECTURER_NUMBER_REPEAT => '讲师编号已存在',
        self::LECTURER_ORDER_AUDITOR => '预约已被审核',
        self::LECTURER_DATE_ORDERED => '讲师时间范围已被预约',
        self::LECTURER_DATE_DISENABLED => '讲师时间段不可预约',
        self::LECTURER_PROJECT_REPEAT => '认证项目已有编号',
        self::LECTURER_PROJECT_UNEXISTS => '认证项目不存在',
        self::LECTURER_PROJECT_ALREADY_ENDED => '认证项目已结束',
        self::LECTURER_PROJECT_APPLICATION_NOT_ALLOWED => '认证项目未开放报名',
        self::LECTURER_PROJECT_NO_VISIT_AUTH => '无权限报名',
        self::LECTURER_PROJECT_LEARNER_ALREADY_EXIST => '成员已存在',
        self::LECTURER_PROJECT_LEARNER_UNDER_REVIEW => '成员审核中',
        self::LECTURER_PROJECT_LEARNER_OVERSTEP => '报名人数上限',
        self::LECTURER_PROJECT_ENROLL_HIRE_NOT_EXISTS => '入职日期缺失',
        self::LECTURER_PROJECT_ENROLL_HIRE_NOT_SUBSTANDARD => '入职天数不达标',

        self::JOBLEVEL_NOT_FOUND => '职级不存在',
        self::JOBLEVEL_NO_EXISTS => '职级编号已存在',
        self::JOBLEVEL_NAME_EXISTS => '职级名称已存在',
        self::JOBLEVEL_USED => '职级已被使用',
        self::JOBLEVEL_ORDER_EXISTS => '职级排序已存在',

        self::QUE_EXISTS => '任务正在执行，请稍后再试',

        self::EMP_GRP_NOT_FOUND => '人群不存在',
        self::EMP_GRP_USED => '当前人群下有人员，不允许删除',
        self::EMP_GRP_NOT_DYNAMIC => '该人群不是动态人群',

        self::OFFLINE_ASSESSMENT_MUST_NUM_MORE => '通过规则中的必过题数多于实际必过题数',
        self::EXAM_DATA_PROCESSING => '试题数据处理中',
        self::EXAM_APPROVE_NOT_FOUND => '考试批阅不存在',
        self::EXAM_UNFINISH_NOT_FOUND => '您的考试已提交',
        self::EXAM_MARKING => '批阅中',

        self::CASE_DIRECTORY_IS_EXISTS => '目录已存在',
        self::CASE_DIRECTORY_NOT_FOUND => '目录不存在',
        self::CASE_DIRECTORY_PARENT_NOT_FOUND => '父级目录不存在',
        self::CASE_DIRECTORY_SORT_DIFFERENT_PARENTS => '仅能对具有相同父级的目录进行排序',
        self::CASE_DIRECTORY_GT_MAX_LEVEL => '目录仅支持3级',
        self::CASE_DIRECTORY_HAVE_CHILD => '该目录拥有子集',
        self::CASE_ATTACHMENT_IS_NECESSARY => '您使用的模板，附件为必传项',
        self::CASE_ATTACHMENT_IS_OVERFLOW => '上传附件数量已达上限，无法继续上传',
        self::CASE_ATTACHMENT_UNSUPPORTED_FILE_TYPES => '不支持上传的附件类型',
        self::CASE_STAGE_IS_EXISTS => '已存在的阶段名称',
        self::CASE_TEMPLATE_NOT_FOUND => '模板不存在',
        self::CASE_TEMPLATE_NO_IS_EXISTS => '模板编号已存在',
        self::CASE_TEMPLATE_TITLE_IS_EXISTS => '模板名称已存在',
        self::CASE_POINT_NAME_HAS_EXISTS => '行业名称已存在',
        self::CASE_POINT_NOT_EXISTS_ERROR => '行业不存在',


        self::LEARNING_TEMPLATE_NO_GROUP_CANT => '未分组不可以删除和修改',
        self::LEARNING_TEMPLATE_TITLE_EXISTS => '此分组名称已存在',
        self::LEARNING_TEMPLATE_TITLE_IS_USED => '分组已经被使用，无法删除',
        self::EXAM_UNAUTHORIZED_PARTICIPATION => '您无权限参与该考试',
        self::VOTE_UNAUTHORIZED_PARTICIPATION => '您无权限参与该投票',
        self::VOTE_HAVE_CLOSED => '该投票已结束',
        self::VOTE_UN_START => '该投票未开始',
        self::VOTE_OPEN_NO_EDIT => '公开投票不允许修改',
        self::VOTE_IS_REPEAT_NO_EDIT => '多次投票不允许修改',
        self::VOTE_RESULT_NOT_FOUND => '投票结果没有找到',
        self::VOTE_RESULT_HAS_EXAMINE => '投票已审核，不允许修改',
        self::ASSESSMENT_TEMPLETE_USED => '此模板已被使用，无法删除',
        self::SURVEY_TEMPLETE_USED => '此模板已被使用，无法删除',
        self::ASSESSMENT_TEMPLETE_TITLE_EXIST => '评估模板名称已存在',
        self::SURVEY_TEMPLETE_TITLE_EXIST => '调研模板名称已存在',
        self::ASSESSMENT_TEMPLETE_NO_EXIST => '评估模板编号已存在',
        self::SURVEY_RE_NUM_FULL => '重复调研次数已满',
        self::SURVEY_ANSWER_IS_REPEAT => '不可重复的填空题的答案重复',

        self::SURVEY_NOTIFY_UNPUBLISHED => '调研未发布，不允许发送通知',
        self::SURVEY_NOTIFY_END => '调研已结束，不允许发送通知',
        self::SURVEY_NEED_LOGIN => '该调研需要登录',

        self::FACE_MATCHING_SOURCE_EXISTS => '人脸对比模板已存在',
        self::FACE_MATCHING_DETECT_FAIL => '人脸对比失败',
        self::FACE_MATCHING_SOURCE_NOT_EXIST => '人脸对比模板不存在',
        self::FACE_MATCHING_STORAGE_FOLDER_CREATE_FAIL => '无法创建存储目录',
        self::FACE_MATCHING_INVALID_FILE_TYPE => '不支持的图片格式',
        self::FACE_MATCHING_INVALID_FILE => '不支持的文件格式',

        self::APPROVAL_CATEGORY_IS_EXISTS => '分类已存在',
        self::APPROVAL_CATEGORY_IS_USED => '分类已被使用，无法删除',
        self::APPROVAL_PROCESS_IS_EXISTS => '审批流程已存在',
        self::APPROVAL_LEVEL_IS_EXISTS => '审批层级已存在',
        self::APPROVAL_PROCESS_NOT_ENABLED => '公司无启用的审批流',
        self::APPROVAL_REVIEW_EMPLOYEE_MUST => '必选选择审批人',
        self::COURSE_REVIEW_NO_AUTH => '无课程审批权限',

        self::COMPETITION_ROUND_START_ERROR => '轮次开始时间或结束时间不正确',
        self::COMPETITION_CANT_RECEIVE_AWARD => '无权获得赛季大奖',
        self::COMPETITION_JS_NO_IS_EXISTS => '竞赛编号不可重复',
        self::COMPETITION_NOT_IN_VOTE_RANGE => '不在投票范围内',
        self::COMPETITION_ROUND_IS_END => '本轮次已经结束，不可删除',
        self::COMPETITION_ROUND_IS_START => '本轮次已经开始，不可修改和删除',
        self::COMPETITION_APPLY_TIME_ERROR => '报名设置时间错误',
        self::COMPETITION_NOT_HAVE_ROUND => '请先添加轮次信息，再发布',
        self::COMPETITION_NOT_BEGIN => '竞赛暂未开始',
        self::COMPETITION_ACHIEVEMENT_GROUP_USED => '此战队在对战组中，请先删除该对战队，再尝试...',
        self::COMPETITION_ACHIEVEMENT_BATTLE_EXISTS => '该对组战队已存在',
        self::COMPETITION_ACHIEVEMENT_HELP_EXISTS => '在该PK中已经助力完成',
        self::COMPETITION_VOTE_EXISTS => '今日已投',
        self::COMPETITION_IS_USED => '竞赛被占用，无法删除',
        self::COMPETITION_NOTIFY_UNPUBLISHED => '竞赛未发布，不允许发送通知',
        self::COMPETITION_NOTIFY_END => '竞赛已结束，不允许发送通知',
        self::COMPETITION_VOTE_NOT_STARTED => '投票未开始',
        self::COMPETITION_VOTE_ALREADY_ENDED => '投票已结束',
        self::COMPETITION_NOT_FOUND => '比赛不存在',
        self::COMPETITION_NO_PERMISSION => '您无权限参与该比赛',

        self::POSITION_COMPETENCY_CATEGORY_EXISTS => '胜任力指标分类已存在',
        self::POSITION_COMPETENCY_CATEGORY_NOT_FOUND => '胜任力指标分类不存在',
        self::POSITION_COMPETENCY_EXISTS => '胜任力指标已存在',
        self::POSITION_COMPETENCY_NOT_FOUND => '胜任力指标不存在或者已被删除',
        self::POSITION_COMPETENCY_ELEMENT_EXISTS => '能力指标已存在',
        self::CATEGORY_NAME_EXIST => '分类已存在',

        self::POSITION_SKILL_CATEGORY_EXISTS => '技能分类已存在',
        self::POSITION_SKILL_CATEGORY_NOT_FOUND => '技能分类不存在',
        self::POSITION_SKILL_EXISTS => '技能已存在',
        self::POSITION_SKILL_NOT_FOUND => '技能不存在或者已被删除',
        self::POSITION_SKILL_ELEMENT_EXISTS => '技能已存在',
        self::SKILL_NOT_EXISTS => '能力模型下缺少技能',

        self::INSPECTION_ELECTIVE_TASK_UNFINISHED => '您有未完成的任务',
        self::INSPECTION_ELECTIVE_CLASSIFY_UNFINISHED => '您的考核有未完成的分类',
        self::INSPECTOR_IS_NOT => '您不是巡检员',
        self::INSPECTION_AT_LEAST_ONE => '请至少完成一个考核',

        self::HARMONY_ERROR => '包含敏感信息，无法显示结果',

        self::RETRAINING_NO_EXISTS => '编号已存在',
        self::RETRAINING_NO_TASKS => '请先添加模板任务',
        self::RETRAINING_NOT_ALLOWED_REPEAT => '再认证暂未开启',
        self::RETRAINING_REACH_CYCLE_INDEX => '您的循环认证次数已到',
        self::RETRAINING_TIME_NOT_UP => '再认证时间未到',
        self::RETRAINING_LEARNER_AUTHENTICATE_ONGOING => '您还有进行中的认证，请勿重复认证',
        self::RETRAINING_EXAM_INVALID => '无效的认证与再培训考试',
        self::APPRIAISAL_POSITION_SKILL_EXISTS_ELEMENT => '岗位认证存在技能，先从岗位认证删除技能',
        self::RETRAINING_NOT_EXISTS => '很抱歉，该认证与再培训不存在！',
        self::RETRAINING_LEARNER_NOT_PUBLISHED => '很抱歉，该认证与再培训暂未对外公开！',
        self::RETRAINING_LEARNER_NOT_AUTH => '很抱歉，您不在本次认证与再培训范围内！',

        self::EXPERIENCE_DETAIL_BEYOND_LIMIT => '您上传的心得数量已达上限',

        self::PHOTOGRAPH_DETAIL_BEYOND_LIMIT => '您上传的拍照已达上限',
        self::PHOTOGRAPH_LEARNER_NOT_EXISTS => '学员不在该班级下',
        self::PHOTOGRAPH_LEARNER_SUPPORT_EXISTS => '学员已点过赞',
        self::PHOTOGRAPH_LEARNER_SUPPORT_MAX => '点赞已超过最大限制',

        self::CERTIFICATION_USED => '证书使用中，无法删除或禁用',
        self::CERTIFICATION_USER_USED => '证书人员无法删除',
        self::DIRECTORY_PARENT_NOT_SAME_SELF => '父目录不能为本目录',
        self::NOT_GROUP_CANNOT_SELECTED => '未分组目录不能选择',

        self::EVENT_MEMBER_SIGN_INVALID_CAPTCHA => '无效的短信验证码',
        self::EVENT_MEMBER_SIGN_VX_INVALID_ACCESS_TOKEN => '无效的access_token',
        self::EVENT_MEMBER_SIGN_VX_INVALID_PWD => '无效的签到口令',

        self::GEN_LIVE_CREATE_ERROR => '直播创建失败',
        self::GEN_LIVE_NOT_EXISTS => '直播不存在',
        self::GEN_LIVE_UPDATE_ERROR => '直播更新失败',
        self::GEN_LIVE_INVALID_INPUT => '直播审核参数失败',
        self::GEN_LIVE_MEMBER_NOT_ALLOWED => '无权限查看直播',
        self::COURSE_MULTI_DIRECTORY_LIMIT_ERROR => '副目录不能超过5个',
        self::GEN_LIVE_GENERATE_TIME => '离上次生成数据时间不超过10分钟，请稍后再试',
        self::GEN_LIVE_LIMIT_ATTENDEES => '直播人数超过限制，请修改或联系工作人员',
        self::GEN_LIVE_NO_AUTH => '请登录',

        self::KNOWLEDGE_BASE_NAME_EXIST => '知识库名称已经存在',
        self::KNOWLEDGE_BASE_NOT_EXIST => '知识库不存在',
        self::KNOWLEDGE_QUESTION_HAS_EXISTS => '此问题在此知识库下已存在',
        self::KNOWLEDGE_CATEGORY_CANNOT_DELETE => '默认分类不能删除或编辑',
        self::KNOWLEDGE_CATEGORY_CANNOT_EQ_ROOT_NAME => '分类名称不能为默认分类',
        self::KNOWLEDGE_CATEGORY_HAS_QUESTION => '此分类下有问题，不能删除',
        self::KNOWLEDGE_QUESTION_NOT_EXISTS => '知识库问题不存在',
        self::KNOWLEDGE_CATEGORY_NAME_EQ => '分类名称没有变',
        self::KNOWLEDGE_QUESTION_IS_SYSTEM => '此问题为系统复制，您不可以修改哦',
        self::KNOWLEDGE_BASE_HAS_QUESTION => '此知识库下有问题，不能删除',
        self::KNOWLEDGE_APPLY_EXIST => '申请已存在',

        self::EVENT_PRIZE_IS_GAIN => '该奖品已有获奖人员，不可删除',
        self::EVENT_ALLOW_NUM_MORETHAN_EXISTS => '奖品的已获得人数大于设置数',
        self::EVENT_DESIGATED_IS_HAVED => '奖品已屏蔽中奖人，此人已在他处作弊',
        self::EVENT_DESIGATED_IS_OVERFLOW => '作弊人数大于奖品数量',
        self::EVENT_NOT_START => '活动未开始',
        self::EVENT_END => '活动已结束',

        self::EVENT_MEMBER_SIGNED => '已签到',
        self::COURSE_HAVE_LIMIT => '课程还未学完，需学完才能评分',
        self::COURSE_TYPE_NOT_EQ => '两次课件的类型不一样，请上传同样的文件类型',
        self::COURSE_MUST_END => '课程还未学完，需学完才能参与测验',
        self::EXPORT_LIMIT => '抱歉，您不能导出数据',
        self::COURSE_STAR_LIMIT => '评分超限制',

        self::INSPECTION_QUESTION_CATEGORY_USED => '分类正在使用，无法删除',
        self::TASK_NO_PERMISSIONS => '您无权限参与该作业',
        self::TASK_END => '作业已结束，无法参与',
        self::OFFLINEEXERCISE_NO_PERMISSIONS => '您无权限参与该线下练习',
        self::CONTRACT_TYPE_USED => '合同类型正在使用',

        self::GEN_LIVE_CATEGORY_NOT_REMOVE => '分类已使用，不能删除',


        self::QUESTION_NO_EXISTS => '编号已存在',

        self::SPECIAL_SUBJECT_NO_USED => '编号已被占用',

        self::EMP_SELF_REG_DATA_INVALID => '表单数据验证失败，请检查数据',
        self::EMP_SELF_REG_UNIQUE => '表单数据不唯一',
        self::EMP_SELF_REG_UNIQUE_USERNAME => '用户名已被使用或者已申请注册',
        self::EMP_SELF_REG_MOBILE_CAPTCHA_FAIL => '验证码验证失败',
        self::EMP_SELF_REG_UNIQUE_ID_NUMBER => '您已注册，登录即可',

        self::DAILY_CLOCK_CANT_PUBLISH => '每日打卡开始时间已开始，不可发布',

        self::TRAINING_CENTER_UNDEFINED => '培训中心未知错误',
        self::TRAINING_CENTER_EXISTS => '培训中心已存在',
        self::TRAINING_CENTER_NOT_FOUND => '培训中心不存在',
        self::TRAINING_CENTER_NO_EXISTS => '编号已被使用',
        self::TRAINING_CENTER_MAX_LEVEL => '已达到最大层级',
        self::TRAINING_CENTER_USED => '该培训中心正被使用中',
        self::TRAINING_CENTER_NOT_LEAF => '该培训中心包含子培训中心',
        self::VOTE_NO_REPEAT => '不允许重复投票',
        self::KNOWLEDGE_CONTAIN_AUDIT_IDS => '提交知识不能包含审核中和已通过的',

        self::COURSE_HUNDUN_SIGN_ERROR => '签名错误',
        self::COURSE_HUNDUN_PARAMS_ERROR => '参数错误',
        self::COURSE_HUNDUN_NO_AUTH => '暂无查看权限',
        self::COURSE_HUNDUN_TIME_OVERDUE => '请求已过期',
        self::COURSE_HUNDUN_USER_TOKEN_INVALID => '用户token失效',
        self::COURSE_HUNDUN_DATA_ERROR => '数据错误',
        self::COURSE_HUNDUN_CHECK_ERROR => '校验失败',
        self::COURSE_HUNDUN_USER_REGISTER_REACH_LIMIT => '注册账号已达上限',
        self::COURSE_HUNDUN_USER_REGISTED => '用户已经注册过',
        self::COURSE_MODULE_UN_REGISTED => '暂无查看权限',

        self::LPP_NOT_FOUND => '弹题不存在或已删除',
        self::LPP_CREATE_FAIL => '创建失败',
        self::LPP_UPDATE_FAIL => '更新失败',
        self::LPP_TIME_LARGER_DURATION => '时间点大于课程时长',
        self::LPP_TIME_DUPLCATED => '存在时间点重复',
        self::LPP_OPTION_ID_DUPLICATED => '存在重复的选项ID',
        self::LPP_OPTION_INVALID_COUNT => '错误的正确答案选项数量',

        //积分审核
        self::SCORE_TYPE_EXISTS => "积分类型已存在",
        self::SCORE_TYPE_NO_EXISTS => "积分类型不存在",
        self::SCORE_APPLY_NO_EXISTS => "积分申请不存在",
        self::SCORE_APPLY_STATE_ERROR => "积分申请状态错误",
        self::SCORE_APPLY_NO_CHECKING => "无审核的积分申请",

        //消耗品管理
        self::CONSUMABLE_EXISTS => "消耗品已存在",
        self::CONSUMABLE_NO_EXISTS => "消耗品不存在",


        self::LIVE_HON_SHAN_TIME_ERROR => '时间需要大于当前时间',
        self::LIVE_HONGSHAN_HAS_END => '直播已结束或会议不存在',

        self::SHORTLINK_INVALID_URL => '无效的链接',
        self::TRAINING_TASK_END => '项目已完成',
        self::TRAINING_HAS_USE => '项目已关联班级',


        self::GZ_WATCH_CARD_NO_OR_DISPLAY_ERROR => '身份证号或姓名错误',
        self::KNOWLEDGE_POINT_CATEGORY_EXISTS => '分类名称已存在',
        self::LIVE_ROLE_ERROR => '角色与直播不匹配',
        self::LIVE_UN_DELAYED => '没有开通无延迟直播',


        self::NOT_ENOUGH_SCORE => '没有足够的积分',
        self::POSITION_GRADING_NO_QUESTION => '暂无试题',

        self::GRADE_SETTING_NAME_EXISTS_ERROR => '等级已存在',
        self::GRADE_SETTING_LIMIT => '最多可添加5个等级',

        self::AI_SCENARIO_NOT_FOUND => '情景模拟不存在',
        self::AI_SCENARIO_NODE_NOT_FOUND => '情景模拟节点不存在或已删除',
        self::AI_SCENARIO_NOT_PUBLISHED => '情景模拟未发布',
        self::AI_SCENARIO_COPY_FAIL => '复制失败，请重试',
        self::AI_SCENARIO_PROCESS_NOT_FOUND => '未设置情景模拟内容',
        self::AI_SCENARIO_PROCESS_NEXT_NODE_NOT_FOUND => '没有下一题或者已被删除',
        self::AI_SCENARIO_PROCESS_PREV_NODE_NOT_PASSED => '前题未答，无法获取下一题',
        self::AI_SCENARIO_PROCESS_NODE_ANSWERED => '该题已经答过了',
        self::AI_SCENARIO_SUBMIT_EXCEPTION => '提交出现异常，请检查数据或者稍后重试',

        self::YEAR_REPORT_OUTDATE => '报告已过期',

        self::GUIDANCE_CLASSIFY_EXISTS => '分类已存在',
        self::GUIDANCE_INSTRUCTIONS_EXISTS => '操作指引已存在',

        self::STAT_FILTER_GROUP_TYPE_NOT_SUPPORT => '该类型人群无法进行过滤',

        self::RETRAINING_LEVEL_NO_EXISTS => '编号被占用',

        self::LEARNING_PACK_TOP_EXISTS => '该优先级已存在',

        self::RETRAINING_CATEGORY_NO_EXISTS => '编号被占用',

        self::CLASSROOM_NOT_EXISTS => "教室不存在",

        self::CLASSROOM_HAS_RE => "教室已被预定",

        self::COURSE_PACKAGE_PROJECT_NO_AUTH => "暂无该成长地图权限",

        self::TRAINING_PROGRAM_UN_EXISTS => "培训大纲不存在",
        self::TRAINING_PROGRAM_NO_EXISTS => "编号已存在",

        self::HUNDUN_SIGN_ERROR => "签名错误",
        self::HUNDUN_MOBILE_FORMAT_ERROR => "手机号格式错误",
        self::HUNDUN_PARAMS_ERROR => "参数错误",
        self::HUNDUN_REACH_REGISTER_LIMIT => "注册账号已达上限",
        self::HUNDUN_REGISTER_FAILED => "注册用户失败",
        self::HUNDUN_PARAM_ERROR => "参数错误",
        self::HUNDUN_USER_REGISTED => "该用户已注册",
        self::HUNDUN_REACH_USER_SIGNOUT_LIMIT => "达到注销用户上限，默认注销数量占总购买数量的10%",
        self::HUNDUN_COMPANY_UNEXISTS => "权限错误：企业账号不存在",
        self::HUNDUN_UNAUTHORIZED_COURSE_PACKAGE => "权限错误：企业未授权课程包",
        self::HUNDUN_UNAUTHORIZED_COURSE => "课程未授权",

        self::DATABOARD_SYSTEM_UNALLOWED_DELETED => "系统看板不允许删除！",

        self::TIME_RANGE_EXCEEDS_LIMIT => "时间范围超过上限",
        self::ENROLL_NOT_EXISTS => "报名活动不存在！",
        self::ENROLL_NOT_PUBLISHED => "报名活动暂未发布！",
        self::ENROLL_LEARNER_HAS_ENROLLED => "您已报名！",
        self::ENROLL_LEARNER_UNDER_EXAMINE => "您已报名，正在审核...",
        self::ENROLL_LEARNER_NOT_SELECT_SESSIONS => "请选择报名场次！",
        self::ENROLL_SESSIONS_NOT_EXISTS => "报名失败，您所选择的报名场次不存在！",
        self::ENROLL_TIME_OVER => "报名失败，报名时间已结束！",
        self::ENROLL_LEARNER_NUM_REACHED_MAXIMUM_LIMIT => "报名失败，报名人数已达上限！",
        self::ENROLL_REQUIREMENTS_CREDIT_DISQUALIFIED => "很抱歉，您未获得报名要求的最低学分，暂时不能报名！",
        self::ENROLL_REQUIREMENTS_CERTIFICATE_DISQUALIFIED => "很抱歉，您未获得报名要求的证书，暂时不能报名！",
        self::ENROLL_REQUIREMENTS_EXAM_DISQUALIFIED => "很抱歉，您未通过报名要求的考试，暂时不能报名！",
        self::ENROLL_TIMES_MULTI_REACHED_MAXIMUM_LIMIT => "报名失败，您的报名次数已达上限！",
        self::ENROLL_NOT_ALLOWED_CANCEL => "很抱歉，该报名活动不支持取消报名！",
        self::ENROLL_CANCEL_DEADLINE_OVER => "很抱歉，超出报名活动取消截止时间，暂时不能取消报名！",
        self::ENROLL_TIME_NOT_BEGIN => "报名未开始！",
        self::ENROLL_OFFICIAL_NUM_REACHED_MAXIMUM_LIMIT => "审核失败，报名正式名额已达上限！",
        self::ENROLL_SESSION_IS_OBLIGATORY => "请选择报名场次！",
        self::ENROLL_SESSION_NOT_ALLOW_ENROLL_MULTI => "报名失败，该活动不允许多次报名！",
        self::ENROLL_REPLACE_REQUIREMENTS_CREDIT_DISQUALIFIED => "报名失败，未获得报名要求的最低学分！",
        self::ENROLL_REPLACE_REQUIREMENTS_CERTIFICATE_DISQUALIFIED => "报名失败，未获得报名要求的证书！",
        self::ENROLL_REPLACE_REQUIREMENTS_EXAM_DISQUALIFIED => "报名失败，未通过报名要求的考试！",


        self::LEARNING_TEACHING_SIGN_NO_OPEN => "带教未开启上级签名",
        self::LEARNING_TEACHING_SIGN_OTHER_EMP => "您不是该带教的上级",
        self::LEARNING_TEACHING_STUDENT_UNSIGN => "学员未完成签名",
        self::LEARNING_TEACHING_SIGN_FINISHED => "您已完成签名",
        self::LEARNING_TEACHING_NOT_END => "带教未结束",
        self::LEARNING_TEACHING_TUTOR_SIGN_NO_OPEN => "带教未开启导师签名",
        self::LEARNING_TEACHING_SIGN_OTHER_TUTOR => "您不是导师",
        self::LEARNING_TEACHING_STUDENT_SIGN_NO_OPEN => "带教未开启学员签名",
        self::LEARNING_TEACHING_SIGN_OTHER_STUDENT => "您不是学员",
        self::LEARNING_TEACHING_TUTOR_UNSIGN => "导师未完成签名",
        self::LEARNING_TEACHING_TEACHING_UNSIGN => "上级未完成签名",
        self::LEARNING_TEACHING_UNSIGN => "存在未签名的带教",
        self::TRAINING_TUTORING_LEANER_NO_SIGNATURE_REQUIRED => "无需签名",
        self::TRAINING_TUTORING_TASK_NOT_SUBMIT => "带训任务还未提交，暂时不能签名",
        self::SCENE_TALK_WEIGHT_SUM_NOT_ALLOWED => "场景对话权重之和需等于100！",
        self::SCENE_KEYWORD_WEIGHT_SUM_NOT_ALLOWED => "答案关键词权重之和需等于100！",

        self::MATERIAL_NOT_EXISTS_ERROR => "素材不存在",
        self::MATERIAL_TYPE_NOT_EQ => "两次素材的类型不一样，请上传同样的文件类型",
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_MATERIAL_ERROR => "目录库里有素材时不能删除哦,请先删除目录库里的素材",

        self::LANGUAGE_POINTS_NOT_EXISTS_ERROR => "知识点不存在",
        self::LANGUAGE_POINTS_NO_EXISTS => "编号已存在",

        self::TEACHING_MATERIAL_NOT_EXISTS_ERROR => "教材不存在",
        self::TEACHING_MATERIAL_NO_EXISTS => "编号已存在",

        self::VERSION_NO_REDUCIBLE_VERSION => "该版本不是审核通过的版本，不可还原",
        self::VERSION_HAS_REVIEW_VERSION => "还有待审核的版本，不可再新增版本",

        self::PAY_CONFIG_NOT_EXISTS => "此内容没有设置支付",
        self::PAY_CONFIG_CONTENT_TYPE_NOT_SUPPORT => "类型不支持",


        self::OCR_IDCARD_RECOGNIZE_FAIL => '未识别到证件,请上传清晰的证件照片',

        self::ACTION_ASSESSMENT_NOT_EXISTS => '训后行动评估不存在',
        self::ACTION_ASSESSMENT_LEARNER_EXISTS => '学员信息已存在',
        self::ACTION_ASSESSMENT_LEARNER_NOT_EXISTS => '学员信息不存在',
        self::ACTION_ITEMS_NOT_REPEAT_SUBMIT => '不能重复提交行动项',
        self::ACTION_ASSESSMENT_NO_REVIEW_PERMISSION => '没有审核权限',
        self::ACTION_ASSESSMENT_NOT_REPEAT_REVIEW => '不能重复审核',
        self::ACTION_ASSESSMENT_NO_COMMENT_PERMISSION => '没有评价权限',
        self::ACTION_ASSESSMENT_NOT_REPEAT_COMMENT => '不能重复评价',

        self::COMPETENCY_INDICATOR_NOT_FOUND => '岗位胜任指标不存在',
        self::COMPETENCY_INDICATOR_GROUP_NOT_FOUND => '分组不存在',
        self::COMPETENCY_INDICATOR_SKILL_NOT_FOUND => '技能不存在',
        self::COMPETENCY_INDICATOR_GROUP_EXISTS => '分组已存在',
        self::COMPETENCY_INDICATOR_SKILL_EXISTS => '技能已存在',

        self::AI_VIDEO_CONTENT_ERROR => "视频内容不存在或者转码不成功",
        self::AI_VIDEO_CONTENT_EXISTS_ERROR => "任务已存在，请等待",

        // 智能陪练 - 大模型
        self::LARGE_MODEL_MAX_DIMENSION_EACH_SCORE_MODEL => '已达维度数量上限',

        self::APPROVAL_HAS_EXISTS => "已审批，不能重复审批",
        self::APPROVAL_HAS_NO_ROLE => "当前节点无权限审批",

    ];
}
