<?php

namespace App\Common;

interface ErrorCodesDE extends Errors {

    const ERROR_MESSAGES_DE = [
        \Key\Constants::SYS_SUCCESS => 'OK',

        \Key\Constants::SYS_ERROR_DEFAULT => 'Unbekannter Fehler',
        \Key\Constants::SYS_INPUT_INVALID => 'Eingabe ungültig',

        \Key\Constants::USER_OBJECT_NOT_FOUND => 'Objekt nicht gefunden',
        \Key\Constants::USER_OBJECT_ALREADY_EXISTS => 'Objekt existiert bereits',
        \Key\Constants::USER_OBJECT_OCCUPIED => 'Objekt belegt',

        \Key\Constants::OPERATION_TOO_FREQUENT => 'Zu häufiger Betrieb, bitte später wieder versuchen',

        self::SECURITY_PWD_WEAK => 'Schwache Sicherheit des Standardpasswortes',

        self::ACCOUNT_NOT_FOUNT => 'Unternehmen existiert nicht oder wurde deaktiviert',
        self::ACCOUNT_NAME_EXISTS => 'Name des Unternehmens existiert bereits',
        self::ACCOUNT_CREATE_DICTIONARY_ERROR => 'Datenwörterbuch konnte nicht erstellt werden',
        self::ACCOUNT_CREATE_DEPARTMENT_ERROR => 'Abteilung kann nicht erstellt werden',
        self::ACCOUNT_CREATE_ROLE_ERROR => 'Rolle kann nicht erstellt werden',
        self::ACCOUNT_CREATE_USER_ERROR => 'Benutzer kann nicht erstellt werden',
        self::ACCOUNT_CREATE_EMPLOYEE_ERROR => 'Mitarbeiter kann nicht erstellt werden',
        self::ACCOUNT_CREATE_ASSESSMENT_ERROR => 'Standardumlage kann nicht erstellt werden',
        self::ACCOUNT_INVALID => 'Verbundenes Unternehmen abgelaufen oder deaktiviert',
        self::ACCOUNT_CODE_INVALID => 'Ungültige Unternehmensnummer',
        self::ACCOUNT_EXPIRED => 'Unternehmen abgelaufen',
        self::ACCOUNT_FUNCTION_NOT_ENABLED => 'Diese Funktion ist nicht aktiviert',
        self::ACCOUNT_URL_EXPIRE => 'Login funktioniert nicht, bitte überprüfen Sie den Link oder versuchen Sie es wieder',

        self::CUSTOM_FIELD_NAME_EXISTS => 'Benutzerdefinierter Feldname existiert bereits',
        self::IMPORT_CONFIG_NOT_FOUND => 'Importkonfiguration nicht gefunden',
        self::IMPORT_MAX_ROWS => 'Überschreitung der erforderlichen Anzahl von Zeilen',

        // 360 Bewertungsbezogen
        self::PUBLISH_NO_QUESTIONNAIRE => 'Fragebogen wurde gelöscht',
        self::PUBLISH_NO_MODEL => 'Modell aus dem Fragebogen gelöscht, bitte wählen Sie den Fragebogen erneut aus',
        self::PUBLISH_NO_DIMENSION => 'Kompetenzspielraum aus dem Fragebogen gelöscht, bitte wählen Sie den Fragebogen erneut aus',
        self::PUBLISH_NO_ELEMENT => 'Kompetenzelemente aus dem Fragebogen gelöscht, bitte wählen Sie den Fragebogen erneut aus',
        self::PUBLISH_NO_QUESTION => 'Keine Fragen im Fragebogen vorhanden, bitte wählen Sie den Fragebogen erneut aus',

        self::EMPLOYEE_HAVE_LOCKED => 'Konto gesperrt, bitte kontaktieren Sie den Administrator',
        self::EMPLOYEE_NO_EXISTS => 'Mitarbeiternummer existiert bereits',
        self::USER_INVALID_NEW_PWD => 'Passwortformat nicht korrekt, bitte überprüfen Sie die Passwortanforderungen',
        self::USER_PWD_NEW_SAME_OLD => 'Das neue Passwort kann nicht mit dem alten identisch sein',
        self::USER_USR_ERROR_DEFAULT => 'Unbekannter Fehler',
        self::USER_CAPTCHA_IMAGE_INVALID => 'Grafische Verifizierungscode abgelaufen oder falsch ausgefüllt',
        self::USER_CAPTCHA_SMS_INVALID => 'Falscher SMS-Verifizierungscode',
        self::USER_PHONE_INVALID => 'Phone number is invalid',
        self::USER_ACCOUNT_NOT_FOUND => 'No account found',
        self::USER_LOGIN_FAIL => 'Benutzeranmeldung fehlgeschlagen',
        self::USER_QR_LOGIN_FAIL => 'Scan code login failed, please refresh the retry or select other login',
        self::USER_QR_LOGIN_TIMEOUT => 'QR code has expired, please refresh the QR code to re-scan',
        self::USER_PWD_ERROR => 'Falsches Benutzerkennwort',
        self::USER_LOGIN_FAIL_TOO_MANY => 'Zu viele Wiederholungsversuche',
        self::USER_NOT_FOUND => 'Benutzer existiert nicht',
        self::USER_EXISTS_IN_COMPANY => 'Benutzer bereits im Unternehmen',
        self::USER_INVALID_OLD_PASSWORD => 'Ungültiges altes Passwort',
        self::USER_CREATE_ERROR => 'create a user fail',
        self::USER_SMS_CAPTCHA_FREQUENCY => 'Verifizierungscodes zu oft gesendet',
        self::USER_INVALID_USERNAME => 'Unzulässiger Benutzername',
        self::USER_LEAVE_OFFICE => 'Mitarbeiter ist zurückgetreten',
        self::USER_SMS_TIMEOUT => 'Zeitüberschreitung des SMS-Verifizierungscodes',
        self::USER_SMS_INVALID => 'Ungültiger SMS-Verifizierungscode',
        self::MOBILE_EXIST => 'Mobiltelefonnummer existiert bereits',
        self::USER_2FA_BOUND => '2FA wurde gebunden',

        self::QUESTION_BANK_EXISTS => 'Titel der Fragenbank existiert bereits',
        self::QUESTION_IMPORT_TEMPLETE => 'Überschrift stimmt nicht überein, bitte laden Sie die Vorlage wieder herunter',
        self::QUESTION_EXISTS => 'Frage existiert bereits',
        self::QUESTION_COYE_FAIL => 'Frage kann nicht kopiert werden',
        self::PAPER_EXISTS => 'Titel der Arbeit existiert bereits',
        self::EXAM_EXISTS => 'Prüfungsname existiert bereits',
        self::EXAM_END => 'Prüfung ist beendet',
        self::EXAM_COYE_FAIL => 'Prüfung kann nicht kopiert werden',
        self::EXAM_EMPLOYEE_END => 'Mitarbeiterprüfung ist beendet',
        self::EXAM_DETAIL_FAIL => 'Prüfungsdetails können nicht abgerufen werden',
        self::EXAM_DIR_NOT_FOUND => 'Abruf des Prüfungsverzeichnisses fehlgeschlagen',
        self::SYSTEM_EXAM_DIR_CANNOT_DELETE => "Standardprüfungsverzeichnis kann nicht gelöscht werden",
        self::EXAM_DIR_EXISTS_CHILD => 'Dieses Verzeichnis hat Unterverzeichnisse, die nicht gelöscht werden können. Bitte löschen Sie zuerst die Unterverzeichnisse.',
        self::EXAM_USERNAME_EXIST => 'Falsche Mobiltelefonnummer oder E-Mail-Adresse',
        self::EXAM_DIR_EXISTS_BANK => 'Dieses Verzeichnis enthält eine Fragenbank, die nicht gelöscht werden kann. Bitte löschen Sie zuerst die Fragenbank.',
        self::EXAM_DIR_EXISTS_PAPER => 'In diesem Verzeichnis befinden sich Fragebögen, bitte löschen Sie zuerst die Fragen',
        self::EXAM_NEED_LOGIN => 'Für diese Prüfung ist eine Anmeldung erforderlich',
        self::EXAM_EMPLOYEE_TEMPLATE => 'Kopfzeile stimmt nicht überein, bitte laden Sie die Vorlage erneut herunter.',
        self::EXAM_MOBILE_NOT_EXIST => 'Mobiltelefonnummer existiert nicht',
        self::EXAM_REDIS_NO_DATE => 'redisKeine Antworten für Kandidaten',
        self::EXAM_STUDENT_OUT_TIME => 'Leider ist die aktuelle Zeit für die Prüfung nicht verfügbar!',
        self::EXAM_MOCK_DIR_HAS_EXAM => 'In diesem Verzeichnis befinden sich Prüfungen, die nicht gelöscht werden können, bitte löschen Sie zuerst die Prüfung',
        self::EXAM_NOTIFY_UNPUBLISHED => 'Prüfung ist noch nicht freigegeben, keine Benachrichtigung möglich',
        self::EXAM_NOTIFY_END => 'Prüfung ist beendet, keine Benachrichtigung möglich',
        self::EXAM_NOT_EXIST => 'Prüfung existiert nicht',
        self::EXAM_PAPER_HAS_UPDATE => 'Prüfung wurde aktualisiert, bitte wiederholen Sie die Prüfung',
        self::EXAM_UNPUBLISHED => 'Prüfungen werden nicht ausgehängt, bitte wenden Sie sich an den Administrator!',

        self::LEARNING_PLAN_NAME_EXIST => 'Name des Lernprogramms existiert bereits',
        self::LEARNING_NO_EXIST => 'Nummer ist vergeben!',
        self::LEARNING_DURATION_TO_LONG => 'Dauer zu lang!',
        self::LEARNING_BREAKTHROUGH_NAME_EXIST => 'Name des Lerndurchbruchs existiert bereits',
        self::LEARNING_CATEGORY_DELETE_CONTAINS => 'Unter der Kategorie befinden sich Lerndurchbruch, bitte löschen Sie zuerst den Lerndurchbruch',
        self::LEARNING_PLAN_NO_PERMISSION => 'Keine Genehmigung',
        self::LEARNING_LEARNER_OVERSTEP => 'Die Anzahl der Einschreibungen hat das Maximum erreicht',
        self::LEARNING_LEARNER_ALREADY_EXIST => 'Dieser Auszubildende existiert bereits',
        self::LEARNING_PLAN_NO_MORE_GROUP => 'Es gibt keine weiteren Gruppen in dieser intelligenten Klasse',
        self::LEARNING_PLAN_NOT_PUBLISHED => 'Lernprogramm wurde nicht veröffentlicht',
        self::LEARNING_CLASS_NOT_PUBLISHED => 'Klassen wurde nicht veröffentlicht ',
        self::LEARNING_PACK_NOT_PUBLISHED => 'Lernpaket wurde nicht veröffentlicht',
        self::LEARNING_PACK_SETTINGS_CREDIT => 'Kreditvergabe des Lernpakets überschreitet das Limit',
        self::LERN_ENROLL_POSITION_NOT_PASSED => 'Position nicht erfüllt, Einschreibung nicht erlaubt',
        self::LERN_ENROLL_OFFLINE_NOT_PASSED => 'Anzahl der Unterrichte nicht erfüllt, keine Einschreibung möglich',
        self::LERN_ENROLL_NOT_LECTURER => 'Kein Dozent, keine Einschreibung möglich',
        self::LEARNING_UN_EXISTS => 'Das Projekt existiert leider nicht!',
        self::LEARNING_LEARNER_UNDER_REVIEW => 'In Überprüfung',
        self::LEARNING_TASK_OBLIGATORY => 'Bitte fügen Sie zuerst Lerninhalte hinzu',
        self::LEARNING_TEACHING_TEMPLATE_USED => 'Vorlage des Tutorials wurde bereits verwendet und kann nicht gelöscht werden',
        self::LEARNING_TEACHING_ALREADY_STARTED => 'Tutorial hat bereits begonnen',
        self::LEARNING_TEACHING_PROJECT_HAS_LEANRER => 'Tutorialsbeziehung existiert unter dem Nachhilfeprojekt, kann nicht gelöscht werden.',
        self::LEARNING_TASK_EXISTS => 'Aufgabe existiert bereits',
        self::LEARNING_TASK_ASSIGNING => 'Aufgabe wird gerade zugewiesen, bitte versuchen Sie es später noch einmal',
        self::LEARNING_APPRAISER_NO_CERTIFICATE => 'Beurteilte hat noch nicht die entsprechenden Zertifikate erworben!',
        self::LEARNING_TEACHER_NO_CERTIFICATE => 'Beurteiler hat das entsprechende Zertifikat noch nicht erworben!',
        self::LEARNING_PACK_NOT_FOUND => 'Lernpaket ist nicht vorhanden',
        self::LEARNING_INTERACTION_NOT_EXISTS_ERROR => 'Interaktion ist nicht vorhanden',
        self::LEARNING_SIMPLE_NO_OFFLINE => 'Bitte fügen Sie vor der Veröffentlichung einen Präsenzkurs hinzu。',
        self::LEARNING_PLAN_ACTIVITY_NOT_FOUND => 'Aktivität existiert nicht',
        self::LEARNING_PLAN_ACTIVITY_NOT_STARTED => 'Aktivität nicht gestartet',
        self::LEARNING_PLAN_ACTIVITY_NO_AUTH => 'Keine Erlaubnis, sich für die Aktivität anzumelden',
        self::LEARNING_NO_OPERATION_AUTH => 'Keine Berechtigung',
        self::LEARNING_PLAN_NO_EXISTS => 'Lernmodul existiert nicht',
        self::LEARNING_PLAN_NO_VISIT_AUTH => 'Kein Zugang',
        self::LEARNING_PLAN_IS_RELATED_PROJECT => 'Das Projekt wurde umgesetzt!',
        self::LEARNING_BREAKTHROUGH_OCCUPIED => 'Der Durchbruch ist besetzt!',
        self::LEARNING_BREAKTHROUGH_CAG_HAVE_BREAKTHROUGH => 'Es gibt Durchbrüche in dieser Kategorie und das Löschen ist nicht zulässig!',
        self::LEARNING_APPLICATION_NON_START => 'Registrierung hat nicht begonnen',
        self::LEARNING_APPLICATION_ALREADY_OVER => 'Registrierung ist geschlossen',
        self::LERN_ENROLL_SCORE_NOT_SUBSTANDARD => 'Wenn die Kredits nicht den Standards entsprechen, ist eine Registrierung nicht möglich!',
        self::LERN_ENROLL_UNCERTIFIED => 'Anmeldung ist nicht zulässig, wenn Sie nicht über die entsprechenden Zertifikate verfügen!',
        self::LERN_ENROLL_EXAM_NOT_PASSED => 'Anmeldung ist nicht zulässig, wenn Sie die entsprechende Prüfung nicht bestanden haben!',
        self::LERN_ENROLL_NOT_ALLOW_CANCEL => 'Rücktritt sind für diesen Kurs nicht zulässig!',
        self::LERN_ENROLL_CANCEL_TIME_CUT_OFF => 'Rücktrittsfrist ist abgelaufen!',
        self::LERN_ENROLL_DELEGATE_TOP => 'Maximale Teilnehmerzahl des Programms ist erreicht!',
        self::LERN_ENROLL_DELEGATE_CLOSE => 'Vollmachtanmeldung ist nicht aktivert!',
        self::LERN_DELEGATE_IS_EXIST => 'Neue Bedingungen stehen im Widerspruch zu bestehenden Bedingungen!',
        self::LERN_DELEGATE_DELEGATE_NO_EXIST => 'Für dieselbe verantwortliche Person können nur bereits eingerichtete Abteilungen hinzugefügt werden!',
        self::LEARNING_PACK_END => 'Lernpaket IST beendet!',
        self::LEARNER_NOT_ZERO => 'Auszubildende sind hinzugefügt worden, Löschen ist nicht erlaubt!',
        self::LEARNING_PACK_UN_ENABLED => 'Lernpaket ist deaktiviert!',
        self::LEARNING_PLAN_LEARNER_ALREADY_SIGNED => 'Bitte melden Sie sich nicht wiederholt an',
        self::LEARNING_APPLICATION_NOT_ALLOWED => 'Klasse ist nicht zur Einschreibung geöffnet',
        self::LEARNING_PLAN_NO_AUTH => 'Keine Erlaubnis',
        self::LEARNING_PLAN_INVALID_QR_CODE => 'Ungültiger QR-Code',
        self::LEARNING_PLAN_ALREADY_ENDED => 'Klasse ist geschlossen',
        self::LEARNING_CLASS_SIGN_NOT_START => 'Check-in hat nicht begonnen',
        self::LEARNING_CLASS_SIGN_ENDED => 'Einschreibung ist beendet',
        self::LEARNING_CLASS_SIGN_LEARNER_SIGNED => 'Angemeldet',
        self::LEARNING_PLAN_SIGN_NOT_PUBLISHED => 'Kurs ist nicht veröffentlicht',
        self::LEARNING_PLAN_SIGN_NO_AUTH => 'Sie sind dem Kurs noch nicht beigetreten und können sich noch nicht anmelden',
        self::LEARNING_PLAN_ENDED_SIGN => 'Unterricht ist beendet',
        self::LEARNING_PACK_SIGN_NO_AUTH => 'Sie sind dem Lernpaket nicht beigetreten und können sich noch nicht anmelden',
        self::LEARNING_PLAN_SIGN_INVALID_QR_CODE => 'Ungültiger QR-Code',
        self::LEARNING_PLAN_SIGN_OVER_DISTANCE => 'Ihr Standort liegt nicht im Check-in-Bereich und Sie können sich vorübergehend nicht anmelden',
        self::LEARNING_PLAN_SIGN_CLOSED_GPS => 'Es wurden keine geografischen Standortinformationen erfasst. Bitte überprüfen Sie, ob die Positionierung aktiviert ist',
        self::LERN_MAP_TAGGING_FINISHED_UNCERTIFIED => 'Bedingungen zur Erlangung des Zertifikats sind nicht erfüllt und können nicht als abgeschlossen markiert werden',
        self::LERN_MAP_TAGGING_FINISHED_NOT_AUTH => 'Keine Berechtigung, diese Aufgabe wird vom Administrator als erledigt markiert',
        self::LERN_MAP_TAGGING_FINISHED_CLASS_INCOMPLETE => 'Abschlussquote dieses Kurses liegt nicht bei 100 % und kann nicht als abgeschlossen markiert werden',
        self::LEARNING_QUEUE_EXISTS => 'In Bearbeitung, bitte warten',
        self::LERN_PACK_DISABLED => 'Dieses Lernpaket wurde deaktiviert, bitte später wieder versuchen!',
        self::LERN_PASS_DISABLED => 'Dieser Durchbruch ist deaktiviert, bitte später wieder versuchen!',
        self::LERN_OPERATE_NOT_ALLOWED => 'Wartungsarbeiten im Gange, bitte gehen Sie zum Admin-Backend!',
        self::LEARNING_PLAN_NO_SIGNS => 'Zurzeit keine Anmeldung möglich!',
        self::OFFLINE_TEACHING_SIGN_TIME_OUT => 'QR-Code ungültig!',
        self::LERN_CLASS_NO_VISIT_AUTH => 'Sie sind dieser Klasse nicht beigetreten!',
        self::LERN_PLAN_NO_VISIT_AUTH => 'Sie haben nicht an diesem Lernpaket teilgenommen!',
        self::LERN_PACK_NO_VISIT_AUTH => 'Sie haben sich nicht an diesem Lernpaket beteiligt!',
        self::LERN_PASS_NO_VISIT_AUTH => 'Sie sind diesem Durchbruch nicht beigetreten!',
        self::LERN_ADD_LEARNER_ON_GOING => 'Häufige Vorgänge, bitte später wieder versuchen!',
        self::LERN_PASS_UNPUBLISHED => 'Durchbruch nicht freigegeben',
        self::LERN_PASS_NOT_EXISTS => 'Durchbruch existiert nicht',
        self::LERN_PASS_NOT_AUTH => 'Sie haben keine Erlaubnis, an diesem Durchbruch teilzunehmen',

        self::LERN_PRO_NOT_ALLOW_LEARNER_IN_MULTI_CLASS => 'Bei diesem Projekt nicht möglich, sich dieselbe Person für mehrere Kurse anmeldet',
        self::LERN_PRO_NOT_ALLOW_LEARNER_SHIFT => 'Dieses Programm ermöglicht es den Auszubildenden nicht, die Klasse selbstständig anzupassen',
        self::LERN_OVERSTEP_SHIFT_CLASS_TIME => 'Klassenanpassungszeit überschritten, wählen Sie bitte eine andere Klasse',

        self::KNOWLEDGE_NOT_EXISTS_ERROR => 'Wissen existiert nicht',
        self::DIRECTORY_NAME_EXISTS_ERROR => 'Verzeichnisname existiert bereits',
        self::DIRECTORY_NOT_EXISTS_ERROR => 'Verzeichnis existiert nicht',
        self::DIRECTORY_LEVEL_LIMIT => 'Auf dieser Verzeichnisebene kann kein Verzeichnis erstellt werden',
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_KNOW_ERROR => 'Wenn Wissen im Verzeichnis vorhanden ist, kann es nicht gelöscht werden. Bitte löschen Sie zuerst das Wissen im Verzeichnis',
        self::DIRECTORY_EXISTS_CHILD_ERROR => 'Dieses Verzeichnis verfügt über Unterverzeichnisse und kann nicht gelöscht werden. Bitte löschen Sie zuerst die Unterverzeichnisse',
        self::CONTENT_IS_NOT_EXISTS_ERROR => 'Dieser Inhalt existiert nicht',
        self::DIRECTORY_COURSE_NOT_EXISTS_ERROR => 'Kurs existiert nicht',
        self::DIRECTORY_HAS_CHILD_ERROR => 'Dieses Verzeichnis hat Unterverzeichnisse und kann nicht verschoben werden',
        self::KNOWLEDGE_NOT_HAVE_AUTH_ERROR => 'Keine Besichtigungserlaubnis',
        self::KNOWLEDGE_HAS_USE => 'Dieses Wissen wurde in der Aufgabe verwendet und kann nicht gelöscht werden',
        self::ORG_NOT_FIND_IN_KNOWLEDGE => 'Dieses Unternehmen hat die Mikrofrage-Funktion noch nicht geöffnet',
        self::USER_NOT_PERMISSION => 'Leider haben Sie keine Berechtigung, auf dieses Wissen zuzugreifen!',
        self::KNOWLEDGE_TOKEN_ERROR => 'Falsches Tokenwert!',
        self::COURSE_IS_NOT_COMPANY => 'Dieser Kurs ist kein von einem Unternehmen erstellter Kurs und kann nicht als öffentlicher Kurs eingerichtet werden',
        self::COURSE_TYPE_IS_NOT_ALLOWED => 'Live-Klassen können nicht als öffentliche Klassen festgelegt werden',
        self::ROOT_DIRECTORY_CANNOT_DELETE_ERROR => 'Standardkurskatalog kann nicht gelöscht werden',

        self::COURSE_NOT_EXIST => 'Dieser Kurs existiert nicht',
        self::COURSE_IS_SELF => 'Sie können einen von Ihnen erstellten Kurs nicht favorisieren',
        self::COURSE_HAS_FOLLOWED => 'Sie haben diesen Kurs bereits favorisiert',
        self::COURSE_HAS_USED_USER => 'Der angegebene Benutzer hat diesen Kurs bereits',
        self::COURSE_EXIST_IN_GROUP => 'Der Kurs existiert bereits',
        self::SERIES_GROUP_ORDER_EXISTS => 'Der Sortierwert existiert bereits',
        self::IMG_LIMIT_ERROR => 'Bildgrößenlimit überschritten',
        self::FILE_LIMIT_ERROR => 'Dateigrößenlimit überschritten',
        self::FILE_READ_FAIL => 'Die Datei kann nicht gelesen werden. Bitte laden Sie sie bei Bedarf hoch',
        self::UPLOAD_FILE_FAIL => 'Datei konnte nicht hochgeladen werden',
        self::SECURITY_RULE_INVALID_IP_CONFIG => 'Fehler bei der Konfiguration der IP-Whitelist',

        self::POSITION_ERROR_UNDEFINED => 'Unbekannter Positionsfehler',
        self::POSITION_NOT_FOUND => 'Position existiert nicht',
        self::POSITION_NUMBER_OCCUPIED => 'Positionsnummer besetzt',
        self::POSITION_CATEGORY_DELETE_CONTAINS => 'Position existiert in Gruppe und kann nicht gelöscht werden',
        self::POSITION_CATEGORY_NOT_FOUND => 'Positionsgruppe nicht vorhanden',
        self::POSITION_EMPLOYEE_USED => 'Position wird verwendet',
        self::POSITION_TARGET_INCLUDE_SELF => 'Zielposten kann nicht Ihr eigener sein',

        self::MEDAL_SCORE_EXIST => 'Medaillenwert bereits vorhanden',
        self::MEDAL_NAME_EXIST => 'Medaillenname bereits vorhanden',
        self::BANNER_SORT_EXIST => 'Priorität bereits vorhanden',
        self::BANNER_TOTAL_NUM => 'Mmaximale Anzahl an Karussellbildern erreicht',
        self::MEDAL_SCORE_INSUFFICIENT => 'Unzureichende Kredits',
        self::NOT_AUTH_DEPT => 'Keine Berechtigung für diese Abteilung festgelegt',
        self::NOT_REPEAT_DEPT => 'Diese Abteilung wurde bereits eingerichtet und kann nicht wiederholt hinzugefügt werden',

        self::ORDER_COURSE_ERROR => 'Kursdaten in der Bestellung wurden falsch zusammengestellt',
        self::ORDER_ACCREDIT_ERROR => 'Autorisierung der Bestellung fehlgeschlagen',
        self::ORDER_PAY_REFUND => 'Bestellung zur Erstattung übertragen',
        self::ORDER_PAY_NOTPAY => 'Bestellung nicht bezahlt',
        self::ORDER_PAY_CLOSED => 'Bestellung geschlossen',
        self::ORDER_PAY_REVOKED => 'Bestellung storniert (Kartenzahlung)',
        self::ORDER_PAY_USERPAYING => 'Benutzerzahlung in Bearbeitung ',
        self::ORDER_PAY_PAYERROR => 'Bezahlung der Bestellung fehlgeschlagen',
        self::ORDER_COURSE_EXIST => 'Die freie oder verschlüsselte Klasse, der Sie beigetreten sind, existiert bereits',

        self::DEPT_UNDEFINED_ERROR => 'Unbekannter Abteilungsfehler',
        self::DEPT_NOT_FOUND => 'Abteilung existiert nicht',
        self::DEPT_NON_GROUP_DENY_CHILD => 'Untergeordnete Abteilungen können nicht ohne Gruppierung erstellt werden',
        self::DEPT_DUPLICATED_IN_BRANCH => 'Die aktuelle Knotenabteilung existiert bereits',
        self::DEPT_DENY_CHILD => 'Unter dieser Abteilung können keine Unterabteilungen erstellt werden',
        self::DEPT_NAME_EDIT_DISABLED => 'Der Name dieser Abteilung kann nicht bearbeitet werden',
        self::DEPT_EDIT_DISABLED => 'Das Bearbeiten ist in dieser Abteilung untersagt',
        self::DEPT_EMPLOYEE_EXISTS => 'Es gibt Mitarbeiter in dieser Abteilung und der Vorgang kann nicht durchgeführt werden',
        self::DEPT_NO_EXISTS => 'Abteilungsnummer existiert bereits',
        self::DEPT_PARENT_NOT_FOUND => 'Übergeordnete Abteilung existiert nicht',

        self::EMPLOYEE_UNDEFINED_ERROR => 'Unbekannter Fehler',
        self::EMPLOYEE_NOT_FOUND => 'Mitarbeiter existiert nicht',
        self::EMPLOYEE_DISPLAY_OCCUPIED => 'Name bereits vergeben',
        self::EMPLOYEE_NUMBER_EXISTS => 'Mitarbeiternummer bereits vergeben',
        self::EMPLOYEE_NOT_FOUND_OR_DISABLED => 'Benutzer existiert nicht oder deaktiviert',
        self::EMPLOYEE_LIMIT_EXCEEDS => 'Mitarbeiterzahl die Obergrenze erreicht',
        self::EMPLOYEE_MOBILE_OCCUPIED => 'Handynummer wurde verwendet',
        self::EMPLOYEE_EMAIL_CAPTCHA_INVALID => 'Ungültiger E-Mail-Verifizierungscode',
        self::EMPLOYEE_EMAIL_OCCUPIED => 'Diese E-Mail-Adresse wird bereits verwendet',
        self::EMPLOYEE_IMPORT_TEMPLATE_INVALID => 'Ungültige Importvorlage',

        self::ACTIVITY_NAME_EXIST => ' Veranstaltungsname existiert bereits',
        self::EMPLOEE_NO_AUTH => 'Sie sind kein Mitarbeiter dieses Unternehmens',
        self::EMPLOEE_NOT_EXIST => 'Mitarbeiter nicht im System',
        self::EXPIRY_TIME_CAN_NOT_EMPTY => 'Anmeldefrist erforderlich',
        self::EXCEEDING_LIMIT => 'Personenzahl der Veranstaltung übersteigt die maximale Personenzahl der Veranstaltung',
        self::END_TIME_WRONG => 'Endzeit muss größer als die Startzeit sein',
        self::EXPIRY_TIME_WRONG => 'Anmeldefrist muss kleiner oder gleich dem Enddatum der Veranstaltung sein',

        self::COURSE_NOT_ALLOW_REMOVE => 'Kurse, die weniger als 7 Tage abgeschlossen sind, können nicht gelöscht/entfernt werden',
        self::COURSE_NOT_OVER => 'Kurs ist nicht beendet',
        self::COURSE_IS_OVER => 'Kurs ist beendet',
        self::COURSE_NOT_AUTH_VIEW => 'Keine Berechtigung zum Anzeigen des Kurses',
        self::COURSE_UPLOAD_AUDIO_ERROR => 'Audiodatei konnte nicht hochgeladen werden',
        self::COURSE_AUDIO_EMPTY => 'Bitte Audiodatei generieren',
        self::COURSE_HAS_USED => 'Der Kurs wird verwendet und eine Löschung ist nicht zulässig',
        self::COURSE_NOT_AUTH => 'Keine Berechtigung zum Ansehen',
        self::COURSE_NO_EXISTS => 'Kurs existiert nicht',

        self::FAVORITE_HAS_EXISTS_ERROR => 'Sie haben diesen Inhalt bereits favorisiert',
        self::FAVORITE_NO_EXISTS_ERROR => 'Sie haben diesen Inhalt noch nicht mit einem Lesezeichen versehen, daher können Sie das Lesezeichen nicht entfernen',
        self::COMMENT_NOT_EXISTS_ERROR => 'Kommentar nicht vorhanden',
        self::EMPTY_MISTAKE_QUESTION => 'Keine falsche Fragen',
        self::COMMENT_NOT_ROLE_ERROR => 'Kommentare können nur vom Administrator und mir selbst gelöscht werden',

        self::SIGN_DAILY_SIGNED => 'Heute eangemeldet',
        self::PK_CREATE_ERROR => 'PK-Erstellung fehlgeschlagen',
        self::PK_DETAIL_ERROR => 'Abrufen der PK-Details fehlgeschlagen',
        // self::PK_DETAIL_ERROR => 'PK speichern fehlgeschlagen',
        self::VOTE_TOPIC_EXIST => 'Abstimmungsthema existiert bereits',
        self::VOTE_NO_PERMISSIONS => 'Nichtmitglieder können nicht wählen',

        self::REPLY_EXIST => 'Es liegt bereits Antworten vor und kann nicht gelöscht werden',
        self::NOT_ISSUE_CREATOR => 'Kann nicht bedient werden, wenn Sie nicht der Ersteller der Frage sind',
        self::NOT_REPLY_CREATOR => 'Kann nicht bedient werden, wenn Sie nicht der Ersteller der Antwort',
        self::SURVEY_TITLE_EXIST => 'Titel der Umfrage existiert bereits',
        self::SURVEY_NO_PERMISSIONS => 'Nichtmitglieder können nicht an der Umfrage teilnehmen',
        self::TEAM_USED => 'Unter diesem Team gibt es Wissen, das nicht gelöscht werden kann',
        self::TEAM_NAME_EXIST => 'Teamnamen können nicht wiederholt werden',

        self::LIEVROOM_NOT_FOUND => 'Live-Raum existiert nicht',
        self::QUESTION_NOT_RECOGNIZE => 'Nicht erkannt werden können',
        self::VENDOR_OLD_PASSWORD_WRONG => 'Falsches ursprüngliches Passwort des Lieferanten',
        self::VENDOR_NEW_PASSWORD_WRONG => 'Das neue Passwort darf nicht mit dem ursprünglichen Passwort identisch sein',

        self::COURSE_REPOSITORY_HAS_USED => 'Der Kurs wird verwendet und kann nicht aus der Kursbibliothek verschoben werden',
        self::COURSE_REPOSITORY_HAS_USED_BANNER => 'Kurs wird im Karussell empfohlen bzw. verwendet und kann nicht entfernt werden',
        self::COURSE_REPOSITORY_CANNOT_REMOVE => 'Nicht-Superadministratoren können einen Kurs nicht entfernen',
        self::COURSE_CONSUMER_POINT_NOT_ENOUGH => 'Unzureichende Punkte',
        self::TASK_TITLE_EXIST => 'Name der Aufgabe existiert bereits',

        self::TRAINING_PLAN_EXIST => 'Name des Trainingsprogramms existiert bereits',
        self::TRAINING_TASK_GROUP_EXIST => 'Gruppenname existiert bereits',
        self::TRAINING_PROJECT_PUSH_FAULT => 'Einreichung zur Überprüfung fehlgeschlagen',
        self::TRAINING_PROJECT_HAS_PUSH => 'Zur Überprüfung eingereicht',
        self::TRAINING_ACTIVE_HAS_SUBMIT => 'Aktivität wurde eingereicht, bitte nicht ändern',
        self::TRAINING_HAS_SPLITED => 'Der Plan wurde aufgeschlüsselt, bitte wiederholen Sie die Aufschlüsselung nicht',
        self::TRAINING_MONTH_NO_SPLITED => 'Monatlicher Plan kann nicht aufgeschlüsselt werden',
        self::TRAINING_YAER_NOT_FOUND => 'Das Jahr des Plans ist nicht festgelegt worden, da kann nicht aufgeschlüsselt werden',
        self::TRAINING_PLAN_NO_ACTIVE => 'Es gibt keine Aktivität im Plan, da kann nicht aufgeschlüsselt werden',

        self::HEADLINE_NO_ASSESS => 'Keine Betriebserlaubnis',
        self::HEADLINE_NO_OPEN => 'Funktion deaktiviert',
        self::PERMISSION_ROLE_EXIST => 'Rollenname existiert bereits',
        self::PERMISSION_ROLE_CLASSIFY_EXIST => 'Name der Rollenkategorie existiert bereits',
        self::PERMISSION_ROLE_EXISTS => 'Rolle existiert bereits unter dieser Kategorie',
        self::PERMISSION_ROLE_FUNCTION_EMPTY => 'Funktionsberechtigung darf nicht leer sein',

        self::QUEUE_EXISTS => 'Die Aufgabe wird ausgeführt, bitte später wieder versuchen',

        self::DEMO_ACCOUNT_TIMEOUT => 'Testkonto läuft ab',
        self::DEMO_ACCOUNT_NO_TRIAL => 'Testkonto wird eröffnet',

        self::LHA_OP_ERROR => 'Der Antrag wurde genehmigt oder abgelehnt',
        self::INTEGRAL_ORDER_FAIL => 'Unzureichende Punkte oder Inventar',
        self::INTEGRAL_PRODUCT_EXISTS => 'Produktname existiert bereits',
        self::INTEGRAL_ORDER_LIMIT=>"Die aktuelle Anzahl der Produkteinlösungen hat die Obergrenze erreicht",


        self::KNOWLEDGE_POINT_NAME_HAS_EXISTS => 'Name des Wissenspunkts existiert bereits',
        self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => 'Wissenspunkt existiert nicht',

        self::LOGIN_NEED_ACCOUNT_CODE => 'Fehlende Firmennummer',
        self::LOGIN_INVALID_ACCOUNT_CODE => 'Ungültige Firmennummer',
        self::USER_RESET_PASSWORD_EMAILS_ERROR => 'Diese E-Mail-Adresse entspricht mehreren Konten und kann nicht abgerufen werden',
        self::LOGIN_USER_MOBILE_NOT_BINDING => 'Die Mobiltelefonnummer ist nicht gebunden und kann nicht angemeldet werden',
        self::LOGIN_MOBILE_USED_MANY => 'Diese Handynummer wird von mehreren Personen verwendet und kann nicht angemeldet werden',
        self::LOGIN_IP_BLOCKED => 'IP wurde blockiert',

        self::ASSESSMENT_TOPIC_EXIST => 'Bewertungsname existiert bereits',
        self::ASSESSMENT_NO_PERMISSIONS => 'Keine Berechtigung zum Erstellen einer Bewertung',
        self::ASSESSMENT_PARTAKE_NO_PERMISSIONS => 'Leider haben Sie keine Berechtigung, an dieser Bewertung teilzunehmen!',
        self::ASSESSMENT_END => 'Entschuldigung, diese Bewertung ist beendet',

        self::OFFLINE_TEACHING_NAME_EXIST => 'Präsenzkurs mit diesem Namen existiert bereits',
        self::OFFLINE_TEACHING_USED => 'Klasse wurde von der intelligenten Klasse verwendet und kann nicht gelöscht werden',
        self::OFFLINE_TEACHING_RECORD_CANT_DELETE => 'Dieser Datensatz wurde genehmigt und kann nicht gelöscht werden',

        self::COURSE_HAVE_ESTIMATE => 'Sie haben ihn bereits bewertet, Sie können ihn nicht erneut kommentieren',
        self::COURSE_NO_PERMISSION => 'Keine Betriebsberechtigung',

        // self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => 'Wissenspunkt nicht vorhanden',

        self::PLATFORM_NOT_SETTING_DING => 'remdplattform nicht an Ding Talk gebunden',
        self::PRODUCT_NOT_ENOUGH => 'Anzahl der Geschenke nicht ausreichend',

        self::BASE_OBJECT_THUMBED_UP => 'Objekt wurde geliked',
        self::BASE_OBJECT_CATEGORY_NOT_FOUND => 'Gruppe existiert nicht',
        self::BASE_OBJECT_CATEGORY_USED => 'Gruppe wird bereits verwendet',

        self::CIRCLE_APPLICATION_FAULT => 'Bereits Mitglied des Kreises, kann nicht wieder beitreten',
        self::CIRCLE_TOPIC_EXISTS => 'Name des Themas kann nicht wiederholt werden',
        self::CIRCLE_IS_USED => 'Q&A-Kreis belegt und kann nicht gelöscht werden',
        self::CIRCLE_NO_PERMISSION => 'Nicht im Q&A-Kreis',
        self::CIRCLE_INFO_NOT_FOUND => 'Beitrag/Frage existiert nicht',
        self::CIRCL_VIEWE_NO_PERMISSION => 'Keine Ansichtsberechtigung',

        self::GAME_UNDEFINED => 'Unbekannter Fehler',
        self::GAME_BEYOND_ATTEMPT => 'Anzahl der Versuche überschritten',
        self::GAME_WON_ALREADY => 'Sie haben bereits einen Preis gewonnen',
        self::GAME_PRIZE_DEPLETED => 'Keine Preise mehr',
        self::GAME_NOT_ENABLED => 'Spiel nicht aktiviert',
        self::GAME_NOT_START => 'Spiel hat nicht begonnen',
        self::GAME_OVER => 'Spiel ist beendet',
        self::GAME_NOT_OPEN => 'Lotterie hat noch nicht begonnen',
        self::GAME_PEOPLE_NUM_NOT_ENOUGH => 'Nicht genügend Personen erfüllen die Lotterievoraussetzungen',
        self::GAME_NUMBER_EXISTS => 'Gewinnspielnummer existiert bereits',
        self::GAME_DUMMY_FREQUENT => 'Netzwerksystem ist beschäftigt, bitte später wieder versuchen',
        self::GAME_INVAID_PARTICIPANT => 'Ungültiger Teilnehmer',
        self::GAME_OP_FREQUENT => 'Zu häufiger Betrieb, bitte später wieder versuchen',

        self::SYNC_ERROR_DATA_FORM_ERROR => 'Das angeforderte Datenformat ist nicht korrekt, bitte überprüfen Sie es',

        self::FUNDING_IS_JOIN => 'Teilgenommen',
        self::FUNDING_IS_APPLY => 'Eingeschrieben',

        self::COIN_NOT_SUFFICIENT_FUNDS => 'Goldsaldo ist unzureichend',
        self::COURSE_CATEGORY_NAME_EXISTS => 'Name der Kurskategorie existiert bereits',
        self::COURSE_CATEGORY_HAS_USED => 'Kurskategorie wird bereits verwendet',
        self::SKILLED_CATEGORY_NAME_EXISTS => 'Bezeichnung existiert bereits',
        self::SKILLED_CATEGORY_HAS_USED => 'Dieses Fachgebiet wird verwendet',

        self::OFFLINE_ASSESSMENT_USED => 'Identifizierung hat begonnen',
        self::OFFLINE_ASSESSMENT_TEMPLATE_USED => 'Identifizierungsvorlage wurde verwendet und kann nicht gelöscht werden',
        self::OFFLINE_ASSESSMENT_REACH_RE_NUM => 'Die Anzahl der wiederholbaren Bewertungen ist erschöpft',
        self::OFFLINE_ASSESSMENT_CANT_RE => 'Diese Prüfung kann nicht wiederholt werden',
        self::OFFLINE_ASSESSMENT_NO_ACL => 'Keine Berechtigung zum Betrieb, bitte wenden Sie sich an den Administrator',

        self::SMS_CAPTCHA_SMS_INVALID => 'Falscher SMS-Verifizierungscode',
        self::SMS_CAPTCHA_SMS_EXPIRED => 'SMS-Verifizierungscode abgelaufen',
        self::SMS_LIMIT_EXCEEDS => 'Verifizierungscode ist noch nicht abgelaufen',

        self::LEARNING_PROJECT_NO_EXISTS => 'Projektnummer bereits vorhanden',

        self::LEARNING_SIGN_INVALID => 'Ungültige Anmeldung',
        self::LEARNING_SIGN_NONSUPPORT_CODE => 'Diese Anmeldung unterstützt keine Anmeldung mit Anmeldecode',
        self::LEARNING_SIGN_CODE_ERROR => 'Falscher Anmeldecode',
        self::LERN_SIGN_UNAUTHORIZED_PARTICIPATION => 'Keine Berechtigung',
        self::LERN_SIGN_PASSWORD_ERROR => 'Falsches Passwort',

        self::LIVE_INVALID => 'Ungültiges Live-Streaming',
        self::LIVE_NOT_FOUND => 'Live-Streaming existiert nicht',
        self::LIVE_NO_PERMISSION => 'Keine Berechtigungen',
        self::LIVE_ROOM_NOT_FOUND => 'Live-Raum existiert nicht',
        self::LIVE_MEMBER_IS_EXISTS => 'Existiert bereits',
        self::LIVE_MEMBER_IS_NULL => 'Die von Ihnen ausgewählte Person ist leer',
        self::LIVE_APPROVED_EXISTS => 'Live genehmigt existiert',
        self::LIVE_LECTURER_NOT_REQUEST => 'Live-Dozent nicht erwünscht',
        self::LIVE_LECTURER_NOT_APPROVED => 'Live-Dozent nicht zugelassen',
        self::LIVE_LECTURER_APPROVED_ALREADY => 'Live-Dozent bereits genehmigt',
        self::LIVE_COMPERE_IN_LECTURERS => 'Moderatoren können nicht als Dozenten eingestellt werden',

        self::LECTURER_LEVEL_STANDARD_MUST_SET => 'Setzen Sie mindestens einen Indikator für die Dozentenbewertung',
        self::LECTURER_INSIDE_IS_EXISTS => 'Der Mitarbeiter ist bereits Dozent',
        self::LECTURER_INSIDE_TYPE_ERROR => 'Interner Dozentenformatfehler',
        self::LECTURER_NUMBER_REPEAT => 'Dozenten-ID existiert bereits',
        self::LECTURER_ORDER_AUDITOR => 'Termin wurde überprüft',
        self::LECTURER_DATE_ORDERED => 'Zeitrahmen des Dozenten wurde gebucht',
        self::LECTURER_DATE_DISENABLED => 'Dozentenzeitslots können nicht reserviert werden',
        self::LECTURER_PROJECT_REPEAT => 'Nummer des Zertifizierungsprogramms existiert bereits',
        self::LECTURER_PROJECT_UNEXISTS => 'Zertifizierungsprogramm nicht vorhanden',
        self::LECTURER_PROJECT_ALREADY_ENDED => 'Zertifizierungsprogramm ist beendet',
        self::LECTURER_PROJECT_APPLICATION_NOT_ALLOWED => 'Zertifizierungsprogramm ist nicht für die Einschreibung geöffnet',
        self::LECTURER_PROJECT_NO_VISIT_AUTH => 'Keine Berechtigung zur Anmeldung',
        self::LECTURER_PROJECT_LEARNER_ALREADY_EXIST => 'Mitglied existiert bereits',
        self::LECTURER_PROJECT_LEARNER_UNDER_REVIEW => 'Überprüfung des Mitglieds im Gange',
        self::LECTURER_PROJECT_LEARNER_OVERSTEP => 'Maximale Anzahl von Einschreibungen',

        self::JOBLEVEL_NOT_FOUND => 'Rang ist nicht vorhanden',
        self::JOBLEVEL_NO_EXISTS => 'Rangnummer existiert bereits',
        self::JOBLEVEL_NAME_EXISTS => 'Rangname bereits vorhanden',
        self::JOBLEVEL_USED => 'Rang wurde bereits verwendet',
        self::JOBLEVEL_ORDER_EXISTS => 'Rangfolge bereits vorhanden',

        self::QUE_EXISTS => 'Aufgabe läuft, bitte später wieder versuchen',

        self::EMP_GRP_NOT_FOUND => 'Gruppe existiert nicht',
        self::EMP_GRP_USED => 'Gruppe wurde genutzt',
        self::EMP_GRP_NOT_DYNAMIC => 'Diese Gruppe ist keine dynamische Gruppe',

        self::OFFLINE_ASSESSMENT_MUST_NUM_MORE => 'Die Anzahl der Pflichtfragen in den Bestehensregeln ist höher als die tatsächliche Anzahl der Pflichtfragen',
        self::EXAM_DATA_PROCESSING => 'Daten zu Testfragen werden verarbeitet',
        self::EXAM_APPROVE_NOT_FOUND => 'Prüfungsbenotung nicht vorhanden',
        self::EXAM_UNFINISH_NOT_FOUND => 'Ihre Prüfung wurde eingereicht',
        self::EXAM_MARKING => 'Wird markiert',

        self::CASE_DIRECTORY_IS_EXISTS => 'Katalog existiert bereits',
        self::CASE_DIRECTORY_NOT_FOUND => 'Verzeichnis existiert nicht',
        self::CASE_DIRECTORY_PARENT_NOT_FOUND => 'Übergeordnetes Verzeichnis existiert nicht',
        self::CASE_DIRECTORY_SORT_DIFFERENT_PARENTS => 'Nur Verzeichnisse mit demselben Elternteil können sortiert werden',
        self::CASE_DIRECTORY_GT_MAX_LEVEL => 'Es werden nur 3 Ebenen von Verzeichnissen unterstützt',
        self::CASE_DIRECTORY_HAVE_CHILD => 'Das Verzeichnis hat Unterverzeichnisse',
        self::CASE_ATTACHMENT_IS_NECESSARY => 'Die von Ihnen verwendete Vorlage, der Anhang ist erforderlich',
        self::CASE_ATTACHMENT_IS_OVERFLOW => 'Die Anzahl der hochgeladenen Anhänge hat das Limit erreicht und kann nicht weiter hochgeladen werden',
        self::CASE_ATTACHMENT_UNSUPPORTED_FILE_TYPES => 'Anlagentypen, die für das Hochladen nicht unterstützt werden',
        self::CASE_STAGE_IS_EXISTS => 'Vorhandener Phasenname',
        self::CASE_TEMPLATE_NOT_FOUND => 'Vorlage existiert nicht',
        self::CASE_TEMPLATE_NO_IS_EXISTS => 'Vorlagennummer existiert bereits',
        self::CASE_TEMPLATE_TITLE_IS_EXISTS => 'Vorlagenname existiert bereits',

        self::LEARNING_TEMPLATE_NO_GROUP_CANT => 'Nicht gruppiert kann nicht gelöscht oder geändert werden',
        self::LEARNING_TEMPLATE_TITLE_EXISTS => 'Dieser Gruppenname existiert bereits',
        self::LEARNING_TEMPLATE_TITLE_IS_USED => 'Die Gruppe ist bereits in Gebrauch und kann nicht gelöscht werden',
        self::EXAM_UNAUTHORIZED_PARTICIPATION => 'Sie haben keine Berechtigung zur Teilnahme an dieser Prüfung',
        self::VOTE_UNAUTHORIZED_PARTICIPATION => 'Sie haben keine Berechtigung zur Teilnahme an dieser Abstimmung',
        self::VOTE_HAVE_CLOSED => 'Diese Abstimmung ist beendet',
        self::VOTE_UN_START => 'Diese Abstimmung hat noch nicht begonnen',
        self::VOTE_OPEN_NO_EDIT => 'Bei der öffentlichen Abstimmung sind keine Änderungen möglich',
        self::VOTE_IS_REPEAT_NO_EDIT => 'Mehrfachabstimmungen erlauben keine Änderungen',
        self::VOTE_RESULT_NOT_FOUND => 'Abstimmungsergebnisse nicht gefunden',
        self::VOTE_RESULT_HAS_EXAMINE => 'Die Abstimmung wurde überprüft und eine Änderung ist nicht zulässig',
        self::ASSESSMENT_TEMPLETE_USED => 'Diese Vorlage wurde verwendet und kann nicht gelöscht werden',
        self::SURVEY_TEMPLETE_USED => 'Diese Vorlage wurde verwendet und kann nicht gelöscht werden',
        self::ASSESSMENT_TEMPLETE_TITLE_EXIST => 'Name der Bewertungsvorlage bereits vorhanden',
        self::SURVEY_TEMPLETE_TITLE_EXIST => 'Name der Forschungsvorlage bereits vorhanden',
        self::ASSESSMENT_TEMPLETE_NO_EXIST => 'Nummer der Bewertungsvorlage bereits vorhanden',
        self::SURVEY_RE_NUM_FULL => 'Anzahl der Wiederholungsbefragungen wurde erreicht',
        self::SURVEY_ANSWER_IS_REPEAT => 'Antworten auf nicht wiederholbare Lückentextfragen werden wiederholt',

        self::SURVEY_NOTIFY_UNPUBLISHED => 'Forschung wurde nicht veröffentlicht und Benachrichtigungen sind nicht zulässig',
        self::SURVEY_NOTIFY_END => 'Forschung ist beendet und Benachrichtigungen sind nicht zulässig',
        self::SURVEY_NEED_LOGIN => 'Für diese Forschung ist eine Anmeldung erforderlich',

        self::FACE_MATCHING_SOURCE_EXISTS => 'Gesichtsvergleichsvorlage bereits vorhanden',
        self::FACE_MATCHING_DETECT_FAIL => 'Gesichtsvergleich fehlgeschlagen',
        self::FACE_MATCHING_SOURCE_NOT_EXIST => 'Gesichtsvergleichsvorlage nicht vorhanden',
        self::FACE_MATCHING_STORAGE_FOLDER_CREATE_FAIL => 'Speicherverzeichnis kann nicht erstellt werden',
        self::FACE_MATCHING_INVALID_FILE_TYPE => 'Nicht unterstütztes Bildformat',
        self::FACE_MATCHING_INVALID_FILE => 'Nicht unterstütztes Dateiformat',

        self::APPROVAL_CATEGORY_IS_EXISTS => 'Kategorie existiert bereits',
        self::APPROVAL_CATEGORY_IS_USED => 'Die Kategorie wurde verwendet und kann nicht gelöscht werden',
        self::APPROVAL_PROCESS_IS_EXISTS => 'Genehmigungsprozess bereits vorhanden',
        self::APPROVAL_LEVEL_IS_EXISTS => 'Genehmigungsebene bereits vorhanden',
        self::APPROVAL_PROCESS_NOT_ENABLED => 'Das Unternehmen hat keinen Genehmigungsfluss aktiviert',
        self::APPROVAL_REVIEW_EMPLOYEE_MUST => 'Obligatorische Auswahl des Genehmigenden',
        self::COURSE_REVIEW_NO_AUTH => 'Keine Kursgenehmigungsberechtigung',

        self::COMPETITION_ROUND_START_ERROR => 'Falsche Startzeit oder Endzeit der Runde',
        self::COMPETITION_CANT_RECEIVE_AWARD => 'Kein Anspruch auf Saisonpreise',
        self::COMPETITION_JS_NO_IS_EXISTS => 'Wettbewerbsnummer nicht wiederholbar',
        self::COMPETITION_NOT_IN_VOTE_RANGE => 'Von der Abstimmung ausgeschlossen',
        self::COMPETITION_ROUND_IS_END => 'Diese Runde ist beendet und kann nicht gelöscht werden',
        self::COMPETITION_ROUND_IS_START => 'Diese Runde wurde bereits gestartet und kann nicht geändert oder gelöscht werden',
        self::COMPETITION_APPLY_TIME_ERROR => 'Falsche Einrichtungszeit der Einschreibung',
        self::COMPETITION_NOT_HAVE_ROUND => 'Bitte fügen Sie erst die Rundeninformationen hinzu, bevor Sie veröffentlichen',
        self::COMPETITION_NOT_BEGIN => 'Wettbewerb hat noch nicht begonnen',
        self::COMPETITION_ACHIEVEMENT_GROUP_USED => 'Dieses Team ist in einer Matchmaking-Gruppe, bitte löschen Sie es, bevor Sie es erneut versuchen...',
        self::COMPETITION_ACHIEVEMENT_BATTLE_EXISTS => 'Dieses Team existiert bereits',
        self::COMPETITION_ACHIEVEMENT_HELP_EXISTS => 'Unterstützung wurde in diesem PK abgeschlossen',
        self::COMPETITION_VOTE_EXISTS => 'Habe heute schon abgestimmt',
        self::COMPETITION_IS_USED => 'Wettbewerb belegt und kann nicht gelöscht werden',
        self::COMPETITION_NOTIFY_UNPUBLISHED => 'Wettbewerb wurde nicht veröffentlicht, keine Benachrichtigungen zulassen',
        self::COMPETITION_NOTIFY_END => 'Wettbewerb ist geschlossen, keine Benachrichtigungen zulassen',
        self::COMPETITION_VOTE_NOT_STARTED => 'Abstimmung hat nicht begonnen',
        self::COMPETITION_VOTE_ALREADY_ENDED => 'Abstimmung ist geschlossen',

        self::POSITION_COMPETENCY_CATEGORY_EXISTS => 'Klassifizierung des Kompetenzindikators bereits vorhanden',
        self::POSITION_COMPETENCY_CATEGORY_NOT_FOUND => 'Klassifizierung der Kompetenzindikatoren nicht vorhanden',
        self::POSITION_COMPETENCY_EXISTS => 'Kompetenzindikatoren bereits vorhanden',
        self::POSITION_COMPETENCY_NOT_FOUND => 'Kompetenzindikator existiert nicht oder wurde gelöscht',
        self::POSITION_COMPETENCY_ELEMENT_EXISTS => 'Fähigkeitsindikator bereits vorhanden',
        self::CATEGORY_NAME_EXIST => 'Kategorie existiert bereits',

        self::POSITION_SKILL_CATEGORY_EXISTS => 'Qualifikationsklassifizierung bereits vorhanden',
        self::POSITION_SKILL_CATEGORY_NOT_FOUND => 'Qualifikationsklassifizierung nicht vorhanden',
        self::POSITION_SKILL_EXISTS => 'Fertigkeit bereits vorhanden',
        self::POSITION_SKILL_NOT_FOUND => 'Fertigkeit existiert nicht oder wurde gelöscht',
        self::POSITION_SKILL_ELEMENT_EXISTS => 'Fertigkeit bereits vorhanden',
        self::SKILL_NOT_EXISTS => 'Fehlende Fähigkeiten im Kompetenzmodell',

        self::INSPECTION_ELECTIVE_TASK_UNFINISHED => 'Sie haben unerledigte Aufgaben',
        self::INSPECTION_ELECTIVE_CLASSIFY_UNFINISHED => 'Ihre Bewertung enthält noch nicht abgeschlossene Kategorien',
        self::INSPECTOR_IS_NOT => 'Sie sind kein Inspektor',
        self::INSPECTION_AT_LEAST_ONE => 'Bitte absolvieren Sie mindestens eine Bewertung',

        self::HARMONY_ERROR => 'Enthält vertrauliche Informationen. Ergebnisse können nicht angezeigt werden',

        self::RETRAINING_NO_EXISTS => 'Nummer existiert bereits',
        self::RETRAINING_NO_TASKS => 'Bitte fügen Sie zunächst Vorlagenaufgaben hinzu',
        self::RETRAINING_NOT_ALLOWED_REPEAT => 'Erneute Authentifizierung ist noch nicht aktiviert',
        self::RETRAINING_REACH_CYCLE_INDEX => 'Ihre Zertifizierungszykluszeiten sind abgelaufen',
        self::RETRAINING_TIME_NOT_UP => 'Zeitpunkt für die Rezertifizierung ist noch nicht gekommen',
        self::RETRAINING_LEARNER_AUTHENTICATE_ONGOING => 'Ihre Zertifizierung läuft noch, bitte wiederholen Sie die Zertifizierung nicht',
        self::RETRAINING_EXAM_INVALID => 'Ungültige Zertifizierungs- und Umschulungsprüfungen',
        self::APPRIAISAL_POSITION_SKILL_EXISTS_ELEMENT=>'In der Stellenbescheinigung sind Fertigkeiten enthalten. Löschen Sie zunächst die Fertigkeiten aus der Stellenbescheinigung',
        self::RETRAINING_NOT_EXISTS=>'Leider gibt es diese Zertifizierung und Umschulung nicht!',
        self::RETRAINING_LEARNER_NOT_PUBLISHED=>'Leider sind diese Zertifizierung und Umschulung noch nicht veröffentlicht!',
        self::RETRAINING_LEARNER_NOT_AUTH=>'Leider fallen Sie nicht in den Geltungsbereich dieser Zertifizierung und Umschulung!',

        self::EXPERIENCE_DETAIL_BEYOND_LIMIT => 'Anzahl der von Ihnen hochgeladenen Erfahrung hat das Limit erreicht',

        self::PHOTOGRAPH_DETAIL_BEYOND_LIMIT => 'Anzahl der von Ihnen hochgeladenen Fotos hat das Limit erreicht',
        self::PHOTOGRAPH_LEARNER_NOT_EXISTS => 'Auszubildende nicht in dieser Klasse',
        self::PHOTOGRAPH_LEARNER_SUPPORT_EXISTS => 'Den Auszubildenden hat es gefallen',
        self::PHOTOGRAPH_LEARNER_SUPPORT_MAX => 'Like hat die Höchstgrenze überschritten',

        self::CERTIFICATION_USED => 'Das Zertifikat wird verwendet und kann nicht gelöscht oder deaktiviert werden',
        self::CERTIFICATION_USER_USED => 'Zertifikatspersonal kann nicht löschen',
        self::DIRECTORY_PARENT_NOT_SAME_SELF => 'Das übergeordnete Verzeichnis darf nicht dieses Verzeichnis sein',
        self::NOT_GROUP_CANNOT_SELECTED => 'Nicht gruppierte Verzeichnisse können nicht ausgewählt werden',

        self::EVENT_MEMBER_SIGN_INVALID_CAPTCHA => 'Ungültiger SMS-Verifizierungscode',
        self::EVENT_MEMBER_SIGN_VX_INVALID_ACCESS_TOKEN => 'Ungültig access_token',
        self::EVENT_MEMBER_SIGN_VX_INVALID_PWD => 'Ungültiges Anmeldekennwort',

        self::GEN_LIVE_CREATE_ERROR => 'Erstellung des Live-Streamings fehlgeschlagen',
        self::GEN_LIVE_NOT_EXISTS => 'Live-Streaming nicht vorhanden',
        self::GEN_LIVE_UPDATE_ERROR => 'Live-Update fehlgeschlagen',
        self::GEN_LIVE_INVALID_INPUT => 'Live-Stream-Überprüfungsparameter fehlgeschlagen',
        self::GEN_LIVE_MEMBER_NOT_ALLOWED => 'Keine Berechtigung zum Anzeigen des Live-Streamings',
        self::COURSE_MULTI_DIRECTORY_LIMIT_ERROR => 'Nicht mehr als 5 Unterverzeichnisse',
        self::GEN_LIVE_GENERATE_TIME => 'Es sind weniger als 10 Minuten seit der letzten Datengenerierung vergangen. Bitte später wieder versuchen',
        self::GEN_LIVE_LIMIT_ATTENDEES => 'Die Anzahl der Personen in der Live-treaming überschreitet das Limit. Bitte ändern Sie es oder wenden Sie sich an die Mitarbeiter',
        self::GEN_LIVE_NO_AUTH => 'Bitte anmelden',

        self::KNOWLEDGE_BASE_NAME_EXIST => 'Name der Wissensdatenbank existiert bereits',
        self::KNOWLEDGE_BASE_NOT_EXIST => 'Wissensdatenbank existiert nicht',
        self::KNOWLEDGE_QUESTION_HAS_EXISTS => 'Diese Frage existiert bereits in dieser Wissensdatenbank',
        self::KNOWLEDGE_CATEGORY_CANNOT_DELETE => 'Standardkategorie kann nicht gelöscht oder bearbeitet werden',
        self::KNOWLEDGE_CATEGORY_CANNOT_EQ_ROOT_NAME => 'Kategoriename kann nicht die Standardkategorie sein',
        self::KNOWLEDGE_CATEGORY_HAS_QUESTION => 'Unter dieser Kategorie befinden sich Fragen, da nicht gelöscht werden können',
        self::KNOWLEDGE_QUESTION_NOT_EXISTS => 'Frage in der Wissensdatenbank existiert nicht',
        self::KNOWLEDGE_CATEGORY_NAME_EQ => 'Name der Kategorie nicht geändert',
        self::KNOWLEDGE_QUESTION_IS_SYSTEM => 'Diese Frage wird vom System kopiert, Sie können sie nicht ändern',
        self::KNOWLEDGE_BASE_HAS_QUESTION => 'Es gibt Fragen unter dieser Wissensdatenbank, das nicht gelöscht werden kann',
        self::KNOWLEDGE_APPLY_EXIST => 'Anwendung existiert bereits',

        self::EVENT_PRIZE_IS_GAIN => 'Dieser Preis hat bereits einen Gewinner und kann nicht gelöscht werden',
        self::EVENT_ALLOW_NUM_MORETHAN_EXISTS => 'Die Anzahl der Personen, die den Preis erhalten haben, ist größer als die festgelegte Anzahl',
        self::EVENT_DESIGATED_IS_HAVED => 'Der Gewinn wurde für den Gewinner gesperrt, der anderweitig betrogen hat',
        self::EVENT_DESIGATED_IS_OVERFLOW => 'Die Anzahl der Betrüger ist größer als die Anzahl der Preise',
        self::EVENT_NOT_START => 'Veranstaltung hat nicht begonnen',
        self::EVENT_END => 'Veranstaltung ist beendet',

        self::EVENT_MEMBER_SIGNED => 'Angemeldet',
        self::COURSE_HAVE_LIMIT => 'Kurs ist noch nicht abgeschlossen und muss abgeschlossen werden, bevor Sie benotet werden können',
        self::COURSE_TYPE_NOT_EQ => 'Die beiden Kursunterlagentypen sind unterschiedlich. Bitte laden Sie denselben Dateityp hoch',
        self::COURSE_MUST_END => 'Kurs noch nicht abgeschlossen. Sie müssen ihn abschließen, bevor Sie den Test ablegen können',
        self::EXPORT_LIMIT => 'Leider können Sie keine Daten exportieren',
        self::COURSE_STAR_LIMIT => 'Überschreitung der Grenzwerte',

        // self::CONTRACT_TYPE_USED => 'Vertragstyp in Verwendung',
        // self::EXPORT_LIMIT => 'Leider können Sie keine Daten exportieren',

        self::INSPECTION_QUESTION_CATEGORY_USED => 'Kategorie ist in Gebrauch und kann nicht gelöscht werden',
        self::TASK_NO_PERMISSIONS => 'Sie haben keine Berechtigung zur Teilnahme an dieser Aufgabe',
        self::TASK_END => 'Aufgabe ist geschlossen und Sie können nicht teilnehmen',
        self::OFFLINEEXERCISE_NO_PERMISSIONS => 'Sie haben keine Berechtigung, an dieser Offline-Übung teilzunehmen',
        self::CONTRACT_TYPE_USED => 'Vertragstyp in Verwendung',

        self::GEN_LIVE_CATEGORY_NOT_REMOVE => 'Kategorie wurde verwendet und kann nicht gelöscht werden',


        self::QUESTION_NO_EXISTS => 'Nummer existiert bereits',

        self::SPECIAL_SUBJECT_NO_USED => 'Nummer bereits belegt',

        self::EMP_SELF_REG_DATA_INVALID => 'Validierung der Formulardaten fehlgeschlagen. Bitte überprüfen Sie die Daten',
        self::EMP_SELF_REG_UNIQUE => 'Formulardaten sind nicht eindeutig',
        self::EMP_SELF_REG_UNIQUE_USERNAME => 'Benutzername wurde verwendet oder die Registrierung wurde beantragt',

        self::DAILY_CLOCK_CANT_PUBLISH => 'Die tägliche Check-in-Startzeit hat begonnen und kann nicht freigegeben werden',

        self::TRAINING_CENTER_UNDEFINED => 'Unbekannter Fehler im Schulungszentrum',
        self::TRAINING_CENTER_EXISTS => 'Schulungszentrum existiert bereits',
        self::TRAINING_CENTER_NOT_FOUND => 'Schulungszentrum existiert nicht',
        self::TRAINING_CENTER_NO_EXISTS => 'Nummer wird bereits verwendet',
        self::TRAINING_CENTER_MAX_LEVEL => 'Maximales Level erreicht',
        self::TRAINING_CENTER_USED => 'Dieses Schulungszentrum wird derzeit genutzt',
        self::TRAINING_CENTER_NOT_LEAF => 'Dieses Schulungszentrum enthält Unterschulungszentren',
        self::VOTE_NO_REPEAT => 'Doppelte Stimmabgabe nicht erlaubt',
        self::KNOWLEDGE_CONTAIN_AUDIT_IDS => 'Zu den eingereichten Kenntnissen können nicht diejenigen gehören, die gerade überprüft werden, und diejenigen, die bestanden wurden',

        self::COURSE_HUNDUN_SIGN_ERROR => 'Signaturfehler',
        self::COURSE_HUNDUN_PARAMS_ERROR => 'Parameterfehler',
        self::COURSE_HUNDUN_NO_AUTH => 'Keine Ansichtsberechtigung',
        self::COURSE_HUNDUN_TIME_OVERDUE => 'Anfrage abgelaufen',
        self::COURSE_HUNDUN_USER_TOKEN_INVALID => 'Benutzertoken läuft ab',
        self::COURSE_HUNDUN_DATA_ERROR => 'Datenfehler',
        self::COURSE_HUNDUN_CHECK_ERROR => 'Verifizierung fehlgeschlagen',
        self::COURSE_HUNDUN_USER_REGISTER_REACH_LIMIT => 'Maximale Anzahl von registrierten Konten',
        self::COURSE_HUNDUN_USER_REGISTED => 'Benutzer hat sich bereits registriert',
        self::COURSE_MODULE_UN_REGISTED => 'Keine Ansichtsberechtigung',

        self::LPP_NOT_FOUND => 'Popup-Frage existiert nicht oder wurde gelöscht',
        self::LPP_CREATE_FAIL => 'Erstelluung fehlgeschlagen',
        self::LPP_UPDATE_FAIL => 'Aktualisierung fehlgeschlagen',
        self::LPP_TIME_LARGER_DURATION => 'Zeitpunkt ist länger als die Kursdauer',
        self::LPP_TIME_DUPLCATED => 'Es gibt einen doppelten Zeitpunkt',
        self::LPP_OPTION_ID_DUPLICATED => 'Doppelte Options-IDs vorhanden',
        self::LPP_OPTION_INVALID_COUNT => 'Anzahl der falschen richtigen Antwortoptionen',

        //Punkteüberprüfung
        self::SCORE_TYPE_EXISTS=>"Punkttyp bereits vorhanden",
        self::SCORE_TYPE_NO_EXISTS=>"Punkttyp existiert nicht",
        self::SCORE_APPLY_NO_EXISTS=>"Punktanwendung existiert nicht",
        self::SCORE_APPLY_STATE_ERROR=>"Fehler beim Status der Punktanwendung",
        self::SCORE_APPLY_NO_CHECKING=>"Punktbewerbung ohne Prüfung",

        //Verwaltung von Verbrauchsmaterial
        self::CONSUMABLE_EXISTS=>"Verbrauchsmaterialien bereits vorhanden",
        self::CONSUMABLE_NO_EXISTS=>"Verbrauchsmaterialien nicht vorhanden",


        self::LIVE_HON_SHAN_TIME_ERROR => 'Zeit muss größer sein als die aktuelle Zeit',
        self::LIVE_HONGSHAN_HAS_END => 'Live-Streaming ist beendet oder Sitzung existiert nicht',

        self::SHORTLINK_INVALID_URL => 'Ungültiger Link',
        self::TRAINING_TASK_END => 'Projekt ist abgeschlossen',
        self::TRAINING_HAS_USE => 'Projekt ist einer Klasse zugeordnet',


        self::GZ_WATCH_CARD_NO_OR_DISPLAY_ERROR => 'Falsche Personalausweisnummer oder falscher Name',
        self::KNOWLEDGE_POINT_CATEGORY_EXISTS => 'Kategoriename existiert bereits',
        self::LIVE_ROLE_ERROR => 'Rolle passt nicht zur Live-Streaming',
        self::LIVE_UN_DELAYED => 'Live-Streaming ohne Verzögerung nicht aktiviert',


        self::NOT_ENOUGH_SCORE => 'Nicht genügend Punkte',
        self::POSITION_GRADING_NO_QUESTION => 'Keine Testfragen vorhanden',

        self::GRADE_SETTING_NAME_EXISTS_ERROR => 'Stufen sind bereits vorhanden',
        self::GRADE_SETTING_LIMIT => 'Bis zu 5 Stufen können hinzugefügt werden',

        self::AI_SCENARIO_NOT_FOUND => 'Szenariosimulation nicht vorhanden',
        self::AI_SCENARIO_NODE_NOT_FOUND => 'Szenariosimulationsknoten existiert nicht oder wurde gelöscht',
        self::AI_SCENARIO_NOT_PUBLISHED => 'Szenariosimulation nicht freigegeben',
        self::AI_SCENARIO_COPY_FAIL => 'Kopiervorgang fehlgeschlagen. Bitte wieder versuchen',
        self::AI_SCENARIO_PROCESS_NOT_FOUND => 'Inhalt der Szenariosimulation nicht festgelegt',
        self::AI_SCENARIO_PROCESS_NEXT_NODE_NOT_FOUND => 'Es gibt keine nächste Frage oder sie wurde gelöscht',
        self::AI_SCENARIO_PROCESS_PREV_NODE_NOT_PASSED => 'Vorherige Frage wurde nicht beantwortet und die nächste Frage kann nicht abgerufen werden',
        self::AI_SCENARIO_PROCESS_NODE_ANSWERED => 'Diese Frage wurde bereits beantwortet',
        self::AI_SCENARIO_SUBMIT_EXCEPTION => 'Beim Absenden ist eine Ausnahme aufgetreten. Bitte überprüfen Sie die Daten oder versuchen Sie es später erneut',

        self::YEAR_REPORT_OUTDATE => 'Bericht abgelaufen',

        self::GUIDANCE_CLASSIFY_EXISTS => 'Kategorie existiert bereits',
        self::GUIDANCE_INSTRUCTIONS_EXISTS => 'Bedienungsanleitung bereits vorhanden',

        self::STAT_FILTER_GROUP_TYPE_NOT_SUPPORT => 'Diese Art von Personen kann nicht gefiltert werden',

        self::RETRAINING_LEVEL_NO_EXISTS => 'Nummer ist besetzt',

        self::LEARNING_PACK_TOP_EXISTS => 'Diese Priorität existiert bereits',

        self::RETRAINING_CATEGORY_NO_EXISTS => 'Nummer ist besetzt',

        self::CLASSROOM_NOT_EXISTS =>"Klassenzimmer existiert nicht",

        self::CLASSROOM_HAS_RE => "Klassenzimmer ist reserviert",

        self::HUNDUN_SIGN_ERROR => "Signaturfehler",
        self::HUNDUN_MOBILE_FORMAT_ERROR => "Falsche Handynummer",
        self::HUNDUN_PARAMS_ERROR => "Parameterfehler",
        self::HUNDUN_REACH_REGISTER_LIMIT => "Registriertes Konto hat die Obergrenze erreicht",
        self::HUNDUN_REGISTER_FAILED => "Benutzerregistrierung fehlgeschlagen",
        self::HUNDUN_PARAM_ERROR => "Parameterfehler",
        self::HUNDUN_USER_REGISTED => "Dieser Benutzer hat sich bereits registriert",
        self::HUNDUN_REACH_USER_SIGNOUT_LIMIT => "Standardanzahl der Stornierungen beträgt 10% der Gesamtzahl der Käufe",
        self::HUNDUN_COMPANY_UNEXISTS => "Berechtigungsfehler: Unternehmenskonto existiert nicht",
        self::HUNDUN_UNAUTHORIZED_COURSE_PACKAGE => "Berechtigungsfehler: Unternehmen hat das Kurspaket nicht autorisiert",
        self::HUNDUN_UNAUTHORIZED_COURSE => "Kurs nicht autorisiert",

        self::DATABOARD_SYSTEM_UNALLOWED_DELETED => "System-Dashboard darf nicht gelöscht werden!",

        self::MATERIAL_NOT_EXISTS_ERROR =>"Das Filmmaterial ist nicht vorhanden",
        self::MATERIAL_TYPE_NOT_EQ =>"Der Typ ist nicht gleich, laden Sie den gleichen Typ hoch",
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_MATERIAL_ERROR =>"Kann nicht gelöscht werden, wenn das Material in der Bibliothek ist.",

        self::LANGUAGE_POINTS_NOT_EXISTS_ERROR => "issenspunkte sind nicht vorhanden.",
        self::LANGUAGE_POINTS_NO_EXISTS => "bereits vorhanden",

        self::TEACHING_MATERIAL_NOT_EXISTS_ERROR => "Unterrichtsmaterial existiert nicht",
        self::TEACHING_MATERIAL_NO_EXISTS => "bereits vorhanden",

        self::VERSION_NO_REDUCIBLE_VERSION => "Diese Version ist nicht zur Überprüfung freigegeben und kann nicht wiederhergestellt werden",
        self::VERSION_HAS_REVIEW_VERSION => "Version noch nicht überprüft, kann nicht hinzugefügt werden",

        self::ACTION_ASSESSMENT_NOT_EXISTS => 'Aktionsbewertung nach dem Training existiert nicht',
        self::ACTION_ASSESSMENT_LEARNER_EXISTS => 'Studenteninformationen existieren nicht',
        self::ACTION_ASSESSMENT_LEARNER_NOT_EXISTS => 'Studenteninformationen existieren nicht' ,
        self::ACTION_ITEMS_NOT_REPEAT_SUBMIT => 'Aktionselemente können nicht wiederholt eingereicht werden',
        self::ACTION_ASSESSMENT_NO_REVIEW_PERMISSION => 'Keine Überprüfungsberechtigung',
        self::ACTION_ASSESSMENT_NOT_REPEAT_REVIEW => 'Kann nicht wiederholt überprüft werden',
        self::ACTION_ASSESSMENT_NO_COMMENT_PERMISSION => 'Keine Evaluierungsberechtigung',
        self::ACTION_ASSESSMENT_NOT_REPEAT_COMMENT => 'Kann nicht wiederholt kommentieren',
        self::COMPETENCY_INDICATOR_NOT_FOUND => 'Berufskompetenzindikator existiert nicht',
        self::COMPETENCY_INDICATOR_GROUP_NOT_FOUND => 'Gruppe existiert nicht',
        self::COMPETENCY_INDICATOR_SKILL_NOT_FOUND => 'Skill existiert nicht',
        self::COMPETENCY_INDICATOR_GROUP_EXISTS => 'Gruppe existiert bereits',
        self::COMPETENCY_INDICATOR_SKILL_EXISTS => 'Skill bereits vorhanden',
    ];
}