<?php

/**
 * Error Codes.
 */

namespace App\Common;

interface Errors
{

    /** Account error codes */
    const ACCOUNT_NOT_PERMISSION = 50;
    const ACCOUNT_NOT_FOUNT = 51; // typo
    const ACCOUNT_NAME_EXISTS = 52;
    const ACCOUNT_CREATE_DICTIONARY_ERROR = 53;
    const ACCOUNT_CREATE_DEPARTMENT_ERROR = 54;
    const ACCOUNT_CREATE_ROLE_ERROR = 55;
    const ACCOUNT_CREATE_USER_ERROR = 56;
    const ACCOUNT_CREATE_EMPLOYEE_ERROR = 57;
    const ACCOUNT_CREATE_ASSESSMENT_ERROR = 58;
    const ACCOUNT_INVALID = 59;
    const ACCOUNT_CODE_INVALID = 60;
    const ACCOUNT_EXPIRED = 61;
    const ACCOUNT_FUNCTION_NOT_ENABLED = 62;
    const ACCOUNT_URL_EXPIRE = 63;

    /** Custom field error codes 10000-10099 */
    const CUSTOM_FIELD_NAME_EXISTS = 10000;

    /** Security rule 10100-10199 **/
    const SECURITY_PWD_WEAK = 10100;

    /** Import config 10200-10299 */
    const IMPORT_CONFIG_NOT_FOUND = 10200;
    const IMPORT_MAX_ROWS = 10201;

    // 评估相关
    const PUBLISH_NO_QUESTIONNAIRE = 3600001; // 发布的时候，问卷无效
    const PUBLISH_NO_MODEL = 3600002; // 发布的时候，问卷无效
    const PUBLISH_NO_DIMENSION = 3600003; // 发布的时候，问卷无效
    const PUBLISH_NO_ELEMENT = 3600004; // 发布的时候，问卷无效
    const PUBLISH_NO_QUESTION = 3600005; // 发布的时候，问卷无效

    /** 69~89: User error codes */
    const USER_INVALID_NEW_PWD = 68;
    const USER_PWD_NEW_SAME_OLD = 69;
    const USER_USR_ERROR_DEFAULT = 70;
    const USER_CAPTCHA_IMAGE_INVALID = 71;
    const USER_CAPTCHA_SMS_INVALID = 72;
    const USER_PHONE_INVALID = 73;
    const USER_ACCOUNT_NOT_FOUND = 74;
    const USER_LOGIN_FAIL = 75;
    const USER_QR_LOGIN_FAIL = 76;
    const USER_QR_LOGIN_TIMEOUT = 77;
    const USER_PWD_ERROR = 78;
    const USER_LOGIN_FAIL_TOO_MANY = 79;
    const USER_NOT_FOUND = 80;
    const USER_EXISTS_IN_COMPANY = 81;
    const USER_INVALID_OLD_PASSWORD = 82;
    const USER_CREATE_ERROR = 83;
    const USER_SMS_CAPTCHA_FREQUENCY = 84;
    //const INPUT_VALID_ERROR = 85;
    const USER_INVALID_USERNAME = 85;
    const USER_LEAVE_OFFICE = 86;
    const USER_SMS_TIMEOUT = 87;
    const USER_SMS_INVALID = 88;
    const MOBILE_EXIST = 89;
    const USER_2FA_BOUND = 1000001;
    const USER_2FA_DISBLED = 1000002;
    // 输入手机号与用户手机号不一致
    const USER_2FA_MOBILE_NOT_MATCH = 1000003;
    // 短信验证码不一致
    const USER_2FA_MOBILE_CAPTCHA_NOT_MATCH = 1000004;
    // 错误的2FA token
    const USER_2FA_MOBILE_INVALID_TOKEN = 1000005;

    /** 90~109: audio file oss video error codes */
    const OSS_AUDIO_COURSEWARE = 90;
    const DOWNLOAD_OSS_FAIL = 91;
    const AUDIO_CONTACT_FAIL = 92;
    const AUDIO_UPLOAD_FAIL = 93;
    const UPDATE_COURSE_CONTACT_FAIL = 94;
    const COURSE_AUDIO_IS_NULL = 95;
    const VIDEO_NOT_FOUND = 96;
    const UPLOAD_FILE_FAIL = 97;
    const OSS_AUDIO_COURSEWARE_ING = 98;
    const IMG_LIMIT_ERROR = 99;
    const FILE_LIMIT_ERROR = 100;
    const FILE_READ_FAIL = 101;
    const FILE_SIGN_VERIFY_FAIL = 102;
    const SECURITY_RULE_INVALID_IP_CONFIG = 103;
    const IMG_SIZE_LIMIT_ERROR = 104;

    /** 110~149: question error codes */
    const QUESTION_BANK_EXISTS = 110;
    const QUESTION_EXISTS = 111;
    const QUESTION_COYE_FAIL = 112;
    const QUESTION_IMPORT_TEMPLETE = 113;
    const QUESTION_NO_EXISTS = 114;
    const QUESTION_BANK_AI_FAIL = 115;


    /** 149~200: exam error codes */
    const PAPER_EXISTS = 150;
    const EXAM_EXISTS = 170;
    const EXAM_END = 171;
    const EXAM_COYE_FAIL = 172;
    const EXAM_EMPLOYEE_END = 173;
    const EXAM_DETAIL_FAIL = 174;
    const EXAM_NO_OPERATION_AUTH = 175;
    const EXAM_PLAN_NOT_PUBLISHED = 176;
    const EXAM_EMPLOYEE_NOT_RANGE = 177;
    const EXAM_DATA_PROCESSING = 178;
    const EXAM_APPROVE_NOT_FOUND = 179;
    const EXAM_MARKING = 180;
    const EXAM_UNFINISH_NOT_FOUND = 181;
    const EXAM_UNAUTHORIZED_PARTICIPATION = 182;
    const EXAM_DIR_NOT_FOUND = 183;
    const EXAM_UNPUBLISHED = 184;
    const SYSTEM_EXAM_DIR_CANNOT_DELETE = 184;
    const EXAM_DIR_EXISTS_CHILD = 185;
    const EXAM_USERNAME_EXIST = 186;
    const EXAM_DIR_EXISTS_PAPER = 187;
    const EXAM_DIR_EXISTS_BANK = 188;
    const EXAM_NEED_LOGIN = 189;
    const EXAM_EMPLOYEE_TEMPLATE = 190;
    const EXAM_REDIS_NO_DATE = 191;
    const EXAM_STUDENT_OUT_TIME = 192;
    const EXAM_MOCK_DIR_HAS_EXAM = 193;
    const EXAM_NOTIFY_UNPUBLISHED = 194;
    const EXAM_NOTIFY_END = 195;
    const EXAM_NOT_EXIST = 196;
    const EXAM_PAPER_HAS_UPDATE = 197;
    const EXAM_SMS_SEND_FAIL = 198;
    const EXAM_MOBILE_NOT_EXIST = 200;


    /** 201~219: learning error codes */
    const LEARNING_PLAN_NAME_EXIST = 201;
    const LEARNING_NO_EXIST = 202;
    const LEARNING_DURATION_TO_LONG = 2021;
    const LEARNING_BREAKTHROUGH_NAME_EXIST = 203;
    const LEARNING_CATEGORY_DELETE_CONTAINS = 204;
    const LEARNING_PLAN_NO_PERMISSION = 205;
    const LEARNING_LEARNER_OVERSTEP = 206;
    const LEARNING_LEARNER_ALREADY_EXIST = 207;
    const LEARNING_PLAN_NO_MORE_GROUP = 208;
    const LEARNING_CLASS_NOT_PUBLISHED = 209;
    const LEARNING_PLAN_ACTIVITY_NOT_FOUND = 210;
    const LEARNING_PLAN_ACTIVITY_NOT_STARTED = 211;
    const LEARNING_PLAN_ACTIVITY_NO_AUTH = 212;
    const LEARNING_NO_OPERATION_AUTH = 213;
    const LEARNING_PLAN_NO_EXISTS = 214;
    const LEARNING_PLAN_NO_VISIT_AUTH = 215;
    const LEARNING_PLAN_IS_RELATED_PROJECT = 216;
    const LEARNING_BREAKTHROUGH_OCCUPIED = 217;
    const LEARNING_BREAKTHROUGH_CAG_HAVE_BREAKTHROUGH = 218;
    const LEARNING_APPLICATION_NON_START = 219;

    /** 220-239 directory or knowledge error codes*/
    const DIRECTORY_NAME_EXISTS_ERROR = 220;
    const KNOWLEDGE_NOT_EXISTS_ERROR = 221;
    const DIRECTORY_NOT_EXISTS_ERROR = 222;
    const DIRECTORY_EXISTS_CHILD_ERROR = 223;
    const DIRECTORY_LEVEL_LIMIT = 224;
    const DIRECTORY_CAN_NOT_REMOVE_HAS_KNOW_ERROR = 225;
    const CONTENT_IS_NOT_EXISTS_ERROR = 226;
    const DIRECTORY_COURSE_NOT_EXISTS_ERROR = 227;
    const DIRECTORY_HAS_CHILD_ERROR = 228;
    const KNOWLEDGE_NOT_HAVE_AUTH_ERROR = 229;
    const QUESTION_NOT_RECOGNIZE = 230;
    const KNOWLEDGE_HAS_USE = 231;
    const ORG_NOT_FIND_IN_KNOWLEDGE = 232;
    const USER_NOT_PERMISSION = 233;
    const KNOWLEDGE_TOKEN_ERROR = 234;
    const COURSE_IS_NOT_COMPANY = 235;
    const COURSE_TYPE_IS_NOT_ALLOWED = 236;
    const ROOT_DIRECTORY_CANNOT_DELETE_ERROR = 237;
    const COURSE_HAVE_ESTIMATE = 238;
    const COURSE_NO_PERMISSION = 239;

    /** 240-259 Position error codes */
    const POSITION_ERROR_UNDEFINED = 240;
    const POSITION_NOT_FOUND = 241;
    const POSITION_NUMBER_OCCUPIED = 242;
    const POSITION_CATEGORY_DELETE_CONTAINS = 243;
    const POSITION_CATEGORY_NOT_FOUND = 244;
    const POSITION_EMPLOYEE_USED = 245;
    const POSITION_TARGET_INCLUDE_SELF = 246;

    /** 260~279: course error codes */
    const COURSE_NOT_EXIST = 260;
    const COURSE_IS_SELF = 261;
    const COURSE_HAS_FOLLOWED = 262;
    const COURSE_EXIST_IN_GROUP = 263;
    const COURSE_HAS_USED_USER = 264;
    const SERIES_GROUP_ORDER_EXISTS = 265;
    const DIRECTORY_LEVEL_MAX_LIMIT = 266;
    const DIRECTORY_PARENT_NOT_CHILD = 267;
    const SERIES_CREATE_COURSE_FILE_LIMIT = 268;

    const COURSE_DIR_NOT_SETTING = 269;
    const ASSIGN_TASKS_EID_ASSIGNED = 270;
    const ASSIGN_TASKS_NO_AUTH = 271;
    const ASSIGN_TASKS_NOT_FOUND = 272;
    const ASSIGN_TASKS_NO_AUTH_WRITE = 273;

    /** 280-299 setting error codes*/
    const MEDAL_SCORE_EXIST = 280;
    const MEDAL_NAME_EXIST = 281;
    const BANNER_SORT_EXIST = 282;
    const BANNER_TOTAL_NUM = 283;
    const MEDAL_SCORE_INSUFFICIENT = 284;
    const NOT_AUTH_DEPT = 285;
    const NOT_REPEAT_DEPT = 286;

    /** 300~330: order error codes */
    const ORDER_COURSE_ERROR = 300;
    const ORDER_ACCREDIT_ERROR = 301;
    const ORDER_PAY_ERROR = 302;
    const ORDER_PAY_REFUND = 303;
    const ORDER_PAY_NOTPAY = 304;
    const ORDER_PAY_CLOSED = 305;
    const ORDER_PAY_REVOKED = 306;
    const ORDER_PAY_USERPAYING = 307;
    const ORDER_PAY_PAYERROR = 308;
    const ORDER_COURSE_EXIST = 309;

    /** 331~339 Department error codes */
    const DEPT_UNDEFINED_ERROR = 331;
    const DEPT_NOT_FOUND = 332;
    const DEPT_NON_GROUP_DENY_CHILD = 333;
    const DEPT_DUPLICATED_IN_BRANCH = 334; // duplicated department in the same level of the category tree
    const DEPT_DENY_CHILD = 335;
    const DEPT_NAME_EDIT_DISABLED = 336;
    const DEPT_EDIT_DISABLED = 337;
    const DEPT_EMPLOYEE_EXISTS = 338;
    const DEPT_NO_EXISTS = 339;

    /** 340~359 Employee error codes */
    const EMPLOYEE_UNDEFINED_ERROR = 340;
    const EMPLOYEE_NOT_FOUND = 341;
    const EMPLOYEE_DISPLAY_OCCUPIED = 342;
    const EMPLOYEE_NUMBER_EXISTS = 343;
    const EMPLOYEE_NOT_FOUND_OR_DISABLED = 344;
    const EMPLOYEE_LIMIT_EXCEEDS = 345;
    const EMPLOYEE_MOBILE_OCCUPIED = 346;
    const EMPLOYEE_EMAIL_CAPTCHA_INVALID = 347;
    const EMPLOYEE_EMAIL_OCCUPIED = 348;
    const EMPLOYEE_HAVE_LOCKED = 349;
    const EMPLOYEE_NO_EXISTS = 350;
    const EMPLOYEE_IMPORT_TEMPLATE_INVALID = 351;
    const EMPLOYEE_USERNAME_USED = 352;

    /** 360~370: activity error codes */
    const ACTIVITY_NAME_EXIST = 360;
    const EMPLOEE_NO_AUTH = 361;
    const EMPLOEE_NOT_EXIST = 362;
    const END_TIME_WRONG = 363;
    const EXPIRY_TIME_WRONG = 364;
    const EXPIRY_TIME_CAN_NOT_EMPTY = 365;
    const EXCEEDING_LIMIT = 366;

    /** 371~389: course error codes */
    const COURSE_NOT_ALLOW_REMOVE = 371;
    const COURSE_NOT_OVER = 372;
    const COURSE_IS_OVER = 373;
    const COURSE_NOT_AUTH_VIEW = 374;
    const COURSE_UPLOAD_AUDIO_ERROR = 375;
    const COURSE_AUDIO_EMPTY = 376;
    const COURSE_HAS_USED = 377;
    const COURSE_NOT_AUTH = 378;
    const COURSE_NO_EXISTS = 379;

    /** 390-419：the error codes of org comment and org favorite 企业端收藏和评论错误代码 */
    const FAVORITE_HAS_EXISTS_ERROR = 390;
    const FAVORITE_NO_EXISTS_ERROR = 391;
    const COMMENT_NOT_EXISTS_ERROR = 392;
    const COMMENT_NOT_ROLE_ERROR = 393;

    /** 420-449 practice  */
    const MISTAKE_NOTE_SET_EXISTS_ERROR = 420;
    const EMPTY_MISTAKE_QUESTION = 421;

    const PK_CREATE_ERROR = 435;
    const PK_DETAIL_ERROR = 436;
    const PK_SAVE_ERROR = 437;
    /* const FAVORITE_NO_EXISTS_ERROR = 391;
    const COMMENT_NOT_EXISTS_ERROR = 392;*/

    /** 450~459: activity error codes */
    const SIGN_DAILY_UNDEFINED = 450;
    const SIGN_DAILY_SIGNED = 451;

    /** 460-489: vote error codes */
    const VOTE_TOPIC_EXIST = 460;
    const VOTE_NO_PERMISSIONS = 461;
    const VOTE_UNAUTHORIZED_PARTICIPATION = 462;
    const VOTE_NO_REPEAT = 463;
    const VOTE_HAVE_CLOSED = 464;
    const VOTE_UN_START = 465;
    const VOTE_OPEN_NO_EDIT = 466;
    const VOTE_IS_REPEAT_NO_EDIT = 467;
    const VOTE_RESULT_NOT_FOUND = 468;
    const VOTE_RESULT_HAS_EXAMINE = 469;
    //const SIGN_DAILY_SIGNED = 451;

    /** 490-499 issue label error codes */
    const LABEL_NAME_EXIST = 490;
    const REPLY_EXIST = 491;
    const NOT_ISSUE_CREATOR = 492;
    const NOT_REPLY_CREATOR = 493;
    /** 500-519 survey label error codes */
    const SURVEY_TITLE_EXIST = 500;
    const SURVEY_NO_PERMISSIONS = 501;
    const SURVEY_TEMPLETE_USED = 502;
    const SURVEY_TEMPLETE_TITLE_EXIST = 503;
    const SURVEY_RE_NUM_FULL = 504;
    const SURVEY_ANSWER_IS_REPEAT = 505;
    const SURVEY_NOTIFY_UNPUBLISHED = 506;
    const SURVEY_NOTIFY_END = 507;
    const SURVEY_NEED_LOGIN = 508;
    const SURVEY_NOT_ENABLED = 509;
    const SURVEY_NOT_START = 510;
    const SURVEY_IS_OVER = 511;

    /**520-529 the error codes of team*/
    const TEAM_USED = 520;
    const TEAM_NAME_EXIST = 521;

    /** 530-549 Liveroom  */
    const LIEVROOM_NOT_FOUND = 530;

    /** 550-599 */
    const VENDOR_OLD_PASSWORD_WRONG = 550;
    const VENDOR_NEW_PASSWORD_WRONG = 551;

    /** 600-619 evaluation error codes */
    const REPORT_EXIST = 600;

    /** @var  620-639 course repository error codes */
    const COURSE_REPOSITORY_HAS_USED = 620;
    const COURSE_REPOSITORY_HAS_USED_BANNER = 621;
    const COURSE_REPOSITORY_CANNOT_REMOVE = 622;
    const COURSE_CONSUMER_POINT_NOT_ENOUGH = 623;

    /** @var  640-659 task error codes */
    const TASK_TITLE_EXIST = 640;
    const TASK_NO_PERMISSIONS = 641;
    const TASK_END = 642;

    /** @var  660-669 training_plan error codes */
    const TRAINING_PLAN_EXIST = 660;
    const TRAINING_TASK_GROUP_EXIST = 661;
    const TRAINING_PROJECT_PUSH_FAULT = 662;
    const TRAINING_PROJECT_HAS_PUSH = 663;
    const TRAINING_TASK_END = 664;
    const TRAINING_HAS_USE = 665;
    const TRAINING_ACTIVE_HAS_SUBMIT = 666;
    const TRAINING_HAS_SPLITED = 667;
    const TRAINING_MONTH_NO_SPLITED = 668;
    const TRAINING_YAER_NOT_FOUND = 669;

    /** @var  670-679 headline error codes */
    const HEADLINE_NO_ASSESS = 670;
    const HEADLINE_NO_OPEN = 671;
    const TRAINING_PLAN_NOT_EXIST = 672;

    /** @var  680-699 permission error codes */
    const PERMISSION_ROLE_EXIST = 680;
    const PERMISSION_ROLE_CLASSIFY_EXIST = 682;
    const PERMISSION_ROLE_FUNCTION_EMPTY = 681;
    const PERMISSION_ROLE_EXISTS = 683;

    /** 700-719 Queue error codes */
    const QUEUE_EXISTS = 700;

    /*demo account*/
    const DEMO_ACCOUNT_TIMEOUT = 720;
    const DEMO_ACCOUNT_NO_TRIAL = 721;

    /* Learning history application */
    const LHA_OP_ERROR = 740;

    /* Integral order */
    const INTEGRAL_ORDER_FAIL = 760;
    const INTEGRAL_PRODUCT_EXISTS = 761;
    const INTEGRAL_ORDER_LIMIT = 762;
    const INTEGRAL_ORDER_LIMIT_TIME = 763;

    const INTEGRAL_ORDER_ADDRESS = 764;


    /* knowledge points error code */
    const KNOWLEDGE_POINT_NAME_HAS_EXISTS = 770;
    const KNOWLEDGE_POINT_NOT_EXISTS_ERROR = 771;

    /** 790~820: learning error codes */
    const LEARNING_APPLICATION_ALREADY_OVER = 790;
    const LEARNING_PLAN_LEARNER_ALREADY_SIGNED = 791;
    const LEARNING_APPLICATION_NOT_ALLOWED = 792;
    const LEARNING_PLAN_NO_AUTH = 793;
    const LEARNING_PLAN_INVALID_QR_CODE = 794;
    const LEARNING_PLAN_ALREADY_ENDED = 795;
    const LEARNING_PLAN_NOT_PUBLISHED = 796;
    const LEARNING_LEARNER_UNDER_REVIEW = 797;
    const LEARNING_TASK_OBLIGATORY = 798;
    const LEARNING_PACK_NOT_FOUND = 799;
    const LEARNING_INTERACTION_NOT_EXISTS_ERROR = 7901;
    const LEARNING_SIMPLE_NO_OFFLINE = 7902;

    /** 800-810 Login */
    const LOGIN_NEED_ACCOUNT_CODE = 800;
    const LOGIN_INVALID_ACCOUNT_CODE = 801;
    const USER_RESET_PASSWORD_EMAILS_ERROR = 802;
    const LOGIN_USER_MOBILE_NOT_BINDING = 803;
    const LOGIN_MOBILE_USED_MANY = 804;
    const LOGIN_IP_BLOCKED = 805;
    const USER_EXPIRED = 806;

    /** 811-820 offline teaching*/
    const OFFLINE_TEACHING_NAME_EXIST = 811;
    const OFFLINE_TEACHING_USED = 812;
    const OFFLINE_TEACHING_RECORD_CANT_DELETE = 813;

    /** 821-830: vote error codes */
    const ASSESSMENT_TOPIC_EXIST = 821;
    const ASSESSMENT_NO_PERMISSIONS = 822;
    const ASSESSMENT_TEMPLETE_USED = 823;
    const ASSESSMENT_TEMPLETE_TITLE_EXIST = 824;
    const ASSESSMENT_TEMPLETE_NO_EXIST = 825;
    const ASSESSMENT_PARTAKE_NO_PERMISSIONS = 826;
    const ASSESSMENT_END = 827;


    //const SIGN_DAILY_SIGNED = 451;

    /** 831~840: class sign error codes */
    const LEARNING_CLASS_SIGN_NOT_START = 831;
    const LEARNING_CLASS_SIGN_ENDED = 832;
    const LEARNING_CLASS_SIGN_LEARNER_SIGNED = 833;
    const LEARNING_PLAN_SIGN_NOT_PUBLISHED = 834;
    const LEARNING_PLAN_SIGN_NO_AUTH = 835;
    const LEARNING_PLAN_SIGN_INVALID_QR_CODE = 836;
    const LEARNING_PLAN_ENDED_SIGN = 837;
    const LEARNING_PLAN_SIGN_OVER_DISTANCE = 838;
    const LEARNING_PLAN_SIGN_CLOSED_GPS = 839;
    const LEARNING_PLAN_NO_SIGNS = 840;
    const OFFLINE_TEACHING_SIGN_TIME_OUT = 842;
    const LEARNING_PACK_SIGN_NO_AUTH = 843;
    const LEARNING_SIGN_GO_TO_ENROLL = 844;
    const LEARNING_CLASS_SIGN_OUTING_END = 845;

    /** 841~850: 我的背包报错编码  */
    const PRODUCT_NOT_ENOUGH = 841;

    /** @var 851~870 */
    const BASE_OBJECT_THUMBED_UP = 851;
    const BASE_OBJECT_CATEGORY_NOT_FOUND = 852;
    const BASE_OBJECT_CATEGORY_USED = 853;

    /** @var 870~890  圈子错误 */
    const CIRCLE_APPLICATION_FAULT = 870;
    const CIRCLE_TOPIC_EXISTS = 871;
    const CIRCLE_IS_USED = 872;
    const CIRCLE_NO_PERMISSION = 873;
    const CIRCLE_INFO_NOT_FOUND = 874;
    const CIRCL_VIEWE_NO_PERMISSION = 875;
    const ROBOT_ANSWER_NOT_FOUND = 876;
    const ROBOT_ANSWER_HAD_PROGRESS = 877;
    const CIRCLE_QUESTIONS_IS_NULL = 878;
    const CIRCLE_ROBOT_NOT_OPEN = 879;
    const ROBOT_ANSWER_GET_ERROR = 880;
    const CIRCLE_APPROVAL_LIMIT = 881;
    const CIRCLE_APPROVAL_HAD = 882;
    const CIRCLE_REPLY_BANNED_POST = 883;

    const GAME_UNDEFINED = 1100;
    const GAME_BEYOND_ATTEMPT = 1101;
    const GAME_WON_ALREADY = 1102;
    const GAME_PRIZE_DEPLETED = 1103;
    const GAME_NOT_ENABLED = 1104;
    const GAME_NOT_START = 1105;
    const GAME_OVER = 1106;
    const GAME_NOT_OPEN = 1107;
    const GAME_PEOPLE_NUM_NOT_ENOUGH = 1108;
    const GAME_NUMBER_EXISTS = 1109;
    const GAME_DUMMY_FREQUENT = 1110;
    const GAME_INVAID_PARTICIPANT = 1111;
    const GAME_OP_FREQUENT = 1112;

    /** @var 1201-1300 新的第三方数据同步错误 */
    const SYNC_ERROR_DATA_FORM_ERROR = 1201;

    /** @var 1350-1400 众筹错误码 */
    const FUNDING_IS_JOIN = 1350;
    const FUNDING_IS_APPLY = 1351;


    /** 1451-1470 */
    const COURSE_CATEGORY_NAME_EXISTS = 1451;
    const COURSE_CATEGORY_HAS_USED = 1452;
    const SKILLED_CATEGORY_NAME_EXISTS = 1543;
    const SKILLED_CATEGORY_HAS_USED = 1544;

    /** 1471~1490: learning error codes */
    const LEARNING_TEACHING_TEMPLATE_USED = 1471;
    const LEARNING_TEACHING_ALREADY_STARTED = 1472;
    const LEARNING_TASK_EXISTS = 1473;
    const LEARNING_TASK_ASSIGNING = 1474;
    const LEARNING_APPRAISER_NO_CERTIFICATE = 1475;
    const LEARNING_TEACHER_NO_CERTIFICATE = 1476;
    const LEARNING_TEACHING_PROJECT_HAS_LEANRER = 1477;
    const LEARNING_TEACHING_PROJECT_NO_EDIT = 1478;
    const LEARNING_TEACHING_TEACHING_OVER_NUM = 1479;
    const LEARNING_TEACHING_ON_ONE = 1480;

    /** @var 1401-1450 考核-鉴定错误码 */
    const OFFLINE_ASSESSMENT_USED = 1401;
    const OFFLINE_ASSESSMENT_TEMPLATE_USED = 1402;
    const OFFLINE_ASSESSMENT_MUST_NUM_MORE = 1403;
    const OFFLINE_ASSESSMENT_REACH_RE_NUM = 1404;
    const OFFLINE_ASSESSMENT_CANT_RE = 1405;
    const OFFLINE_ASSESSMENT_NO_ACL = 1406;

    /** @var 1501-1550 金币错误码 */
    const COIN_NOT_SUFFICIENT_FUNDS = 1501;


    /** @var 1551-1559 短信验证码 */
    const SMS_CAPTCHA_SMS_INVALID = 1551;
    const SMS_CAPTCHA_SMS_EXPIRED = 1552;
    const SMS_LIMIT_EXCEEDS = 1553;

    /** 1560~1659: learning error codes */
    const LEARNING_PROJECT_NO_EXISTS = 1560;
    const LEARNING_PACK_NOT_PUBLISHED = 1561;
    const LERN_PRO_NOT_ALLOW_LEARNER_IN_MULTI_CLASS = 1562;
    const LERN_PRO_NOT_ALLOW_LEARNER_SHIFT = 1563;
    const LERN_OVERSTEP_SHIFT_CLASS_TIME = 1564;
    const LERN_ENROLL_SCORE_NOT_SUBSTANDARD = 1565;
    const LERN_ENROLL_UNCERTIFIED = 1566;
    const LERN_ENROLL_EXAM_NOT_PASSED = 1567;
    const LERN_ENROLL_NOT_ALLOW_CANCEL = 1568;
    const LERN_ENROLL_CANCEL_TIME_CUT_OFF = 1569;
    const LERN_MAP_TAGGING_FINISHED_UNCERTIFIED = 1570;
    const LERN_MAP_TAGGING_FINISHED_NOT_AUTH = 1571;
    const LERN_MAP_TAGGING_FINISHED_CLASS_INCOMPLETE = 1572;
    const LEARNING_QUEUE_EXISTS = 1573;
    const LERN_PACK_DISABLED = 1574;
    const LERN_OPERATE_NOT_ALLOWED = 1575;
    const LERN_PASS_DISABLED = 1576;
    const LERN_CLASS_NO_VISIT_AUTH = 1577;
    const LERN_PLAN_NO_VISIT_AUTH = 1578;
    const LERN_PACK_NO_VISIT_AUTH = 1579;
    const LERN_PASS_NO_VISIT_AUTH = 1580;
    const LERN_ADD_LEARNER_ON_GOING = 1581;
    const LERN_PASS_UNPUBLISHED = 1582;
    const LERN_PASS_NOT_EXISTS = 1583;
    const LERN_PASS_NOT_AUTH = 1584;
    const LERN_ENROLL_DELEGATE_TOP = 1585;
    const LERN_ENROLL_DELEGATE_CLOSE = 1586;
    const LERN_DELEGATE_IS_EXIST = 1587;
    const LERN_DELEGATE_DELEGATE_NO_EXIST = 1588;
    const LEARNING_PACK_END = 1589;
    const LEARNING_PACK_UN_ENABLED = 1590;
    const LEARNER_NOT_ZERO = 1591;
    const LEARNING_PACK_SETTINGS_CREDIT = 1592;
    const LERN_ENROLL_POSITION_NOT_PASSED = 1593;
    const LERN_ENROLL_OFFLINE_NOT_PASSED = 1594;
    const LERN_ENROLL_NOT_LECTURER = 1595;
    const LEARNING_UN_EXISTS = 1596;

    /** 1660~1699: class sign error codes */
    const LEARNING_SIGN_INVALID = 1660;
    const LEARNING_SIGN_NONSUPPORT_CODE = 1661;
    const LEARNING_SIGN_CODE_ERROR = 1662;
    const LERN_SIGN_UNAUTHORIZED_PARTICIPATION = 1663;
    const LERN_SIGN_PASSWORD_ERROR = 1664;

    /** @var 1801-1849: 直播 error codes */
    const LIVE_INVALID = 1801;
    const LIVE_NOT_FOUND = 1802;
    const LIVE_NO_PERMISSION = 1803;
    const LIVE_ROOM_NOT_FOUND = 1810;
    const LIVE_MEMBER_IS_EXISTS = 1820;
    const LIVE_MEMBER_IS_NULL = 1821;
    const LIVE_COMPERE_IN_LECTURERS = 1822;

    const LIVE_APPROVED_EXISTS = 1830;
    const LIVE_LECTURER_NOT_REQUEST = 1831;
    const LIVE_LECTURER_NOT_APPROVED = 1832;
    const LIVE_LECTURER_APPROVED_ALREADY = 1833;


    /** @var 1951-2000讲师错误码 */
    const LECTURER_LEVEL_STANDARD_MUST_SET = 1951;
    const LECTURER_INSIDE_IS_EXISTS = 1952;
    const LECTURER_INSIDE_TYPE_ERROR = 1953;
    const LECTURER_NUMBER_REPEAT = 1954;
    const LECTURER_ORDER_AUDITOR = 1955;
    const LECTURER_DATE_ORDERED = 1956;
    const LECTURER_DATE_DISENABLED = 1957;
    const LECTURER_PROJECT_REPEAT = 1958;
    const LECTURER_PROJECT_UNEXISTS = 1959;
    const LECTURER_PROJECT_ALREADY_ENDED = 1960;
    const LECTURER_PROJECT_APPLICATION_NOT_ALLOWED = 1961;
    const LECTURER_PROJECT_NO_VISIT_AUTH = 1962;
    const LECTURER_PROJECT_LEARNER_ALREADY_EXIST = 1963;
    const LECTURER_PROJECT_LEARNER_UNDER_REVIEW = 1964;
    const LECTURER_PROJECT_LEARNER_OVERSTEP = 1965;
    const LECTURER_PROJECT_ENROLL_HIRE_NOT_EXISTS = 1966;
    const LECTURER_PROJECT_ENROLL_HIRE_NOT_SUBSTANDARD = 1967;


    /** 2001 ~ 2050 job level errors */
    const JOBLEVEL_NOT_FOUND = 2001;
    const JOBLEVEL_NO_EXISTS = 2002;
    const JOBLEVEL_NAME_EXISTS = 2003;
    const JOBLEVEL_USED = 2004;
    const JOBLEVEL_ORDER_EXISTS = 2005;

    /** 2051 ~ 2099 queue errors */
    const QUE_EXISTS = 2051;


    /** 2100~2149 Employee Group errors */
    const EMP_GRP_NOT_FOUND = 2100;
    const EMP_GRP_USED = 2101;
    const EMP_GRP_NOT_DYNAMIC = 2102;

    /** 2150~2200 learning_template_log errors */
    const LEARNING_TEMPLATE_NO_GROUP_CANT = 2150;
    const LEARNING_TEMPLATE_TITLE_EXISTS = 2151;
    const LEARNING_TEMPLATE_TITLE_IS_USED = 2152;


    /** 2201 - 2249 案例库 errors*/
    const CASE_CATEGORY_IS_EXISTS = 2201;
    const CASE_DIRECTORY_IS_EXISTS = 2201;
    const CASE_DIRECTORY_NOT_FOUND = 2202;
    const CASE_DIRECTORY_PARENT_NOT_FOUND = 2203;
    const CASE_DIRECTORY_SORT_DIFFERENT_PARENTS = 2204;
    const CASE_DIRECTORY_GT_MAX_LEVEL = 2205;
    const CASE_DIRECTORY_HAVE_CHILD = 2206;
    const CASE_ATTACHMENT_IS_NECESSARY = 2210;
    const CASE_ATTACHMENT_IS_OVERFLOW = 2211;
    const CASE_ATTACHMENT_UNSUPPORTED_FILE_TYPES = 2212;
    const CASE_STAGE_IS_EXISTS = 2221;
    const CASE_TEMPLATE_NOT_FOUND = 2230;
    const CASE_TEMPLATE_NO_IS_EXISTS = 2231;
    const CASE_TEMPLATE_TITLE_IS_EXISTS = 2232;
    const CASE_POINT_NAME_HAS_EXISTS = 2233;
    const CASE_POINT_NOT_EXISTS_ERROR = 2234;

    /** 2250 ~ 2269 Face matching error codes */
    const FACE_MATCHING_SOURCE_EXISTS = 2250;
    const FACE_MATCHING_DETECT_FAIL = 2251;
    const FACE_MATCHING_SOURCE_NOT_EXIST = 2252;
    const FACE_MATCHING_STORAGE_FOLDER_CREATE_FAIL = 2253;
    const FACE_MATCHING_INVALID_FILE_TYPE = 2254;
    const FACE_MATCHING_INVALID_FILE = 2255;

    /** 2270 - 2299 审批流程 errors*/
    const APPROVAL_CATEGORY_IS_EXISTS = 2270;
    const APPROVAL_PROCESS_IS_EXISTS = 2271;
    const APPROVAL_LEVEL_IS_EXISTS = 2272;
    const APPROVAL_PROCESS_NOT_ENABLED = 2273;
    const APPROVAL_CATEGORY_IS_USED = 2274;

    /** 2300 - 2319 课程审批 errors*/
    const COURSE_REVIEW_NO_AUTH = 2300;
    const APPROVAL_REVIEW_EMPLOYEE_MUST = 2301;
    const COURSE_MULTI_DIRECTORY_LIMIT_ERROR = 2302;

    /** 2350~2379 SSO action error codes */
    const SSO_SIMPLE_TOKEN_INVALID = 2350;

    /** 2401 - 2449 竞赛 errors*/
    const COMPETITION_ROUND_START_ERROR = 2401;
    const COMPETITION_CANT_RECEIVE_AWARD = 2402;
    const COMPETITION_JS_NO_IS_EXISTS = 2403;
    const COMPETITION_NOT_IN_VOTE_RANGE = 2404;
    const COMPETITION_ROUND_IS_END = 2405;
    const COMPETITION_ROUND_IS_START = 2406;
    const COMPETITION_APPLY_TIME_ERROR = 2407;
    const COMPETITION_NOT_HAVE_ROUND = 2408;
    const COMPETITION_NOT_BEGIN = 2409;
    const COMPETITION_ACHIEVEMENT_GROUP_USED = 2410;
    const COMPETITION_ACHIEVEMENT_BATTLE_EXISTS = 2411;
    const COMPETITION_ACHIEVEMENT_HELP_EXISTS = 2412;
    const COMPETITION_VOTE_EXISTS = 2413;
    const COMPETITION_IS_USED = 2414;
    const COMPETITION_NOTIFY_UNPUBLISHED = 2415;
    const COMPETITION_NOTIFY_END = 2416;
    const COMPETITION_VOTE_NOT_STARTED = 2417;
    const COMPETITION_VOTE_ALREADY_ENDED = 2418;
    const COMPETITION_NOT_FOUND = 2419;
    const COMPETITION_NO_PERMISSION = 2420;


    /** 2450 ~ 2469 岗位胜任力指标  */
    const POSITION_COMPETENCY_CATEGORY_EXISTS = 2450;
    const POSITION_COMPETENCY_CATEGORY_NOT_FOUND = 2451;
    const POSITION_COMPETENCY_EXISTS = 2452;
    const POSITION_COMPETENCY_NOT_FOUND = 2453;
    const POSITION_COMPETENCY_ELEMENT_EXISTS = 2454;
    const CATEGORY_NAME_EXIST = 2455;

    /** 岗位认证技能  */
    const POSITION_SKILL_CATEGORY_EXISTS = 2460;
    const POSITION_SKILL_CATEGORY_NOT_FOUND = 2461;
    const POSITION_SKILL_EXISTS = 2462;
    const POSITION_SKILL_NOT_FOUND = 2463;
    const POSITION_SKILL_ELEMENT_EXISTS = 2464;
    const SKILL_NOT_EXISTS = 2465;

    /** 2470 ~ 2499 巡检  */
    const INSPECTION_ELECTIVE_TASK_UNFINISHED = 2470;
    const INSPECTION_ELECTIVE_CLASSIFY_UNFINISHED = 2471;
    const INSPECTOR_IS_NOT = 2472;
    const INSPECTION_AT_LEAST_ONE = 2473;

    /** 2500 ~ 2510 敏感词 */
    const HARMONY_ERROR = 2500;

    /** 2511~2559: retraining error codes */
    const RETRAINING_NO_EXISTS = 2511;
    const RETRAINING_NO_TASKS = 2512;
    const RETRAINING_NOT_ALLOWED_REPEAT = 2513;
    const RETRAINING_REACH_CYCLE_INDEX = 2514;
    const RETRAINING_TIME_NOT_UP = 2515;
    const RETRAINING_LEARNER_AUTHENTICATE_ONGOING = 2516;
    const RETRAINING_EXAM_INVALID = 2517;
    const APPRIAISAL_POSITION_SKILL_EXISTS_ELEMENT = 2518;
    const RETRAINING_NOT_EXISTS = 2519;
    const RETRAINING_LEARNER_NOT_PUBLISHED = 2520;
    const RETRAINING_LEARNER_NOT_AUTH = 2521;

    /** 2560 ~  2569: Experience error codes*/
    const EXPERIENCE_DETAIL_BEYOND_LIMIT = 2560;

    /** 2570 ~  2579: Experience error codes*/
    const PHOTOGRAPH_DETAIL_BEYOND_LIMIT = 2570;
    const PHOTOGRAPH_LEARNER_NOT_EXISTS = 2571;
    const PHOTOGRAPH_LEARNER_SUPPORT_EXISTS = 2572;
    const PHOTOGRAPH_LEARNER_SUPPORT_MAX = 2573;

    /** 2580 ~  3000: Experience error codes*/
    const CERTIFICATION_USED = 2581;
    const CERTIFICATION_USER_USED = 2582;

    /** 3001 ~ 3020 */
    const DIRECTORY_PARENT_NOT_SAME_SELF = 3001;
    const NOT_GROUP_CANNOT_SELECTED = 3002;

    /** 3021~3040: 第三方平台（钉钉)错误码  */
    const PLATFORM_NOT_SETTING_DING = 3021;

    /** 3041 - 3060: 活动签到错误码 */
    const EVENT_MEMBER_SIGN_INVALID_CAPTCHA = 3041;
    const EVENT_MEMBER_SIGN_VX_INVALID_ACCESS_TOKEN = 3042;
    const EVENT_MEMBER_SIGN_VX_INVALID_PWD = 3043;
    const EVENT_MEMBER_SIGNED = 3044;

    /** 3081~3120: 展示互动直播*/
    const GEN_LIVE_CREATE_ERROR = 3081;
    const GEN_LIVE_NOT_EXISTS = 3082;
    const GEN_LIVE_UPDATE_ERROR = 3083;
    const GEN_LIVE_INVALID_INPUT = 3084;
    const GEN_LIVE_MEMBER_NOT_ALLOWED = 3085;
    const GEN_LIVE_GENERATE_TIME = 3086;
    const GEN_LIVE_LIMIT_ATTENDEES = 3087;
    const GEN_LIVE_CATEGORY_NOT_REMOVE = 3088;
    const LIVE_HONGSHAN_HAS_END = 3089;
    const LIVE_ROLE_ERROR = 3090;
    const GEN_VOD_NOT_EXISTS = 3091;
    const GEN_VOD_IS_PLAYBACK = 3092;
    const GEN_VOD_PLAYBACK = 3093;
    const GEN_VOD_PPTRECORD_OVERTIME = 3094;
    const GEN_VOD_PPTRECORD_UNABLE = 3095;
    const GEN_VOD_UNABLE_DELETE = 3096;
    const GEN_VOD_NOT_PLAYBACK = 3097;
    const LIVE_UN_DELAYED = 3099;
    const GEN_LIVE_NO_AUTH = 3098;


    /** 3121~3180:知识库 微问 */
    const KNOWLEDGE_BASE_NAME_EXIST = 3121;
    const KNOWLEDGE_BASE_NOT_EXIST = 3122;
    const KNOWLEDGE_QUESTION_HAS_EXISTS = 3123;
    const KNOWLEDGE_CATEGORY_CANNOT_DELETE = 3124;
    const KNOWLEDGE_CATEGORY_CANNOT_EQ_ROOT_NAME = 3125;
    const KNOWLEDGE_CATEGORY_HAS_QUESTION = 3126;
    const KNOWLEDGE_QUESTION_NOT_EXISTS = 3127;
    const KNOWLEDGE_CATEGORY_NAME_EQ = 3128;
    const KNOWLEDGE_QUESTION_IS_SYSTEM = 3129;
    const KNOWLEDGE_BASE_HAS_QUESTION = 3130;
    const KNOWLEDGE_APPLY_EXIST = 3131;

    /** 3250~3300: 活动、活动抽奖错误*/
    const EVENT_PRIZE_IS_GAIN = 3251;
    const EVENT_ALLOW_NUM_MORETHAN_EXISTS = 3252;
    const EVENT_DESIGATED_IS_HAVED = 3253;
    const EVENT_DESIGATED_IS_OVERFLOW = 3254;
    const EVENT_NOT_START = 3255;
    const EVENT_END = 3256;

    /** 3301~3320: 评价*/
    const COURSE_HAVE_LIMIT = 3301;
    const COURSE_TYPE_NOT_EQ = 3302;
    const COURSE_MUST_END = 3303;
    const EXPORT_LIMIT = 3304;
    const COURSE_STAR_LIMIT = 3305;

    /** 3321~3340: 巡检-问题*/
    const INSPECTION_QUESTION_CATEGORY_USED = 3321;

    /** 3341~3360: 合同*/
    const CONTRACT_TYPE_USED = 3341;

    /** 3361~3400: 线下练习*/
    const OFFLINEEXERCISE_NO_PERMISSIONS = 3361;

    /** 3401~3450: 专题*/
    const SPECIAL_SUBJECT_NO_USED = 3401;


    /** Employee self-register error codes */
    const EMP_SELF_REG_DATA_INVALID = 3450;
    const EMP_SELF_REG_UNIQUE = 3451;
    const EMP_SELF_REG_UNIQUE_USERNAME = 3452;
    const EMP_SELF_REG_MOBILE_CAPTCHA_FAIL = 3453;
    const EMP_SELF_REG_UNIQUE_ID_NUMBER = 3454;

    /** 3500~3599 Extra department error codes */
    const DEPT_PARENT_NOT_FOUND = 3500;

    /** 3600~3620 每日打卡 */
    const DAILY_CLOCK_CANT_PUBLISH = 3600;

    /** 3650~3699 培训中心 */
    const TRAINING_CENTER_UNDEFINED = 3650;
    const TRAINING_CENTER_EXISTS = 3651;
    const TRAINING_CENTER_NOT_FOUND = 3652;
    const TRAINING_CENTER_NO_EXISTS = 3653;
    const TRAINING_CENTER_MAX_LEVEL = 3654;
    const TRAINING_CENTER_USED = 3555;
    const TRAINING_CENTER_NOT_LEAF = 3556;

    /** 3700~3720 knowledge */
    const KNOWLEDGE_CONTAIN_AUDIT_IDS = 3700;


    /** 3730~3800: hundun course error codes */
    const COURSE_HUNDUN_SIGN_ERROR = 3730;
    const COURSE_HUNDUN_PARAMS_ERROR = 3731;
    const COURSE_HUNDUN_NO_AUTH = 3732;
    const COURSE_HUNDUN_TIME_OVERDUE = 3733;
    const COURSE_HUNDUN_USER_TOKEN_INVALID = 3734;
    const COURSE_HUNDUN_DATA_ERROR = 3735;
    const COURSE_HUNDUN_CHECK_ERROR = 3736;
    const COURSE_HUNDUN_USER_REGISTER_REACH_LIMIT = 3737;
    const COURSE_HUNDUN_USER_REGISTED = 3738;
    const COURSE_MODULE_UN_REGISTED = 3739;

    /** 4200~4230 */
    const LIVE_HON_SHAN_TIME_ERROR = 4200;

    /** 3810~3850: learning practice point */
    const LPP_NOT_FOUND = 3810;
    const LPP_CREATE_FAIL = 3811;
    const LPP_UPDATE_FAIL = 3812;
    const LPP_TIME_LARGER_DURATION = 3813;
    const LPP_TIME_DUPLCATED = 3814;
    const LPP_OPTION_ID_DUPLICATED = 3815;
    const LPP_OPTION_INVALID_COUNT = 3816;

    /** 3850 ~ 3899: short link */
    const SHORTLINK_INVALID_URL = 3850;

    /** 3900 ~ 3949: Custom BI */
    const BI_FIELDS_INVALID = 3900;
    const BI_COLUMNS_INVALID = 3901;
    /** 4100 ~ 4120: KnowledgePointCategory */
    const KNOWLEDGE_POINT_CATEGORY_EXISTS = 4100;


    /** 3900~3949: gz watch error code */
    const GZ_WATCH_CARD_NO_OR_DISPLAY_ERROR = 3900;

    /** 4000~4010: learning_class_point error code */
    const NOT_ENOUGH_SCORE = 4000;


    /** 4011~4020: position_grading_exam error code */
    const POSITION_GRADING_NO_QUESTION = 4011;


    /** 4021~4030: GradeSetting error code */
    const GRADE_SETTING_NAME_EXISTS_ERROR = 4011;
    const GRADE_SETTING_LIMIT = 4012;

    /** 4200-4299: Ai scenario error codes */
    const AI_SCENARIO_NOT_FOUND = 4200;
    const AI_SCENARIO_NODE_NOT_FOUND = 4201;
    const AI_SCENARIO_NO_USED = 4202;
    const AI_SCENARIO_NOT_PUBLISHED = 4203;
    const AI_SCENARIO_COPY_FAIL = 4204;
    const AI_SCENARIO_PROCESS_NOT_FOUND = 4205;
    const AI_SCENARIO_PROCESS_NEXT_NODE_NOT_FOUND = 4206;
    const AI_SCENARIO_PROCESS_PREV_NODE_NOT_PASSED = 4207;
    const AI_SCENARIO_PROCESS_NODE_ANSWERED = 4308;
    const AI_SCENARIO_SUBMIT_EXCEPTION = 4309;

    /** Year report 5000 ~ 5099 */
    const YEAR_REPORT_OUTDATE = 5000;

    /** GuidanceClassify 5100 ~ 5199 */
    const GUIDANCE_CLASSIFY_EXISTS = 5100;
    const GUIDANCE_INSTRUCTIONS_EXISTS = 5101;

    /** Statistics 5200 ~ 5299 */
    const STAT_FILTER_GROUP_TYPE_NOT_SUPPORT = 5200;

    // 培训协议
    const TRAIN_AGREEMENT_NO_EXISTS = 5300;


    // 平台公告
    const NOTICE_NO_EXISTS = 5400;

    //积分审核
    const SCORE_TYPE_EXISTS = 5560;
    const SCORE_TYPE_NO_EXISTS = 5561;
    const SCORE_APPLY_NO_EXISTS = 5562;
    const SCORE_APPLY_STATE_ERROR = 5563;
    const SCORE_APPLY_NO_CHECKING = 5564;
    const TIME_RANGE_EXCEEDS_LIMIT = 5565;

    //消耗品
    const CONSUMABLE_EXISTS = 5760;
    const CONSUMABLE_NO_EXISTS = 5760;



    /** Retraining level 5401 ~ 5450 */
    const RETRAINING_LEVEL_NO_EXISTS = 5401;


    /** Learning pack 5451 ~ 5699 */
    const LEARNING_PACK_TOP_EXISTS = 5451;

    /** Retraining category 5700 ~ 5799 */
    const RETRAINING_CATEGORY_NO_EXISTS = 5700;

    /** training_plan 5800 ~ 5899 */
    const TRAINING_PLAN_NO_ACTIVE = 5800;

    /** 教室管理 5900 ~ 5920 */
    const CLASSROOM_NOT_EXISTS = 5901;
    const CLASSROOM_HAS_RE = 5901;

    /** @var 6000-6050成长地图 */
    const COURSE_PACKAGE_PROJECT_NO_EXISTS = 6000;
    const COURSE_PACKAGE_PROJECT_NO_AUTH = 6001;

    /** @var 6050-6100培训大纲 */
    const TRAINING_PROGRAM_UN_EXISTS = 6050;
    const TRAINING_PROGRAM_NO_EXISTS = 6051;

    /** 混沌对接错误code 7001 ~ 7050 */
    const HUNDUN_SIGN_ERROR = 7001;
    const HUNDUN_MOBILE_FORMAT_ERROR = 7002;
    const HUNDUN_PARAMS_ERROR = 7003;
    const HUNDUN_REACH_REGISTER_LIMIT = 7004;
    const HUNDUN_REGISTER_FAILED = 7005;
    const HUNDUN_PARAM_ERROR = 7006;
    const HUNDUN_USER_REGISTED = 7007;
    const HUNDUN_REACH_USER_SIGNOUT_LIMIT = 7008;
    const HUNDUN_COMPANY_UNEXISTS = 7009;
    const HUNDUN_UNAUTHORIZED_COURSE_PACKAGE = 7010;
    const HUNDUN_UNAUTHORIZED_COURSE = 7011;

    /** 数据看板错误code 7051 ~ 7100 */
    const DATABOARD_SYSTEM_UNALLOWED_DELETED = 7051;


    /** 独立报名错误code 7101 ~ 7200 */
    const ENROLL_NOT_EXISTS = 7101;
    const ENROLL_NOT_PUBLISHED = 7102;
    const ENROLL_LEARNER_HAS_ENROLLED = 7103;
    const ENROLL_LEARNER_UNDER_EXAMINE = 7104;
    const ENROLL_LEARNER_NOT_SELECT_SESSIONS = 7105;
    const ENROLL_SESSIONS_NOT_EXISTS = 7106;
    const ENROLL_TIME_OVER = 7107;
    const ENROLL_LEARNER_NUM_REACHED_MAXIMUM_LIMIT = 7108;
    const ENROLL_REQUIREMENTS_CREDIT_DISQUALIFIED = 7109;
    const ENROLL_REQUIREMENTS_CERTIFICATE_DISQUALIFIED = 7110;
    const ENROLL_REQUIREMENTS_EXAM_DISQUALIFIED = 7111;
    const ENROLL_TIMES_MULTI_REACHED_MAXIMUM_LIMIT = 7112;
    const ENROLL_NOT_ALLOWED_CANCEL = 7113;
    const ENROLL_CANCEL_DEADLINE_OVER = 7114;
    const ENROLL_TIME_NOT_BEGIN = 7115;
    const ENROLL_OFFICIAL_NUM_REACHED_MAXIMUM_LIMIT = 7116;
    const ENROLL_SESSION_IS_OBLIGATORY = 7117;
    const ENROLL_SESSION_NOT_ALLOW_ENROLL_MULTI = 7118;
    const ENROLL_REPLACE_REQUIREMENTS_CREDIT_DISQUALIFIED = 7124;
    const ENROLL_REPLACE_REQUIREMENTS_CERTIFICATE_DISQUALIFIED = 7125;
    const ENROLL_REPLACE_REQUIREMENTS_EXAM_DISQUALIFIED = 7126;

    /** 带教签名code 7201 ~ 7250 */
    const LEARNING_TEACHING_SIGN_NO_OPEN = 7201;
    const LEARNING_TEACHING_SIGN_OTHER_EMP = 7202;
    const LEARNING_TEACHING_STUDENT_UNSIGN = 7203;
    const LEARNING_TEACHING_SIGN_FINISHED = 7204;
    const LEARNING_TEACHING_NOT_END = 7205;
    const LEARNING_TEACHING_TUTOR_SIGN_NO_OPEN = 7206;
    const LEARNING_TEACHING_SIGN_OTHER_TUTOR = 7207;
    const LEARNING_TEACHING_STUDENT_SIGN_NO_OPEN = 7208;
    const LEARNING_TEACHING_SIGN_OTHER_STUDENT = 7209;
    const LEARNING_TEACHING_TUTOR_UNSIGN = 7210;
    const LEARNING_TEACHING_TEACHING_UNSIGN = 7211;
    const LEARNING_TEACHING_UNSIGN = 7212;

    /** 带训 code 7251 ~ 7350 */
    const TRAINING_TUTORING_LEANER_NO_SIGNATURE_REQUIRED = 7251;
    const TRAINING_TUTORING_TASK_NOT_SUBMIT = 7252;

    /** 场景库 code 7351 ~ 7450 */
    const SCENE_TALK_WEIGHT_SUM_NOT_ALLOWED = 7351;
    const SCENE_KEYWORD_WEIGHT_SUM_NOT_ALLOWED = 7352;

    /** 素材库 code 7551 ~ 7600 */
    const MATERIAL_NOT_EXISTS_ERROR = 7551;
    const MATERIAL_TYPE_NOT_EQ = 7552;
    const DIRECTORY_CAN_NOT_REMOVE_HAS_MATERIAL_ERROR = 7553;

    /** 知识点库 code 7601 ~ 7620 */
    const LANGUAGE_POINTS_NOT_EXISTS_ERROR = 7601;
    const LANGUAGE_POINTS_NO_EXISTS = 7602;

    /** 知识点库 code 7621 ~ 7650 */
    const TEACHING_MATERIAL_NOT_EXISTS_ERROR = 7621;
    const TEACHING_MATERIAL_NO_EXISTS = 7622;

    /**
     * 版本 code 7651 ~ 7670
     */
    const VERSION_NO_REDUCIBLE_VERSION = 7651;
    const VERSION_HAS_REVIEW_VERSION = 7652;

    /**
     * 支付 code 7691 ~ 7720
     */
    const PAY_CONFIG_NOT_EXISTS = 7691;
    const PAY_CONFIG_CONTENT_TYPE_NOT_SUPPORT = 7692;
    const PAY_ORDER_HAS_EXISTS = 7693;
    const PAY_ORDER_DOING = 7694;
    const PAY_ORDER_CONTENT_NOT_EXISTS = 7695;
    const PAY_ORDER_STATUS_NOT_PAY = 7696;

    // 7750-7770
    const AI_VIDEO_CONTENT_ERROR = 7750;
    const AI_VIDEO_CONTENT_EXISTS_ERROR = 7751;

    /**
     * 1 - 用户
     * 1 - 模块（0 - base; 1 - 非base）
     * 001 - 模块1 ID
     * 001 - 错误ID
     * 11001001
     */
    const OCR_IDCARD_RECOGNIZE_FAIL = 1100101;

    const PASSWORD_FORMAT_INVALID = 1000101;

    /**
     * 训后行动评估 ID 003
     * 胜任指标 ID 001~005
     */
    const ACTION_ASSESSMENT_NOT_EXISTS = 11003001;
    const ACTION_ASSESSMENT_LEARNER_EXISTS = 11003002;
    const ACTION_ASSESSMENT_LEARNER_NOT_EXISTS = 11003003;
    const ACTION_ITEMS_NOT_REPEAT_SUBMIT = 11003004;
    const ACTION_ASSESSMENT_NO_REVIEW_PERMISSION = 11003005;
    const ACTION_ASSESSMENT_NOT_REPEAT_REVIEW = 11003006;
    const ACTION_ASSESSMENT_NO_COMMENT_PERMISSION = 11003007;
    const ACTION_ASSESSMENT_NOT_REPEAT_COMMENT = 11003008;

    /**
     * 胜任管理 ID 002
     * 胜任指标 ID 001~005
     */
    const COMPETENCY_INDICATOR_NOT_FOUND = 11002001;
    const COMPETENCY_INDICATOR_GROUP_NOT_FOUND = 11002002;
    const COMPETENCY_INDICATOR_SKILL_NOT_FOUND = 11002003;
    const COMPETENCY_INDICATOR_GROUP_EXISTS = 11002004;
    const COMPETENCY_INDICATOR_SKILL_EXISTS = 11002005;

    /**
     * 大模型 ID    004
     * 评分模型     001 ~ 009
     * 评分模型维度 010 ~ 020
     */
    const LARGE_MODEL_MAX_DIMENSION_EACH_SCORE_MODEL = 11004001;

    const APPROVAL_HAS_EXISTS = 7752;
    const APPROVAL_HAS_NO_ROLE = 7753;
}
