<?php

namespace App\Common;

interface ErrorCodesEN  extends Errors {

    const ERROR_MESSAGES_EN = [
        \Key\Constants::SYS_SUCCESS => 'OK',

        \Key\Constants::SYS_ERROR_DEFAULT => 'Unknown error',
        \Key\Constants::SYS_INPUT_INVALID => 'Invalid arguments',

        \Key\Constants::USER_OBJECT_NOT_FOUND => 'Object does not exist',
        \Key\Constants::USER_OBJECT_ALREADY_EXISTS => 'Object already exists',
        \Key\Constants::USER_OBJECT_OCCUPIED => 'Object has been used',

        \Key\Constants::OPERATION_TOO_FREQUENT => 'Operation too frequent, please try again later',

        self::SECURITY_PWD_WEAK => 'Weak default password',

        self::ACCOUNT_NOT_FOUNT => 'Company does not exist or has been disabled',
        self::ACCOUNT_NAME_EXISTS => 'Duplicate company name',
        self::ACCOUNT_CREATE_DICTIONARY_ERROR => 'Failed to create data dictionary',
        self::ACCOUNT_CREATE_DEPARTMENT_ERROR => 'Failed to create department',
        self::ACCOUNT_CREATE_ROLE_ERROR => 'Failed to create role',
        self::ACCOUNT_CREATE_USER_ERROR => 'Failed to create user',
        self::ACCOUNT_CREATE_EMPLOYEE_ERROR => 'Failed to create employee',
        self::ACCOUNT_CREATE_ASSESSMENT_ERROR => 'Failed to create default assessment',
        self::ACCOUNT_INVALID => 'Affiliate is expired or disabled',
        self::ACCOUNT_CODE_INVALID => 'Invalid company number',
        self::ACCOUNT_EXPIRED => 'Company has expired',
        self::ACCOUNT_FUNCTION_NOT_ENABLED => 'The function is not enabled',
        self::ACCOUNT_URL_EXPIRE => 'Login is not working, please check the link or try again',

        self::CUSTOM_FIELD_NAME_EXISTS => 'Custom field exists',
        self::IMPORT_CONFIG_NOT_FOUND => 'Import config not found',
        self::IMPORT_MAX_ROWS => 'Exceeds the specified number of lines',

        // 360 evaluation related
        self::PUBLISH_NO_QUESTIONNAIRE => 'Questionnaire has been deleted',
        self::PUBLISH_NO_MODEL => 'The model in the questionnaire has been deleted, please reselect the questionnaire',
        self::PUBLISH_NO_DIMENSION => 'The ability latitude in the questionnaire has been deleted, please reselect the questionnaire',
        self::PUBLISH_NO_ELEMENT => 'The competency element in the questionnaire has been removed, please reselect the questionnaire',
        self::PUBLISH_NO_QUESTION => 'There are no questions in the questionnaire, please reselect the questionnaire',

        self::EMPLOYEE_HAVE_LOCKED => 'Account is locked, please contact administrator',
        self::EMPLOYEE_NO_EXISTS => 'Employee number already exists',
        self::USER_INVALID_NEW_PWD => 'Password format is incorrect, please check the password requirements',
        self::USER_PWD_NEW_SAME_OLD => 'The new password cannot be the same as the old one',
        self::USER_USR_ERROR_DEFAULT => 'Unknown error',
        self::USER_CAPTCHA_IMAGE_INVALID => 'The graphic authentication code has expired or was filled in incorrectly',
        self::USER_CAPTCHA_SMS_INVALID => 'Incorrect SMS verification code',
        self::USER_PHONE_INVALID => 'Phone number is invalid',
        self::USER_ACCOUNT_NOT_FOUND => 'No account found',
        self::USER_LOGIN_FAIL => 'Login failed',
        self::USER_QR_LOGIN_FAIL => 'Scan code login failed, please refresh the retry or select other login',
        self::USER_QR_LOGIN_TIMEOUT => 'QR code has expired, please refresh the QR code to re-scan',
        self::USER_PWD_ERROR => 'User password error',
        self::USER_LOGIN_FAIL_TOO_MANY => 'Too many retries',
        self::USER_NOT_FOUND => 'The user does not exist',
        self::USER_EXISTS_IN_COMPANY => 'The user is already inside the company',
        self::USER_INVALID_OLD_PASSWORD => 'Invalid old password',
        self::USER_CREATE_ERROR => 'create a user fail',
        self::USER_SMS_CAPTCHA_FREQUENCY => 'Sending verification code too often',
        self::USER_INVALID_USERNAME => 'Illegal username',
        self::USER_LEAVE_OFFICE => 'Employee has left',
        self::USER_SMS_TIMEOUT => 'SMS verification code timeout',
        self::USER_SMS_INVALID => 'Invalid SMS verification code',
        self::MOBILE_EXIST => 'Phone number already exists',

        self::USER_2FA_BOUND => '2FA has already been bound',
        self::USER_2FA_DISBLED => '',
        self::USER_2FA_MOBILE_NOT_MATCH => 'Invalid mobile number',
        self::USER_2FA_MOBILE_CAPTCHA_NOT_MATCH => 'Invalid mobile captcha',
        self::USER_2FA_MOBILE_INVALID_TOKEN => 'Session timeout, please login in again.',

        self::QUESTION_BANK_EXISTS => 'Question bank header already exists',
        self::QUESTION_IMPORT_TEMPLETE => 'Table header does not match, please download the template again',
        self::QUESTION_EXISTS => 'Title already exists',
        self::QUESTION_COYE_FAIL => 'Question copy failed',
        self::PAPER_EXISTS => 'The title of the test paper already exists',
        self::EXAM_EXISTS => 'Exam title already exists',
        self::EXAM_END => 'The exam has ended',
        self::EXAM_COYE_FAIL => 'Failed to copy the exam',
        self::EXAM_EMPLOYEE_END => 'Staff exam has ended',
        self::EXAM_DETAIL_FAIL => 'Failed to get exam details',
        self::EXAM_DIR_NOT_FOUND => 'Failed to get exam directory',
        self::SYSTEM_EXAM_DIR_CANNOT_DELETE => 'The default exam directory cannot be deleted',
        self::EXAM_DIR_EXISTS_CHILD => 'This directory has subdirectories, it cannot be deleted, please delete the subdirectories first',
        self::EXAM_USERNAME_EXIST => 'There is an error in your phone number or email address',
        self::EXAM_DIR_EXISTS_BANK => 'This directory has a question bank, can not be deleted, please delete the question bank first',
        self::EXAM_DIR_EXISTS_PAPER => 'There are test papers in this directory, you can not delete them, please delete the test questions first',
        self::EXAM_NEED_LOGIN => 'This exam needs to be logged in',
        self::EXAM_EMPLOYEE_TEMPLATE => 'The table header does not match, please download the template again',
        self::EXAM_MOBILE_NOT_EXIST => 'Mobile phone number does not exist',
        self::EXAM_REDIS_NO_DATE => "redis does not have the candidate's answer",
        self::EXAM_STUDENT_OUT_TIME => "I'm sorry, the current time is not in the scope of the exam!" ,
        self::EXAM_MOCK_DIR_HAS_EXAM => 'There is an exam in this directory, it cannot be deleted, please delete the exam first',
        self::EXAM_NOTIFY_UNPUBLISHED => 'Exam is not published, not allowed to send notification',
        self::EXAM_NOTIFY_END => 'Exam is closed, not allowed to send notification',
        self::EXAM_NOT_EXIST => 'Exam does not exist',

        self::LEARNING_PLAN_NAME_EXIST => 'Learning plan name already exists',
        self::LEARNING_NO_EXIST => "The number is occupied! ",
        self::LEARNING_DURATION_TO_LONG => "Duration is too long",
        self::LEARNING_BREAKTHROUGH_NAME_EXIST => 'Breakthrough name already exists',
        self::LEARNING_CATEGORY_DELETE_CONTAINS => 'There is a breakthrough under the category, please delete the breakthrough first',
        self::LEARNING_PLAN_NO_PERMISSION => 'No permission',
        self::LEARNING_LEARNER_OVERSTEP => 'Enrollment has reached the maximum number',
        self::LEARNING_LEARNER_ALREADY_EXIST => 'This participant already exists',
        self::LEARNING_PLAN_NO_MORE_GROUP => 'There are no more groups for this smart class',
        self::LEARNING_PLAN_NOT_PUBLISHED => 'Study plan is not published',
        self::LEARNING_CLASS_NOT_PUBLISHED => 'Class is not published',
        self::LEARNING_PACK_NOT_PUBLISHED => 'Learning package not published',
        self::LEARNING_PACK_SETTINGS_CREDIT => 'The credit reward of study package exceeds the limit',
        self::LERN_ENROLL_POSITION_NOT_PASSED => 'The position is not met and registration is not allowed',
        self::LERN_ENROLL_OFFLINE_NOT_PASSED => 'Insufficient teaching quantity, registration not allowed',
        self::LERN_ENROLL_NOT_LECTURER => 'Not a lecturer, registration not allowed',
        self::LEARNING_UN_EXISTS => 'Sorry, the project does not exist!',
        self::LEARNING_LEARNER_UNDER_REVIEW => 'Under review',
        self::LEARNING_TASK_OBLIGATORY => 'Please add learning content first',
        self::LEARNING_TEACHING_TEMPLATE_USED => 'Template with teaching has been used and cannot be removed',
        self::LEARNING_TEACHING_ALREADY_STARTED => 'The tutorial has started',
        self::LEARNING_TEACHING_PROJECT_HAS_LEANRER => 'A teaching relationship exists under the teaching project and cannot be deleted',
        self::LEARNING_TEACHING_PROJECT_NO_EDIT => 'Non-draft instruction is not allowed to modify',
        self::LEARNING_TEACHING_TEACHING_OVER_NUM => 'If the number of tutors exceeds the limit, please terminate other tutors first',
        self::LEARNING_TEACHING_ON_ONE => 'Students can only participate once in this tutorial template',
        self::LEARNING_TASK_EXISTS => 'Task already exists',
        self::LEARNING_TASK_ASSIGNING => 'Task assignment in progress, please try again later',
        self::LEARNING_APPRAISER_NO_CERTIFICATE => "The appraisee has not yet obtained the relevant certificate! ",
        self::LEARNING_TEACHER_NO_CERTIFICATE => "The appraisee has not yet obtained the relevant certificate! ",
        self::LEARNING_PACK_NOT_FOUND => 'Learning package does not exist',
        self::LEARNING_INTERACTION_NOT_EXISTS_ERROR => 'Interaction does not exist',
        self::LEARNING_SIMPLE_NO_OFFLINE => 'Please add face-to-face classes before publishing',
        self::LEARNING_PLAN_ACTIVITY_NOT_FOUND => 'Activity does not exist',
        self::LEARNING_PLAN_ACTIVITY_NOT_STARTED => 'Activity has not started',
        self::LEARNING_PLAN_ACTIVITY_NO_AUTH => 'No permission to sign in to this activity',
        self::LEARNING_NO_OPERATION_AUTH => 'No permission',
        self::LEARNING_PLAN_NO_EXISTS => 'Learning module does not exist',
        self::LEARNING_PLAN_NO_VISIT_AUTH => 'No access rights',
        self::LEARNING_PLAN_IS_RELATED_PROJECT => "The project has been executed! ",
        self::LEARNING_BREAKTHROUGH_OCCUPIED => 'This break-in is occupied!' ,
        self::LEARNING_BREAKTHROUGH_CAG_HAVE_BREAKTHROUGH => "There is a breakthrough under this category and deletion is not allowed! ",
        self::LEARNING_APPLICATION_NON_START => 'Registration has not started',
        self::LEARNING_APPLICATION_ALREADY_OVER => 'Registration has been closed',
        self::LERN_ENROLL_SCORE_NOT_SUBSTANDARD => "Credit not met, registration not allowed! ",
        self::LERN_ENROLL_UNCERTIFIED => "Registration is not allowed if the corresponding certificate has not been obtained! ",
        self::LERN_ENROLL_EXAM_NOT_PASSED => "Not allowed to register if you have not passed the corresponding exam! ",
        self::LERN_ENROLL_NOT_ALLOW_CANCEL => "The class is not allowed to cancel the registration! ",
        self::LERN_ENROLL_CANCEL_TIME_CUT_OFF => "The time for cancellation of registration has expired! ",
        self::LERN_ENROLL_DELEGATE_TOP => "The maximum number of people in the project has been reached！",
        self::LERN_ENROLL_DELEGATE_CLOSE => "Agent registration not opened！",
        self::LERN_DELEGATE_IS_EXIST => "The new condition conflicts with the existing condition！",
        self::LERN_DELEGATE_DELEGATE_NO_EXIST => "For the same person in charge, only set departments can be added！",
        self::LEARNING_PACK_END => 'The learning package has ended！',
        self::LEARNER_NOT_ZERO => 'Students have been added, unable to delete!',
        self::LEARNING_PACK_UN_ENABLED => 'Learning pack disabled！',
        self::LEARNING_PLAN_LEARNER_ALREADY_SIGNED => 'Please do not double sign in',
        self::LEARNING_APPLICATION_NOT_ALLOWED => 'Class is not open for registration',
        self::LEARNING_PLAN_NO_AUTH => 'No permission',
        self::LEARNING_PLAN_INVALID_QR_CODE => 'Invalid QR code',
        self::LEARNING_PLAN_ALREADY_ENDED => 'Class has ended',
        self::LEARNING_CLASS_SIGN_NOT_START => 'Check-in has not started',
        self::LEARNING_CLASS_SIGN_ENDED => 'Check-in has ended',
        self::LEARNING_CLASS_SIGN_LEARNER_SIGNED => 'Signed in',
        self::LEARNING_PLAN_SIGN_NOT_PUBLISHED => 'Class not published',
        self::LEARNING_PLAN_SIGN_NO_AUTH => 'You have not joined the class yet and cannot sign in yet',
        self::LEARNING_PLAN_ENDED_SIGN => 'Class has ended',
        self::LEARNING_PACK_SIGN_NO_AUTH => 'You haven\'t joined the learning package, and can not sign in temporarily',
        self::LEARNING_PLAN_SIGN_INVALID_QR_CODE => 'Invalid QR code',
        self::LEARNING_PLAN_SIGN_OVER_DISTANCE => 'Your location is not within the check-in range and you cannot check-in at this time',
        self::LEARNING_PLAN_SIGN_CLOSED_GPS => 'No geolocation information was obtained, please check if location is turned on',
        self::LERN_MAP_TAGGING_FINISHED_UNCERTIFIED => 'The conditions for obtaining a certificate have not been met and cannot be tagged to completion',
        self::LERN_MAP_TAGGING_FINISHED_NOT_AUTH => 'No permission, this task is marked for completion by the administrator',
        self::LERN_MAP_TAGGING_FINISHED_CLASS_INCOMPLETE => 'The class completion rate has not reached 100% and cannot be marked as completed',
        self::LEARNING_QUEUE_EXISTS => 'Processing, please wait',
        self::LERN_PACK_DISABLED => 'The learning package has been disabled, please try again later!' ,
        self::LERN_PASS_DISABLED => 'This break-in has been disabled, please try again later!' ,
        self::LERN_OPERATE_NOT_ALLOWED => "Maintenance is in progress, please go to the admin backend to do it! ",
        self::LEARNING_PLAN_NO_SIGNS => "No check-in for now! ",
        self::OFFLINE_TEACHING_SIGN_TIME_OUT => "QR code invalid! ",
        self::LERN_CLASS_NO_VISIT_AUTH => "You haven't joined the class yet! ",
        self::LERN_PLAN_NO_VISIT_AUTH => "You have not joined this study program! ",
        self::LERN_PACK_NO_VISIT_AUTH => "You have not joined this study package! ",
        self::LERN_PASS_NO_VISIT_AUTH => "You have not joined this breakout! ",
        self::LERN_ADD_LEARNER_ON_GOING => "Operation is frequent, please try again later! ",
        self::LERN_PASS_UNPUBLISHED => 'Level not published',
        self::LERN_PASS_NOT_EXISTS => 'Break-in does not exist',
        self::LERN_PASS_NOT_AUTH => 'You do not have permission to participate in this pass',

        self::LERN_PRO_NOT_ALLOW_LEARNER_IN_MULTI_CLASS => 'The program does not allow the same person to register for more than one class',
        self::LERN_PRO_NOT_ALLOW_LEARNER_SHIFT => 'The program does not allow students to transfer classes on their own',
        self::LERN_OVERSTEP_SHIFT_CLASS_TIME => 'Out of class transfer time, please select another class',

        self::KNOWLEDGE_NOT_EXISTS_ERROR => 'Knowledge does not exist',
        self::DIRECTORY_NAME_EXISTS_ERROR => 'Directory name already exists',
        self::DIRECTORY_NOT_EXISTS_ERROR => 'Directory does not exist',
        self::DIRECTORY_LEVEL_LIMIT => 'Cannot create directory at this directory level',
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_KNOW_ERROR => "You can't delete the knowledge in the directory library, please delete the knowledge in the directory library first",
        self::DIRECTORY_EXISTS_CHILD_ERROR => "This directory has subdirectories, you can't delete it, please delete the subdirectories first",
        self::CONTENT_IS_NOT_EXISTS_ERROR => 'This content does not exist',
        self::DIRECTORY_COURSE_NOT_EXISTS_ERROR => 'Course does not exist',
        self::DIRECTORY_HAS_CHILD_ERROR => 'This directory has subdirectories, cannot move directory',
        self::KNOWLEDGE_NOT_HAVE_AUTH_ERROR => 'No permission to view at this time',
        self::KNOWLEDGE_HAS_USE => 'This knowledge has been used in a task and cannot be deleted',
        self::ORG_NOT_FIND_IN_KNOWLEDGE => 'This company has not opened the micro-query function for the time being',
        self::USER_NOT_PERMISSION => "Sorry, you do not have permission to access this knowledge! ",
        self::KNOWLEDGE_TOKEN_ERROR => "Token value error! ",
        self::COURSE_IS_NOT_COMPANY => "This course is not a company-built course and cannot be set as a public course",
        self::COURSE_TYPE_IS_NOT_ALLOWED => "The live class cannot be set as a public class",
        self::ROOT_DIRECTORY_CANNOT_DELETE_ERROR => "The default course directory cannot be deleted",
        self::DIRECTORY_LEVEL_MAX_LIMIT => 'The directory hierarchy can be no more than 5 levels',
        self::DIRECTORY_PARENT_NOT_CHILD => 'Subdirectories of this directory cannot be parent directories',

        self::COURSE_NOT_EXIST => "The course does not exist",
        self::COURSE_IS_SELF => "You can't bookmark a course you created",
        self::COURSE_HAS_FOLLOWED => 'You have bookmarked this course',
        self::COURSE_HAS_USED_USER => 'The specified user already has this course',
        self::COURSE_EXIST_IN_GROUP => 'This course already exists',
        self::SERIES_GROUP_ORDER_EXISTS => 'Sorting value already exists.',
        self::IMG_LIMIT_ERROR => 'Image size exceeded limit',
        self::FILE_LIMIT_ERROR => 'File size exceeded limit',
        self::FILE_READ_FAIL => 'Unable to read file, please upload as requested',
        self::UPLOAD_FILE_FAIL => 'Failed to upload file',
        self::SECURITY_RULE_INVALID_IP_CONFIG => 'Error IP whitelist configuration',
        self::IMG_SIZE_LIMIT_ERROR => 'Image size exceeded limit',

        self::POSITION_ERROR_UNDEFINED => 'Unknown post error',
        self::POSITION_NOT_FOUND => 'Post does not exist',
        self::POSITION_NUMBER_OCCUPIED => 'Position number is occupied',
        self::POSITION_CATEGORY_DELETE_CONTAINS => 'Positions exist in the group and cannot be deleted',
        self::POSITION_CATEGORY_NOT_FOUND => 'Post group does not exist',
        self::POSITION_EMPLOYEE_USED => 'Position is used',
        self::POSITION_TARGET_INCLUDE_SELF => 'The target post cannot be itself',

        self::MEDAL_SCORE_EXIST => 'Medal score already exists',
        self::MEDAL_NAME_EXIST => 'Medal name already exists',
        self::BANNER_SORT_EXIST => 'Priority already exists',
        self::BANNER_TOTAL_NUM => 'Maximum number of rotating images has been reached',
        self::MEDAL_SCORE_INSUFFICIENT => 'Insufficient credits',
        self::NOT_AUTH_DEPT => 'No permission set for this department',
        self::NOT_REPEAT_DEPT => 'This department has been set and cannot be added repeatedly',

        self::ORDER_COURSE_ERROR => 'The course data in the order was assembled incorrectly',
        self::ORDER_ACCREDIT_ERROR => 'Order authorization failed',
        self::ORDER_PAY_REFUND => 'Order transferred to refund',
        self::ORDER_PAY_NOTPAY => 'Order not paid',
        self::ORDER_PAY_CLOSED => 'Order is closed',
        self::ORDER_PAY_REVOKED => 'Order has been revoked (card payment)',
        self::ORDER_PAY_USERPAYING => 'Order user is paying',
        self::ORDER_PAY_PAYERROR => 'Order payment failed',
        self::ORDER_COURSE_EXIST => 'The free class you joined, or the encrypted class already exists',

        self::DEPT_UNDEFINED_ERROR => 'Unknown department error',
        self::DEPT_NOT_FOUND => 'Department does not exist',
        self::DEPT_NON_GROUP_DENY_CHILD => 'Cannot create subordinate department under ungrouped',
        self::DEPT_DUPLICATED_IN_BRANCH => 'Current node department already exists',
        self::DEPT_DENY_CHILD => 'Cannot create subordinate department under this department',
        self::DEPT_NAME_EDIT_DISABLED => 'Editing is disabled for this department name',
        self::DEPT_EDIT_DISABLED => 'Editing is disabled for this department',
        self::DEPT_EMPLOYEE_EXISTS => 'An employee exists in this department and cannot perform the operation',
        self::DEPT_NO_EXISTS => 'Department number already exists',
        self::DEPT_PARENT_NOT_FOUND => 'The parent department does not exist',

        self::EMPLOYEE_UNDEFINED_ERROR => 'Unknown error',
        self::EMPLOYEE_NOT_FOUND => 'Employee does not exist',
        self::EMPLOYEE_DISPLAY_OCCUPIED => 'Name is already occupied',
        self::EMPLOYEE_NUMBER_EXISTS => 'Employee number is occupied',
        self::EMPLOYEE_NOT_FOUND_OR_DISABLED => 'User does not exist or is disabled',
        self::EMPLOYEE_LIMIT_EXCEEDS => 'The maximum number of employees has been reached',
        self::EMPLOYEE_MOBILE_OCCUPIED => 'Mobile phone number has been used',
        self::EMPLOYEE_EMAIL_CAPTCHA_INVALID => 'Invalid email verification code',
        self::EMPLOYEE_EMAIL_OCCUPIED => 'This mailbox has been used',
        self::EMPLOYEE_IMPORT_TEMPLATE_INVALID => 'Invalid import template',
        self::EMPLOYEE_USERNAME_USED => 'Username is used',

        self::ACTIVITY_NAME_EXIST => 'Activity name already exists',
        self::EMPLOEE_NO_AUTH => 'You are not an employee of this company',
        self::EMPLOEE_NOT_EXIST => 'Employee is not in the system',
        self::EXPIRY_TIME_CAN_NOT_EMPTY => 'Registration deadline required',
        self::EXCEEDING_LIMIT => 'Event staff exceeds the maximum number of people for the event',
        self::END_TIME_WRONG => 'The end time should be greater than the start time',
        self::EXPIRY_TIME_WRONG => 'The registration deadline should be less than or equal to the end date of the event',

        self::COURSE_NOT_ALLOW_REMOVE => 'Course end less than 7 days, not allowed to delete/offline',
        self::COURSE_NOT_OVER => 'Course is not yet finished',
        self::COURSE_IS_OVER => 'Course has ended',
        self::COURSE_NOT_AUTH_VIEW => 'No permission to view the course',
        self::COURSE_UPLOAD_AUDIO_ERROR => 'Failed to upload audio file',
        self::COURSE_AUDIO_EMPTY => 'Please generate audio file',
        self::COURSE_HAS_USED => 'The course is being used and deletion is not allowed',
        self::COURSE_NOT_AUTH => 'No permission to view at this time',
        self::COURSE_NO_EXISTS => 'Course does not exist',

        self::FAVORITE_HAS_EXISTS_ERROR => 'This content has been bookmarked',
        self::FAVORITE_NO_EXISTS_ERROR => 'You have not bookmarked this content and cannot unbookmark it',
        self::COMMENT_NOT_EXISTS_ERROR => 'Comment does not exist',
        self::EMPTY_MISTAKE_QUESTION => 'There are no errors',
        self::COMMENT_NOT_ROLE_ERROR => 'Comments can only be deleted by the administrator and myself',

        self::SIGN_DAILY_SIGNED => 'Checked in today',
        self::PK_CREATE_ERROR => 'PK creation failed',
        self::PK_DETAIL_ERROR => 'Failed to get PK details',
        // self::PK_DETAIL_ERROR => 'PK save failed',
        self::VOTE_TOPIC_EXIST => 'Voting topic already exists',
        self::VOTE_NO_PERMISSIONS => 'Non-member cannot participate in the poll',

        self::REPLY_EXIST => 'Reply already exists, cannot be deleted',
        self::NOT_ISSUE_CREATOR => 'Not the creator of the question, cannot be manipulated',
        self::NOT_REPLY_CREATOR => 'Not the creator of the answer, cannot be manipulated',
        self::SURVEY_TITLE_EXIST => 'The title of the research already exists',
        self::SURVEY_NO_PERMISSIONS => "Non-member can't participate in the research",
        self::TEAM_USED => 'There is knowledge under this team that cannot be deleted',
        self::TEAM_NAME_EXIST => 'Team name cannot be repeated',
        self::SURVEY_NOT_ENABLED => 'Research disabled',
        self::SURVEY_NOT_START => 'Investigation not started',
        self::SURVEY_IS_OVER => 'The investigation is over.',

        self::LIEVROOM_NOT_FOUND => 'Live room does not exist',
        self::QUESTION_NOT_RECOGNIZE => 'Cannot be recognized',
        self::VENDOR_OLD_PASSWORD_WRONG => 'Vendor original password error',
        self::VENDOR_NEW_PASSWORD_WRONG => 'The new password cannot be the same as the original password',

        self::COURSE_REPOSITORY_HAS_USED => 'Course is being used and cannot be moved out of the course library',
        self::COURSE_REPOSITORY_HAS_USED_BANNER => 'The course is being used by a recommendation or rotating image and cannot be moved out',
        self::COURSE_REPOSITORY_CANNOT_REMOVE => 'Courses cannot be removed by non-super admins',
        self::COURSE_CONSUMER_POINT_NOT_ENOUGH => 'Not enough points',
        self::TASK_TITLE_EXIST => 'Job name already exists',

        self::TRAINING_PLAN_EXIST => 'Training program name already exists',
        self::TRAINING_TASK_GROUP_EXIST => 'Group name exists',
        self::TRAINING_PROJECT_PUSH_FAULT => 'Approval submission failed',
        self::TRAINING_PROJECT_HAS_PUSH => 'Approval has been submitted',

        self::HEADLINE_NO_ASSESS => 'No operation permission',
        self::HEADLINE_NO_OPEN => 'Function is disabled',
        self::PERMISSION_ROLE_EXIST => 'Role name already exists',
        self::PERMISSION_ROLE_FUNCTION_EMPTY => 'Function permission cannot be empty',

        self::QUEUE_EXISTS => 'Task is executing, please try again later',

        self::DEMO_ACCOUNT_TIMEOUT => 'Trial account expired',
        self::DEMO_ACCOUNT_NO_TRIAL => 'Trial account is open',

        self::LHA_OP_ERROR => 'This application has been approved or rejected',
        self::INTEGRAL_ORDER_FAIL => 'Insufficient points or inventory',
        self::INTEGRAL_PRODUCT_EXISTS => 'Product name already exists',

        self::KNOWLEDGE_POINT_NAME_HAS_EXISTS => 'Knowledge point name already exists',
        self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => 'Knowledge point does not exist',

        self::LOGIN_NEED_ACCOUNT_CODE => 'Missing company number',
        self::LOGIN_INVALID_ACCOUNT_CODE => 'Invalid company number',
        self::USER_RESET_PASSWORD_EMAILS_ERROR => 'This mailbox corresponds to multiple accounts and cannot be retrieved',
        self::LOGIN_USER_MOBILE_NOT_BINDING => "Mobile phone number is not bound, can't login",
        self::LOGIN_MOBILE_USED_MANY => 'The phone number is used by multiple people and cannot be logged in',
        self::LOGIN_IP_BLOCKED => 'IP is blocked',
        self::USER_EXPIRED => 'User is expired',

        self::ASSESSMENT_TOPIC_EXIST => 'Evaluation name already exists',
        self::ASSESSMENT_NO_PERMISSIONS => 'No permission to create assessment',
        self::ASSESSMENT_PARTAKE_NO_PERMISSIONS => 'Sorry, you do not have permission to participate in this assessment!' ,
        self::ASSESSMENT_END => 'Sorry, the evaluation has ended',

        self::OFFLINE_TEACHING_NAME_EXIST => 'A face-to-face lesson by this name already exists',
        self::OFFLINE_TEACHING_USED => 'This lesson is already being used by a smart class and cannot be deleted',
        self::OFFLINE_TEACHING_RECORD_CANT_DELETE => 'The record has been reviewed and approved and cannot be deleted',

        self::COURSE_HAVE_ESTIMATE => "You have already evaluated, you can't comment anymore",
        self::COURSE_NO_PERMISSION => 'No permission to operate',

        // self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => 'Knowledge point does not exist',

        self::PLATFORM_NOT_SETTING_DING => 'Third-party platform is not bound to nail',
        self::PRODUCT_NOT_ENOUGH => 'Insufficient number of gifts',

        self::BASE_OBJECT_THUMBED_UP => 'This object has already been liked',
        self::BASE_OBJECT_CATEGORY_NOT_FOUND => 'Group does not exist',
        self::BASE_OBJECT_CATEGORY_USED => 'The grouping has already been used',

        self::CIRCLE_APPLICATION_FAULT => 'The circle has been joined and cannot be repeated',
        self::CIRCLE_TOPIC_EXISTS => 'Topic name cannot be repeated',
        self::CIRCLE_IS_USED => 'Quiz circle is occupied and cannot be deleted',

        self::GAME_UNDEFINED => 'Unknown error',
        self::GAME_BEYOND_ATTEMPT => 'Exceeded number of attempts',
        self::GAME_WON_ALREADY => 'You have already won the prize',
        self::GAME_PRIZE_DEPLETED => 'No more prizes',
        self::GAME_NOT_ENABLED => 'Game is not enabled',
        self::GAME_NOT_START => 'Game not started',
        self::GAME_OVER => 'Game has ended',
        self::GAME_NOT_OPEN => 'The prize has not started',
        self::GAME_PEOPLE_NUM_NOT_ENOUGH => 'Not enough people to start the lottery',
        self::GAME_NUMBER_EXISTS => 'Contest number already exists',
        self::GAME_DUMMY_FREQUENT => 'Network system is busy, please try again later',
        self::GAME_INVAID_PARTICIPANT => 'Invalid participant',
        self::GAME_OP_FREQUENT => 'Operation is too frequent, please try again later.',

        self::SYNC_ERROR_DATA_FORM_ERROR => 'The requested data is not in the right format, please check the data format',

        self::FUNDING_IS_JOIN => 'Engaged',
        self::FUNDING_IS_APPLY => 'Enrolled',

        self::COIN_NOT_SUFFICIENT_FUNDS => 'Insufficient coin balance',
        self::COURSE_CATEGORY_NAME_EXISTS => 'Course category name already exists',
        self::COURSE_CATEGORY_HAS_USED => 'Course category is being used',
        self::SKILLED_CATEGORY_NAME_EXISTS => 'Name already exists',
        self::SKILLED_CATEGORY_HAS_USED => 'This specialization category is being used',

        self::OFFLINE_ASSESSMENT_USED => 'Identification has been started',
        self::OFFLINE_ASSESSMENT_TEMPLATE_USED => 'Identification template has been started and cannot be deleted',
        self::OFFLINE_ASSESSMENT_REACH_RE_NUM => 'The number of repeatable appraisals has been exhausted',
        self::OFFLINE_ASSESSMENT_CANT_RE => 'The appraisal is not repeatable',
        self::OFFLINE_ASSESSMENT_NO_ACL => 'No operation authority at the moment, please contact the administrator',

        self::SMS_CAPTCHA_SMS_INVALID => 'There is an error in the SMS verification code',
        self::SMS_CAPTCHA_SMS_EXPIRED => 'SMS verification code has expired',
        self::SMS_LIMIT_EXCEEDS => 'The verification code has not expired',

        self::LEARNING_PROJECT_NO_EXISTS => 'Item number already exists',

        self::LEARNING_SIGN_INVALID => 'Invalid check-in',
        self::LEARNING_SIGN_NONSUPPORT_CODE => 'This check-in does not support check-in code check-in',
        self::LEARNING_SIGN_CODE_ERROR => 'Check-in code error',
        self::LERN_SIGN_UNAUTHORIZED_PARTICIPATION => 'No permission',
        self::LERN_SIGN_PASSWORD_ERROR => 'Password error',

        self::LIVE_INVALID => 'Invalid live stream',
        self::LIVE_NOT_FOUND => 'Live stream does not exist',
        self::LIVE_NO_PERMISSION => 'No permission',
        self::LIVE_ROOM_NOT_FOUND => 'Live does not exist',
        self::LIVE_MEMBER_IS_EXISTS => 'Exists',
        self::LIVE_MEMBER_IS_NULL => 'The person you selected is empty',
        self::LIVE_APPROVED_EXISTS => 'The person on the mic already exists',
        self::LIVE_LECTURER_NOT_REQUEST => 'No mike operation has been initiated',
        self::LIVE_LECTURER_NOT_APPROVED => 'Not allowed to be on the mic',
        self::LIVE_LECTURER_APPROVED_ALREADY => 'Allowed to go to the mic',
        self::LIVE_COMPERE_IN_LECTURERS => 'Host is not allowed to set as lecturer',

        self::LECTURER_LEVEL_STANDARD_MUST_SET => 'Set at least one instructor rating indicator',
        self::LECTURER_INSIDE_IS_EXISTS => 'The employee is already a lecturer',
        self::LECTURER_INSIDE_TYPE_ERROR => 'Internal instructor format error',
        self::LECTURER_NUMBER_REPEAT => 'Instructor number already exists',
        self::LECTURER_ORDER_AUDITOR => 'Appointment has been audited',
        self::LECTURER_DATE_ORDERED => 'Tutor time range has been booked',
        self::LECTURER_DATE_DISENABLED => 'Instructor time range is not available for booking',
        self::LECTURER_PROJECT_REPEAT => 'The certification project already has a number',
        self::LECTURER_PROJECT_UNEXISTS => 'The certification project does not exist',
        self::LECTURER_PROJECT_ALREADY_ENDED => 'Certification project has ended',
        self::LECTURER_PROJECT_APPLICATION_NOT_ALLOWED => 'The certification project is not open for registration',
        self::LECTURER_PROJECT_NO_VISIT_AUTH => 'No permission to register',
        self::LECTURER_PROJECT_LEARNER_ALREADY_EXIST => 'Member already exists',
        self::LECTURER_PROJECT_LEARNER_UNDER_REVIEW => 'Member review in progress',
        self::LECTURER_PROJECT_LEARNER_OVERSTEP => 'Maximum number of applicants',

        self::JOBLEVEL_NOT_FOUND => 'Rank does not exist',
        self::JOBLEVEL_NO_EXISTS => 'Rank number already exists',
        self::JOBLEVEL_NAME_EXISTS => 'Rank name already exists',
        self::JOBLEVEL_USED => 'Rank has been used',
        self::JOBLEVEL_ORDER_EXISTS => 'Rank sort already exists',

        self::QUE_EXISTS => 'Task is executing, please try again later',

        self::EMP_GRP_NOT_FOUND => 'Crowd does not exist',
        self::EMP_GRP_USED => 'There are employees in the group, deletion is not allowed',
        self::EMP_GRP_NOT_DYNAMIC => 'This group is not a dynamic group',

        self::OFFLINE_ASSESSMENT_MUST_NUM_MORE => 'More must-pass questions than actual must-pass questions in pass rule',
        self::EXAM_DATA_PROCESSING => 'Test data being processed',
        self::EXAM_APPROVE_NOT_FOUND => 'Exam approval does not exist',
        self::EXAM_UNFINISH_NOT_FOUND => 'Your exam has been submitted',
        self::EXAM_MARKING => 'Exam approval in progress',

        self::CASE_DIRECTORY_IS_EXISTS => 'Directory already exists',
        self::CASE_DIRECTORY_NOT_FOUND => 'Directory does not exist',
        self::CASE_DIRECTORY_PARENT_NOT_FOUND => 'Parent directory does not exist',
        self::CASE_DIRECTORY_SORT_DIFFERENT_PARENTS => 'Only directories with the same parent can be sorted',
        self::CASE_DIRECTORY_GT_MAX_LEVEL => 'Directory only supports 3 levels',
        self::CASE_DIRECTORY_HAVE_CHILD => 'This directory has a subset',
        self::CASE_ATTACHMENT_IS_NECESSARY => 'You are using a template where attachments are mandatory',
        self::CASE_ATTACHMENT_IS_OVERFLOW => 'The number of attachments uploaded has reached the limit and cannot be continued',
        self::CASE_ATTACHMENT_UNSUPPORTED_FILE_TYPES => 'Unsupported attachment types',
        self::CASE_STAGE_IS_EXISTS => 'Name of existing stage',
        self::CASE_TEMPLATE_NOT_FOUND => 'Template does not exist',
        self::CASE_TEMPLATE_NO_IS_EXISTS => 'Template number already exists',
        self::CASE_TEMPLATE_TITLE_IS_EXISTS => 'Template name already exists',
        self::CASE_POINT_NAME_HAS_EXISTS => 'The industry name already exists',
        self::CASE_POINT_NOT_EXISTS_ERROR => 'Industry does not exist',

        self::LEARNING_TEMPLATE_NO_GROUP_CANT => 'Ungrouped cannot be deleted or modified',
        self::LEARNING_TEMPLATE_TITLE_EXISTS => 'This group name already exists',
        self::LEARNING_TEMPLATE_TITLE_IS_USED => 'The grouping is already used and cannot be deleted',
        self::EXAM_UNAUTHORIZED_PARTICIPATION => 'You do not have permission to participate in this exam',
        self::VOTE_UNAUTHORIZED_PARTICIPATION => 'You do not have permission to participate in this poll',
        self::VOTE_HAVE_CLOSED => 'This poll has ended',
        self::VOTE_UN_START => 'This poll has not begun',
        self::ASSESSMENT_TEMPLETE_USED => 'This template has been used and cannot be deleted',
        self::SURVEY_TEMPLETE_USED => 'This template has been used and cannot be deleted',
        self::ASSESSMENT_TEMPLETE_TITLE_EXIST => 'Evaluation template name already exists',
        self::SURVEY_TEMPLETE_TITLE_EXIST => 'The name of the research template already exists',
        self::ASSESSMENT_TEMPLETE_NO_EXIST => 'Assessment template number already exists',
        self::SURVEY_RE_NUM_FULL => 'The number of repeated studies is full',
        self::SURVEY_ANSWER_IS_REPEAT => 'Duplicate answer for non-repeatable fill-in-the-blank question',

        self::SURVEY_NOTIFY_UNPUBLISHED => 'Research is not published and notifications are not allowed to be sent',
        self::SURVEY_NOTIFY_END => 'The research is closed and not allowed to send notifications',
        self::SURVEY_NEED_LOGIN => 'This survey needs to be logged in',

        self::FACE_MATCHING_SOURCE_EXISTS => 'Face comparison template already exists',
        self::FACE_MATCHING_DETECT_FAIL => 'Face comparison failed',
        self::FACE_MATCHING_SOURCE_NOT_EXIST => 'Face comparison template does not exist',
        self::FACE_MATCHING_STORAGE_FOLDER_CREATE_FAIL => 'Unable to create storage directory',
        self::FACE_MATCHING_INVALID_FILE_TYPE => 'Unsupported image format',
        self::FACE_MATCHING_INVALID_FILE => 'Unsupported file formats',

        self::APPROVAL_CATEGORY_IS_EXISTS => 'Category already exists',
        self::APPROVAL_CATEGORY_IS_USED => 'Category has been used and cannot be deleted',
        self::APPROVAL_PROCESS_IS_EXISTS => 'Approval process already exists',
        self::APPROVAL_LEVEL_IS_EXISTS => 'Approval level already exists',
        self::APPROVAL_PROCESS_NOT_ENABLED => 'There are no enabled approval flows for the company',
        self::APPROVAL_REVIEW_EMPLOYEE_MUST => 'Must select approver',
        self::COURSE_REVIEW_NO_AUTH => 'No course approval authority',

        self::COMPETITION_ROUND_START_ERROR => "Incorrect round start time or end time",
        self::COMPETITION_CANT_RECEIVE_AWARD => 'No entitlement to season award',
        self::COMPETITION_JS_NO_IS_EXISTS => 'Contest number may not be repeated',
        self::COMPETITION_NOT_IN_VOTE_RANGE => 'Not in the voting',
        self::COMPETITION_ROUND_IS_END => 'This round is over and cannot be deleted',
        self::COMPETITION_ROUND_IS_START => 'This round has started and cannot be modified or deleted',
        self::COMPETITION_APPLY_TIME_ERROR => 'Registration set time error',
        self::COMPETITION_NOT_HAVE_ROUND => 'Please add the round information first, then post',
        self::COMPETITION_NOT_BEGIN => 'The contest has not started yet',
        self::COMPETITION_ACHIEVEMENT_GROUP_USED => 'This team is in a match group, please delete the match first, then try again...' ,
        self::COMPETITION_ACHIEVEMENT_BATTLE_EXISTS => 'This team already exists',
        self::COMPETITION_ACHIEVEMENT_HELP_EXISTS => 'Boost has been completed in this PK',
        self::COMPETITION_VOTE_EXISTS => 'Voted today',
        self::COMPETITION_IS_USED => 'Contest is occupied and cannot be deleted',
        self::COMPETITION_NOTIFY_UNPUBLISHED => 'The contest is not published and notifications are not allowed',
        self::COMPETITION_NOTIFY_END => 'Contest is closed, not allowed to send notifications',
        self::COMPETITION_VOTE_NOT_STARTED => 'Voting has not commenced',
        self::COMPETITION_VOTE_ALREADY_ENDED => 'Polls closed',
        self::COMPETITION_NOT_FOUND => 'The contest does not exist',
        self::COMPETITION_NO_PERMISSION => 'You do not have permission to participate in this contest',

        self::POSITION_COMPETENCY_CATEGORY_EXISTS => 'Competency indicator classification already exists',
        self::POSITION_COMPETENCY_CATEGORY_NOT_FOUND => 'Competency indicator classification does not exist',
        self::POSITION_COMPETENCY_EXISTS => 'Competency indicator already exists',
        self::POSITION_COMPETENCY_NOT_FOUND => 'Competency indicator does not exist or has been removed',
        self::POSITION_COMPETENCY_ELEMENT_EXISTS => 'Competency indicator already exists',

        self::POSITION_SKILL_CATEGORY_EXISTS => 'Skill classification already exists',
        self::POSITION_SKILL_CATEGORY_NOT_FOUND => 'Skill classification does not exist',
        self::POSITION_SKILL_EXISTS => 'Skill already exists',
        self::POSITION_SKILL_NOT_FOUND => 'Skill does not exist or has been deleted',
        self::POSITION_SKILL_ELEMENT_EXISTS => 'Skill already exists',

        self::INSPECTION_ELECTIVE_TASK_UNFINISHED => 'You have unfinished tasks',
        self::INSPECTION_ELECTIVE_CLASSIFY_UNFINISHED => 'You have unfinished classifications for your assessment',
        self::INSPECTOR_IS_NOT => 'You are not an inspector',
        self::INSPECTION_AT_LEAST_ONE => 'Please complete at least one appraisal',

        self::HARMONY_ERROR => 'Contains sensitive information and cannot display results',

        self::RETRAINING_NO_EXISTS => 'Number already exists',
        self::RETRAINING_NO_TASKS => 'Please add the template task first',
        self::RETRAINING_NOT_ALLOWED_REPEAT => 'Recertification is not yet enabled',
        self::RETRAINING_REACH_CYCLE_INDEX => 'Your recurring authentication count has expired',
        self::RETRAINING_TIME_NOT_UP => 'Recertification time has not yet expired',
        self::RETRAINING_LEARNER_AUTHENTICATE_ONGOING => 'You still have ongoing authentication, please do not repeat authentication',
        self::RETRAINING_NOT_EXISTS=>'Sorry, recertification does not exist!',
        self::RETRAINING_LEARNER_NOT_PUBLISHED=>'Sorry, recertification has not been made public yet!',
        self::RETRAINING_LEARNER_NOT_AUTH=>'Sorry, you are not in the scope of recertification!',

        self::EXPERIENCE_DETAIL_BEYOND_LIMIT => 'The number of insights you have uploaded has reached the limit',

        self::PHOTOGRAPH_DETAIL_BEYOND_LIMIT => 'The number of photos you have uploaded has reached the upper limit',
        self::PHOTOGRAPH_LEARNER_NOT_EXISTS => 'The participant is not under this class',
        self::PHOTOGRAPH_LEARNER_SUPPORT_EXISTS => 'The participant has already clicked',
        self::PHOTOGRAPH_LEARNER_SUPPORT_MAX => 'Like has exceeded the maximum limit',

        self::CERTIFICATION_USED => 'Certificate is in use and cannot be removed or disabled',
        self::CERTIFICATION_USER_USED => 'Certificate personnel cannot be deleted',
        self::DIRECTORY_PARENT_NOT_SAME_SELF => 'Parent directory cannot be used for this directory',
        self::NOT_GROUP_CANNOT_SELECTED => 'Ungrouped directory cannot be selected',

        self::EVENT_MEMBER_SIGN_INVALID_CAPTCHA => 'Invalid SMS verification code',
        self::EVENT_MEMBER_SIGN_VX_INVALID_ACCESS_TOKEN => 'Invalid access_token',
        self::EVENT_MEMBER_SIGN_VX_INVALID_PWD => 'Invalid sign-in password',

        self::GEN_LIVE_CREATE_ERROR => 'Live creation failed',
        self::GEN_LIVE_NOT_EXISTS => 'Live stream does not exist',
        self::GEN_LIVE_UPDATE_ERROR => 'Live update failed',
        self::GEN_LIVE_INVALID_INPUT => 'Live review parameter failed',
        self::GEN_LIVE_MEMBER_NOT_ALLOWED => 'No permission to view live stream',
        self::COURSE_MULTI_DIRECTORY_LIMIT_ERROR => "Can't have more than 5 subdirectories",
        self::GEN_LIVE_GENERATE_TIME => 'It has not been more than 10 minutes since the last data generation, please try again later',
        self::GEN_LIVE_LIMIT_ATTENDEES => 'The number of live viewers exceeds the limit, please modify or contact staff',

        self::KNOWLEDGE_BASE_NAME_EXIST => 'The name of the knowledge base already exists',
        self::KNOWLEDGE_BASE_NOT_EXIST => 'Knowledge base does not exist',
        self::KNOWLEDGE_QUESTION_HAS_EXISTS => 'This issue already exists under this knowledge base',
        self::KNOWLEDGE_CATEGORY_CANNOT_DELETE => 'The default category cannot be deleted or edited',
        self::KNOWLEDGE_CATEGORY_CANNOT_EQ_ROOT_NAME => 'Category name cannot be the default category',
        self::KNOWLEDGE_CATEGORY_HAS_QUESTION => 'There is a problem under this category and it cannot be deleted',
        self::KNOWLEDGE_QUESTION_NOT_EXISTS => 'Knowledge base issue does not exist',
        self::KNOWLEDGE_CATEGORY_NAME_EQ => 'Category name has not changed',
        self::KNOWLEDGE_QUESTION_IS_SYSTEM => 'This issue is copied for the system, you can not modify oh',
        self::KNOWLEDGE_BASE_HAS_QUESTION => 'There is a problem under this knowledge base, you can not delete',

        self::EVENT_PRIZE_IS_GAIN => 'This prize has already been awarded to a winner and cannot be deleted',
        self::EVENT_ALLOW_NUM_MORETHAN_EXISTS => 'The number of people who have won the prize is greater than the set number',
        self::EVENT_DESIGATED_IS_HAVED => 'The prize has been blocked from the winner and the person has cheated elsewhere',
        self::EVENT_DESIGATED_IS_OVERFLOW => 'The number of cheaters is greater than the number of prizes',
        self::EVENT_NOT_START => 'The event has not started',
        self::EVENT_END => 'The event has ended',

        self::EVENT_MEMBER_SIGNED => 'Checked in',
        self::COURSE_HAVE_LIMIT => 'Course not yet finished, need to finish it to be graded',
        self::COURSE_TYPE_NOT_EQ => 'The type of the lesson is different twice, please upload the same file type',
        self::COURSE_MUST_END => 'The course is not yet finished, you need to finish it to take the quiz',
        self::EXPORT_LIMIT => 'Sorry, you cannot export data',
        self::COURSE_STAR_LIMIT=>"Scoring over the limit",

        // self::CONTRACT_TYPE_USED => 'The contract type is in use',
        // self::EXPORT_LIMIT => 'Sorry, you cannot export data',

        self::INSPECTION_QUESTION_CATEGORY_USED => 'Category is in use and cannot be deleted',
        self::TASK_NO_PERMISSIONS => 'You do not have permission to participate in this job',
        self::TASK_END => 'The job has ended and cannot be participated',
        self::OFFLINEEXERCISE_NO_PERMISSIONS => 'You do not have permission to participate in this offline exercise',
        self::CONTRACT_TYPE_USED => 'The contract type is in use',

        self::GEN_LIVE_CATEGORY_NOT_REMOVE => 'Category is used and cannot be deleted',


        self::QUESTION_NO_EXISTS => 'Number already exists',

        self::SPECIAL_SUBJECT_NO_USED => 'Number is occupied',

        self::EMP_SELF_REG_DATA_INVALID => 'Form data validation failed, please check data',
        self::EMP_SELF_REG_UNIQUE => 'Form data is not unique',
        self::EMP_SELF_REG_UNIQUE_USERNAME => 'Username has been used or registration has been requested',
        self::EMP_SELF_REG_MOBILE_CAPTCHA_FAIL => 'Invalid verification code',
        self::EMP_SELF_REG_UNIQUE_ID_NUMBER => 'You have registered, please login in',

        self::DAILY_CLOCK_CANT_PUBLISH => 'Daily clock start time has started and cannot be published',

        self::TRAINING_CENTER_UNDEFINED => 'Training center unknown error',
        self::TRAINING_CENTER_EXISTS => 'Training center already exists',
        self::TRAINING_CENTER_NOT_FOUND => 'Training center does not exist',
        self::TRAINING_CENTER_NO_EXISTS => 'Number has been used',
        self::TRAINING_CENTER_MAX_LEVEL => 'Maximum level has been reached',
        self::TRAINING_CENTER_USED => 'This training center is in use',
        self::TRAINING_CENTER_NOT_LEAF => 'This training center contains sub-training centers',
        self::VOTE_NO_REPEAT => 'Duplicate votes are not allowed',
        self::KNOWLEDGE_CONTAIN_AUDIT_IDS => 'Submitted knowledge cannot contain audited and approved',

        self::COURSE_HUNDUN_SIGN_ERROR => 'Signature error',
        self::COURSE_HUNDUN_PARAMS_ERROR => 'Parameter error',
        self::COURSE_HUNDUN_NO_AUTH => 'No view access at this time',
        self::COURSE_HUNDUN_TIME_OVERDUE => 'Request has expired',
        self::COURSE_HUNDUN_USER_TOKEN_INVALID => 'User token expired',
        self::COURSE_HUNDUN_DATA_ERROR => 'Data error',
        self::COURSE_HUNDUN_CHECK_ERROR => 'Checksum failure',
        self::COURSE_HUNDUN_USER_REGISTER_REACH_LIMIT => 'Registration account has reached the limit',
        self::COURSE_HUNDUN_USER_REGISTED => 'User has already registered',
        self::COURSE_MODULE_UN_REGISTED => 'No view access at this time',

        self::LPP_NOT_FOUND => 'Bullet question does not exist or has been deleted',
        self::LPP_CREATE_FAIL => 'Failed to create',
        self::LPP_UPDATE_FAIL => 'Update failed',
        self::LPP_TIME_LARGER_DURATION => 'Point in time is greater than course duration',
        self::LPP_TIME_DUPLCATED => 'There is a duplicate time point',
        self::LPP_OPTION_ID_DUPLICATED => 'There is a duplicate option ID',
        self::LPP_OPTION_INVALID_COUNT => 'Number of incorrect correct answer options',


        self::LIVE_HON_SHAN_TIME_ERROR => 'Time needs to be greater than the current time',
        self::LIVE_HONGSHAN_HAS_END => 'The live broadcast has ended or the session does not exist',

        self::SHORTLINK_INVALID_URL => 'Invalid link',
        self::TRAINING_TASK_END => 'Item has been completed',
        self::TRAINING_HAS_USE => 'Project has associated class',

        self::BI_FIELDS_INVALID => 'Error in condition field',
        self::BI_COLUMNS_INVALID => 'Wrong display field setting',

        self::GZ_WATCH_CARD_NO_OR_DISPLAY_ERROR => 'ID number or name error',
        self::KNOWLEDGE_POINT_CATEGORY_EXISTS => 'Category name already exists',
        self::LIVE_ROLE_ERROR => 'Role and live do not match',
        self::LIVE_UN_DELAYED => 'No role create undelay live',


        self::NOT_ENOUGH_SCORE => 'Not enough points',
        self::POSITION_GRADING_NO_QUESTION => 'No trial at this time',

        self::GRADE_SETTING_NAME_EXISTS_ERROR => 'Level already exists',
        self::GRADE_SETTING_LIMIT => 'Up to 5 levels can be added',

        self::AI_SCENARIO_NOT_FOUND => 'Scenario simulation does not exist',
        self::AI_SCENARIO_NODE_NOT_FOUND => 'Scenario node does not exist or has been deleted',
        self::AI_SCENARIO_NOT_PUBLISHED => 'The scenario simulation is not published',
        self::AI_SCENARIO_COPY_FAIL => 'Copy failed, please try again',
        self::AI_SCENARIO_PROCESS_NOT_FOUND => 'No scenario content set',
        self::AI_SCENARIO_PROCESS_NEXT_NODE_NOT_FOUND => 'There is no next question or it has been deleted',
        self::AI_SCENARIO_PROCESS_PREV_NODE_NOT_PASSED => 'The previous question has not been answered, cannot get the next question',
        self::AI_SCENARIO_PROCESS_NODE_ANSWERED => 'The question has already been answered',
        self::AI_SCENARIO_SUBMIT_EXCEPTION => 'There was an exception to the submission, please check the data or try again later',

        self::GUIDANCE_CLASSIFY_EXISTS => 'Category already exists',
        self::GUIDANCE_INSTRUCTIONS_EXISTS => 'Operation guidelines already exist',

        self::STAT_FILTER_GROUP_TYPE_NOT_SUPPORT => 'The group of this type is not supported to filter',

        self::TIME_RANGE_EXCEEDS_LIMIT=>"Time range exceeds upper limit",
        self::ENROLL_NOT_EXISTS => "Registration activity does not exist！",
        self::ENROLL_NOT_PUBLISHED => "Registration event not yet released！",
        self::ENROLL_LEARNER_HAS_ENROLLED => "You have already signed up！",
        self::ENROLL_LEARNER_UNDER_EXAMINE => "You have signed up and are being reviewed...",
        self::ENROLL_LEARNER_NOT_SELECT_SESSIONS => "Please select a session to register for！",
        self::ENROLL_SESSIONS_NOT_EXISTS => "Failed to register, the session you selected does not exist！",
        self::ENROLL_TIME_OVER => "Failed to enrol, enrolment period has ended！",
        self::ENROLL_LEARNER_NUM_REACHED_MAXIMUM_LIMIT => "Enrolment failed, maximum number of enrolments reached！",
        self::ENROLL_REQUIREMENTS_CREDIT_DISQUALIFIED => "Sorry, you have not earned the minimum number of credits required for enrolment！",
        self::ENROLL_REQUIREMENTS_CERTIFICATE_DISQUALIFIED => "Sorry, you do not have the certificates required for enrolment！",
        self::ENROLL_REQUIREMENTS_EXAM_DISQUALIFIED => "Sorry, you have not passed the test required for enrolment and cannot enrol at this time！",
        self::ENROLL_TIMES_MULTI_REACHED_MAXIMUM_LIMIT => "Failed to register, you have reached your maximum number of registrations！",
        self::ENROLL_NOT_ALLOWED_CANCEL => "Sorry, cancellations are not available for this registration！",
        self::ENROLL_CANCEL_DEADLINE_OVER => "Sorry for exceeding the cancellation deadline for registration！",
        self::ENROLL_TIME_NOT_BEGIN => "Registration has not started！",
        self::ENROLL_OFFICIAL_NUM_REACHED_MAXIMUM_LIMIT => "Failed to be audited, the official quota for enrolment has been reached！",
        self::ENROLL_SESSION_IS_OBLIGATORY => "Please select a venue for registration！",
        self::ENROLL_SESSION_NOT_ALLOW_ENROLL_MULTI => "Registration failed, multiple registrations are not allowed for this event!",
        self::ENROLL_REPLACE_REQUIREMENTS_CREDIT_DISQUALIFIED => "Failed to enrol and did not earn the minimum number of credits required for enrolment!",
        self::ENROLL_REPLACE_REQUIREMENTS_CERTIFICATE_DISQUALIFIED => "Failure to enrol and obtain the certificates required for enrolment!",
        self::ENROLL_REPLACE_REQUIREMENTS_EXAM_DISQUALIFIED => "Failed to register and pass the exam required for registration!",

        self::LEARNING_TEACHING_SIGN_NO_OPEN => "The parent signature is not enabled",
        self::LEARNING_TEACHING_SIGN_OTHER_EMP => "You are not the superior to teach",
        self::LEARNING_TEACHING_STUDENT_UNSIGN => "The student has not completed the signature",
        self::LEARNING_TEACHING_SIGN_FINISHED => "You have completed your signature",
        self::LEARNING_TEACHING_NOT_END => "The teaching is not over",
        self::LEARNING_TEACHING_TUTOR_SIGN_NO_OPEN => "The tutor's signature is not opened",
        self::LEARNING_TEACHING_SIGN_OTHER_TUTOR => "You are not a mentor",
        self::LEARNING_TEACHING_TUTOR_UNSIGN => "The tutor did not complete the signature",
        self::LEARNING_TEACHING_TEACHING_UNSIGN => "The superior does not complete the signature",
        self::LEARNING_TEACHING_UNSIGN => "An unsigned tape exists",
        self::LEARNING_TEACHING_STUDENT_SIGN_NO_OPEN => "Sign of the student who has not started the teaching",
        self::LEARNING_TEACHING_SIGN_OTHER_STUDENT => "You are not a student.",
        self::TRAINING_TUTORING_LEANER_NO_SIGNATURE_REQUIRED => "No signature required",
        self::TRAINING_TUTORING_TASK_NOT_SUBMIT => "The lead training assignment has not yet been submitted and cannot be signed at this time",
        self::SCENE_TALK_WEIGHT_SUM_NOT_ALLOWED => "The sum of the scene dialogue weights needs to equal 100!",
        self::SCENE_KEYWORD_WEIGHT_SUM_NOT_ALLOWED => "The sum of the answer keyword weights needs to equal 100!",

        self::MATERIAL_NOT_EXISTS_ERROR => "Material does not exist",
        self::MATERIAL_TYPE_NOT_EQ => "The two material types are different, please upload the same file type",
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_MATERIAL_ERROR => "When there are materials in the catalog, you cannot delete them. Please delete the materials in the catalog first",

        self::LANGUAGE_POINTS_NOT_EXISTS_ERROR => "The knowledge point does not exist",
        self::LANGUAGE_POINTS_NO_EXISTS => "Number already exists",

        self::TEACHING_MATERIAL_NOT_EXISTS_ERROR => "The textbook does not exist",
        self::TEACHING_MATERIAL_NO_EXISTS => "Number already exists",

        self::VERSION_NO_REDUCIBLE_VERSION => "This version is not an approved version and cannot be restored",
        self::VERSION_HAS_REVIEW_VERSION => "There are still versions to be reviewed, no new versions can be added",

        self::OCR_IDCARD_RECOGNIZE_FAIL => 'ID not recognized, please upload clear ID photo.',

        self::ACTION_ASSESSMENT_NOT_EXISTS => 'Post-training action assessment does not exist',
        self::ACTION_ASSESSMENT_LEARNER_EXISTS => 'Student information already exists',
        self::ACTION_ASSESSMENT_LEARNER_NOT_EXISTS => 'Student information does not exist',
        self::ACTION_ITEMS_NOT_REPEAT_SUBMIT => 'Action items cannot be submitted repeatedly',
        self::ACTION_ASSESSMENT_NO_REVIEW_PERMISSION => 'No review permission',
        self::ACTION_ASSESSMENT_NOT_REPEAT_REVIEW => 'Cannot review repeatedly',
        self::ACTION_ASSESSMENT_NO_COMMENT_PERMISSION => 'No comment permission',
        self::ACTION_ASSESSMENT_NOT_REPEAT_COMMENT => 'Cannot repeat evaluation',
        self::COMPETENCY_INDICATOR_NOT_FOUND => 'Job competency indicator does not exist',
        self::COMPETENCY_INDICATOR_GROUP_NOT_FOUND => 'Group does not exist',
        self::COMPETENCY_INDICATOR_SKILL_NOT_FOUND => 'Skills do not exist',
        self:: COMPETENCY_INDICATOR_GROUP_EXISTS => 'Group already exists',
        self::COMPETENCY_INDICATOR_SKILL_EXISTS => 'Skill already exists',
    ];
}