<?php

namespace App\Common;

interface ErrorCodesES extends Errors {

    const ERROR_MESSAGES_ES = [
        \Key\Constants::SYS_SUCCESS => 'OK',

        \Key\Constants::SYS_ERROR_DEFAULT => 'Error desconocido',
        \Key\Constants::SYS_INPUT_INVALID => 'Error de parámetro',

        \Key\Constants::USER_OBJECT_NOT_FOUND => 'El objeto no existe',
        \Key\Constants::USER_OBJECT_ALREADY_EXISTS => 'El objeto ya existe',
        \Key\Constants::USER_OBJECT_OCCUPIED => 'El objeto está usado',

        \Key\Constants::OPERATION_TOO_FREQUENT => 'Operaciones demasiado frecuentes. Vuelva a intentar más tarde',

        self::SECURITY_PWD_WEAK => 'La contraseña predeterminada es demasiado simple',

        self::ACCOUNT_NOT_FOUNT => 'La empresa no existe o está prohibida',
        self::ACCOUNT_NAME_EXISTS => 'El nombre de la empresa es repetido',
        self::ACCOUNT_CREATE_DICTIONARY_ERROR => 'Error de crear diccionario de datos',
        self::ACCOUNT_CREATE_DEPARTMENT_ERROR => 'Error de crear departamento',
        self::ACCOUNT_CREATE_ROLE_ERROR => 'Error de crear papel',
        self::ACCOUNT_CREATE_USER_ERROR => 'Error de crear usuario',
        self::ACCOUNT_CREATE_EMPLOYEE_ERROR => 'Error de crear empleado',
        self::ACCOUNT_CREATE_ASSESSMENT_ERROR => 'Error de crear prueba predeterminada',
        self::ACCOUNT_INVALID => 'La empresa relacionada no existe o está prohibida',
        self::ACCOUNT_CODE_INVALID => 'Código de empresa inválido',
        self::ACCOUNT_EXPIRED => 'La empresa está caducada',
        self::ACCOUNT_FUNCTION_NOT_ENABLED => 'Esta función no está habilitada',
        self::ACCOUNT_URL_EXPIRE => 'Inicio de sesión inválido. Verifique el enlace o vuelva a intentar',

        self::CUSTOM_FIELD_NAME_EXISTS => 'El nombre del campo personalizado ya existe',
        self::IMPORT_CONFIG_NOT_FOUND => 'No se ha configurado ajuste de importar',
        self::IMPORT_MAX_ROWS => 'Superar filas especificadas',

        // Sobre la evaluación de 360
        self::PUBLISH_NO_QUESTIONNAIRE => 'El cuestionario ha sido eliminado',
        self::PUBLISH_NO_MODEL => 'El modelo del cuestionario ha sido eliminado. Vuelva a elegir el cuestionario',
        self::PUBLISH_NO_DIMENSION => 'La dimensión de competencia del cuestionario ha sido eliminada. Vuelva a elegir el cuestionario',
        self::PUBLISH_NO_ELEMENT => 'El elemento de competencia del cuestionario ha sido eliminada. Vuelva a elegir el cuestionario',
        self::PUBLISH_NO_QUESTION => 'Ahora no hay preguntas en el cuestionario. Vuelva a elegir el cuestionario',

        self::EMPLOYEE_HAVE_LOCKED => 'La cuenta está bloqueada. Comuníquese con el administrador.',
        self::EMPLOYEE_NO_EXISTS => 'El código del empleado ya existe',
        self::USER_INVALID_NEW_PWD => 'El formato de contraseña es incorrecto. Verifique el requisito de contraseña',
        self::USER_PWD_NEW_SAME_OLD => 'La contraseña nueva no puede ser igual que la original',
        self::USER_USR_ERROR_DEFAULT => 'Error desconocido',
        self::USER_CAPTCHA_IMAGE_INVALID => 'El código de verificación gráfico está caducado o error al completar',
        self::USER_CAPTCHA_SMS_INVALID => 'El código de verificación de mensaje es incorrecto',
        self::USER_PHONE_INVALID => 'Phone number is invalid',
        self::USER_ACCOUNT_NOT_FOUND => 'No account found',
        self::USER_LOGIN_FAIL => 'Error de iniciar sesión',
        self::USER_QR_LOGIN_FAIL => 'Scan code login failed, please refresh the retry or select other login',
        self::USER_QR_LOGIN_TIMEOUT => 'QR code has expired, please refresh the QR code to re-scan',
        self::USER_PWD_ERROR => 'Error de contraseña de usuario',
        self::USER_LOGIN_FAIL_TOO_MANY => 'Demasiados reintentos',
        self::USER_NOT_FOUND => 'Este usuario no existe',
        self::USER_EXISTS_IN_COMPANY => 'El usuario ya está en la empresa',
        self::USER_INVALID_OLD_PASSWORD => 'Contraseña original inválida',
        self::USER_CREATE_ERROR => 'create a user fail',
        self::USER_SMS_CAPTCHA_FREQUENCY => 'El envío del código de verificación es demasiado frecuente',
        self::USER_INVALID_USERNAME => 'Nombre de usuario ilegal',
        self::USER_LEAVE_OFFICE => 'El empleado ha renunciado',
        self::USER_SMS_TIMEOUT => 'Código de verificación de mensaje fuera de tiempo',
        self::USER_SMS_INVALID => 'Código de verificación de mensaje inválido',
        self::MOBILE_EXIST => 'El número del móvil ya existe',
        self::USER_2FA_BOUND => 'Se ha vinculado 2FA',

        self::QUESTION_BANK_EXISTS => 'El título del banco de preguntas ya existe',
        self::QUESTION_IMPORT_TEMPLETE => 'El encabezado no coincide. Vuelva a descargar la plantilla',
        self::QUESTION_EXISTS => 'El título ya existe',
        self::QUESTION_COYE_FAIL => 'Error de copiar la pregunta',
        self::PAPER_EXISTS => 'El título del papel ya existe',
        self::EXAM_EXISTS => 'El nombre del examen ya existe',
        self::EXAM_END => 'El examen ya termina',
        self::EXAM_COYE_FAIL => 'Error de copiar el examen',
        self::EXAM_EMPLOYEE_END => 'El examen de empleados ya termina',
        self::EXAM_DETAIL_FAIL => 'Error de obtener el detalle del examen',
        self::EXAM_DIR_NOT_FOUND => 'Error de obtener el directorio del examen',
        self::SYSTEM_EXAM_DIR_CANNOT_DELETE => "El directorio del examen predeterminado no puede eliminarse",
        self::EXAM_DIR_EXISTS_CHILD => 'Este directorio no puede eliminarse porque tiene subdirectorios. Elimine primero los subdirectorios',
        self::EXAM_USERNAME_EXIST => 'Error del número del móvil o email',
        self::EXAM_DIR_EXISTS_BANK => 'Este directorio no puede eliminarse porque tiene banco de preguntas. Elimine primero el banco de preguntas',
        self::EXAM_DIR_EXISTS_PAPER => 'Este directorio no puede eliminarse porque tiene papel. Elimine primero las preguntas',
        self::EXAM_NEED_LOGIN => 'Necesitar iniciar sesión para este examen',
        self::EXAM_EMPLOYEE_TEMPLATE => 'El encabezado no coincide. Vuelva a descargar la plantilla',
        self::EXAM_MOBILE_NOT_EXIST => 'El número del móvil no existe',
        self::EXAM_REDIS_NO_DATE => 'redis no tiene respuesta del examinado',
        self::EXAM_STUDENT_OUT_TIME => '¡Lo sentimos que el tiempo actual no está dentro del alcance del examen!',
        self::EXAM_MOCK_DIR_HAS_EXAM => 'Este directorio no puede eliminarse porque tiene exámenes. Elimine primero los exámenes',
        self::EXAM_NOTIFY_UNPUBLISHED => 'El examen no está publicado. No se permite enviar notificación',
        self::EXAM_NOTIFY_END => 'El examen ya termina. No se permite enviar notificación',
        self::EXAM_NOT_EXIST => 'El examen no existe',
        self::EXAM_PAPER_HAS_UPDATE => 'Las preguntas han sido actualizadas. Vuelva a realizar el examen',
        self::EXAM_UNPUBLISHED => 'El examen no está publicado. ¡Comuníquese con el administrador!',

        self::LEARNING_PLAN_NAME_EXIST => 'El nombre del plan de aprendizaje ya existe',
        self::LEARNING_NO_EXIST => '¡El código está ocupado!',
        self::LEARNING_DURATION_TO_LONG => '¡Duración demasiado larga!',
        self::LEARNING_BREAKTHROUGH_NAME_EXIST => 'El nombre del desafío ya existe',
        self::LEARNING_CATEGORY_DELETE_CONTAINS => 'La clasificación tiene desafío. Elimine primero el desafío',
        self::LEARNING_PLAN_NO_PERMISSION => 'Sin permiso',
        self::LEARNING_LEARNER_OVERSTEP => 'El número de personas inscritas ha alcanzado el límite superior',
        self::LEARNING_LEARNER_ALREADY_EXIST => 'Este estudiante ya existe',
        self::LEARNING_PLAN_NO_MORE_GROUP => 'Esta clase inteligente ya no tiene más grupos',
        self::LEARNING_PLAN_NOT_PUBLISHED => 'El plan de aprendizaje no está publicado',
        self::LEARNING_CLASS_NOT_PUBLISHED => 'La clase no está publicada',
        self::LEARNING_PACK_NOT_PUBLISHED => 'El paquete de aprendizaje no está publicado',
        self::LEARNING_PACK_SETTINGS_CREDIT => 'El premio de créditos del paquete de aprendizaje supera el límite',
        self::LERN_ENROLL_POSITION_NOT_PASSED => 'El puesto no cumple. No se permite la inscripción',
        self::LERN_ENROLL_OFFLINE_NOT_PASSED => 'El número de cursos no cumple. No se permite la inscripción',
        self::LERN_ENROLL_NOT_LECTURER => 'No es instructor. No se permite la inscripción',
        self::LEARNING_UN_EXISTS => '¡Lo siento, ¡ el proyecto no existe!',
        self::LEARNING_LEARNER_UNDER_REVIEW => 'Revisando',
        self::LEARNING_TASK_OBLIGATORY => 'Añada primero el contenido del aprendizaje',
        self::LEARNING_TEACHING_TEMPLATE_USED => 'La plantilla de educación laboral ha sido usada y no puede eliminarse',
        self::LEARNING_TEACHING_ALREADY_STARTED => 'La educación laboral ha comenzado',
        self::LEARNING_TEACHING_PROJECT_HAS_LEANRER => 'El proyecto de educación laboral tiene relación de educación laboral y no puede eliminarse',
        self::LEARNING_TASK_EXISTS => 'La tarea ya existe',
        self::LEARNING_TASK_ASSIGNING => 'Está distribuyendo las tareas. Vuelva a intentar más tarde',
        self::LEARNING_APPRAISER_NO_CERTIFICATE => '¡La persona valorada todavía no ha obtenido el certificado pertinente!',
        self::LEARNING_TEACHER_NO_CERTIFICATE => '¡El calificador todavía no ha obtenido el certificado pertinente!',
        self::LEARNING_PACK_NOT_FOUND => 'El paquete de aprendizaje no existe',
        self::LEARNING_INTERACTION_NOT_EXISTS_ERROR => 'La interacción no existe',
        self::LEARNING_SIMPLE_NO_OFFLINE => 'Añada primero el curso presencial antes de publicarlo',
        self::LEARNING_PLAN_ACTIVITY_NOT_FOUND => 'La actividad no existe',
        self::LEARNING_PLAN_ACTIVITY_NOT_STARTED => 'La actividad no comienza',
        self::LEARNING_PLAN_ACTIVITY_NO_AUTH => 'Sin permiso de registrar esta actividad',
        self::LEARNING_NO_OPERATION_AUTH => 'Sin permiso',
        self::LEARNING_PLAN_NO_EXISTS => 'El módulo de aprendizaje no existe',
        self::LEARNING_PLAN_NO_VISIT_AUTH => 'Sin permiso de acceso',
        self::LEARNING_PLAN_IS_RELATED_PROJECT => '¡Este proyecto ha sido ejecutado!',
        self::LEARNING_BREAKTHROUGH_OCCUPIED => '¡Este desafío está ocupado!',
        self::LEARNING_BREAKTHROUGH_CAG_HAVE_BREAKTHROUGH => 'Esta clasificación tiene desafío y no puede eliminarse',
        self::LEARNING_APPLICATION_NON_START => 'La inscripción no comienza',
        self::LEARNING_APPLICATION_ALREADY_OVER => 'La inscripción ya termina',
        self::LERN_ENROLL_SCORE_NOT_SUBSTANDARD => 'No tiene los créditos calificados. ¡No se permite la inscripción!',
        self::LERN_ENROLL_UNCERTIFIED => 'No ha obtenido el certificado pertinente. ¡No se permite la inscripción!',
        self::LERN_ENROLL_EXAM_NOT_PASSED => 'No ha pasado el examen pertinente. ¡No se permite la inscripción!',
        self::LERN_ENROLL_NOT_ALLOW_CANCEL => '¡Esta clase no permite cancelar la inscripción!',
        self::LERN_ENROLL_CANCEL_TIME_CUT_OFF => '¡Vence el tiempo para cancelar la inscripción!',
        self::LERN_ENROLL_DELEGATE_TOP => '¡Alcanza el límite superior de personas para el proyecto!',
        self::LERN_ENROLL_DELEGATE_CLOSE => '¡La inscripción encomendada no ha comenzado!',
        self::LERN_DELEGATE_IS_EXIST => '¡Existe conflicto entre nuevas condiciones y condiciones ya existentes!',
        self::LERN_DELEGATE_DELEGATE_NO_EXIST => '¡El mismo responsable solo puede añadir departamentos configurados!',
        self::LEARNING_PACK_END => '¡El mismo responsable solo puede añadir departamentos configurados!',
        self::LEARNER_NOT_ZERO => 'Se ha añadido el estudiante. ¡No se permite eliminar!',
        self::LEARNING_PACK_UN_ENABLED => '¡El paquete de aprendizaje está prohibido!',
        self::LEARNING_PLAN_LEARNER_ALREADY_SIGNED => 'No repita el registro',
        self::LEARNING_APPLICATION_NOT_ALLOWED => 'La inscripción de la clase no está abierta',
        self::LEARNING_PLAN_NO_AUTH => 'Sin permiso',
        self::LEARNING_PLAN_INVALID_QR_CODE => 'Código QR inválido',
        self::LEARNING_PLAN_ALREADY_ENDED => 'La clase ya termina',
        self::LEARNING_CLASS_SIGN_NOT_START => 'El registro no comienza',
        self::LEARNING_CLASS_SIGN_ENDED => 'El registro ya termina',
        self::LEARNING_CLASS_SIGN_LEARNER_SIGNED => 'Registrado',
        self::LEARNING_PLAN_SIGN_NOT_PUBLISHED => 'La clase no está publicada',
        self::LEARNING_PLAN_SIGN_NO_AUTH => 'Todavía no se ha unido a esta clase y no puede registrar',
        self::LEARNING_PLAN_ENDED_SIGN => 'La clase ya termina',
        self::LEARNING_PACK_SIGN_NO_AUTH => 'Todavía no se ha unido a este paquete de aprendizaje y no puede registrar',
        self::LEARNING_PLAN_SIGN_INVALID_QR_CODE => 'Código QR inválido',
        self::LEARNING_PLAN_SIGN_OVER_DISTANCE => 'Su ubicación no está dentro del alcance de registro y no puede registrar',
        self::LEARNING_PLAN_SIGN_CLOSED_GPS => 'No se puede obtener la ubicación geográfica. Verifique si habilita el posicionamiento',
        self::LERN_MAP_TAGGING_FINISHED_UNCERTIFIED => 'Todavía no ha cumplido con las condiciones de obtener el certificado, por lo que no puede marcar como completado',
        self::LERN_MAP_TAGGING_FINISHED_NOT_AUTH => 'Sin permiso. Esta tarea será marcada como completada por el administrador',
        self::LERN_MAP_TAGGING_FINISHED_CLASS_INCOMPLETE => 'La tasa de completación de esta clase no alcanza 100%, por lo que no puede marcar como completada',
        self::LEARNING_QUEUE_EXISTS => 'Procesando. Espere',
        self::LERN_PACK_DISABLED => 'Este paquete de aprendizaje ya está prohibido. ¡Vuelva a intentar más tarde!',
        self::LERN_PASS_DISABLED => 'Este desafío ya está prohibido. ¡Vuelva a intentar más tarde!',
        self::LERN_OPERATE_NOT_ALLOWED => 'Manteniendo. ¡Realice la operación en backend de administración!',
        self::LEARNING_PLAN_NO_SIGNS => '¡Todavía no hay registro!',
        self::OFFLINE_TEACHING_SIGN_TIME_OUT => '¡Código QR inválido!',
        self::LERN_CLASS_NO_VISIT_AUTH => '¡Todavía no se ha unido a esta clase!',
        self::LERN_PLAN_NO_VISIT_AUTH => '¡Todavía no se ha unido a este plan de aprendizaje!',
        self::LERN_PACK_NO_VISIT_AUTH => '¡Todavía no se ha unido a este paquete de aprendizaje!',
        self::LERN_PASS_NO_VISIT_AUTH => '¡Todavía no se ha unido a este desafío!',
        self::LERN_ADD_LEARNER_ON_GOING => 'Operaciones demasiado frecuentes. ¡Vuelva a intentar más tarde!',
        self::LERN_PASS_UNPUBLISHED => 'El desafío no está publicado',
        self::LERN_PASS_NOT_EXISTS => 'El desafío no existe',
        self::LERN_PASS_NOT_AUTH => 'No tiene el permiso de participar en este desafío',

        self::LERN_PRO_NOT_ALLOW_LEARNER_IN_MULTI_CLASS => 'Este proyecto no permite que una persona se inscriba a múltiples clases',
        self::LERN_PRO_NOT_ALLOW_LEARNER_SHIFT => 'Este proyecto no permite que el estudiante cambie la clase independientemente',
        self::LERN_OVERSTEP_SHIFT_CLASS_TIME => 'Ya vence el tiempo de cambio de clase. Elija otras clases',

        self::KNOWLEDGE_NOT_EXISTS_ERROR => 'El conocimiento no existe',
        self::DIRECTORY_NAME_EXISTS_ERROR => 'El nombre del directorio ya existe',
        self::DIRECTORY_NOT_EXISTS_ERROR => 'El directorio no existe',
        self::DIRECTORY_LEVEL_LIMIT => 'No se puede crear directorio en el nivel de este directorio',
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_KNOW_ERROR => 'El banco de directorios no se puede eliminar cuando tiene conocimiento. Elimine primero el conocimiento del banco de directorios',
        self::DIRECTORY_EXISTS_CHILD_ERROR => 'Este directorio no puede eliminarse porque tiene subdirectorios. Elimine primero los subdirectorios',
        self::CONTENT_IS_NOT_EXISTS_ERROR => 'Este contenido no existe',
        self::DIRECTORY_COURSE_NOT_EXISTS_ERROR => 'El curso no existe',
        self::DIRECTORY_HAS_CHILD_ERROR => 'Este directorio no puede moverse porque tiene subdirectorios',
        self::KNOWLEDGE_NOT_HAVE_AUTH_ERROR => 'Todavía no tiene permiso de ver',
        self::KNOWLEDGE_HAS_USE => 'Este conocimiento no puede eliminarse porque ha sido uso en la tarea',
        self::ORG_NOT_FIND_IN_KNOWLEDGE => 'Esta empresa aún no abre la función de Weiwen',
        self::USER_NOT_PERMISSION => '¡Lo sentimos que no tiene el permiso de acceder a este conocimiento!',
        self::KNOWLEDGE_TOKEN_ERROR => '¡Error del valor Token!',
        self::COURSE_IS_NOT_COMPANY => 'Este curso no es creado por la empresa y no puede configurarse como curso público',
        self::COURSE_TYPE_IS_NOT_ALLOWED => 'El curso de transmisión en vivo no puede configurarse como curso público',
        self::ROOT_DIRECTORY_CANNOT_DELETE_ERROR => 'El directorio del curso predeterminado no puede eliminarse',

        self::COURSE_NOT_EXIST => 'Este curso no existe',
        self::COURSE_IS_SELF => 'No puede colectar el curso creado por uno mismo',
        self::COURSE_HAS_FOLLOWED => 'Ha colectado este curso',
        self::COURSE_HAS_USED_USER => 'El usuario designado ha tenido este curso',
        self::COURSE_EXIST_IN_GROUP => 'Este curso ya existe',
        self::SERIES_GROUP_ORDER_EXISTS => 'El valor de ordenación ya existe',
        self::IMG_LIMIT_ERROR => 'El tamaño de imagen supera el límite',
        self::FILE_LIMIT_ERROR => 'El tamaño de imagen supera el límite',
        self::FILE_READ_FAIL => 'Error de leer el documento. Cargue según requisito',
        self::UPLOAD_FILE_FAIL => 'Error de cargar documento',
        self::SECURITY_RULE_INVALID_IP_CONFIG => 'Configuración de la lista blanca de IP errónea',

        self::POSITION_ERROR_UNDEFINED => 'Error desconocido de puesto',
        self::POSITION_NOT_FOUND => 'El puesto no existe',
        self::POSITION_NUMBER_OCCUPIED => 'El código del puesto está ocupado',
        self::POSITION_CATEGORY_DELETE_CONTAINS => 'Existe puesto en el grupo, que no se puede eliminar',
        self::POSITION_CATEGORY_NOT_FOUND => 'El grupo del puesto no existe',
        self::POSITION_EMPLOYEE_USED => 'El puesto ha sido usado',
        self::POSITION_TARGET_INCLUDE_SELF => 'El objetivo del puesto no puede ser el mismo',

        self::MEDAL_SCORE_EXIST => 'La puntuación de la medalla ya existe',
        self::MEDAL_NAME_EXIST => 'El nombre de la medalla ya existe',
        self::BANNER_SORT_EXIST => 'La prioridad ya existe',
        self::BANNER_TOTAL_NUM => 'Se ha alcanzado el número máximo de gráficos de rotación',
        self::MEDAL_SCORE_INSUFFICIENT => 'Créditos insuficientes',
        self::NOT_AUTH_DEPT => 'Este departamento no tiene permiso de configuración',
        self::NOT_REPEAT_DEPT => 'Este departamento está configurado y no se puede añadir repetidamente',

        self::ORDER_COURSE_ERROR => 'Error de ensamblaje de los datos de cursos en el pedido',
        self::ORDER_ACCREDIT_ERROR => 'Error de autorizar el pedido',
        self::ORDER_PAY_REFUND => 'Reembolso por pedido transferido',
        self::ORDER_PAY_NOTPAY => 'Pedido no pagado',
        self::ORDER_PAY_CLOSED => 'Pedido cerrado',
        self::ORDER_PAY_REVOKED => 'Pedido revocado (pago con tarjeta)',
        self::ORDER_PAY_USERPAYING => 'Está pagando el usuario del pedido ',
        self::ORDER_PAY_PAYERROR => 'Error del pago del pedido',
        self::ORDER_COURSE_EXIST => 'El curso gratuito o cifrado al que se unió ya existe',

        self::DEPT_UNDEFINED_ERROR => 'Error desconocido de departamento',
        self::DEPT_NOT_FOUND => 'El departamento no existe',
        self::DEPT_NON_GROUP_DENY_CHILD => 'No puede crear departamento subordinario sin agrupación',
        self::DEPT_DUPLICATED_IN_BRANCH => 'El departamento de nodo actual ya existe',
        self::DEPT_DENY_CHILD => 'No puede crear departamento subordinario bajo este departamento',
        self::DEPT_NAME_EDIT_DISABLED => 'Se prohíbe editar el nombre de este departamento',
        self::DEPT_EDIT_DISABLED => 'Se prohíbe editar este departamento',
        self::DEPT_EMPLOYEE_EXISTS => 'No se puede ejecutar la operación porque este departamento tiene empleado',
        self::DEPT_NO_EXISTS => 'El código del departamento ya existe',
        self::DEPT_PARENT_NOT_FOUND => 'El departamento superior no existe',

        self::EMPLOYEE_UNDEFINED_ERROR => 'Error desconocido',
        self::EMPLOYEE_NOT_FOUND => 'Error desconocido',
        self::EMPLOYEE_DISPLAY_OCCUPIED => 'El nombre está ocupado',
        self::EMPLOYEE_NUMBER_EXISTS => 'El código del empleado está ocupado',
        self::EMPLOYEE_NOT_FOUND_OR_DISABLED => 'El usuario no existe o está prohibido',
        self::EMPLOYEE_LIMIT_EXCEEDS => 'El número de empleados ya alcanza el límite superior',
        self::EMPLOYEE_MOBILE_OCCUPIED => 'El número del móvil ha sido usado',
        self::EMPLOYEE_EMAIL_CAPTCHA_INVALID => 'El número del móvil ha sido usado',
        self::EMPLOYEE_EMAIL_OCCUPIED => 'Este email ha sido usado',
        self::EMPLOYEE_IMPORT_TEMPLATE_INVALID => 'Plantilla de importación inválida',

        self::ACTIVITY_NAME_EXIST => 'El nombre de la actividad ya existe',
        self::EMPLOEE_NO_AUTH => 'No es empleado de esta empresa',
        self::EMPLOEE_NOT_EXIST => 'El empleado no está en el sistema',
        self::EXPIRY_TIME_CAN_NOT_EMPTY => 'La fecha límite de inscripción es obligatoria',
        self::EXCEEDING_LIMIT => 'Las personas de actividad superan el número máximo de personas',
        self::END_TIME_WRONG => 'El tiempo de terminación debe ser mayor que el tiempo de inicio',
        self::EXPIRY_TIME_WRONG => 'La fecha límite de inscripción debe ser menor o igual que la fecha de terminación de la actividad',

        self::COURSE_NOT_ALLOW_REMOVE => 'No se permite eliminar/retirar el curso si no cumplen 7 días después de la terminación',
        self::COURSE_NOT_OVER => 'El curso todavía no ha terminado',
        self::COURSE_IS_OVER => 'El curso ya termina',
        self::COURSE_NOT_AUTH_VIEW => 'Sin permiso de ver el curso',
        self::COURSE_UPLOAD_AUDIO_ERROR => 'Error de cargar documento de audio',
        self::COURSE_AUDIO_EMPTY => 'Genere un documento de audio',
        self::COURSE_HAS_USED => 'El curso está usándose y no puede eliminarse',
        self::COURSE_NOT_AUTH => 'Aún no tiene permiso de ver',
        self::COURSE_NO_EXISTS => 'El curso no existe',

        self::FAVORITE_HAS_EXISTS_ERROR => 'Ha colectado este contenido',
        self::FAVORITE_NO_EXISTS_ERROR => 'Todavía no ha colectado este contenido y no puede cancelarlo',
        self::COMMENT_NOT_EXISTS_ERROR => 'El comentario no existe',
        self::EMPTY_MISTAKE_QUESTION => 'Sin preguntas incorrectas',
        self::COMMENT_NOT_ROLE_ERROR => 'El comentario puede eliminarse solo por el administrador y uno mismo',

        self::SIGN_DAILY_SIGNED => 'Ha registrado hoy',
        self::PK_CREATE_ERROR => 'Error de crear PK',
        self::PK_DETAIL_ERROR => 'Error de obtener el detalle de PK',
        // self::PK_DETAIL_ERROR => 'Error de guardar PK',
        self::VOTE_TOPIC_EXIST => 'El tema de votación ya existe',
        self::VOTE_NO_PERMISSIONS => 'Los no miembros no pueden participar en la votación',

        self::REPLY_EXIST => 'Ya tiene respuesta y no puede eliminarse',
        self::NOT_ISSUE_CREATOR => 'El no creador de la pregunta no puede operar',
        self::NOT_REPLY_CREATOR => 'El no creador de la respuesta no puede operar',
        self::SURVEY_TITLE_EXIST => 'El título de la encuesta ya existe',
        self::SURVEY_NO_PERMISSIONS => 'Los no miembros no pueden participar en la encuesta',
        self::TEAM_USED => 'Este equipo tiene conocimiento y no puede eliminarse',
        self::TEAM_NAME_EXIST => 'El nombre del equipo no puede repetirse',

        self::LIEVROOM_NOT_FOUND => 'La sala de transmisión en vivo no existe',
        self::QUESTION_NOT_RECOGNIZE => 'No se puede reconocer',
        self::VENDOR_OLD_PASSWORD_WRONG => 'Error de contraseña original del proveedor',
        self::VENDOR_NEW_PASSWORD_WRONG => 'La contraseña nuevo no puede ser igual que la original',

        self::COURSE_REPOSITORY_HAS_USED => 'El curso está usándose y no puede moverse de la biblioteca de cursos',
        self::COURSE_REPOSITORY_HAS_USED_BANNER => 'El curso está recomendado o con gráficos de rotación usados, y no puede moverse',
        self::COURSE_REPOSITORY_CANNOT_REMOVE => 'El no súper administrador no puede mover el curso',
        self::COURSE_CONSUMER_POINT_NOT_ENOUGH => 'Integrales insuficientes',
        self::TASK_TITLE_EXIST => 'El nombre del ejercicio ya existe',

        self::TRAINING_PLAN_EXIST => 'El nombre del plan de capacitación ya existe',
        self::TRAINING_TASK_GROUP_EXIST => 'El nombre del grupo ya existe',
        self::TRAINING_PROJECT_PUSH_FAULT => 'Error de presentar la aprobación',
        self::TRAINING_PROJECT_HAS_PUSH => 'Aprobación presentada',
        self::TRAINING_ACTIVE_HAS_SUBMIT => 'La actividad ha sido presentada. No la modifique',
        self::TRAINING_HAS_SPLITED => 'El plan ya ha sido descompuesto. No repite la descomposición',
        self::TRAINING_MONTH_NO_SPLITED => 'El plan mensual no puede descomponerse',
        self::TRAINING_YAER_NOT_FOUND => 'El año del plan no está configurado y no se puede descomponer',
        self::TRAINING_PLAN_NO_ACTIVE => 'El plan no tiene actividad y no se puede descomponer',

        self::HEADLINE_NO_ASSESS => 'Sin permiso de operación',
        self::HEADLINE_NO_OPEN => 'La función está prohibida',
        self::PERMISSION_ROLE_EXIST => 'El nombre del papel ya existe',
        self::PERMISSION_ROLE_CLASSIFY_EXIST => 'El nombre de la clasificación del papel ya existe',
        self::PERMISSION_ROLE_EXISTS => 'Esta clasificación ya tiene papel',
        self::PERMISSION_ROLE_FUNCTION_EMPTY => 'El permiso de función no puede estar vacío',

        self::QUEUE_EXISTS => 'Está ejecutando la tarea. Vuelva a intentar más tarde',

        self::DEMO_ACCOUNT_TIMEOUT => 'La cuenta de prueba está caducada',
        self::DEMO_ACCOUNT_NO_TRIAL => 'Abriendo la cuenta de prueba',

        self::LHA_OP_ERROR => 'Esta solicitud está aprobada o rechazada',
        self::INTEGRAL_ORDER_FAIL => 'Integrales o inventario insuficientes',
        self::INTEGRAL_PRODUCT_EXISTS => 'El nombre del artículo ya existe',
        self::INTEGRAL_ORDER_LIMIT=>"Las veces de canje de artículos ahora alcanza el límite superior",


        self::KNOWLEDGE_POINT_NAME_HAS_EXISTS => 'El nombre del punto de conocimiento ya existe',
        self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => 'El punto de conocimiento no existe',

        self::LOGIN_NEED_ACCOUNT_CODE => 'Falta código de empresa',
        self::LOGIN_INVALID_ACCOUNT_CODE => 'Código de empresa inválido',
        self::USER_RESET_PASSWORD_EMAILS_ERROR => 'Este email corresponde a varias cuentas y no puede usarse para recuperar',
        self::LOGIN_USER_MOBILE_NOT_BINDING => 'El número del móvil no está vinculado y no puede iniciar sesión',
        self::LOGIN_MOBILE_USED_MANY => 'Este número del móvil ha sido usado por varias personas y no puede iniciar sesión',
        self::LOGIN_IP_BLOCKED => 'IP está impedida',

        self::ASSESSMENT_TOPIC_EXIST => 'El nombre de la evaluación ya existe',
        self::ASSESSMENT_NO_PERMISSIONS => 'Sin permiso de crear evaluación',
        self::ASSESSMENT_PARTAKE_NO_PERMISSIONS => '¡Lo sentimos que no tiene el permiso de participar en esta evaluación!',
        self::ASSESSMENT_END => 'Lo sentimos que la evaluación ya termina',

        self::OFFLINE_TEACHING_NAME_EXIST => 'El curso presencial de este nombre ya existe',
        self::OFFLINE_TEACHING_USED => 'Este curso ha sido usado por clase inteligente y no puede eliminarse',
        self::OFFLINE_TEACHING_RECORD_CANT_DELETE => 'Este registro ha sido revisado y aprobado y no puede eliminarse',

        self::COURSE_HAVE_ESTIMATE => 'Ha comentado. No puede comentar más',
        self::COURSE_NO_PERMISSION => 'Sin permiso de operar',

        // self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => 'El punto de conocimiento no existe',

        self::PLATFORM_NOT_SETTING_DING => 'La plataforma de terceros no vincula Dingding',
        self::PRODUCT_NOT_ENOUGH => 'Cantidad insuficiente de regalos',

        self::BASE_OBJECT_THUMBED_UP => 'Este objeto ha recibido Me Gusta',
        self::BASE_OBJECT_CATEGORY_NOT_FOUND => 'El grupo no existe',
        self::BASE_OBJECT_CATEGORY_USED => 'El grupo ha sido usado',

        self::CIRCLE_APPLICATION_FAULT => 'Se ha unido a este círculo. No repita la unión',
        self::CIRCLE_TOPIC_EXISTS => 'El nombre del tema no puede repetirse',
        self::CIRCLE_IS_USED => 'El círculo de preguntas y respuestas está ocupado y no puede eliminarse',
        self::CIRCLE_NO_PERMISSION => 'No está dentro del alcance del círculo de preguntas y respuestas',
        self::CIRCLE_INFO_NOT_FOUND => 'El post/la pregunta no existe',
        self::CIRCL_VIEWE_NO_PERMISSION => 'Todavía no tiene permiso de operar',

        self::GAME_UNDEFINED => 'Error desconocido',
        self::GAME_BEYOND_ATTEMPT => 'Ha superado intentos límite',
        self::GAME_WON_ALREADY => 'Ha ganado el premio',
        self::GAME_PRIZE_DEPLETED => 'Ya no hay premio',
        self::GAME_NOT_ENABLED => 'No habilitar el juego',
        self::GAME_NOT_START => 'El juego no comienza',
        self::GAME_OVER => 'El juego ya termina',
        self::GAME_NOT_OPEN => 'La lotería no comienza',
        self::GAME_PEOPLE_NUM_NOT_ENOUGH => 'El número de personas para la lotería no es suficiente',
        self::GAME_NUMBER_EXISTS => 'El código de la competición ya existe',
        self::GAME_DUMMY_FREQUENT => 'El sistema de red está ocupado. Vuelva a intentar más tarde',
        self::GAME_INVAID_PARTICIPANT => 'Participante inválido',
        self::GAME_OP_FREQUENT => 'Operaciones demasiado frecuentes. Vuelva a intentar más tarde',

        self::SYNC_ERROR_DATA_FORM_ERROR => 'El formato de datos solicitado es incorrecto. Verifique el formato de datos',

        self::FUNDING_IS_JOIN => 'Participado',
        self::FUNDING_IS_APPLY => 'Inscrito',

        self::COIN_NOT_SUFFICIENT_FUNDS => 'El monto de moneda es insuficiente',
        self::COURSE_CATEGORY_NAME_EXISTS => 'El nombre de la clasificación del curso ya existe',
        self::COURSE_CATEGORY_HAS_USED => 'La clasificación del curso está usándose',
        self::SKILLED_CATEGORY_NAME_EXISTS => 'El nombre ya existe',
        self::SKILLED_CATEGORY_HAS_USED => 'Este tipo competente está usándose',

        self::OFFLINE_ASSESSMENT_USED => 'La valoración ha comenzado',
        self::OFFLINE_ASSESSMENT_TEMPLATE_USED => 'La plantilla de la valoración ha comenzado a usar y no puede eliminarse',
        self::OFFLINE_ASSESSMENT_REACH_RE_NUM => 'Se han agotado las veces de evaluaciones repetidas',
        self::OFFLINE_ASSESSMENT_CANT_RE => 'Esta evaluación no permite repetición',
        self::OFFLINE_ASSESSMENT_NO_ACL => 'Todavía no tiene permiso de operar. Comuníquese con el administrador',

        self::SMS_CAPTCHA_SMS_INVALID => 'Error del código de verificación de mensaje',
        self::SMS_CAPTCHA_SMS_EXPIRED => 'El código de verificación de mensaje está caducado',
        self::SMS_LIMIT_EXCEEDS => 'El código de verificación no ha caducado',

        self::LEARNING_PROJECT_NO_EXISTS => 'El código del proyecto ya existe',

        self::LEARNING_SIGN_INVALID => 'Registrado inválido',
        self::LEARNING_SIGN_NONSUPPORT_CODE => 'Este registro no admite el código de registro',
        self::LEARNING_SIGN_CODE_ERROR => 'Error del código de registrado',
        self::LERN_SIGN_UNAUTHORIZED_PARTICIPATION => 'Sin permiso',
        self::LERN_SIGN_PASSWORD_ERROR => 'Error de contraseña',

        self::LIVE_INVALID => 'Transmisión en vivo inválida',
        self::LIVE_NOT_FOUND => 'La transmisión en vivo no existe',
        self::LIVE_NO_PERMISSION => 'Sin permiso',
        self::LIVE_ROOM_NOT_FOUND => 'La sala de transmisión en vivo no existe',
        self::LIVE_MEMBER_IS_EXISTS => 'Ya existe',
        self::LIVE_MEMBER_IS_NULL => 'La persona elegida está vacía',
        self::LIVE_APPROVED_EXISTS => 'Ya existe persona conectada con micrófono',
        self::LIVE_LECTURER_NOT_REQUEST => 'No iniciar operación de conexión con micrófono',
        self::LIVE_LECTURER_NOT_APPROVED => 'No se permite conexión con micrófono',
        self::LIVE_LECTURER_APPROVED_ALREADY => 'Se ha permitido la conexión con micrófono',
        self::LIVE_COMPERE_IN_LECTURERS => 'El presentador no puede configurarse como instructor',

        self::LECTURER_LEVEL_STANDARD_MUST_SET => 'Ajuste al menos un indicador de calificación del nivel del instructor',
        self::LECTURER_INSIDE_IS_EXISTS => 'Este empleado ya es instructor',
        self::LECTURER_INSIDE_TYPE_ERROR => 'Error del formato del instructor interno',
        self::LECTURER_NUMBER_REPEAT => 'El código del instructor ya existe',
        self::LECTURER_ORDER_AUDITOR => 'La reserva ha sido revisada',
        self::LECTURER_DATE_ORDERED => 'El alcance de tiempo del instructor ha sido reservado',
        self::LECTURER_DATE_DISENABLED => 'El período del instructor no puede reservarse',
        self::LECTURER_PROJECT_REPEAT => 'El proyecto de certificación ya tiene código',
        self::LECTURER_PROJECT_UNEXISTS => 'El proyecto de certificación no existe',
        self::LECTURER_PROJECT_ALREADY_ENDED => 'El proyecto de certificación ya termina',
        self::LECTURER_PROJECT_APPLICATION_NOT_ALLOWED => 'La inscripción del proyecto de certificación no está abierta',
        self::LECTURER_PROJECT_NO_VISIT_AUTH => 'Sin permiso de inscribirse',
        self::LECTURER_PROJECT_LEARNER_ALREADY_EXIST => 'Este miembro ya existe',
        self::LECTURER_PROJECT_LEARNER_UNDER_REVIEW => 'Revisando el miembro',
        self::LECTURER_PROJECT_LEARNER_OVERSTEP => 'El número de personas inscritas ha alcanzado el límite superior',

        self::JOBLEVEL_NOT_FOUND => 'El nivel de puesto no existe',
        self::JOBLEVEL_NO_EXISTS => 'El código del nivel de puesto ya existe',
        self::JOBLEVEL_NAME_EXISTS => 'El nombre del nivel de puesto ya existe',
        self::JOBLEVEL_USED => 'El nivel de puesto ha sido usado',
        self::JOBLEVEL_ORDER_EXISTS => 'El nivel de puesto ha sido usado',

        self::QUE_EXISTS => 'Está ejecutando la tarea. Vuelva a intentar más tarde',

        self::EMP_GRP_NOT_FOUND => 'La multitud no existe',
        self::EMP_GRP_USED => 'La multitud ha sido usada',
        self::EMP_GRP_NOT_DYNAMIC => 'This group is not a dynamic group',

        self::OFFLINE_ASSESSMENT_MUST_NUM_MORE => 'El número de preguntas obligatorias en la regla de aprobación debe ser mayor que el número de preguntas obligatorias reales',
        self::EXAM_DATA_PROCESSING => 'Procesando los datos de preguntas',
        self::EXAM_APPROVE_NOT_FOUND => 'La revisión del examen no existe',
        self::EXAM_UNFINISH_NOT_FOUND => 'Ha presentado su examen',
        self::EXAM_MARKING => 'Revisando',

        self::CASE_DIRECTORY_IS_EXISTS => 'El directorio ya existe',
        self::CASE_DIRECTORY_NOT_FOUND => 'El directorio no existe',
        self::CASE_DIRECTORY_PARENT_NOT_FOUND => 'El directorio principal no existe',
        self::CASE_DIRECTORY_SORT_DIFFERENT_PARENTS => 'Solo puede ordenar directorios con el mismo nivel principal',
        self::CASE_DIRECTORY_GT_MAX_LEVEL => 'El directorio solo admite 3 niveles',
        self::CASE_DIRECTORY_HAVE_CHILD => 'Este directorio tiene subdirectorios',
        self::CASE_ATTACHMENT_IS_NECESSARY => 'Para la plantilla que usa usted, el anexo es obligatorio',
        self::CASE_ATTACHMENT_IS_OVERFLOW => 'El número de anexos cargados alcanza el límite superior y no puede continuar con la carga',
        self::CASE_ATTACHMENT_UNSUPPORTED_FILE_TYPES => 'Tipo de anexo no compatible',
        self::CASE_STAGE_IS_EXISTS => 'El nombre de la etapa ya existe',
        self::CASE_TEMPLATE_NOT_FOUND => 'La plantilla no existe',
        self::CASE_TEMPLATE_NO_IS_EXISTS => 'El código de la plantilla ya existe',
        self::CASE_TEMPLATE_TITLE_IS_EXISTS => 'El nombre de la plantilla ya existe',

        self::LEARNING_TEMPLATE_NO_GROUP_CANT => 'No puede eliminar ni modificar sin agrupación',
        self::LEARNING_TEMPLATE_TITLE_EXISTS => 'El nombre de este grupo ya existe',
        self::LEARNING_TEMPLATE_TITLE_IS_USED => 'El grupo ha sido usado y no puede eliminarse',
        self::EXAM_UNAUTHORIZED_PARTICIPATION => 'No tiene el permiso de participar en este examen',
        self::VOTE_UNAUTHORIZED_PARTICIPATION => 'No tiene el permiso de participar en esta votación',
        self::VOTE_HAVE_CLOSED => 'Esta votación ya termina',
        self::VOTE_UN_START => 'Esta votación no comienza',
        self::VOTE_OPEN_NO_EDIT => 'La votación pública no permite modificar',
        self::VOTE_IS_REPEAT_NO_EDIT => 'La votación pública no permite modificar',
        self::VOTE_RESULT_NOT_FOUND => 'No se encuentra el resultado de la votación',
        self::VOTE_RESULT_HAS_EXAMINE => 'La votación ha sido revisada y no permite modificarse',
        self::ASSESSMENT_TEMPLETE_USED => 'Esta plantilla ha sido usada y no puede eliminarse',
        self::SURVEY_TEMPLETE_USED => 'Esta plantilla ha sido usada y no puede eliminarse',
        self::ASSESSMENT_TEMPLETE_TITLE_EXIST => 'El nombre de la plantilla de la evaluación ya existe',
        self::SURVEY_TEMPLETE_TITLE_EXIST => 'El nombre de la plantilla de la encuesta ya existe',
        self::ASSESSMENT_TEMPLETE_NO_EXIST => 'El código de la plantilla de la evaluación ya existe',
        self::SURVEY_RE_NUM_FULL => 'Ya cumplen las veces repetidas de la encuesta',
        self::SURVEY_ANSWER_IS_REPEAT => 'La respuesta es repetida de la pregunta de espacio en blanco con respuesta no repetida',

        self::SURVEY_NOTIFY_UNPUBLISHED => 'La encuesta no está publicada. No se permite enviar notificación',
        self::SURVEY_NOTIFY_END => 'La encuesta ya termina. No se permite enviar notificación',
        self::SURVEY_NEED_LOGIN => 'Necesitar iniciar sesión para esta encuesta',

        self::FACE_MATCHING_SOURCE_EXISTS => 'La plantilla de comparación facial ya existe',
        self::FACE_MATCHING_DETECT_FAIL => 'Error de comparación facial',
        self::FACE_MATCHING_SOURCE_NOT_EXIST => 'La plantilla de comparación facial no existe',
        self::FACE_MATCHING_STORAGE_FOLDER_CREATE_FAIL => 'No puede crear directorio de almacenamiento',
        self::FACE_MATCHING_INVALID_FILE_TYPE => 'Formato de imagen no compatible',
        self::FACE_MATCHING_INVALID_FILE => 'Formato de documento no compatible',

        self::APPROVAL_CATEGORY_IS_EXISTS => 'La clasificación ya existe',
        self::APPROVAL_CATEGORY_IS_USED => 'La clasificación ha sido usada y no puede eliminarse',
        self::APPROVAL_PROCESS_IS_EXISTS => 'El proceso de aprobación ya existe',
        self::APPROVAL_LEVEL_IS_EXISTS => 'El nivel de aprobación ya existe',
        self::APPROVAL_PROCESS_NOT_ENABLED => 'El flujo de revisión que no puede habilitar la empresa',
        self::APPROVAL_REVIEW_EMPLOYEE_MUST => 'Debe elegir el aprobador',
        self::COURSE_REVIEW_NO_AUTH => 'Sin permiso de aprobar curso',

        self::COMPETITION_ROUND_START_ERROR => 'El tiempo de inicio o de terminación de ronda no es correcto',
        self::COMPETITION_CANT_RECEIVE_AWARD => 'No tiene el permiso de obtener el gran premio de la temporada',
        self::COMPETITION_JS_NO_IS_EXISTS => 'El código de la competición no puede repetirse',
        self::COMPETITION_NOT_IN_VOTE_RANGE => 'No está en el alcance de votación',
        self::COMPETITION_ROUND_IS_END => 'Esta ronda ya termina y no puede eliminarse',
        self::COMPETITION_ROUND_IS_START => 'Esta ronda ha comenzado y no puede modificarse ni eliminarse',
        self::COMPETITION_APPLY_TIME_ERROR => 'Error del tiempo configurado para la inscripción',
        self::COMPETITION_NOT_HAVE_ROUND => 'Añada primero la información de la ronda antes de publicarla',
        self::COMPETITION_NOT_BEGIN => 'La competición todavía no comienza',
        self::COMPETITION_ACHIEVEMENT_GROUP_USED => 'Este equipo está en el grupo de combate. Elimina primero este equipo y vuelva a intentar...',
        self::COMPETITION_ACHIEVEMENT_BATTLE_EXISTS => 'Este equipo de combate ya existe',
        self::COMPETITION_ACHIEVEMENT_HELP_EXISTS => 'Ha completado la asistencia en este PK',
        self::COMPETITION_VOTE_EXISTS => 'Ha votado hoy',
        self::COMPETITION_IS_USED => 'La competición está ocupada y no puede eliminarse',
        self::COMPETITION_NOTIFY_UNPUBLISHED => 'La competición no está publicada. No se permite enviar notificación',
        self::COMPETITION_NOTIFY_END => 'La competición ya termina. No se permite enviar notificación',
        self::COMPETITION_VOTE_NOT_STARTED => 'La votación todavía no comienza',
        self::COMPETITION_VOTE_ALREADY_ENDED => 'La votación ya termina',

        self::POSITION_COMPETENCY_CATEGORY_EXISTS => 'La clasificación del indicador de competencia ya existe',
        self::POSITION_COMPETENCY_CATEGORY_NOT_FOUND => 'La clasificación del indicador de competencia no existe',
        self::POSITION_COMPETENCY_EXISTS => 'El indicador de competencia ya existe',
        self::POSITION_COMPETENCY_NOT_FOUND => 'El indicador de competencia no existe o ha sido eliminado',
        self::POSITION_COMPETENCY_ELEMENT_EXISTS => 'El indicador de capacidad ya existe',
        self::CATEGORY_NAME_EXIST => 'La clasificación ya existe',

        self::POSITION_SKILL_CATEGORY_EXISTS => 'La clasificación de habilidad ya existe',
        self::POSITION_SKILL_CATEGORY_NOT_FOUND => 'La clasificación de habilidad no existe',
        self::POSITION_SKILL_EXISTS => 'La habilidad ya existe',
        self::POSITION_SKILL_NOT_FOUND => 'La habilidad no existe o ha sido eliminado',
        self::POSITION_SKILL_ELEMENT_EXISTS => 'La habilidad ya existe',
        self::SKILL_NOT_EXISTS => 'Falta habilidad bajo el modelo de capacidad',

        self::INSPECTION_ELECTIVE_TASK_UNFINISHED => 'Tiene tarea no completada',
        self::INSPECTION_ELECTIVE_CLASSIFY_UNFINISHED => 'Tiene clasificación no completada en su evaluación',
        self::INSPECTOR_IS_NOT => 'No es inspector',
        self::INSPECTION_AT_LEAST_ONE => 'Complete al menos una evaluación',

        self::HARMONY_ERROR => 'Incluye información sensible y no se puede mostrar el resultado',

        self::RETRAINING_NO_EXISTS => 'El código ya existe',
        self::RETRAINING_NO_TASKS => 'Añada primero la tarea de plantilla',
        self::RETRAINING_NOT_ALLOWED_REPEAT => 'Ahora no habilita la recertificación',
        self::RETRAINING_REACH_CYCLE_INDEX => 'Ya cumple sus veces de certificación circular',
        self::RETRAINING_TIME_NOT_UP => 'No ha llegado el momento de la recertificación',
        self::RETRAINING_LEARNER_AUTHENTICATE_ONGOING => 'Todavía tiene certificación pendiente. No repita la certificación',
        self::RETRAINING_EXAM_INVALID => 'Examen de certificación y reeducación inválido',
        self::APPRIAISAL_POSITION_SKILL_EXISTS_ELEMENT=>'Existe habilidad en la certificación del puesto. Elimine primero la habilidad de la certificación del puesto',
        self::RETRAINING_NOT_EXISTS=>'¡Lo sentimos que la certificación y reeducación no existen!',
        self::RETRAINING_LEARNER_NOT_PUBLISHED=>'¡Lo sentimos que la certificación y reeducación no existen!',
        self::RETRAINING_LEARNER_NOT_AUTH=>'¡Lo sentimos que no está dentro del alcance de la certificación y reeducación!',

        self::EXPERIENCE_DETAIL_BEYOND_LIMIT => 'El número de experiencias cargadas alcanza el límite superior',

        self::PHOTOGRAPH_DETAIL_BEYOND_LIMIT => 'Las fotos cargadas alcanza el límite superior',
        self::PHOTOGRAPH_LEARNER_NOT_EXISTS => 'El estudiante no está bajo esta clase',
        self::PHOTOGRAPH_LEARNER_SUPPORT_EXISTS => 'El estudiante ha dado Me Gusta',
        self::PHOTOGRAPH_LEARNER_SUPPORT_MAX => 'Los likes han superado el límite máximo',

        self::CERTIFICATION_USED => 'El certificado está usándose y no puede eliminarse o prohibirse',
        self::CERTIFICATION_USER_USED => 'La persona del certificado no puede eliminarse',
        self::DIRECTORY_PARENT_NOT_SAME_SELF => 'El directorio principal no puede ser el mismo directorio',
        self::NOT_GROUP_CANNOT_SELECTED => 'El directorio no agrupado no puede elegirse',

        self::EVENT_MEMBER_SIGN_INVALID_CAPTCHA => 'Código de verificación de mensaje inválido',
        self::EVENT_MEMBER_SIGN_VX_INVALID_ACCESS_TOKEN => 'access_token inválido',
        self::EVENT_MEMBER_SIGN_VX_INVALID_PWD => 'Contraseña de registro inválida',

        self::GEN_LIVE_CREATE_ERROR => 'Error de crear transmisión en vivo',
        self::GEN_LIVE_NOT_EXISTS => 'La transmisión en vivo no existe',
        self::GEN_LIVE_UPDATE_ERROR => 'Error de actualizar la transmisión en vivo',
        self::GEN_LIVE_INVALID_INPUT => 'Error de parámetros de revisión de la transmisión en vivo',
        self::GEN_LIVE_MEMBER_NOT_ALLOWED => 'Sin permiso de ver la transmisión en vivo',
        self::COURSE_MULTI_DIRECTORY_LIMIT_ERROR => 'Hasta 5 subdirectorios',
        self::GEN_LIVE_GENERATE_TIME => 'El tiempo de generación de datos no ha superado los 10 minutos desde la última vez. Vuelva a intentar más tarde',
        self::GEN_LIVE_LIMIT_ATTENDEES => 'El número de personas de la transmisión en vivo ha superado el límite. Modifique o comuníquese con el trabajador',
        self::GEN_LIVE_NO_AUTH => 'Inicie sesión',

        self::KNOWLEDGE_BASE_NAME_EXIST => 'El nombre de la base de conocimientos ya existe',
        self::KNOWLEDGE_BASE_NOT_EXIST => 'La base de conocimientos no existe',
        self::KNOWLEDGE_QUESTION_HAS_EXISTS => 'Esta pregunta ya existe bajo esta base de conocimientos',
        self::KNOWLEDGE_CATEGORY_CANNOT_DELETE => 'No se puede eliminar ni editar la clasificación predeterminada',
        self::KNOWLEDGE_CATEGORY_CANNOT_EQ_ROOT_NAME => 'El nombre de la clasificación no puede ser clasificación predeterminada',
        self::KNOWLEDGE_CATEGORY_HAS_QUESTION => 'Esta clasificación tiene preguntas y no puede eliminarse',
        self::KNOWLEDGE_QUESTION_NOT_EXISTS => 'La pregunta de la base de conocimientos no existe',
        self::KNOWLEDGE_CATEGORY_NAME_EQ => 'El nombre de la clasificación no cambia',
        self::KNOWLEDGE_QUESTION_IS_SYSTEM => 'Esta pregunta es copiada por el sistema y no puede modificarla',
        self::KNOWLEDGE_BASE_HAS_QUESTION => 'Esta base de conocimientos tiene preguntas y no puede eliminarse',
        self::KNOWLEDGE_APPLY_EXIST => 'La solicitud ya existe',

        self::EVENT_PRIZE_IS_GAIN => 'Este premio ya tiene ganador y no puede eliminarse',
        self::EVENT_ALLOW_NUM_MORETHAN_EXISTS => 'El número de ganadores del premio es mayor que el número ajustado',
        self::EVENT_DESIGATED_IS_HAVED => 'El premio ha sido bloqueado para el ganador, que ha hecho trampa en otro lugar',
        self::EVENT_DESIGATED_IS_OVERFLOW => 'El número de personas que hacen trampa es mayor que la cantidad de premios',
        self::EVENT_NOT_START => 'La actividad no comienza',
        self::EVENT_END => 'La actividad ya termina',

        self::EVENT_MEMBER_SIGNED => 'Ha registrado',
        self::COURSE_HAVE_LIMIT => 'Todavía no ha completado el curso y puede calificar después de completar el aprendizaje',
        self::COURSE_TYPE_NOT_EQ => 'Los tipos de los dos materiales didácticos son diferentes. Cargue el mismo tipo de documento',
        self::COURSE_MUST_END => 'Todavía no ha completado el curso y puede participar en la prueba después de completar el aprendizaje',
        self::EXPORT_LIMIT => 'Lo sentimos que no puede exportar los datos',
        self::COURSE_STAR_LIMIT =>"Marcar por encima del límite",

        // self::CONTRACT_TYPE_USED => 'El tipo del contrato está usándose',
        // self::EXPORT_LIMIT => 'Lo sentimos que no puede exportar los datos',

        self::INSPECTION_QUESTION_CATEGORY_USED => 'La clasificación está usándose y no puede eliminarse',
        self::TASK_NO_PERMISSIONS => 'No tiene el permiso de participar en este ejercicio',
        self::TASK_END => 'El ejercicio ya termina y no puede participar en él',
        self::OFFLINEEXERCISE_NO_PERMISSIONS => 'No tiene el permiso de participar en esta práctica presencial',
        self::CONTRACT_TYPE_USED => 'El tipo del contrato está usándose',

        self::GEN_LIVE_CATEGORY_NOT_REMOVE => 'La clasificación está usándose y no puede eliminarse',


        self::QUESTION_NO_EXISTS => 'El código ya existe',

        self::SPECIAL_SUBJECT_NO_USED => 'El código está ocupado',

        self::EMP_SELF_REG_DATA_INVALID => 'Error de verificar los datos del formulario. Verifique los datos',
        self::EMP_SELF_REG_UNIQUE => 'Los datos del formulario no son únicos',
        self::EMP_SELF_REG_UNIQUE_USERNAME => 'El nombre de usuario ha sido usado o solicitado para el registro',

        self::DAILY_CLOCK_CANT_PUBLISH => 'El tiempo de ficha diaria ya comienza y no puede publicar',

        self::TRAINING_CENTER_UNDEFINED => 'Error desconocido del centro de capacitación',
        self::TRAINING_CENTER_EXISTS => 'El centro de capacitación ya existe',
        self::TRAINING_CENTER_NOT_FOUND => 'El centro de capacitación no existe',
        self::TRAINING_CENTER_NO_EXISTS => 'El código ha sido usado',
        self::TRAINING_CENTER_MAX_LEVEL => 'Alcanza el nivel máximo',
        self::TRAINING_CENTER_USED => 'El centro de capacitación está usándose',
        self::TRAINING_CENTER_NOT_LEAF => 'El centro de capacitación incluye subcentro de capacitación',
        self::VOTE_NO_REPEAT => 'No permite repetir la votación',
        self::KNOWLEDGE_CONTAIN_AUDIT_IDS => 'Los conocimientos presentados no deben comprender los que están revisándose o los aprobados',

        self::COURSE_HUNDUN_SIGN_ERROR => 'Error de firma',
        self::COURSE_HUNDUN_PARAMS_ERROR => 'Error de parámetro',
        self::COURSE_HUNDUN_NO_AUTH => 'Aún no tiene permiso de ver',
        self::COURSE_HUNDUN_TIME_OVERDUE => 'La solicitud está caducada',
        self::COURSE_HUNDUN_USER_TOKEN_INVALID => 'token del usuario pierde su validez',
        self::COURSE_HUNDUN_DATA_ERROR => 'Error de datos',
        self::COURSE_HUNDUN_CHECK_ERROR => 'Error de verificación',
        self::COURSE_HUNDUN_USER_REGISTER_REACH_LIMIT => 'Las cuentas de registro alcanzan el límite superior',
        self::COURSE_HUNDUN_USER_REGISTED => 'El usuario ha sido registrado',
        self::COURSE_MODULE_UN_REGISTED => 'Aún no tiene permiso de ver',

        self::LPP_NOT_FOUND => 'La pregunta emergente no existe o ha sido eliminada',
        self::LPP_CREATE_FAIL => 'Error de crear',
        self::LPP_UPDATE_FAIL => 'Error de actualizar',
        self::LPP_TIME_LARGER_DURATION => 'El punto de tiempo es mayor que la duración del curso',
        self::LPP_TIME_DUPLCATED => 'Existen puntos de tiempo repetidos',
        self::LPP_OPTION_ID_DUPLICATED => 'Existen ID de opciones repetidas',
        self::LPP_OPTION_INVALID_COUNT => 'Número incorrecto de opciones de respuestas correctas',

        //Revisión de integrales
        self::SCORE_TYPE_EXISTS=>"El tipo de integrales ya existe",
        self::SCORE_TYPE_NO_EXISTS=>"El tipo de integrales no existe",
        self::SCORE_APPLY_NO_EXISTS=>"La solicitud de integrales no existe",
        self::SCORE_APPLY_STATE_ERROR=>"Error del estado de la solicitud de integrales",
        self::SCORE_APPLY_NO_CHECKING=>"Solicitud de integrales sin revisión",

        //Administración de consumible
        self::CONSUMABLE_EXISTS=>"El consumible ya existe",
        self::CONSUMABLE_NO_EXISTS=>"El consumible no existe",


        self::LIVE_HON_SHAN_TIME_ERROR => 'El tiempo debe ser mayor que el tiempo actual',
        self::LIVE_HONGSHAN_HAS_END => 'La transmisión en vivo ya termina o la reunión no existe',

        self::SHORTLINK_INVALID_URL => 'Enlace inválido',
        self::TRAINING_TASK_END => 'El proyecto ha sido completado',
        self::TRAINING_HAS_USE => 'El proyecto ha vinculado la clase',


        self::GZ_WATCH_CARD_NO_OR_DISPLAY_ERROR => 'Error del número de cédula o nombre',
        self::KNOWLEDGE_POINT_CATEGORY_EXISTS => 'El nombre de la clasificación ya existe',
        self::LIVE_ROLE_ERROR => 'El papel no coincide con la transmisión en vivo',
        self::LIVE_UN_DELAYED => 'No ha abierto transmisión en vivo sin retraso',


        self::NOT_ENOUGH_SCORE => 'No tiene integrales suficientes',
        self::POSITION_GRADING_NO_QUESTION => 'Todavía no hay pregunta',

        self::GRADE_SETTING_NAME_EXISTS_ERROR => 'El nivel ya existe',
        self::GRADE_SETTING_LIMIT => 'Añadir hasta 5 niveles',

        self::AI_SCENARIO_NOT_FOUND => 'La simulación del escenario no existe',
        self::AI_SCENARIO_NODE_NOT_FOUND => 'El nodo de la simulación del escenario no existe o ha sido eliminado',
        self::AI_SCENARIO_NOT_PUBLISHED => 'La simulación del escenario no está publicada',
        self::AI_SCENARIO_COPY_FAIL => 'Error de copiar. Vuelva a intentar',
        self::AI_SCENARIO_PROCESS_NOT_FOUND => 'La simulación del escenario no está configurada',
        self::AI_SCENARIO_PROCESS_NEXT_NODE_NOT_FOUND => 'No hay pregunta siguiente o ha sido eliminada',
        self::AI_SCENARIO_PROCESS_PREV_NODE_NOT_PASSED => 'No ha respondido la pregunta anterior y no puede obtener la siguiente',
        self::AI_SCENARIO_PROCESS_NODE_ANSWERED => 'Esta pregunta ha sido respondido',
        self::AI_SCENARIO_SUBMIT_EXCEPTION => 'Error de presentar. Verifique los datos o vuelva a intentar más tarde',

        self::YEAR_REPORT_OUTDATE => 'El informe ha sido caducado',

        self::GUIDANCE_CLASSIFY_EXISTS => 'La clasificación ya existe',
        self::GUIDANCE_INSTRUCTIONS_EXISTS => 'La gruía de operación ya existe',

        self::STAT_FILTER_GROUP_TYPE_NOT_SUPPORT => 'No se puede filtrar este tipo de multitud',

        self::RETRAINING_LEVEL_NO_EXISTS => 'El código está ocupado',

        self::LEARNING_PACK_TOP_EXISTS => 'Esta prioridad ya existe',

        self::RETRAINING_CATEGORY_NO_EXISTS => 'El código está ocupado',

        self::CLASSROOM_NOT_EXISTS =>"El aula no existe",

        self::CLASSROOM_HAS_RE => "El aula ha sido reservada",

        self::HUNDUN_SIGN_ERROR => "Error de firma",
        self::HUNDUN_MOBILE_FORMAT_ERROR => "Error del formato del número del móvil",
        self::HUNDUN_PARAMS_ERROR => "Error de parámetro",
        self::HUNDUN_REACH_REGISTER_LIMIT => "Las cuentas de registro alcanzan el límite superior",
        self::HUNDUN_REGISTER_FAILED => "Error de registrarse como usuario",
        self::HUNDUN_PARAM_ERROR => "Error de parámetro",
        self::HUNDUN_USER_REGISTED => "El usuario ha sido registrado",
        self::HUNDUN_REACH_USER_SIGNOUT_LIMIT => "Alcanza el límite superior de cancelación de usuarios. El número de cancelaciones por defecto ocupa un 10% de la cantidad total comprada.",
        self::HUNDUN_COMPANY_UNEXISTS => "Error de permiso: la cuenta de la empresa no existe",
        self::HUNDUN_UNAUTHORIZED_COURSE_PACKAGE => "Error de permiso: la empresa no autoriza el paquete de curso",
        self::HUNDUN_UNAUTHORIZED_COURSE => "No autorizar el curso",

        self::DATABOARD_SYSTEM_UNALLOWED_DELETED => "¡No se permite eliminar el tablero del sistema!",

        self::MATERIAL_NOT_EXISTS_ERROR => "El material no existe",
        self::MATERIAL_TYPE_NOT_EQ => "El tipo de material de archivo no es el mismo en ambas ocasiones, por favor cargue el mismo tipo de archivo",
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_MATERIAL_ERROR => "No se puede eliminar el material de archivo cuando hay material de archivo en la biblioteca de directorios Oh, por favor, elimine el material de archivo de la biblioteca de directorios primero",

        self::LANGUAGE_POINTS_NOT_EXISTS_ERROR => "El punto de conocimiento no existe",
        self::LANGUAGE_POINTS_NO_EXISTS => "El número ya existe",

        self::TEACHING_MATERIAL_NOT_EXISTS_ERROR => "El material no existe",
        self::TEACHING_MATERIAL_NO_EXISTS => "El número ya existe",

        self::VERSION_NO_REDUCIBLE_VERSION => "Esta versión no es una versión aprobada y no se puede restaurar",
        self::VERSION_HAS_REVIEW_VERSION => "Versiones que aún no se han revisado, no se pueden agregar más versiones",

        self::ACTION_ASSESSMENT_NOT_EXISTS => 'La evaluación de la acción posterior a la capacitación no existe',
        self::ACTION_ASSESSMENT_LEARNER_EXISTS => 'La información del estudiante no existe',
        self::ACTION_ASSESSMENT_LEARNER_NOT_EXISTS => 'La información del estudiante no existe' ,
        self::ACTION_ITEMS_NOT_REPEAT_SUBMIT => 'Los elementos de acción no se pueden enviar repetidamente',
        self::ACTION_ASSESSMENT_NO_REVIEW_PERMISSION => 'Sin permiso de revisión',
        self::ACTION_ASSESSMENT_NOT_REPEAT_REVIEW => 'No se pueden revisar repetidamente',
        self:: ACTION_ASSESSMENT_NO_COMMENT_PERMISSION => 'Sin permiso de evaluación',
        self::ACTION_ASSESSMENT_NOT_REPEAT_COMMENT => 'No se pueden comentar repetidamente',
        self::COMPETENCY_INDICATOR_NOT_FOUND => 'El indicador de competencia laboral no existe',
        self::COMPETENCY_INDICATOR_GROUP_NOT_FOUND => 'El grupo no existe',
        self::COMPETENCY_INDICATOR_SKILL_NOT_FOUND => 'Las habilidades no existen',
        self:: COMPETENCY_INDICATOR_GROUP_EXISTS => 'El grupo ya existe',
        self::COMPETENCY_INDICATOR_SKILL_EXISTS => 'La habilidad ya existe',

    ];
}