<?php
namespace App\Common;

interface ErrorCodesZhTW extends Errors {

    const ERROR_MESSAGES_ZH_TW = [
        \Key\Constants::SYS_SUCCESS => '成功',

        \Key\Constants::SYS_ERROR_DEFAULT => '未知錯誤',
        \Key\Constants::SYS_INPUT_INVALID => '參數錯誤',

        \Key\Constants::USER_OBJECT_NOT_FOUND => '對象不存在',
        \Key\Constants::USER_OBJECT_ALREADY_EXISTS => '對象已存在',
        \Key\Constants::USER_OBJECT_OCCUPIED => '對象已被使用',

        \Key\Constants::OPERATION_TOO_FREQUENT => '操作過於頻繁，請稍候再試',

        self::SECURITY_PWD_WEAK => '默認密碼過於簡單',

        self::ACCOUNT_NOT_FOUNT => '公司不存在或已被禁用',
        self::ACCOUNT_NAME_EXISTS => '企業名稱重復',
        self::ACCOUNT_CREATE_DICTIONARY_ERROR => '創建數據字典失敗',
        self::ACCOUNT_CREATE_DEPARTMENT_ERROR => '創建部門失敗',
        self::ACCOUNT_CREATE_ROLE_ERROR => '創建角色失敗',
        self::ACCOUNT_CREATE_USER_ERROR => '創建用戶失敗',
        self::ACCOUNT_CREATE_EMPLOYEE_ERROR => '創建員工失敗',
        self::ACCOUNT_CREATE_ASSESSMENT_ERROR => '創建默認的測評失敗',
        self::ACCOUNT_INVALID => '關聯公司已過期或被禁用',
        self::ACCOUNT_CODE_INVALID => '無效的公司編號',
        self::ACCOUNT_EXPIRED => '公司已過期',
        self::ACCOUNT_FUNCTION_NOT_ENABLED => '該功能未啟用',
        self::ACCOUNT_URL_EXPIRE => '登錄失效，請檢查鏈接或重試',

        self::CUSTOM_FIELD_NAME_EXISTS => '自定義字段名稱已存在',
        self::IMPORT_CONFIG_NOT_FOUND => '未配置導入設置',
        self::IMPORT_MAX_ROWS => '超過規定行數',

        // 360評估相關
        self::PUBLISH_NO_QUESTIONNAIRE => '問卷已經被刪除',
        self::PUBLISH_NO_MODEL => '問卷中模型已被刪除，請重新選擇問卷',
        self::PUBLISH_NO_DIMENSION => '問卷中能力緯度已被刪除，請重新選擇問卷',
        self::PUBLISH_NO_ELEMENT => '問卷中能力要素已被刪除，請重新選擇問卷',
        self::PUBLISH_NO_QUESTION => '問卷中暫無試題，請重新選擇問卷',

        self::EMPLOYEE_HAVE_LOCKED => '賬戶被鎖定，請聯系管理員',
        self::EMPLOYEE_NO_EXISTS => '員工編號已存在',
        self::USER_INVALID_NEW_PWD => '密碼格式不正確，請檢查密碼要求',
        self::USER_PWD_NEW_SAME_OLD => '新密碼不能和舊密碼相同',
        self::USER_USR_ERROR_DEFAULT => '未知錯誤',
        self::USER_CAPTCHA_IMAGE_INVALID => '圖形驗證碼已過期或填寫錯誤',
        self::USER_CAPTCHA_SMS_INVALID => '錯誤的短信驗證碼',
        self::USER_PHONE_INVALID => 'Phone number is invalid',
        self::USER_ACCOUNT_NOT_FOUND => 'No account found',
        self::USER_LOGIN_FAIL => '登錄失敗',
        self::USER_QR_LOGIN_FAIL => 'Scan code login failed, please refresh the retry or select other login',
        self::USER_QR_LOGIN_TIMEOUT => 'QR code has expired, please refresh the QR code to re-scan',
        self::USER_PWD_ERROR => '用戶密碼錯誤',
        self::USER_LOGIN_FAIL_TOO_MANY => '重試次數過多',
        self::USER_NOT_FOUND => '該用戶不存在',
        self::USER_EXISTS_IN_COMPANY => '用戶已經在公司裏面了',
        self::USER_INVALID_OLD_PASSWORD => '無效的舊密碼',
        self::USER_CREATE_ERROR => 'create a user fail',
        self::USER_SMS_CAPTCHA_FREQUENCY => '發送驗證碼過於頻繁',
        self::USER_INVALID_USERNAME => '非法的用戶名',
        self::USER_LEAVE_OFFICE => '員工已離職',
        self::USER_SMS_TIMEOUT => '短信驗證碼超時',
        self::USER_SMS_INVALID => '無效的短信驗證碼',
        self::MOBILE_EXIST => '手機號已存在',

        self::USER_2FA_BOUND => '2FA已綁定過了',
        self::USER_2FA_DISBLED => '',
        self::USER_2FA_MOBILE_NOT_MATCH => '錯誤的手機號碼',
        self::USER_2FA_MOBILE_CAPTCHA_NOT_MATCH => '錯誤的簡訊驗證碼',
        self::USER_2FA_MOBILE_INVALID_TOKEN => '請求已超時，請重新登入',

        self::QUESTION_BANK_EXISTS => '題庫標題已存在',
        self::QUESTION_IMPORT_TEMPLETE => '錶頭不符,請重新下載模闆',
        self::QUESTION_EXISTS => '題目已存在',
        self::QUESTION_COYE_FAIL => '題復制失敗',
        self::PAPER_EXISTS => '試卷的標題已存在',
        self::EXAM_EXISTS => '考試名稱已存在',
        self::EXAM_END => '考試已結束',
        self::EXAM_COYE_FAIL => '復制考試失敗',
        self::EXAM_EMPLOYEE_END => '員工考試已結束',
        self::EXAM_DETAIL_FAIL => '獲取考試詳情失敗',
        self::EXAM_DIR_NOT_FOUND => '獲取考試目錄失敗',
        self::SYSTEM_EXAM_DIR_CANNOT_DELETE => "默認的考試目錄不能被刪除",
        self::EXAM_DIR_EXISTS_CHILD => '此目錄有子目錄,不能刪除,請先刪除子目錄',
        self::EXAM_USERNAME_EXIST => '手機號或郵箱有誤',
        self::EXAM_DIR_EXISTS_BANK => '此目錄有題庫,不能刪除,請先刪除題庫',
        self::EXAM_DIR_EXISTS_PAPER => '此目錄有試卷,不能刪除,請先刪除試題',
        self::EXAM_NEED_LOGIN => '該考試需要登錄',
        self::EXAM_EMPLOYEE_TEMPLATE => '錶頭不符,請重新下載模闆',
        self::EXAM_MOBILE_NOT_EXIST => '手機號不存在',
        self::EXAM_REDIS_NO_DATE => 'redis沒有考生的答案',
        self::EXAM_STUDENT_OUT_TIME => '很抱歉，當前時間不在考試範圍內!',
        self::EXAM_MOCK_DIR_HAS_EXAM => '此目錄有考試,不能刪除,請先刪除考試',
        self::EXAM_NOTIFY_UNPUBLISHED => '考試未發佈，不允許發送通知',
        self::EXAM_NOTIFY_END => '考試已結束，不允許發送通知',
        self::EXAM_NOT_EXIST => '考試不存在',

        self::LEARNING_PLAN_NAME_EXIST => '學習計劃名稱已存在',
        self::LEARNING_NO_EXIST => '編號被佔用！',
        self::LEARNING_DURATION_TO_LONG => '時長太長了！',
        self::LEARNING_BREAKTHROUGH_NAME_EXIST => '闖關名稱已存在',
        self::LEARNING_CATEGORY_DELETE_CONTAINS => '分類下有闖關，請先刪除闖關',
        self::LEARNING_PLAN_NO_PERMISSION => '沒有權限',
        self::LEARNING_LEARNER_OVERSTEP => '報名人數已達上限',
        self::LEARNING_LEARNER_ALREADY_EXIST => '該學員已存在',
        self::LEARNING_PLAN_NO_MORE_GROUP => '該智能班級沒有更多分組了',
        self::LEARNING_PLAN_NOT_PUBLISHED => '學習計劃未發佈',
        self::LEARNING_CLASS_NOT_PUBLISHED => '班級未發佈',
        self::LEARNING_PACK_NOT_PUBLISHED => '學習包未發佈',
        self::LEARNING_PACK_SETTINGS_CREDIT => '學習包學分獎勵超過限製',
        self::LERN_ENROLL_POSITION_NOT_PASSED => '崗位不滿足，不允許報名',
        self::LERN_ENROLL_OFFLINE_NOT_PASSED => '授課數量不滿足，不允許報名',
        self::LERN_ENROLL_NOT_LECTURER => '不是講師，不允許報名',
        self::LEARNING_UN_EXISTS => '很抱歉，項目不存在！',
        self::LEARNING_LEARNER_UNDER_REVIEW => '審核中',
        self::LEARNING_TASK_OBLIGATORY => '請先添加學習內容',
        self::LEARNING_TEACHING_TEMPLATE_USED => '帶教模闆已被使用，無法刪除',
        self::LEARNING_TEACHING_ALREADY_STARTED => '帶教已開始',
        self::LEARNING_TEACHING_PROJECT_HAS_LEANRER => '帶教項目下存在帶教關系，無法刪除',
        self::LEARNING_TEACHING_PROJECT_NO_EDIT => '非草稿的帶教不允許修改',
        self::LEARNING_TEACHING_TEACHING_OVER_NUM => '導師帶教數量超過限制，請先結束其它帶教',
        self::LEARNING_TEACHING_ON_ONE => '該帶教模板學員只能參與一次',
        self::LEARNING_TASK_EXISTS => '任務已存在',
        self::LEARNING_TASK_ASSIGNING => '任務分配中，請稍後再試',
        self::LEARNING_APPRAISER_NO_CERTIFICATE => '被鑒定人暫未獲得相關證書！',
        self::LEARNING_TEACHER_NO_CERTIFICATE => '鑒定人暫未獲得相關證書！',
        self::LEARNING_PACK_NOT_FOUND => '學習包不存在',
        self::LEARNING_INTERACTION_NOT_EXISTS_ERROR => '互動不存在',
        self::LEARNING_SIMPLE_NO_OFFLINE => '請先添加面授課再發布。',
        self::LEARNING_PLAN_ACTIVITY_NOT_FOUND => '活動不存在',
        self::LEARNING_PLAN_ACTIVITY_NOT_STARTED => '活動未開始',
        self::LEARNING_PLAN_ACTIVITY_NO_AUTH => '無權限簽到該活動',
        self::LEARNING_NO_OPERATION_AUTH => '無權限',
        self::LEARNING_PLAN_NO_EXISTS => '學習模塊兒不存在',
        self::LEARNING_PLAN_NO_VISIT_AUTH => '無訪問權限',
        self::LEARNING_PLAN_IS_RELATED_PROJECT => '該項目已經執行！',
        self::LEARNING_BREAKTHROUGH_OCCUPIED => '該闖關被佔用！',
        self::LEARNING_BREAKTHROUGH_CAG_HAVE_BREAKTHROUGH => '該分類下有闖關，不允許刪除！',
        self::LEARNING_APPLICATION_NON_START => '報名未開始',
        self::LEARNING_APPLICATION_ALREADY_OVER => '報名已結束',
        self::LERN_ENROLL_SCORE_NOT_SUBSTANDARD => '學分未達標，不允許報名！',
        self::LERN_ENROLL_UNCERTIFIED => '未獲得相應證書，不允許報名！',
        self::LERN_ENROLL_EXAM_NOT_PASSED => '未通過相應考試，不允許報名！',
        self::LERN_ENROLL_NOT_ALLOW_CANCEL => '該班級不允許取消報名！',
        self::LERN_ENROLL_CANCEL_TIME_CUT_OFF => '取消報名時間已截止！',
        self::LERN_ENROLL_DELEGATE_TOP => '達到項目人數上限！',
        self::LERN_ENROLL_DELEGATE_CLOSE => '代報名未開啟！',
        self::LERN_DELEGATE_IS_EXIST => '新增條件與已有條件沖突！',
        self::LEARNING_PACK_END => '學習包已結束！',
        self::LEARNING_PACK_UN_ENABLED => '學習包已禁用！',
        self::LEARNER_NOT_ZERO => '已添加學員，不允許刪除！',
        self::LERN_DELEGATE_DELEGATE_NO_EXIST => '相同負責人，只可以添加已設置的部門！',
        self::LEARNING_PLAN_LEARNER_ALREADY_SIGNED => '請勿重復簽到',
        self::LEARNING_APPLICATION_NOT_ALLOWED => '班級未開放報名',
        self::LEARNING_PLAN_NO_AUTH => '無權限',
        self::LEARNING_PLAN_INVALID_QR_CODE => '無效二維碼',
        self::LEARNING_PLAN_ALREADY_ENDED => '班級已結束',
        self::LEARNING_CLASS_SIGN_NOT_START => '簽到未開始',
        self::LEARNING_CLASS_SIGN_ENDED => '簽到已結束',
        self::LEARNING_CLASS_SIGN_LEARNER_SIGNED => '已簽到',
        self::LEARNING_PLAN_SIGN_NOT_PUBLISHED => '班級未發佈',
        self::LEARNING_PLAN_SIGN_NO_AUTH => '您還未加入該班級，暫無法簽到',
        self::LEARNING_PLAN_ENDED_SIGN => '班級已結束',
        self::LEARNING_PACK_SIGN_NO_AUTH => '您還未加入該學習包，暫無法簽到',
        self::LEARNING_PLAN_SIGN_INVALID_QR_CODE => '無效二維碼',
        self::LEARNING_PLAN_SIGN_OVER_DISTANCE => '您所在的位置不在簽到範圍內，暫無法簽到',
        self::LEARNING_PLAN_SIGN_CLOSED_GPS => '沒有獲取到地理位置信息，請檢查是否打開定位',
        self::LERN_MAP_TAGGING_FINISHED_UNCERTIFIED => '獲得證書條件尚未滿足，無法標記完成',
        self::LERN_MAP_TAGGING_FINISHED_NOT_AUTH => '無權限，該任務由管理員標記完成',
        self::LERN_MAP_TAGGING_FINISHED_CLASS_INCOMPLETE => '該班級完成率未達到100%，無法標記完成',
        self::LEARNING_QUEUE_EXISTS => '處理中，請稍後',
        self::LERN_PACK_DISABLED => '該學習包已被禁用，請稍後再試！',
        self::LERN_PASS_DISABLED => '該闖關已被禁用，請稍後再試！',
        self::LERN_OPERATE_NOT_ALLOWED => '維護中，請到管理後臺進行操作！',
        self::LEARNING_PLAN_NO_SIGNS => '暫無簽到！',
        self::OFFLINE_TEACHING_SIGN_TIME_OUT => '二維碼失效！',
        self::LERN_CLASS_NO_VISIT_AUTH => '您還未加入該班級！',
        self::LERN_PLAN_NO_VISIT_AUTH => '您還未加入該學習計劃！',
        self::LERN_PACK_NO_VISIT_AUTH => '您還未加入該學習包！',
        self::LERN_PASS_NO_VISIT_AUTH => '您還未加入該闖關！',
        self::LERN_ADD_LEARNER_ON_GOING => '操作頻繁，請稍後重試！',
        self::LERN_PASS_UNPUBLISHED => '闖關未發佈',
        self::LERN_PASS_NOT_EXISTS => '闖關不存在',
        self::LERN_PASS_NOT_AUTH => '您無權限參與該闖關',

        self::LERN_PRO_NOT_ALLOW_LEARNER_IN_MULTI_CLASS => '該項目不允許同一個人報名多個班級',
        self::LERN_PRO_NOT_ALLOW_LEARNER_SHIFT => '該項目不允許學員自主調班',
        self::LERN_OVERSTEP_SHIFT_CLASS_TIME => '超出調班時間，請選擇其它班級',

        self::KNOWLEDGE_NOT_EXISTS_ERROR => '知識不存在',
        self::DIRECTORY_NAME_EXISTS_ERROR => '目錄名已經存在',
        self::DIRECTORY_NOT_EXISTS_ERROR => '目錄不存在',
        self::DIRECTORY_LEVEL_LIMIT => '不能在此目錄級別上創建目錄',
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_KNOW_ERROR => '目錄庫裏有知識時不能刪除哦,請先刪除目錄庫裏的知識',
        self::DIRECTORY_EXISTS_CHILD_ERROR => '此目錄有子目錄,不能刪除,請先刪除子目錄哦',
        self::CONTENT_IS_NOT_EXISTS_ERROR => '此內容不存在',
        self::DIRECTORY_COURSE_NOT_EXISTS_ERROR => '課程不存在',
        self::DIRECTORY_HAS_CHILD_ERROR => '此目錄有子目錄,不能移動目錄',
        self::KNOWLEDGE_NOT_HAVE_AUTH_ERROR => '暫無查看權限',
        self::KNOWLEDGE_HAS_USE => '此知識已在任務中使用,不能刪除',
        self::ORG_NOT_FIND_IN_KNOWLEDGE => '此公司暫未開通微問功能',
        self::USER_NOT_PERMISSION => '抱歉,妳沒有訪問此知識的權限!',
        self::KNOWLEDGE_TOKEN_ERROR => 'Token值錯誤!',
        self::COURSE_IS_NOT_COMPANY => '此課程不是公司自建課程,不能設置公共的課',
        self::COURSE_TYPE_IS_NOT_ALLOWED => '直播課不能設置為公共課',
        self::ROOT_DIRECTORY_CANNOT_DELETE_ERROR => '默認的課程目錄不能被刪除',
        self::DIRECTORY_LEVEL_MAX_LIMIT => '目录层级最多不超过5级',
        self::DIRECTORY_PARENT_NOT_CHILD => '本目录的下级目录不能作为上级目录',

        self::COURSE_NOT_EXIST => '該課程不存在',
        self::COURSE_IS_SELF => '不能收藏自己創建的課程哦',
        self::COURSE_HAS_FOLLOWED => '妳已收藏了該課程',
        self::COURSE_HAS_USED_USER => '指定的用戶已有此課程',
        self::COURSE_EXIST_IN_GROUP => '該課程已存在',
        self::SERIES_GROUP_ORDER_EXISTS => '排序值已存在',
        self::IMG_LIMIT_ERROR => '圖片大小超過限制',
        self::FILE_LIMIT_ERROR => '文件大小超過限制',
        self::FILE_READ_FAIL => '無法讀取文件，請按要求上傳',
        self::UPLOAD_FILE_FAIL => '上傳文件失敗',
        self::SECURITY_RULE_INVALID_IP_CONFIG => '錯誤IP白名單配置',
        self::IMG_SIZE_LIMIT_ERROR => '圖片尺寸超過限制',

        self::POSITION_ERROR_UNDEFINED => '未知的崗位錯誤',
        self::POSITION_NOT_FOUND => '崗位不存在',
        self::POSITION_NUMBER_OCCUPIED => '崗位編號已被佔用',
        self::POSITION_CATEGORY_DELETE_CONTAINS => '分組裏存在崗位,無法刪除',
        self::POSITION_CATEGORY_NOT_FOUND => '崗位分組不存在',
        self::POSITION_EMPLOYEE_USED => '崗位被使用',
        self::POSITION_TARGET_INCLUDE_SELF => '目標崗位不能是自身',

        self::MEDAL_SCORE_EXIST => '勛章分數已存在',
        self::MEDAL_NAME_EXIST => '勛章名稱已存在',
        self::BANNER_SORT_EXIST => '優先級已存在',
        self::BANNER_TOTAL_NUM => '輪播圖已達最大數量',
        self::MEDAL_SCORE_INSUFFICIENT => '學分不足',
        self::NOT_AUTH_DEPT => '此部門沒有設置權限',
        self::NOT_REPEAT_DEPT => '此部門已設置，不能重復添加',

        self::ORDER_COURSE_ERROR => '訂單裏的課程數據拼裝錯誤',
        self::ORDER_ACCREDIT_ERROR => '訂單授權失敗',
        self::ORDER_PAY_REFUND => '訂單轉入退款',
        self::ORDER_PAY_NOTPAY => '訂單未支付',
        self::ORDER_PAY_CLOSED => '訂單已關閉',
        self::ORDER_PAY_REVOKED => '訂單已撤銷（刷卡支付）',
        self::ORDER_PAY_USERPAYING => '訂單用戶支付中 ',
        self::ORDER_PAY_PAYERROR => '訂單支付失敗',
        self::ORDER_COURSE_EXIST => '您加入的免費課，或加密課已存在',

        self::DEPT_UNDEFINED_ERROR => '未知的部門錯誤',
        self::DEPT_NOT_FOUND => '部門不存在',
        self::DEPT_NON_GROUP_DENY_CHILD => '不能在未分組下創建下級部門',
        self::DEPT_DUPLICATED_IN_BRANCH => '當前節點部門已存在',
        self::DEPT_DENY_CHILD => '不能在該部門下創建下級部門',
        self::DEPT_NAME_EDIT_DISABLED => '該部門名稱禁止編輯',
        self::DEPT_EDIT_DISABLED => '該部門禁止編輯',
        self::DEPT_EMPLOYEE_EXISTS => '該部門存在員工，無法執行操作',
        self::DEPT_NO_EXISTS => '部門編號已存在',
        self::DEPT_PARENT_NOT_FOUND => '上級部門不存在',

        self::EMPLOYEE_UNDEFINED_ERROR => '未知的錯誤',
        self::EMPLOYEE_NOT_FOUND => '員工不存在',
        self::EMPLOYEE_DISPLAY_OCCUPIED => '姓名已被佔用',
        self::EMPLOYEE_NUMBER_EXISTS => '員工編號已被佔用',
        self::EMPLOYEE_NOT_FOUND_OR_DISABLED => '用戶不存在或者被禁用',
        self::EMPLOYEE_LIMIT_EXCEEDS => '員工數量已達上限',
        self::EMPLOYEE_MOBILE_OCCUPIED => '手機號已被使用',
        self::EMPLOYEE_EMAIL_CAPTCHA_INVALID => '無效的郵箱驗證碼',
        self::EMPLOYEE_EMAIL_OCCUPIED => '該郵箱已被使用',
        self::EMPLOYEE_IMPORT_TEMPLATE_INVALID => '無效的導入模板',

        self::ACTIVITY_NAME_EXIST => '活動名稱已存在',
        self::EMPLOEE_NO_AUTH => '您不是該公司員工',
        self::EMPLOEE_NOT_EXIST => '員工不在系統中',
        self::EXPIRY_TIME_CAN_NOT_EMPTY => '報名截止日期必填',
        self::EXCEEDING_LIMIT => '活動人員超過活動最大人數',
        self::END_TIME_WRONG => '結束時間要大於開始時間',
        self::EXPIRY_TIME_WRONG => '報名截止日期要小於等於活動結束日期',

        self::COURSE_NOT_ALLOW_REMOVE => '課程結束不滿7天，不允許刪除/下架',
        self::COURSE_NOT_OVER => '課程還未結束',
        self::COURSE_IS_OVER => '課程已結束',
        self::COURSE_NOT_AUTH_VIEW => '無權限查看課程',
        self::COURSE_UPLOAD_AUDIO_ERROR => '上傳音頻文件失敗',
        self::COURSE_AUDIO_EMPTY => '請生成音頻文件',
        self::COURSE_HAS_USED => '課程正在被使用，不允許刪除',
        self::COURSE_NOT_AUTH => '暫無查看權限',
        self::COURSE_NO_EXISTS => '課程不存在',

        self::FAVORITE_HAS_EXISTS_ERROR => '已經收藏此內容',
        self::FAVORITE_NO_EXISTS_ERROR => '妳還沒有收藏此內容,無法取消收藏',
        self::COMMENT_NOT_EXISTS_ERROR => '評論不存在',
        self::EMPTY_MISTAKE_QUESTION => '暫無錯題',
        self::COMMENT_NOT_ROLE_ERROR => '評論只能管理員和本人刪除',

        self::SIGN_DAILY_SIGNED => '今天已簽到',
        self::PK_CREATE_ERROR => 'PK創建失敗',
        self::PK_DETAIL_ERROR => 'PK詳情獲取失敗',
        // self::PK_DETAIL_ERROR => 'PK保存失敗',
        self::VOTE_TOPIC_EXIST => '投票主題已存在',
        self::VOTE_NO_PERMISSIONS => '非成員不能參加投票',

        self::REPLY_EXIST => '已有回復,不能刪除',
        self::NOT_ISSUE_CREATOR => '非問題創建者,不能操作',
        self::NOT_REPLY_CREATOR => '非回答創建者,不能操作',
        self::SURVEY_TITLE_EXIST => '調研的標題已存在',
        self::SURVEY_NO_PERMISSIONS => '非成員不能參加調研',
        self::TEAM_USED => '該團隊下有知識不能刪除',
        self::TEAM_NAME_EXIST => '團隊名稱不能重復',
        self::SURVEY_NOT_ENABLED => '調研已禁用',
        self::SURVEY_NOT_START => '調研未開始',
        self::SURVEY_IS_OVER => '調研已結束',

        self::LIEVROOM_NOT_FOUND => '直播間不存在',
        self::QUESTION_NOT_RECOGNIZE => '不能識別',
        self::VENDOR_OLD_PASSWORD_WRONG => '供應商原密碼錯誤',
        self::VENDOR_NEW_PASSWORD_WRONG => '新密碼不能與原密碼相同',

        self::COURSE_REPOSITORY_HAS_USED => '課程正在被使用,不能移出課程庫',
        self::COURSE_REPOSITORY_HAS_USED_BANNER => '課程被推薦或者輪播圖使用,不能移出',
        self::COURSE_REPOSITORY_CANNOT_REMOVE => '非超級管理員不能移除課程',
        self::COURSE_CONSUMER_POINT_NOT_ENOUGH => '積分不夠',
        self::TASK_TITLE_EXIST => '作業名稱已存在',

        self::TRAINING_PLAN_EXIST => '培訓計劃名稱已存在',
        self::TRAINING_TASK_GROUP_EXIST => '分組名稱已存在',
        self::TRAINING_PROJECT_PUSH_FAULT => '審批提交失敗',
        self::TRAINING_PROJECT_HAS_PUSH => '已提交審批',

        self::HEADLINE_NO_ASSESS => '無操作權限',
        self::HEADLINE_NO_OPEN => '功能被禁用',
        self::PERMISSION_ROLE_EXIST => '角色名稱已存在',
        self::PERMISSION_ROLE_FUNCTION_EMPTY => '功能權限不能為空',

        self::QUEUE_EXISTS => '任務正在執行，請稍後再試',

        self::DEMO_ACCOUNT_TIMEOUT => '試用賬號到期',
        self::DEMO_ACCOUNT_NO_TRIAL => '試用賬號開通中',

        self::LHA_OP_ERROR => '該申請已通過或已拒絕',
        self::INTEGRAL_ORDER_FAIL => '積分或庫存不足',
        self::INTEGRAL_PRODUCT_EXISTS => '商品名稱已存在',

        self::KNOWLEDGE_POINT_NAME_HAS_EXISTS => '知識點名稱已存在',
        self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => '知識點不存在',

        self::LOGIN_NEED_ACCOUNT_CODE => '缺少公司編號',
        self::LOGIN_INVALID_ACCOUNT_CODE => '無效公司編號',
        self::USER_RESET_PASSWORD_EMAILS_ERROR => '此郵箱對應多個賬戶,不能使用找回',
        self::LOGIN_USER_MOBILE_NOT_BINDING => '手機號未綁定，無法登錄',
        self::LOGIN_MOBILE_USED_MANY => '該手機號被多人使用，無法登錄',
        self::LOGIN_IP_BLOCKED => 'IP已被阻止',

        self::ASSESSMENT_TOPIC_EXIST => '評估名稱已存在',
        self::ASSESSMENT_NO_PERMISSIONS => '無權限創建評估',
        self::ASSESSMENT_PARTAKE_NO_PERMISSIONS => '抱歉,您沒有參與此評估的權限!',
        self::ASSESSMENT_END => '抱歉,評估已結束',

        self::OFFLINE_TEACHING_NAME_EXIST => '該名稱的面授課已存在',
        self::OFFLINE_TEACHING_USED => '該課已被智能班級使用，不能刪除',
        self::OFFLINE_TEACHING_RECORD_CANT_DELETE => '該記錄已經審核通過，不能刪除',

        self::COURSE_HAVE_ESTIMATE => '妳已經評價過了,不能再評論了哦',
        self::COURSE_NO_PERMISSION => '無操作權限',

        // self::KNOWLEDGE_POINT_NOT_EXISTS_ERROR => '知識點不存在',

        self::PLATFORM_NOT_SETTING_DING => '第三方平臺未綁定釘釘',
        self::PRODUCT_NOT_ENOUGH => '禮物數量不足',

        self::BASE_OBJECT_THUMBED_UP => '該對象已經被點贊過了',
        self::BASE_OBJECT_CATEGORY_NOT_FOUND => '分組不存在',
        self::BASE_OBJECT_CATEGORY_USED => '分組已經被使用',

        self::CIRCLE_APPLICATION_FAULT => '已經加入該圈子，不能重復加入',
        self::CIRCLE_TOPIC_EXISTS => '話題名稱不可重復',
        self::CIRCLE_IS_USED => '問答圈已佔用，不可刪除',
        self::CIRCLE_APPROVAL_LIMIT => '批量審核數量超過限制，請重新選擇',
        self::CIRCLE_APPROVAL_HAD => '有審核已完成的數據，請重新選擇',

        self::GAME_UNDEFINED => '未知錯誤',
        self::GAME_BEYOND_ATTEMPT => '超過了嘗試次數',
        self::GAME_WON_ALREADY => '您已經中過獎了',
        self::GAME_PRIZE_DEPLETED => '已無獎品',
        self::GAME_NOT_ENABLED => '遊戲未啟用',
        self::GAME_NOT_START => '遊戲未開始',
        self::GAME_OVER => '遊戲已結束',
        self::GAME_NOT_OPEN => '開獎未開始',
        self::GAME_PEOPLE_NUM_NOT_ENOUGH => '開獎人數不夠',
        self::GAME_NUMBER_EXISTS => '競賽編號已存在',
        self::GAME_DUMMY_FREQUENT => '網絡系統繁忙,請稍後再試',
        self::GAME_INVAID_PARTICIPANT => '無效的參與者',
        self::GAME_OP_FREQUENT => '操作過於頻繁，請稍候再試',

        self::SYNC_ERROR_DATA_FORM_ERROR => '請求的數據格式不對,請檢查數據格式',

        self::FUNDING_IS_JOIN => '已參與',
        self::FUNDING_IS_APPLY => '已報名',

        self::COIN_NOT_SUFFICIENT_FUNDS => '金幣余額不足',
        self::COURSE_CATEGORY_NAME_EXISTS => '課程分類名稱已存在',
        self::COURSE_CATEGORY_HAS_USED => '課程分類正在被使用',
        self::SKILLED_CATEGORY_NAME_EXISTS => '名稱已存在',
        self::SKILLED_CATEGORY_HAS_USED => '此擅長類別正在被使用',

        self::OFFLINE_ASSESSMENT_USED => '鑒定已開始',
        self::OFFLINE_ASSESSMENT_TEMPLATE_USED => '鑒定模闆已經開始使用，不能刪除',
        self::OFFLINE_ASSESSMENT_REACH_RE_NUM => '可重復考核的次數已用完',
        self::OFFLINE_ASSESSMENT_CANT_RE => '該考核不可重復考核',
        self::OFFLINE_ASSESSMENT_NO_ACL => '暫無操作權限，請聯系管理員',

        self::SMS_CAPTCHA_SMS_INVALID => '短信驗證碼有誤',
        self::SMS_CAPTCHA_SMS_EXPIRED => '短信驗證碼已過期',
        self::SMS_LIMIT_EXCEEDS => '驗證碼未失效',

        self::LEARNING_PROJECT_NO_EXISTS => '項目編號已存在',

        self::LEARNING_SIGN_INVALID => '無效的簽到',
        self::LEARNING_SIGN_NONSUPPORT_CODE => '該簽到不支持簽到碼簽到',
        self::LEARNING_SIGN_CODE_ERROR => '簽到碼錯誤',
        self::LERN_SIGN_UNAUTHORIZED_PARTICIPATION => '無權限',
        self::LERN_SIGN_PASSWORD_ERROR => '密碼錯誤',

        self::LIVE_INVALID => '無效的直播',
        self::LIVE_NOT_FOUND => '直播不存在',
        self::LIVE_NO_PERMISSION => '無權限',
        self::LIVE_ROOM_NOT_FOUND => '直播間不存在',
        self::LIVE_MEMBER_IS_EXISTS => '已存在',
        self::LIVE_MEMBER_IS_NULL => '您選擇的人員為空',
        self::LIVE_APPROVED_EXISTS => '已存在上麥人員',
        self::LIVE_LECTURER_NOT_REQUEST => '未發起上麥操作',
        self::LIVE_LECTURER_NOT_APPROVED => '未被允許上麥',
        self::LIVE_LECTURER_APPROVED_ALREADY => '已允許上麥',
        self::LIVE_COMPERE_IN_LECTURERS => '主持人不可以設置為講師',

        self::TRAINING_PROGRAM_UN_EXISTS => '培訓大綱不存在',
        self::TRAINING_PROGRAM_NO_EXISTS => '編號已存在',

        self::LECTURER_LEVEL_STANDARD_MUST_SET => '講師評級指標至少設置一項',
        self::LECTURER_INSIDE_IS_EXISTS => '該員工已經是講師',
        self::LECTURER_INSIDE_TYPE_ERROR => '內部講師格式錯誤',
        self::LECTURER_NUMBER_REPEAT => '講師編號已存在',
        self::LECTURER_ORDER_AUDITOR => '預約已被審核',
        self::LECTURER_DATE_ORDERED => '講師時間範圍已被預約',
        self::LECTURER_DATE_DISENABLED => '講師時間段不可預約',
        self::LECTURER_PROJECT_REPEAT => '認證項目已有編號',
        self::LECTURER_PROJECT_UNEXISTS => '認證項目不存在',
        self::LECTURER_PROJECT_ALREADY_ENDED => '認證項目已結束',
        self::LECTURER_PROJECT_APPLICATION_NOT_ALLOWED => '認證項目未開放報名',
        self::LECTURER_PROJECT_NO_VISIT_AUTH => '無權限報名',
        self::LECTURER_PROJECT_LEARNER_ALREADY_EXIST => '成員已存在',
        self::LECTURER_PROJECT_LEARNER_UNDER_REVIEW => '成員審核中',
        self::LECTURER_PROJECT_LEARNER_OVERSTEP => '報名人數上限',

        self::JOBLEVEL_NOT_FOUND => '職級不存在',
        self::JOBLEVEL_NO_EXISTS => '職級編號已存在',
        self::JOBLEVEL_NAME_EXISTS => '職級名稱已存在',
        self::JOBLEVEL_USED => '職級已被使用',
        self::JOBLEVEL_ORDER_EXISTS => '職級排序已存在',

        self::QUE_EXISTS => '任務正在執行，請稍後再試',

        self::EMP_GRP_NOT_FOUND => '人群不存在',
        self::EMP_GRP_USED => '當前人群下有人員，不允許删除',
        self::EMP_GRP_NOT_DYNAMIC => '該人群不是動態人群',

        self::OFFLINE_ASSESSMENT_MUST_NUM_MORE => '通過規則中的必過題數多於實際必過題數',
        self::EXAM_DATA_PROCESSING => '試題數據處理中',
        self::EXAM_APPROVE_NOT_FOUND => '考試批閱不存在',
        self::EXAM_UNFINISH_NOT_FOUND => '您的考試已提交',
        self::EXAM_MARKING => '批閱中',

        self::CASE_DIRECTORY_IS_EXISTS => '目錄已存在',
        self::CASE_DIRECTORY_NOT_FOUND => '目錄不存在',
        self::CASE_DIRECTORY_PARENT_NOT_FOUND => '父級目錄不存在',
        self::CASE_DIRECTORY_SORT_DIFFERENT_PARENTS => '僅能對具有相同父級的目錄進行排序',
        self::CASE_DIRECTORY_GT_MAX_LEVEL => '目錄僅支持3級',
        self::CASE_DIRECTORY_HAVE_CHILD => '該目錄擁有子集',
        self::CASE_ATTACHMENT_IS_NECESSARY => '您使用的模闆，附件為必傳項',
        self::CASE_ATTACHMENT_IS_OVERFLOW => '上傳附件數量已達上限，無法繼續上傳',
        self::CASE_ATTACHMENT_UNSUPPORTED_FILE_TYPES => '不支持上傳的附件類型',
        self::CASE_STAGE_IS_EXISTS => '已存在的階段名稱',
        self::CASE_TEMPLATE_NOT_FOUND => '模闆不存在',
        self::CASE_TEMPLATE_NO_IS_EXISTS => '模闆編號已存在',
        self::CASE_TEMPLATE_TITLE_IS_EXISTS => '模闆名稱已存在',
        self::CASE_POINT_NAME_HAS_EXISTS => '行業名稱已存在',
        self::CASE_POINT_NOT_EXISTS_ERROR => '行業不存在',

        self::LEARNING_TEMPLATE_NO_GROUP_CANT => '未分組不可以刪除和修改',
        self::LEARNING_TEMPLATE_TITLE_EXISTS => '此分組名稱已存在',
        self::LEARNING_TEMPLATE_TITLE_IS_USED => '分組已經被使用，無法刪除',
        self::EXAM_UNAUTHORIZED_PARTICIPATION => '您無權限參與該考試',
        self::VOTE_UNAUTHORIZED_PARTICIPATION => '您無權限參與該投票',
        self::VOTE_HAVE_CLOSED => '該投票已結束',
        self::VOTE_UN_START => '該投票未开始',
        self::ASSESSMENT_TEMPLETE_USED => '此模闆已被使用，無法刪除',
        self::SURVEY_TEMPLETE_USED => '此模闆已被使用，無法刪除',
        self::ASSESSMENT_TEMPLETE_TITLE_EXIST => '評估模闆名稱已存在',
        self::SURVEY_TEMPLETE_TITLE_EXIST => '調研模闆名稱已存在',
        self::ASSESSMENT_TEMPLETE_NO_EXIST => '評估模闆編號已存在',
        self::SURVEY_RE_NUM_FULL => '重復調研次數已滿',
        self::SURVEY_ANSWER_IS_REPEAT => '不可重復的填空題的答案重復',

        self::SURVEY_NOTIFY_UNPUBLISHED => '調研未發佈，不允許發送通知',
        self::SURVEY_NOTIFY_END => '調研已結束，不允許發送通知',
        self::SURVEY_NEED_LOGIN => '該調研需要登錄',

        self::FACE_MATCHING_SOURCE_EXISTS => '人臉對比模闆已存在',
        self::FACE_MATCHING_DETECT_FAIL => '人臉對比失敗',
        self::FACE_MATCHING_SOURCE_NOT_EXIST => '人臉對比模闆不存在',
        self::FACE_MATCHING_STORAGE_FOLDER_CREATE_FAIL => '無法創建存儲目錄',
        self::FACE_MATCHING_INVALID_FILE_TYPE => '不支持的圖片格式',
        self::FACE_MATCHING_INVALID_FILE => '不支持的文件格式',

        self::APPROVAL_CATEGORY_IS_EXISTS => '分類已存在',
        self::APPROVAL_CATEGORY_IS_USED => '分類已被使用，無法刪除',
        self::APPROVAL_PROCESS_IS_EXISTS => '審批流程已存在',
        self::APPROVAL_LEVEL_IS_EXISTS => '審批層級已存在',
        self::APPROVAL_PROCESS_NOT_ENABLED => '公司無啟用的審批流',
        self::APPROVAL_REVIEW_EMPLOYEE_MUST => '必選選擇審批人',
        self::COURSE_REVIEW_NO_AUTH => '無課程審批權限',

        self::COMPETITION_ROUND_START_ERROR => '輪次開始時間或結束時間不正確',
        self::COMPETITION_CANT_RECEIVE_AWARD => '無權獲得賽季大獎',
        self::COMPETITION_JS_NO_IS_EXISTS => '競賽編號不可重復',
        self::COMPETITION_NOT_IN_VOTE_RANGE => '不在投票範圍內',
        self::COMPETITION_ROUND_IS_END => '本輪次已經結束，不可刪除',
        self::COMPETITION_ROUND_IS_START => '本輪次已經開始，不可修改和刪除',
        self::COMPETITION_APPLY_TIME_ERROR => '報名設置時間錯誤',
        self::COMPETITION_NOT_HAVE_ROUND => '請先添加輪次信息，再發佈',
        self::COMPETITION_NOT_BEGIN => '競賽暫未開始',
        self::COMPETITION_ACHIEVEMENT_GROUP_USED => '此戰隊在對戰組中，請先刪除該對戰隊，再嘗試...',
        self::COMPETITION_ACHIEVEMENT_BATTLE_EXISTS => '該對組戰隊已存在',
        self::COMPETITION_ACHIEVEMENT_HELP_EXISTS => '在該PK中已經助力完成',
        self::COMPETITION_VOTE_EXISTS => '今日已投',
        self::COMPETITION_IS_USED => '競賽被佔用，無法刪除',
        self::COMPETITION_NOTIFY_UNPUBLISHED => '競賽未發佈，不允許發送通知',
        self::COMPETITION_NOTIFY_END => '競賽已結束，不允許發送通知',
        self::COMPETITION_VOTE_NOT_STARTED => '投票未開始',
        self::COMPETITION_VOTE_ALREADY_ENDED => '投票已結束',
        self::COMPETITION_NOT_FOUND => '比賽不存在',
        self::COMPETITION_NO_PERMISSION => '您無權限參與該比賽',

        self::POSITION_COMPETENCY_CATEGORY_EXISTS => '勝任力指標分類已存在',
        self::POSITION_COMPETENCY_CATEGORY_NOT_FOUND => '勝任力指標分類不存在',
        self::POSITION_COMPETENCY_EXISTS => '勝任力指標已存在',
        self::POSITION_COMPETENCY_NOT_FOUND => '勝任力指標不存在或者已被刪除',
        self::POSITION_COMPETENCY_ELEMENT_EXISTS => '能力指標已存在',

        self::POSITION_SKILL_CATEGORY_EXISTS => '技能分類已存在',
        self::POSITION_SKILL_CATEGORY_NOT_FOUND => '技能分類不存在',
        self::POSITION_SKILL_EXISTS => '技能已存在',
        self::POSITION_SKILL_NOT_FOUND => '技能不存在或者已被刪除',
        self::POSITION_SKILL_ELEMENT_EXISTS => '技能已存在',

        self::INSPECTION_ELECTIVE_TASK_UNFINISHED => '您有未完成的任務',
        self::INSPECTION_ELECTIVE_CLASSIFY_UNFINISHED => '您的考核有未完成的分類',
        self::INSPECTOR_IS_NOT => '您不是巡檢員',
        self::INSPECTION_AT_LEAST_ONE => '請至少完成一個考核',

        self::HARMONY_ERROR => '包含敏感信息，無法顯示結果',

        self::RETRAINING_NO_EXISTS => '編號已存在',
        self::RETRAINING_NO_TASKS => '請先添加模闆任務',
        self::RETRAINING_NOT_ALLOWED_REPEAT => '再認證暫未開啟',
        self::RETRAINING_REACH_CYCLE_INDEX => '您的循環認證次數已到',
        self::RETRAINING_TIME_NOT_UP => '再認證時間未到',
        self::RETRAINING_LEARNER_AUTHENTICATE_ONGOING => '您還有進行中的認證，請勿重復認證',
        self::RETRAINING_NOT_EXISTS=>'很抱歉，該認證與再培訓不存在！',
        self::RETRAINING_LEARNER_NOT_PUBLISHED=>'很抱歉，該認證與再培訓暫未對外公開！',
        self::RETRAINING_LEARNER_NOT_AUTH=>'很抱歉，您不在本次認證與再培訓範圍內！',

        self::EXPERIENCE_DETAIL_BEYOND_LIMIT => '您上傳的心得數量已達上限',

        self::PHOTOGRAPH_DETAIL_BEYOND_LIMIT => '您上傳的拍照已達上限',
        self::PHOTOGRAPH_LEARNER_NOT_EXISTS => '學員不在該班級下',
        self::PHOTOGRAPH_LEARNER_SUPPORT_EXISTS => '學員已點過贊',
        self::PHOTOGRAPH_LEARNER_SUPPORT_MAX => '點贊已超過最大限製',

        self::CERTIFICATION_USED => '證書使用中，無法刪除或禁用',
        self::CERTIFICATION_USER_USED => '證書人員無法刪除',
        self::DIRECTORY_PARENT_NOT_SAME_SELF => '父目錄不能為本目錄',
        self::NOT_GROUP_CANNOT_SELECTED => '未分組目錄不能選擇',

        self::EVENT_MEMBER_SIGN_INVALID_CAPTCHA => '無效的短信驗證碼',
        self::EVENT_MEMBER_SIGN_VX_INVALID_ACCESS_TOKEN => '無效的access_token',
        self::EVENT_MEMBER_SIGN_VX_INVALID_PWD => '無效的簽到口令',

        self::GEN_LIVE_CREATE_ERROR => '直播創建失敗',
        self::GEN_LIVE_NOT_EXISTS => '直播不存在',
        self::GEN_LIVE_UPDATE_ERROR => '直播更新失敗',
        self::GEN_LIVE_INVALID_INPUT => '直播審核參數失敗',
        self::GEN_LIVE_MEMBER_NOT_ALLOWED => '無權限查看直播',
        self::COURSE_MULTI_DIRECTORY_LIMIT_ERROR => '副目錄不能超過5個',
        self::GEN_LIVE_GENERATE_TIME => '離上次生成數據時間不超過10分鐘，請稍後再試',
        self::GEN_LIVE_LIMIT_ATTENDEES => '直播人數超過限制，請修改或聯系工作人員',

        self::KNOWLEDGE_BASE_NAME_EXIST => '知識庫名稱已經存在',
        self::KNOWLEDGE_BASE_NOT_EXIST => '知識庫不存在',
        self::KNOWLEDGE_QUESTION_HAS_EXISTS => '此問題在此知識庫下已存在',
        self::KNOWLEDGE_CATEGORY_CANNOT_DELETE => '默認分類不能刪除或編輯',
        self::KNOWLEDGE_CATEGORY_CANNOT_EQ_ROOT_NAME => '分類名稱不能為默認分類',
        self::KNOWLEDGE_CATEGORY_HAS_QUESTION => '此分類下有問題，不能刪除',
        self::KNOWLEDGE_QUESTION_NOT_EXISTS => '知識庫問題不存在',
        self::KNOWLEDGE_CATEGORY_NAME_EQ => '分類名稱沒有變',
        self::KNOWLEDGE_QUESTION_IS_SYSTEM => '此問題為系統復制，您不可以修改哦',
        self::KNOWLEDGE_BASE_HAS_QUESTION => '此知識庫下有問題，不能刪除',

        self::EVENT_PRIZE_IS_GAIN => '該獎品已有獲獎人員，不可刪除',
        self::EVENT_ALLOW_NUM_MORETHAN_EXISTS => '獎品的已獲得人數大於設置數',
        self::EVENT_DESIGATED_IS_HAVED => '獎品已屏蔽中獎人，此人已在他處作弊',
        self::EVENT_DESIGATED_IS_OVERFLOW => '作弊人數大於獎品數量',
        self::EVENT_NOT_START => '活動未開始',
        self::EVENT_END => '活動已結束',

        self::EVENT_MEMBER_SIGNED => '已簽到',
        self::COURSE_HAVE_LIMIT => '課程還未學完，需學完才能評分',
        self::COURSE_TYPE_NOT_EQ => '兩次課件的類型不一樣，請上傳同樣的文件類型',
        self::COURSE_MUST_END => '課程還未學完，需學完才能參與測驗',
        self::EXPORT_LIMIT => '抱歉，您不能導出數據',
        self::COURSE_STAR_LIMIT => '评分超限制',

        // self::CONTRACT_TYPE_USED => '合同類型正在使用',
        // self::EXPORT_LIMIT => '抱歉，您不能導出數據',

        self::INSPECTION_QUESTION_CATEGORY_USED => '分類正在使用，無法刪除',
        self::TASK_NO_PERMISSIONS => '您無權限參與該作業',
        self::TASK_END => '作業已結束，無法參與',
        self::OFFLINEEXERCISE_NO_PERMISSIONS => '您無權限參與該線下練習',
        self::CONTRACT_TYPE_USED => '合同類型正在使用',

        self::GEN_LIVE_CATEGORY_NOT_REMOVE => '分類已使用，不能刪除',


        self::QUESTION_NO_EXISTS => '編號已存在',

        self::SPECIAL_SUBJECT_NO_USED => '編號已被佔用',

        self::EMP_SELF_REG_DATA_INVALID => '錶單數據驗證失敗，請檢查數據',
        self::EMP_SELF_REG_UNIQUE => '錶單數據不唯一',
        self::EMP_SELF_REG_UNIQUE_USERNAME => '用戶名已被使用或者已申請註冊',
        self::EMP_SELF_REG_MOBILE_CAPTCHA_FAIL => '驗證碼驗證失敗',
        self::EMP_SELF_REG_UNIQUE_ID_NUMBER => '您已注册，登入即可',

        self::DAILY_CLOCK_CANT_PUBLISH => '每日打卡開始時間已開始，不可發佈',

        self::TRAINING_CENTER_UNDEFINED => '培訓中心未知錯誤',
        self::TRAINING_CENTER_EXISTS => '培訓中心已存在',
        self::TRAINING_CENTER_NOT_FOUND => '培訓中心不存在',
        self::TRAINING_CENTER_NO_EXISTS => '編號已被使用',
        self::TRAINING_CENTER_MAX_LEVEL => '已達到最大層級',
        self::TRAINING_CENTER_USED => '該培訓中心正被使用中',
        self::TRAINING_CENTER_NOT_LEAF => '該培訓中心包含子培訓中心',
        self::VOTE_NO_REPEAT => '不允許重復投票',
        self::KNOWLEDGE_CONTAIN_AUDIT_IDS => '提交知識不能包含審核中和已通過的',

        self::COURSE_HUNDUN_SIGN_ERROR => '簽名錯誤',
        self::COURSE_HUNDUN_PARAMS_ERROR => '參數錯誤',
        self::COURSE_HUNDUN_NO_AUTH => '暫無查看權限',
        self::COURSE_HUNDUN_TIME_OVERDUE => '請求已過期',
        self::COURSE_HUNDUN_USER_TOKEN_INVALID => '用戶token失效',
        self::COURSE_HUNDUN_DATA_ERROR => '數據錯誤',
        self::COURSE_HUNDUN_CHECK_ERROR => '校驗失敗',
        self::COURSE_HUNDUN_USER_REGISTER_REACH_LIMIT => '註冊賬號已達上限',
        self::COURSE_HUNDUN_USER_REGISTED => '用戶已經註冊過',
        self::COURSE_MODULE_UN_REGISTED => '暫無查看權限',

        self::LPP_NOT_FOUND => '彈題不存在或已刪除',
        self::LPP_CREATE_FAIL => '創建失敗',
        self::LPP_UPDATE_FAIL => '更新失敗',
        self::LPP_TIME_LARGER_DURATION => '時間點大於課程時長',
        self::LPP_TIME_DUPLCATED => '存在時間點重復',
        self::LPP_OPTION_ID_DUPLICATED => '存在重復的選項ID',
        self::LPP_OPTION_INVALID_COUNT => '錯誤的正確答案選項數量',


        self::LIVE_HON_SHAN_TIME_ERROR => '時間需要大於當前時間',
        self::LIVE_HONGSHAN_HAS_END => '直播已結束或會議不存在',

        self::SHORTLINK_INVALID_URL => '無效的鏈接',
        self::TRAINING_TASK_END => '項目已完成',
        self::TRAINING_HAS_USE => '項目已關聯班級',

        self::BI_FIELDS_INVALID => '條件字段有誤',
        self::BI_COLUMNS_INVALID => '展示字段設置有誤',

        self::GZ_WATCH_CARD_NO_OR_DISPLAY_ERROR => '身份證號或姓名錯誤',
        self::KNOWLEDGE_POINT_CATEGORY_EXISTS => '分類名稱已存在',
        self::LIVE_ROLE_ERROR => '角色與直播不匹配',
        self::LIVE_UN_DELAYED => '沒有開通無延遲直播',

        self::NOT_ENOUGH_SCORE => '沒有足夠的積分',
        self::POSITION_GRADING_NO_QUESTION => '暫無試題',

        self::GRADE_SETTING_NAME_EXISTS_ERROR => '等級已存在',
        self::GRADE_SETTING_LIMIT => '最多可添加5個等級',

        self::AI_SCENARIO_NOT_FOUND => '情景模擬不存在',
        self::AI_SCENARIO_NODE_NOT_FOUND => '情景模擬節點不存在或已刪除',
        self::AI_SCENARIO_NOT_PUBLISHED => '情景模擬未發佈',
        self::AI_SCENARIO_COPY_FAIL => '復制失敗，請重試',
        self::AI_SCENARIO_PROCESS_NOT_FOUND => '未設置情景模擬內容',
        self::AI_SCENARIO_PROCESS_NEXT_NODE_NOT_FOUND => '沒有下一題或者已被刪除',
        self::AI_SCENARIO_PROCESS_PREV_NODE_NOT_PASSED => '前題未答，無法獲取下一題',
        self::AI_SCENARIO_PROCESS_NODE_ANSWERED => '該題已經答過了',
        self::AI_SCENARIO_SUBMIT_EXCEPTION => '提交出現異常，請檢查數據或者稍後重試',

        self::GUIDANCE_CLASSIFY_EXISTS => '分類已存在',
        self::GUIDANCE_INSTRUCTIONS_EXISTS => '操作指引已存在',

        self::STAT_FILTER_GROUP_TYPE_NOT_SUPPORT => '該類型人群無法進行過濾',
        self::TIME_RANGE_EXCEEDS_LIMIT=>"時間範圍超過上限",

        self::ENROLL_NOT_EXISTS => "報名活動不存在！",
        self::ENROLL_NOT_PUBLISHED => "報名活動暫未發布！",
        self::ENROLL_LEARNER_HAS_ENROLLED => "您已報名！",
        self::ENROLL_LEARNER_UNDER_EXAMINE => "您已報名，正在審核...",
        self::ENROLL_LEARNER_NOT_SELECT_SESSIONS => "請選擇報名場次！",
        self::ENROLL_SESSIONS_NOT_EXISTS => "報名失敗，您所選擇的報名場次不存在！",
        self::ENROLL_TIME_OVER => "報名失敗，報名時間已結束！",
        self::ENROLL_LEARNER_NUM_REACHED_MAXIMUM_LIMIT => "報名失敗，報名人數已達上限！",
        self::ENROLL_REQUIREMENTS_CREDIT_DISQUALIFIED => "很抱歉，您不滿足報名的學分要求，暫無法報名！",
        self::ENROLL_REQUIREMENTS_CERTIFICATE_DISQUALIFIED => "很抱歉，您不滿足報名的證書要求，暫無法報名！",
        self::ENROLL_REQUIREMENTS_EXAM_DISQUALIFIED => "很抱歉，您未通過報名要求的考試，暫時不能報名！",
        self::ENROLL_TIMES_MULTI_REACHED_MAXIMUM_LIMIT => "報名失敗，您的報名次數已達上限！",
        self::ENROLL_NOT_ALLOWED_CANCEL => "很抱歉，該報名活動不支持取消報名！",
        self::ENROLL_CANCEL_DEADLINE_OVER => "很抱歉，超出報名活動取消截止時間，暫時不能取消報名！",
        self::ENROLL_TIME_NOT_BEGIN => "報名未開始！",
        self::ENROLL_OFFICIAL_NUM_REACHED_MAXIMUM_LIMIT => "審核失敗，報名正式名額已達上限！",
        self::ENROLL_SESSION_IS_OBLIGATORY => "請選擇報名場次！",
        self::ENROLL_SESSION_NOT_ALLOW_ENROLL_MULTI => "報名失敗，該活動不允許多次報名！",
        self::ENROLL_REPLACE_REQUIREMENTS_CREDIT_DISQUALIFIED => "報名失敗，未獲得報名要求的最低學分！",
        self::ENROLL_REPLACE_REQUIREMENTS_CERTIFICATE_DISQUALIFIED => "報名失敗，未獲得報名要求的證書！",
        self::ENROLL_REPLACE_REQUIREMENTS_EXAM_DISQUALIFIED => "報名失敗，未通過報名要求的考試！",

        self::LEARNING_TEACHING_SIGN_NO_OPEN => "帶教未開啓上級簽名",
        self::LEARNING_TEACHING_SIGN_OTHER_EMP => "您不是該帶教的上級",
        self::LEARNING_TEACHING_STUDENT_UNSIGN => "學員未完成簽名",
        self::LEARNING_TEACHING_SIGN_FINISHED => "您已完成簽名",
        self::LEARNING_TEACHING_NOT_END => "帶教未結束",
        self::LEARNING_TEACHING_TUTOR_SIGN_NO_OPEN => "帶教未開啓導師簽名",
        self::LEARNING_TEACHING_SIGN_OTHER_TUTOR => "您不是導師",
        self::LEARNING_TEACHING_STUDENT_SIGN_NO_OPEN => "帶教未開啓學員簽名",
        self::LEARNING_TEACHING_SIGN_OTHER_STUDENT => "您不是學員",
        self::LEARNING_TEACHING_TUTOR_UNSIGN => "導師未完成簽名",
        self::LEARNING_TEACHING_TEACHING_UNSIGN => "上級未完成簽名",
        self::LEARNING_TEACHING_UNSIGN => "存在未簽名的帶教",
        self::TRAINING_TUTORING_LEANER_NO_SIGNATURE_REQUIRED => "無需簽名",
        self::TRAINING_TUTORING_TASK_NOT_SUBMIT => "帶訓任務還未提交，暫時不能簽名",
        self::SCENE_TALK_WEIGHT_SUM_NOT_ALLOWED => "場景對話權重之和需等于100！",
        self::SCENE_KEYWORD_WEIGHT_SUM_NOT_ALLOWED => "答案關鍵詞權重之和需等于100！",

        self::MATERIAL_NOT_EXISTS_ERROR => "素材不存在",
        self::MATERIAL_TYPE_NOT_EQ => "兩次素材的類型不壹樣，請上傳同樣的文件類型",
        self::DIRECTORY_CAN_NOT_REMOVE_HAS_MATERIAL_ERROR => "目錄庫裏有素材時不能刪除哦,請先刪除目錄庫裏的素材",

        self::LANGUAGE_POINTS_NOT_EXISTS_ERROR => "知識點不存在",
        self::LANGUAGE_POINTS_NO_EXISTS => "編號已存在",

        self::TEACHING_MATERIAL_NOT_EXISTS_ERROR => "教材不存在",
        self::TEACHING_MATERIAL_NO_EXISTS => "編號已存在",

        self::VERSION_NO_REDUCIBLE_VERSION => "該版本不是審核通過的版本，不可還原",
        self::VERSION_HAS_REVIEW_VERSION => "還有待審核的版本，不可再新增版本",

        self::OCR_IDCARD_RECOGNIZE_FAIL => '未識別到證件，請上傳清晰的證件照片',

        self::ACTION_ASSESSMENT_NOT_EXISTS => '訓後行動評估不存在',
        self::ACTION_ASSESSMENT_LEARNER_EXISTS => '學員信息已存在',
        self::ACTION_ASSESSMENT_LEARNER_NOT_EXISTS => '學員信息不存在',
        self::ACTION_ITEMS_NOT_REPEAT_SUBMIT => '不能重復提交行動項',
        self::ACTION_ASSESSMENT_NO_REVIEW_PERMISSION => '沒有審核權限',
        self::ACTION_ASSESSMENT_NOT_REPEAT_REVIEW => '不能重復審核',
        self::ACTION_ASSESSMENT_NO_COMMENT_PERMISSION => '沒有評價權限',
        self::ACTION_ASSESSMENT_NOT_REPEAT_COMMENT => '不能重復評價',
        self::COMPETENCY_INDICATOR_NOT_FOUND => '崗位勝任指標不存在',
        self::COMPETENCY_INDICATOR_GROUP_NOT_FOUND => '分組不存在',
        self::COMPETENCY_INDICATOR_SKILL_NOT_FOUND => '技能不存在',
        self::COMPETENCY_INDICATOR_GROUP_EXISTS => '分組已存在',
        self::COMPETENCY_INDICATOR_SKILL_EXISTS => '技能已存在',
    ];
}