stages:
  - prepare
  - build
  - prod
  - clearRoute
  - fpmRestart

build_dev:
  variables:
    CI: "true"
  stage: build
  only:
    - /^release\/\d+$/
  tags:
    - ydzs-dev
  environment:
    name: development
    url: https://el1.talentyun.com
  when: manual
  script:
    - CurDir=`pwd`
    - dayStr=`date "+%y-%m-%d"`
    - DeployDir=/apps/www/pc
    - PHPComposer=/apps/www/composer.phar
    - php ${PHPComposer} config -g repo.packagist composer https://mirrors.aliyun.com/composer/
    - php ${PHPComposer} install
    - rsync -a --exclude public/ --exclude .git/ --exclude .env* --exclude data/ ./ ${DeployDir}/
    - rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo rm -rf /tmp/ydzs/cache/routes/${dayStr}
    - sudo systemctl restart php-fpm

build_dev_wo_composer:
  variables:
    CI: "true"
  stage: build
  only:
    - /^release\/\d+$/
  tags:
    - ydzs-dev
  environment:
    name: development
    url: https://el1.talentyun.com
  when: manual
  script:
    - CurDir=`pwd`
    - dayStr=`date "+%y-%m-%d"`
    - DeployDir=/apps/www/pc
    - rsync -a --exclude public/ --exclude .git/ --exclude .env* --exclude data/ ./ ${DeployDir}/
    - rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo rm -rf /tmp/ydzs/cache/routes/${dayStr}
    - sudo systemctl restart php-fpm

build_cn_pre:
  stage: prepare
  only:
    - master
  tags:
    - ydzs-prod-cn
  environment:
    name: production
    url: https://el.yidianzhishi.com
  when: manual
  script:
    - PHPComposer=/apps/www/composer.phar
    - >
        if [ ! -e "${PHPComposer}" ]; then
            sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            sudo php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            sudo php composer-setup.php
            sudo php -r "unlink('composer-setup.php');"
            sudo mv composer.phar ${PHPComposer}
        fi


cn:
  stage: prod
  only:
    - master
    - /^Branch_tag/
  tags:
    - cn-be
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - Target=root@172.17.4.159:/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cn)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - php ${PHPComposer} install
    - sudo rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* --exclude build --exclude development --exclude docs --exclude server --exclude test ./ ${DeployDir}/
    - sudo rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo chmod -R 777 ${DeployDir}/data/cache/
    - sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/*
    - curl https://el.yidianzhishi.cn/status.php?__clear_route_cache__=1
    - sudo service php70-php-fpm reload
    - rsync -ae 'ssh -p 20022' --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* ./ ydzsadmin@172.17.4.159:/apps/www/weike-pc
    - ssh ydzsadmin@172.17.4.159 -p 20022 "cd /apps/www && sudo bash ./build-ydzs-queue.sh"
    - curl https://el.yidianzhishi.cn/status.php?__clear_route_cache__=1
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cn)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"

cn-NEW:
  stage: prod
  only:
    - master
  tags:
    - cn-be
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - Target=root@172.17.4.159:/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cn)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - php ${PHPComposer} install
    - sudo rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* --exclude build --exclude development --exclude docs --exclude server --exclude test ./ ${DeployDir}/
    - sudo rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo chmod -R 777 ${DeployDir}/data/cache/
    - sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/*
    - curl https://el.yidianzhishi.cn/status.php?__clear_route_cache__=1
    - sudo service php70-php-fpm reload
    - ssh ydzsadmin@172.17.4.159 -p 20022 "cd /apps/www/weike-pc/bin/queue && sudo bash ./stop_queues_all.sh"
    - rsync -ae 'ssh -p 20022' --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* ./ ydzsadmin@172.17.4.159:/apps/www/weike-pc
    - ssh ydzsadmin@172.17.4.159 -p 20022 "cd /apps/www/weike-pc/bin/queue && sudo bash ./run_queues_mq1.prod.sh"
    - rsync -ae 'ssh -p 20022' --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* ./ ydzsadmin@172.17.4.156:/apps/www/weike-pc
    - ssh ydzsadmin@172.17.4.156 -p 20022 "cd /apps/www/weike-pc/bin/queue && sudo bash ./run_queues_mq2.prod.sh"
    - curl https://el.yidianzhishi.cn/status.php?__clear_route_cache__=1
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cn)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"


cn-nomq:
  stage: prod
  only:
    - master
  tags:
    - cn-be
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cn)nomq部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - php ${PHPComposer} install
    - sudo rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* --exclude build --exclude development --exclude docs --exclude server --exclude test ./ ${DeployDir}/
    - sudo rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo chmod -R 777 ${DeployDir}/data/cache/
    - sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/*
    - curl https://el.yidianzhishi.cn/status.php?__clear_route_cache__=1
    - sudo service php70-php-fpm reload
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cn)nomq部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"    

cn_wo_composer:
  stage: prod
  only:
    - master
    - /^Branch_tag/
  tags:
    - cn-be
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - Target=root@172.17.4.159:/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cn)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - sudo rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* --exclude build --exclude development --exclude docs --exclude server --exclude test ./ ${DeployDir}/
    - sudo rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo chmod -R 777 ${DeployDir}/data/cache/
    - sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/*
    - curl https://el.yidianzhishi.cn/status.php?__clear_route_cache__=1
    - sudo service php70-php-fpm reload
    - rsync -ae 'ssh -p 20022' --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* ./ ydzsadmin@172.17.4.159:/apps/www/weike-pc
    - ssh ydzsadmin@172.17.4.159 -p 20022 "cd /apps/www && sudo bash ./build-ydzs-queue.sh"
    - curl https://el.yidianzhishi.cn/status.php?__clear_route_cache__=1
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cn)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"


mq-only:
  stage: prod
  only:
    - master
  tags:
    - cn-be
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - Target=root@172.17.4.159:/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式mq-only部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - php ${PHPComposer} install
    - rsync -ae 'ssh -p 20022' --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* ./ ydzsadmin@172.17.4.159:/apps/www/weike-pc
    - ssh ydzsadmin@172.17.4.159 -p 20022 "cd /apps/www && sudo bash ./build-ydzs-queue.sh"
    - curl https://el.yidianzhishi.cn/status.php?__clear_route_cache__=1
    - |
      msg="${GITLAB_USER_NAME}发起的 正式mq-only部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"

mq-2-test:
  stage: prod
  only:
    - master
  tags:
    - cn-be
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - Target=root@172.17.4.156:/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - php ${PHPComposer} install
    - rsync -ae 'ssh -p 20022' --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* ./ ydzsadmin@172.17.4.156:/apps/www/weike-pc

mq-2-ex:
  stage: prod
  only:
    - master
  tags:
    - cn-be
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - Target=root@172.17.4.156:/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    # - php ${PHPComposer} install
    - rsync -ae 'ssh -p 20022' --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* ./ ydzsadmin@123.56.170.90:/apps/www/weike-pc
    - ssh ydzsadmin@123.56.170.90 -p 20022 "cd ${DeployDir} && sudo chown -R ydzsadmin:ydzsadmin ./ && cd ${DeployDir}/bin/queue && sudo bash run_queues_mq2.prod.sh"

cn-fpm:
  stage: fpmRestart
  only:
    - master
  tags:
    - ydzs-prod-cn
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - sudo service php70-php-fpm restart
#===================================================================================================

# build_staging:
#   stage: prod
#   only:
#     - staging
#     - pre-release/220520
#   tags:
#     - ydzs-prod-cn
#   when: manual
#   script:
#     - CurDir=`pwd`
#     - DeployDir=/apps/www/weike-pc-staging
#     - PHPComposer=/apps/www/composer.phar
#     - php ${PHPComposer} install
#     - sudo rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* --exclude build --exclude development --exclude docs --exclude server -exclude static --exclude test ./ ${DeployDir}/
#     - sudo rsync -a --delete ./apps/ ${DeployDir}/apps/
#     - sudo chmod -R 777 ${DeployDir}/data/cache/

build_staging:
  stage: prod
  only:
    # - staging
    - lgh/240523/feat-mongodb-seconday
  tags:
    - ydzs-prod-cn
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc-staging
    - sudo rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .env* --exclude build --exclude development --exclude docs --exclude server -exclude static --exclude test ./ ${DeployDir}/
    - sudo chmod -R 777 ${DeployDir}/data/cache/

#===================================================================================================

com:
  variables:
    CI: "true"
  stage: prod
  only:
    - master
    - /^Branch_tag/
  tags:
    - com-be
  environment:
    name: production
    url: https://el.yidianzhishi.com
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(com)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - php ${PHPComposer} install
    - rsync -a --exclude public/ --exclude .git/  --exclude .gitlab-ci.yml ./ ${DeployDir}/
    - rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo chmod -R 777 ${DeployDir}/data/cache/
    - sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/*
    # - sudo rm -rf /nfs-aliyun/ydzs/files/cache/cache_routes.*
    - sudo service php74-php-fpm reload
    - ssh ydzsadmin@39.106.33.85 "cd ${DeployDir} && sudo chown -R ydzsadmin:ydzsadmin ./"
    - rsync -a --exclude public/ --exclude .gitlab-ci.yml ./ ydzsadmin@39.106.33.85:${DeployDir}/
    - rsync -a --delete ./apps/ ydzsadmin@39.106.33.85:${DeployDir}/apps/
    - ssh ydzsadmin@39.106.33.85 "sudo chmod -R 777 ${DeployDir}/data/cache/ && sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/* && sudo service php74-php-fpm reload"
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(com)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"    

com_wo_composer:
  variables:
    CI: "true"
  stage: prod
  only:
    - master
    - /^Branch_tag/
  tags:
    - com-be
  environment:
    name: production
    url: https://el.yidianzhishi.com
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(com)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - rsync -a --exclude public/ --exclude .git/  --exclude .gitlab-ci.yml ./ ${DeployDir}/
    - rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo chmod -R 777 ${DeployDir}/data/cache/
    - sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/*
    # - sudo rm -rf /nfs-aliyun/ydzs/files/cache/cache_routes.*
    - sudo service php74-php-fpm reload
    - ssh ydzsadmin@39.106.33.85 "cd ${DeployDir} && sudo chown -R ydzsadmin:ydzsadmin ./"
    - rsync -a --exclude public/ --exclude .gitlab-ci.yml ./ ydzsadmin@39.106.33.85:${DeployDir}/
    - rsync -a --delete ./apps/ ydzsadmin@39.106.33.85:${DeployDir}/apps/
    - ssh ydzsadmin@39.106.33.85 "sudo chmod -R 777 ${DeployDir}/data/cache/ && sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/* && sudo service php74-php-fpm reload"
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(com)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"    


com-fpm:
  stage: fpmRestart
  only:
    - master
  tags:
    - ydzs-prod-com
  environment:
    name: production
    url: https://el.yidianzhishi.cn
  when: manual
  script:
    - sudo service php74-php-fpm restart
    - ssh ydzsadmin@10.28.207.5 "sudo service php74-php-fpm restart"

#=====================================================================================
yaduo:
  variables:
    CI: "true"
  stage: prod
  only:
    - master
  tags:
    - com-be
  environment:
    name: production
    url: https://el.yidianzhishi.com
  when: manual
  script:
    - whoami
    - ifconfig
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(yaduo)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - ssh ydzsadmin@172.17.2.159 "cd ${DeployDir} && sudo chown -R ydzsadmin:ydzsadmin ./"
    - ssh ydzsadmin@172.17.2.161 "cd ${DeployDir} && sudo chown -R ydzsadmin:ydzsadmin ./"
    - rsync -a --exclude .git --exclude public/ --exclude .gitlab-ci.yml ./ ydzsadmin@172.17.2.159:${DeployDir}/
    - rsync -a --exclude .git --exclude public/ --exclude .gitlab-ci.yml ./ ydzsadmin@172.17.2.161:${DeployDir}/
    - rsync -a --delete ./apps/ ydzsadmin@172.17.2.159:${DeployDir}/apps/
    - rsync -a --delete ./apps/ ydzsadmin@172.17.2.161:${DeployDir}/apps/
    - ssh ydzsadmin@172.17.2.159 "sudo chmod -R 777 ${DeployDir}/data/cache/ && sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/* && sudo service php70-php-fpm reload"
    - ssh ydzsadmin@172.17.2.161 "sudo chmod -R 777 ${DeployDir}/data/cache/ && sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/* && sudo service php70-php-fpm reload"
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(yaduo)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"

yaduo_w_composer:
  variables:
    CI: "true"
  stage: prod
  only:
    - master
  tags:
    - com-be
  environment:
    name: production
    url: https://el.yidianzhishi.com
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(yaduo)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - php ${PHPComposer} install
    - ssh ydzsadmin@39.106.141.225 "cd ${DeployDir} && sudo chown -R ydzsadmin:ydzsadmin ./"
    - ssh ydzsadmin@112.125.89.236 "cd ${DeployDir} && sudo chown -R ydzsadmin:ydzsadmin ./"
    - rsync -a --exclude .git --exclude public/ --exclude .gitlab-ci.yml ./ ydzsadmin@39.106.141.225:${DeployDir}/
    - rsync -a --exclude .git --exclude public/ --exclude .gitlab-ci.yml ./ ydzsadmin@112.125.89.236:${DeployDir}/
    - rsync -a --delete ./apps/ ydzsadmin@39.106.141.225:${DeployDir}/apps/
    - rsync -a --delete ./apps/ ydzsadmin@112.125.89.236:${DeployDir}/apps/
    - ssh ydzsadmin@39.106.141.225 "sudo chmod -R 777 ${DeployDir}/data/cache/ && sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/* && sudo service php70-php-fpm reload"
    - ssh ydzsadmin@112.125.89.236 "sudo chmod -R 777 ${DeployDir}/data/cache/ && sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/* && sudo service php70-php-fpm reload"
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(yaduo)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"

#=====================================================================================
#build_prod_guopin:
#  variables:
#    CI: "true"
# stage: prod
#  only:
#    - master
#  tags:
#    - ydzs-prod-guopin
#  when: manual
#  script:
#    - CurDir=`pwd`
#    - DeployDir=/apps/www/weike-pc
#    - PHPComposer=/apps/www/composer.phar
#    - dateStr=`date "+%Y%m%d%H%M%S"`
#    - >
#        if [ ! -e "${PHPComposer}" ]; then
#            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#            php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
#            php composer-setup.php
#            php -r "unlink('composer-setup.php');"
#            mv composer.phar ${PHPComposer}
#        fi
#    - php ${PHPComposer} install
#    - wget http://gosspublic.alicdn.com/ossutil/1.7.3/ossutil64
#    - chmod 755 ossutil64
#    - ./ossutil64 config -e ${endPoint_guopin} -i ${accessKeyID_guopin} -k ${accessKeySecret_guopin} -L CH --loglevel debug -c ~/.ossutilconfig
#    - cd ./public
#    - npm install
#    - cp app.env.production-guopin.js app.env.js
#    - ./node_modules/.bin/cross-env NODE_ENV=production DIST_CLEAR=1 ./node_modules/.bin/webpack --config webpack.dll.config.js -p
#    - ./node_modules/.bin/cross-env CDN_PATH=https://iguopin-wenjuan.oss-cn-beijing.aliyuncs.com/pca/dist/ ./node_modules/.bin/webpack -p 
#    - ${CurDir}/ossutil64 cp -rf ${CurDir}/public/dist oss://iguopin-wenjuan/pca/dist
#    - sudo mkdir -p ${DeployDir} && sudo chown -R ydzsadmin:ydzsadmin ${DeployDir}
#    - sudo yum -y install rsync
#    - cd ${CurDir} && rsync -a --exclude public/node_modules ./ ${DeployDir}/ && sudo service php-fpm reload && cd ${DeployDir}/bin/queue && sudo bash run_queues.prod.guopin.sh
#    - cd ${CurDir} && rsync -a --exclude public/node_modules ./ ydzsadmin@10.50.50.50:${DeployDir}/
#    - ssh ydzsadmin@10.50.50.50 "sudo service php-fpm reload && cd ${DeployDir}/bin/queue && sudo bash run_queues.prod.guopin.sh"
    
ixuexi-146:
  variables:
    CI: "true"
  stage: prod
  only:
    - master
    - release/ixuexi-20220322
  tags:
    - ixuexi
  environment:
    name: production
    url: https://el.ixuexie.com
  when: manual
  script:
    # runing script in web01 server - 10.50.50.146
    - dateStr=`date "+%Y%m%d%H%M%S"`
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - php ${PHPComposer} config -g repos.packagist composer https://mirrors.aliyun.com/composer/
    - |
        if [ ! -e "${PHPComposer}" ]; then
            cd /apps/www
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
        fi
    - cd ${CurDir} && php ${PHPComposer} install
    - sudo mkdir -p ${DeployDir}
    - cd ${CurDir} && sudo rsync -a --exclude .git --exclude .gitlab-ci.yml ./ ${DeployDir}/ && sudo rm -rf sudo rm -rf /apps/www/opcache_file_cache/bd49345cfedb && sudo systemctl restart php-fpm

ixuexi-50:
  variables:
    CI: "true"
  stage: prod
  only:
    - master
  tags:
    - ixuexi-50-be
  environment:
    name: production
    url: https://el.ixuexie.com
  when: manual
  script:
    # runing script in web02 server - 10.50.50.50
    - dateStr=`date "+%Y%m%d%H%M%S"`
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - php ${PHPComposer} config -g repos.packagist composer https://mirrors.aliyun.com/composer/
    - |
        if [ ! -e "${PHPComposer}" ]; then
            cd /apps/www
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
        fi
    - cd ${CurDir} && php ${PHPComposer} install
    - sudo mkdir -p ${DeployDir}
    - cd ${CurDir} && sudo rsync -a --exclude .git --exclude .gitlab-ci.yml ./ ${DeployDir}/ && sudo rm -rf sudo rm -rf /apps/www/opcache_file_cache/bd49345cfedb && sudo systemctl restart php-fpm
    
ixuexi-mq:
  variables:
    CI: "true"
  stage: prod
  only:
    - master
  tags:
    - ixuexi-mq
  environment:
    name: production
    url: https://el.ixuexie.com
  when: manual
  script:
    # runing script in web01 server - 10.50.50.146
    - whoami
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - sudo mkdir -p ${DeployDir}
    - PHPComposer=/apps/www/composer.phar
    - php ${PHPComposer} config -g repos.packagist composer https://mirrors.aliyun.com/composer/
    - |
        if [ ! -e "${PHPComposer}" ]; then
            cd /apps/www
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
        fi
    - sudo chown -R gitlab-runner:gitlab-runner ${DeployDir}/
    - sudo touch /tmp/swoole_loader.log
    - sudo chmod 777 -R /tmp/swoole_loader.log
    - cd ${CurDir} && php ${PHPComposer} install
    - cd ${CurDir} && sudo rsync -a --exclude .git --exclude .gitlab-ci.yml ./ ${DeployDir}/
    - cd ${DeployDir}/bin/queue && sudo bash ./run_queues.prod.guopin.sh
    
ixuexi-mq-restart:
  variables:
    CI: "true"
  stage: prod
  only:
    - master
  tags:
    - ixuexi-mq
  environment:
    name: production
    url: https://el.ixuexie.com
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - cd ${DeployDir}/bin/queue && sudo bash ./run_queues.prod.sh    
    
changcheng_pre:
  stage: prepare
  only:
    - master
  tags:
    - changcheng
  when: manual
  script:
    - PHPComposer=/apps/www/composer.phar
#    - sudo mkdir -p /apps/www
    - yum install -y unzip
    - >
        if [ ! -e "${PHPComposer}" ]; then
            sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            sudo php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            sudo php composer-setup.php
            sudo php -r "unlink('composer-setup.php');"
            sudo mv composer.phar ${PHPComposer}
            sudo ${PHPComposer} config -g repo.packagist composer https://mirrors.aliyun.com/composer/
        fi
        
changcheng_env_test:
  stage: prod
  only:
    - master
  tags:
    - changcheng
  environment:
    name: production
    url: https://gwm.yidianzhishi.com
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - ifconfig
    
changcheng_MONDAY:
  stage: prod
  only:
    - master
  tags:
    - changcheng
  environment:
    name: production
    url: https://gwm.yidianzhishi.com
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - ifconfig
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cc)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - php ${PHPComposer} install
    - sudo rsync -a --exclude public/ --exclude .git/ ./ ${DeployDir}/
    - sudo rsync -a --delete ./apps/ ${DeployDir}/apps/
    - sudo chmod -R 777 ${DeployDir}/data/cache/
    - sudo rm -rf /apps/www/opcache_file_cache/* && sudo rm -rf ${DeployDir}/data/cache/*
    - sudo rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml ./ root@192.168.133.61:${DeployDir}/
    - sudo rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml ./ root@192.168.133.62:${DeployDir}/
    - sudo rsync -a --delete ./apps/ root@192.168.133.61:${DeployDir}/apps/
    - sudo rsync -a --delete ./apps/ root@192.168.133.62:${DeployDir}/apps/
    - sudo ssh root@192.168.133.61 "sudo rm -rf ${DeployDir}/data/cache/routes/* && sudo chmod 777 ${DeployDir}/data/cache && sudo service php74-php-fpm restart"
    - sudo ssh root@192.168.133.62 "sudo rm -rf ${DeployDir}/data/cache/routes/* && sudo chmod 777 ${DeployDir}/data/cache && sudo service php74-php-fpm restart"
    - cd ${DeployDir}/bin/queue && sudo bash ./run_queues.changcheng.sh
    - sudo bash ${DeployDir}/bin/services/run_services.sh
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(cc)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"  
      
#============================================================================
yunji:
  stage: prod
  only:
    - master
  tags:
    - wx
  environment:
    name: production
    url: https://gwm.yidianzhishi.com
  when: manual
  script:
    - CurDir=`pwd`
    - DeployDir=/apps/www/weike-pc
    - PHPComposer=/apps/www/composer.phar
    - whoami
    - php -m
    - which php
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(yunji)部署 开始执行"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body"
    - php ${PHPComposer} install
    - rsync -a --exclude public/ --exclude .git/ --exclude .gitlab-ci.yml ./ ${DeployDir}/
    - rsync -a --delete ./apps/ ${DeployDir}/apps/
    - chmod -R 777 ${DeployDir}/data/cache/
    - rm -rf /apps/www/opcache_file_cache/* && rm -rf ${DeployDir}/data/cache/*
    - |
      msg="${GITLAB_USER_NAME}发起的 正式PC(yunji)部署 执行完成"
      body='{"msgtype": "text","text": {"content": "'${msg}'"}}'
      curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=be5ea585-8d02-4eb4-a134-e2196df85ca4' -H 'Content-Type: application/json' --data "$body" 
    
    
    
    